### ISSUE TITLE
Architecture sketch for encrypted storage (unlikely to come)

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#1]
- the server has multiple "hubs" each of which consists of [a log](http://milinda.pathirage.org/kappa-architecture.com/) which has multiple channels
- example channels are 'bookmarks', 'history', etc.
- the messages in the channels are encrypted [CRDT](https://github.com/dominictarr/crdt) operations
- devices write their changes to the log of the floccus hub on the server using
- A symmetric master key shared by all devices on that hub
  - (New devices could be added using PAKE: Desktop:addDevice -> Desktop:_get a password_ -> Phone:_enter password_ -> DH-like, forward secure, password-blinded key-exchange (PAKE) via 'meta' channel -> Desktop writes master key encrypted with PAKE session key to )

**Comment by e-alfred** [comment]
I am just curious about the things you would like to implement aside from bookmarks and history sync?

**Comment by marcelklehr** [comment]
Bookmarks and history are the most pressing ones for me. What would you like to see? I can imagine tab sync being useful, for example.

**Comment by e-alfred** [comment]
Yes, tab syncing would be nice as well. Maybe this list could help a bit with the features that would be useful: https://en.wikipedia.org/wiki/Comparison_of_browser_synchronizers#Syncable_Items

Form history, search engines, add-ons/extensions, preferences/settings would be nice items.

**Comment by marcelklehr** [comment]
Thanks for the useful list! Not all of that stuff is available through the WebExtension API, yet, though, so I'll see whether I'll get to those.
