### ISSUE TITLE
Brave support

### ISSUE THREAD

**Issue by HLFH** [marcelklehr/floccus#10]
Hi,

Could you support the [Brave ](https://github.com/brave/browser-laptop) browser of Brendan Eich?
https://blog.brave.com/loading-chrome-extensions-in-brave/

Thanks,

**Comment by marcelklehr** [comment]
Thanks for reaching out with this!
After looking at the page you linked to I couldn't identify why floccus currently doesn't work with brave (I haven't tried it myself, though). Do you know the reason? Do I need to provide it in a specific format? Or is it simply the fact that it's not in the Chrome App store?

**Comment by HLFH** [comment]
We should wait for WebExtensions support: https://github.com/brave/browser-laptop/issues/253

I added Floccus to the [desired extensions list](https://github.com/brave/browser-laptop/wiki/Desired-extensions).

**Comment by marcelklehr** [comment]
I'm going to close this, as it's not a problem with floccus.
