### ISSUE TITLE
add support for v0.10.1 again

### ISSUE THREAD

**Issue by theScrabi** [marcelklehr/floccus#100]
Could it be made possible to add downwards support for v0.10.1 again?
ownCloud user might not yet be able to upgrade to v0.11.0 yet.

**Comment by marcelklehr** [comment]
Mh. I get your point. However, version 0.10.1 doesn't have `get-single-bookmark REST endpoint (GET /bookmark/x)`, which I introduced to make folder sync work flawlessly (see https://github.com/nextcloud/bookmarks/releases ).

**Comment by theScrabi** [comment]
Hm but since 0.10.1 doesn't have folders would it make sense to check and not use it there. An alternative would however be to update the oc bookmarks, do you know how deep the changes of v0.11.0 where?

**Comment by marcelklehr** [comment]
> since 0.10.1 doesn't have folders would it make sense to check and not use it there

Mh. It would be possible, but I'm kind of reluctant, because the experience would be rather bad.

> to update the oc bookmarks, do you know how deep the changes of v0.11.0 where?

They weren't that deep, IMO. Mostly just fixes of various things plus the additional API endpoint, which didn't involve anything revolutionary either. :)

**Comment by theScrabi** [comment]
I see, so maybe we are able to update https://github.com/mondjung/bookmarks then :)

**Comment by marcelklehr** [comment]
Should be possible. I'm not really interested in pro-actively supporting owncloud, though.
