### ISSUE TITLE
Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by wisdomseeker71** [marcelklehr/floccus#106]
### Software versions

* Browser: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
* Nextcloud: Nextcloud 13.0.2
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.3

### Steps to reproduce

1. Set up server to sync to https://myserver.mydomain.com:8080 (with valid letsencrypt SSL cert)
2. Set the options to sync an empty server folder (which exists) to any bookmark folder.

### Expected outcome

A successful sync

### Actual outcome

Error! Cannot read property 'indexOf' of null

**Comment by marcelklehr** [comment]
Hey
Could you clarify exactly what you mean by an existing "empty server folder"? The way floccus handles folders in nextcloud doesn't actually make empty folders possible, afaict.

**Comment by wisdomseeker71** [comment]
Thanks for the clarification. It was unclear to me what "Server path" was for, as distinct from "URL". I created a directory that matched what was there, just to be sure. I also tried leaving that field empty. Same result.

**Comment by marcelklehr** [comment]
Try updating to v2.2.4 and re-entering your credentials.

**Comment by wisdomseeker71** [comment]
After the update, it appears to work, now. I have a little trouble setting "server path", which I worked around. The example shows something like "/my/folder", but when I started with a "/", the field would reset/clear immediately. Minor issue.

Thanks for the followup.

**Comment by marcelklehr** [comment]
Aah, that's a regression. "/" is illegal, and thus gets reset to "". My bad for removing the timer on that. Glad the rest works, though.

**Comment by marcelklehr** [comment]
closing in favor of https://github.com/marcelklehr/floccus/issues/115
