### ISSUE TITLE
Unable to Sync

### ISSUE THREAD

**Issue by KINFOO** [marcelklehr/floccus#107]
### Software versions

* Browser: Firefox ESR 52.8.0
* Nextcloud: 13.0.2 stable
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.0

### Steps to reproduce

1. Open _Firefox_
2. Click burger menu
3. Click Modules Icon
4. Click configure on `Floccus (nextcloud Sync)` line
5. Enter valid `https://` server
6. Enter valid User name
7. Enter valid Password
8. Hit `Sync now`

### Expected outcome

Successful sync

### Actual outcome

> `✘ Error!`

#### Stacktrace

```js
Starting sync process for account kevin@https://drive.kinfoo.fr  background-script.js:4779:17
SERVERCREATE qoPKTlUfjukc undefined  background-script.js:4958:29
Syncing failed with Error: This Bookmark does not belong to the current account
Trace de la pile :
_callee7$@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/background-script.js:6053:23
tryCatch@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/polyfill.js:6150:37
invoke@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/polyfill.js:6424:22
defineIteratorMethods/</prototype[method]@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/polyfill.js:6183:16
step@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/background-script.js:5719:183
step/<@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/background-script.js:5719:361
[198]</notify/</run@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/polyfill.js:3911:22
[198]</notify/<@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/polyfill.js:3924:28
[64]</module.exports/flush@moz-extension://307013f9-3c96-487c-8330-c3e847363d2d/dist/js/polyfill.js:1209:9
```

Thanks for the good work

**Comment by marcelklehr** [comment]
Hey kevin!
Thank you for taking the time to report this.
Sadly your Firefox version is no longer supported because it turned out it only has rudimentary coverage of the APIs used by this addon. Your floccus version is thus outdated (current version is v2.2.3).
Consider upgrading to Fx >= v58.
