### ISSUE TITLE
Sync Firefox's Entire Bookmark Tree

### ISSUE THREAD

**Issue by maverick74** [marcelklehr/floccus#11]
I would like the possibility for Floccus to sync Firefox's Entire Bookmark Tree, which means it should have an option to recreate in NextCloud's bookmark page a tree containing:

Bookmarks Toolbar, Bookmarks Menu and the Unsorted Bookmarks folders as well as all the subfolders in them...

This way we could have a proper Bookmark Sync addon :)

**Comment by marcelklehr** [comment]
Yep, that would be cool. Also see #5, though ;)

**Comment by maverick74** [comment]
i read #5 before i submitted this, but thought it was not the same thing :)

Hope this gets improved soon. It's a **very useful and desirable feature** for me. This way i can own my bookmarks and not someone else. (comparing it to Firefox bookmark accounts we'll have the bonus of being able to access them online anywhere and add links anywhere as well... Gold!)

**Comment by marcelklehr** [comment]
No, you're right. It's not the same thing, but it depends on #5 ;)

**Comment by marcelklehr** [comment]
Fixed in version 2.0.0 :tada: :)

**Comment by marcelklehr** [comment]
It doesn't, as I implemented folder support by converting folder paths to tags, so the bookmarks app still doesn't support folders.
