### ISSUE TITLE
Firefox & Chromium Add-On installation issues: "bob" remains username and other authentification issues

### ISSUE THREAD

**Issue by CajusH** [marcelklehr/floccus#110]
### Software versions

* Browser: Firefox 60.0.1 64 bit on openSUSE 42.3
* Nextcloud: 13.0.1 (still using sqlite DB, which is the Installation default)
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.3

### Steps to reproduce

1. fresh installation of Nextcloud, 1 user, login through web interface works
2. add floccus to Firefox and add account
3. select root folder as bookmark source to sync everything
4. click on sync now

### Expected outcome

sync should upload all browser bookmarks to Nextcloud

### Actual outcome

network error, no bookmarks uploaded.
I found out that although I entered the correct user name, Floccus still uses "bob", which isn't my name ;-)
Floccus stores the information in the firefox profile at
browser-extension-data/floccus@handmadeideas.org/storage.js
I found the credentials "bob" and the password I entered. (pasword in CLEARTEXT !!!)
After changing "bob" to my real user name and restarting the browser it started syncing, but after a while it got stuck.
It says "Syncing..." the "Sync Now" button is greyed-out and below the buttons I see a lot of "Couldn't authenticate for creating on the server".

Storing the Nextcloud server URL isn't working either. I entered http://192.168.2.1/nextcloud , but later I found http://192.168.2.1 in storage.js (causing network error again). After changing that in storage.js
the debug console shows some progress, but very, very slow. Besides that I see messages every minute:
_Firefox kann keine Verbindung zu dem Server unter ws://127.0.0.1:12546/ aufbauen._
(Firefox cannot connect to server...) Why are you accessing this address?

Getting stuck at "Syncing...." also happens to Floccus in Chromium. Besides that I cannot see anything synced to or from Chromium. I added another account for Chromium using a different Server Path ("chromium") and started another sync. Now I can see entries from Chromium appearing in my Nextcloud DB, but everything is extremly slow. more than 30 minutes for 100 bookmarks !!??

One more edit again: the "bob" issue also applies to Floccus on Chromium....
I deleted the account to restart the syncing. After creating a new one, I see "bob" and access denied in the Nextcloud log. Changing the username a few times make the right username stay in Floccus, but syncing is stuck and will not restart after browser quit and restart.

**Comment by e-alfred** [comment]
I have the same problem on latest Vivaldi, Opera and Firefox on different operating systems (Linux, Windows, MacOS). I had to try several times to get it running on these browsers by removing all configuration and then try multiple times until it saved the right domain and username instead of "example.com" and "bob". My domain is also analogous to `https://domain.name:5236/nextcloud`.

I think Floccus is now in a stage where updates shouldn't require removing everything and syncing everything from scratch.

**Comment by marcelklehr** [comment]
Hey there,
I'm sorry you're having trouble. I can confirm your issue.
I've been meaning to refactor the UI for some time, now. This is a good reason :)

**Comment by marcelklehr** [comment]
Sorry for the inconvenience, folks! v2.2.4 should fix this.

> On some instances, the latest Floccus release simply reset the domain and username to http://example.com and bob and created an empty folder with that name in the bookmarks manager.

@e-alfred This is strange. Could you open a separate issue for this?

**Comment by e-alfred** [comment]
I think it was related to this bug because it didn't save the settings after adding a new account and created one with those values. For the other problems I will create new bug reports.
