### ISSUE TITLE
Newly created bookmark disappears on sync

### ISSUE THREAD

**Issue by 1stone** [marcelklehr/floccus#114]
### Software versions

* Browser: Chrome 66.0
* Nextcloud: 13.0
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.4 / 2.2.5

### Steps to reproduce
Prerequisites:
* established sync of bookmarks (bookmarks-menubar only)

Steps:
* Added new bookmark to a folder in bookmark-menubar
* Performed manual floccus sync

### Expected outcome
I expected the new bookmark to be synced to the server.

### Actual outcome
The bookmark was **deleted** in Chrome as soon as the sync was performed.

### Additional notes
- The situation is reproducable
- ... but only with this particular bookmark (simple https://host.domain.tld/)
- That bookmark is unique and does not exist in any other bookmark folder
- I'm not able to reproduce it with other bookmarks

**Comment by marcelklehr** [comment]
Mmmh. Strange. Does the particular URL redirect you when you open it?

Could you replay the above steps and provide a log of what happens in floccus?

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* Clear the logs if they're not empty already
* add you bookmark and go to floccus options
* trigger a sync by clicking on `Sync now` for the associated account
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by 1stone** [comment]
> Does the particular URL redirect you when you open it?

Yes and no.
Yes: It returns a 302 if you don't have an authenticated session (Cookie), resulting a a multi-level redirect (SAML-Authentication)
No: When testing this, there was an authenticated session, so every request was straight responded with 200.

> Could you replay the above steps and provide a log of what happens in floccus?

Well, I followed your instructions (thanks for explaining this thoroughly), but unfortunately, today the problem is not reproducable anymore :-(
The bookmark which silently failed previously, no saves properly.
I've no clue was changed in the meanwhile (besides other browsers syncing).

So given that, there is probably not enough meat left to hunt this problem down.
Go ahead and close the issue if you like. I'll reopen/comment on it, in case I have the chance to analyze this again.

**Comment by marcelklehr** [comment]
> When testing this, there was an authenticated session

The bookmarks app also tries to access the urls you store in order to obtain meta data. When it is being redirected, it usually corrects the URL you're storing to the one it got redirected to, so that's why I'm asking.

It could be that this only happens/ed when the sync kicked in automatically on changes in the tree, or the recent release also inadvertently fixed this issue. :)
Feel free to get back to me if this should reoccur.
