### ISSUE TITLE
Couldn't authenticate for removing bookmarks from the server.

### ISSUE THREAD

**Issue by gituser823** [marcelklehr/floccus#118]
### Software versions

* Browser: Chrome 66.0.3359.181 64-bit
* Nextcloud: 13.0.2
* Nextcloud Bookmarks app:0.11.0
* Floccus: 2.2.7

### Steps to reproduce

1. I just tried to Log-in via the Chrome-Addon.
I can log in to my Nextcloud via HTTP just fine with the same Credentials.
My Nextcloud runs in docker on a synology nas, if that matters.

My OS is Linux Mint 18.3 MATE 54-bit, Kernel 4.4.0-112-generic

I did not put anything into Serverpath, not sure if that's correct.
There is another bug in the Serverpath I think: When I try to enter a "/" it gets automatically removed after some miliseconds.

### Expected outcome

It should have logged in to Nextcloud to sync the Bookmarks for the first time.
...

### Actual outcome

The Addon says "Error" and "Couldn't authenticate for removing bookmarks from the server."
...

**Comment by marcelklehr** [comment]
Mh. How did you install the chrome extension? Via the webstore or via the .crx from the release on github?

**Comment by marcelklehr** [comment]
Nevermind, the github release page wasn't up yet. I can confirm the server path but not the authentication error. Could you double check your credentials possibly after disabling and enabling the extension?

**Comment by gituser823** [comment]
I downloaded the extension from the addons store.

I have disabled and re-enabled the extension, but I still get the same Error.

I do have a strange behaviour in nextcloud though:
I shows me the update 1.4.5 for "theming" is available, but when I install it and then click on My Apps again, it shows the Update again.

Although I can install other,new Addons without Problems and Upload files etc. Maybe its unrelated.

I restarted the docker container and I still get the same Error.

**Comment by marcelklehr** [comment]
Mh. I cannot replicate this. Could you double check that you have entered your credentials correctly?

**Comment by marcelklehr** [comment]
@gituser823 Please try v2.2.8. It might solve your problem.

**Comment by marcelklehr** [comment]
Is your problem solved in v2.2.8?

**Comment by gituser823** [comment]
Hi,   sorry, I did not have time to check it yet. 

 Am 21-Jun-2018 22:11:13 +0200 schrieb notifications@github.com:   

Is your problem solved in v2.2.8? 

--
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT

**Comment by marcelklehr** [comment]
Any news on this?

**Comment by Sulumar** [comment]
I face the exact same issue with floccus on Firefox.

I think it has something to do with the https certificate being self signed

**Comment by marcelklehr** [comment]
@Sulumar Ah, that's more of a browser issue. I recommend using letsencrypt to get SSL certificates for free that will work in your browser out of the box ;)
