### ISSUE TITLE
Error Trying to create a URL that is already bookmarked

### ISSUE THREAD

**Issue by skewty** [marcelklehr/floccus#119]
### Software versions

* Browser: Firefox Developer Edition 61.0b10 64-bit
* Nextcloud: 13.0.2
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.7

### Steps to reproduce
1. Click [Sync now] on account that would always error before completing in previous version

### Expected outcome
Sync completion without error.

### Actual outcome
Error!
```
Trying to create a URL that is already bookmarked.  This shouldn't happen!  Please tell the developer about this!
url=http://1006beachavenue.com/
```

**Comment by marcelklehr** [comment]
This error should be fixed, but it can still be the result of an earlier version of floccus as it usually only shows after upgrading or resetting the account. You have a duplicate bookmark on the server. Removing it should fix the error.

**Comment by marcelklehr** [comment]
Did that help?

**Comment by skewty** [comment]
```
Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this! url=https://gitlab.sec/
```

Browser: Chromium Version 65.0.3325.162 (Official Build) (64-bit)
Nextcloud Bookmarks:	0.12.0-rc1
Floccus: 2.2.8

I don't think it is fixed.

**Comment by marcelklehr** [comment]
Mh. Can you confirm by using search on the server, that there's two bookmarks for that url?

**Comment by skewty** [comment]
I believe it has to do with having a local bookmark that also / already exists on the server.

IMHO since duplicate bookmarks seem to be permitted on the server, they shouldn't crash floccus.

I got that error when trying to sync my "Toolbar" bookmarks.  When I removed all the entries in my local copy of the toolbar and tried sync again, it worked.

I did run into an odd issue where floccus was left in some unrecoverable state though.  When I clicked the icon all I got was an empty white surface with no widgets/controls/text.  Restarting my browser didn't fix it (and yes I checked for background copies running).  I quickly got around the issue by uninstalling and reinstalling floccus.

**Comment by marcelklehr** [comment]
> IMHO since duplicate bookmarks seem to be permitted on the server, they shouldn't crash floccus.

That's kind of a though spot, since the bookmarks app has certain constraints to ensure every URL is only stored once, but apparently those fail in some situations. In general I agree with you though.

The upcoming version of floccus will no longer depend on the server for merging local with remote bookmarks and will thus hopefully turn out to be more stable.

**Comment by marcelklehr** [comment]
You can now test the beta version over here #131 ;)

**Comment by skewty** [comment]
Getting this error using the v3 beta builds in #131:
```
bookmark is not defined bookmark is not defined
bookmark is not defined bookmark is not defined
```
In the debug console there is a failure at: Account.js:187:10
ReferenceError: "bookmark is not defined"

And then at: Account.js:170:6
Syncing failed with bookmark is not defined


Browser = Firefox

**Comment by marcelklehr** [comment]
Ah, darn. What does the log say before the error appears?

**Comment by marcelklehr** [comment]
@skewty This should be fixed in the latest beta. Give it a go and preferably report any issues over here #131 ;)

**Comment by marcelklehr** [comment]
v3 is out :tada: If you experience problems, feel free to open a new issue :)
