### ISSUE TITLE
Nextcloud Full text search (Beta) breaks syncing

### ISSUE THREAD

**Issue by xelcho** [marcelklehr/floccus#122]
### Software versions

* Browser: Chromium 66.0.3359.181
* Nextcloud: 13.0x
* Nextcloud Bookmarks app: Bookmarks
* Floccus: Most recent version

### Steps to reproduce

1. Installation of nextcloudplus (pi) version.
2.Activation of Bookmarks app
3.Activation of Full text search - Bookmarks (BETA) app

### Expected outcome

floccus and nextcloud bookmarks app to play nice together and sync like good friends...

...

### Actual outcome

caused floccus sync to fail... logs included error 500....
on nextcloud the errors were:
Error | index | Error: Class 'OCA\FullTextSearch\Api\v1\FullTextSearch' not found -- | -- | --
Sync failed.

**Comment by marcelklehr** [comment]
Did you read the instructions and install the main full text search app?

**Comment by xelcho** [comment]
My Bad! I did not. Once the platform is installed all is well.

**Comment by marcelklehr** [comment]
:blush: :tada:

Glad it works for you :)
