### ISSUE TITLE
Not syncing any folder except the created NextCloud folder, intentional?

### ISSUE THREAD

**Issue by TobiasDev** [marcelklehr/floccus#123]
### Software versions
* Browser: Firefox
* Nextcloud: Latest
* Nextcloud Bookmarks app: Latest
* Floccus: Latest

### Steps to reproduce
1. Changed sync folder to Bookmarks Toolbar

### Expected outcome
That it would sync all the bookmarks inside the bookmarks toolbar folder to my selected NextCloud instance. 
...

### Actual outcome
Didn't sync anything. It only syncs when I reset and add bookmarks to the NextCloud folder it created. 
...

**Comment by marcelklehr** [comment]
Hey!
What happens if you click sync now after selecting the bookmarks toolbar?

**Comment by TobiasDev** [comment]
![image](https://user-images.githubusercontent.com/5912371/41160660-afe54982-6b30-11e8-97f8-c564c20200a9.png)

**Comment by TobiasDev** [comment]
Now it says it is working again. But, it actually doesn't show up in my NC Bookmarks.

**Comment by TobiasDev** [comment]
But nothing shows up in the bookmarks

**Comment by marcelklehr** [comment]
This is unusual. Could you please provide concrete version information rather than 'latest'?

**Comment by TobiasDev** [comment]
Sure... Wait, just as I was writing it started to work. Uhm... I will test this some more. 

Versions:
Nextcloud: 13
Nextcloud Bookmarks app: 0.11
Floccus: 2.2.7

**Comment by TobiasDev** [comment]
Okay... now it stopped working again.

Error: pathSegment is undefined

**Comment by marcelklehr** [comment]
Firefox version?

**Comment by TobiasDev** [comment]
Hello again! 

Sorry for the late answer. 

I'm currently on Firefox. 60.0.2, and it keeps being weird. I just installed the plugin at work (same firefox version, extension version, etc., double checked to be sure). 

Here it says network error for syncing, but I everything else works with internet.

**Comment by TobiasDev** [comment]
Now it is back to saying: Error! Node is null.

**Comment by TobiasDev** [comment]
Okay, sorry. 

So I have tried some different things to see if I can get this working (currently at work, trying to get my Firefox there set-up). I only want to sync to the bookmarks toolbar, so I don't do root syncing or such. 

So first time set-up this was the errors I was getting:
1. Error!: pathSegment is undefined - That suddenly stopped happening
2. Error!: Node is null

So for some reason both of them disappeared at some point. And it started saying all okay, sync okay, etc. But it didn't actually sync any of my bookmarks. After this I tried resetting the Bookmark toolbar folder, and it synced to my "Firefox NextCloud folder". That seemed to actually worked. it synced my bookmarks to the nextCloud folder. So i decided to re-start everything, delete the set-up etc. so I could get the bookmarks toolbar to work. Now I get this error: Error! Incorrect arguments type for bookmarks.getSubTree. 

I sadly don't know what any of these errors mean, and it just doesn't want to sync my Firefox bookmarks no matter what I do. Even when I get it to sync them, it only syncs them to the NextCloud folder, I can't get them to sync to the bookmarks toolbar for some reason.

**Comment by marcelklehr** [comment]
Mh. Let's have a look at the logs:


In order to aid in debugging, please provide client-side logs.

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* in the console tab, clear the output
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and copy the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by marcelklehr** [comment]
In a [similar issue](https://github.com/marcelklehr/floccus/issues/128) we found that it works in a newly created profile, could you try this as well?

**Comment by TobiasDev** [comment]
Yeah, it started working for me now... Not sure what changed. But yes that works. :)

**Comment by marcelklehr** [comment]
Mh. Glad it works. We're going to continue investing in #128 ...
