### ISSUE TITLE
help for set up

### ISSUE THREAD

**Issue by arnauldb** [marcelklehr/floccus#127]
Hello,

I can't arrive to set up floccus and I don't know what to input exactly in the fields.

Here is a screenshot: 
http://i.imgur.com/Ko36sQO.png

Thank you for any help.

**Comment by marcelklehr** [comment]
Hey @arnauldb 

For this to work with your Nextcloud server, you need at least version v0.11 of the Bookmarks app installed. ;) Let me know if that fixes things.

**Comment by arnauldb** [comment]
Hello,

I installed the Bookmarks app. I have two browsers, with the floccus addon installed. On the first one I have all my bookmarks in the "bookmarks bar". With the set up as on the screenshot : http://i.imgur.com/Ko36sQO.png .

And I have a second browser with the Floccus add on installed and the same settings.

When I click on "Sync now" it is synchronizing, but the bookmarks don't appear in the bookmarks bar of the second browser...(I clicked on "Sync now in the second browser too).

Am I doing something wrong ? I don't understand, sorry.

**Comment by marcelklehr** [comment]
The error tells me that something with the server url you entered is wrong. Instead of JSON, floccus receives HTML (identifiable by the uncanny `>`) You could try adding a trailing slash, but I think you should check your bookmarks app version.

**Comment by arnauldb** [comment]
Hello,

Now, it is synchronizing fine, thank you. I imported my bookmarks in the Bookmarks app, then synchronized, and the bookmarks appeared in the other browser. However, they don't appear in the bookmark bar, but in a folder called "Nextcloud"...
(screenshot) http://i.imgur.com/NvkwwyT.png
How can I have them appear in the bookmark bar ?

**Comment by marcelklehr** [comment]
You can change the sync folder in the account options

**Comment by arnauldb** [comment]
Ok, Thank you.
