### ISSUE TITLE
Multiple Nextcloud accounts

### ISSUE THREAD

**Issue by 9662** [marcelklehr/floccus#13]
As far as I can ascertain, floccus currently supports connecting to a single Nextcloud account. As a user with access to more than one Nextcloud installation (work and personal), I suggest adding support for configuring multiple accounts.

Notes:
* Each account could synchronise to their own bookmarks folder.
* The name of the bookmark folder *could* be made user-configurable (and/or default to something based on the respective user Nextcloud ID, e.g., `Bookmarks for 9662@cloud.example.com/`).

**Comment by marcelklehr** [comment]
This is a very good Idea! The name of the folder is already user-configurable, btw, I just haven't advertise it, yet. Just change the name and things should continue to work. You can also sort it somewhere else, if you prefer to have it in the bookmarks toolbar or some place else ;)

**Comment by marcelklehr** [comment]
This is fixed in master, but not yet released.
