### ISSUE TITLE
Bookmarks with no name are renamed to the server's <title> and are reordered as the last bookmarks

### ISSUE THREAD

**Issue by synthead** [marcelklehr/floccus#132]
### Software versions

* Browser: Firefox 61.0
* Nextcloud: 13.0.4
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.8

### Steps to reproduce

1. Create a bookmark with no name.
2. Sync using Floccus.
3. Observe that the bookmark has been given a name of the server's `<title>` and that the bookmark has been reordered as the last bookmark.

### Expected outcome

The bookmark names and ordering in FireFox should remain as-is, and a bookmark with no name should be synced to the Bookmarks app in Nextcloud via Floccus

### Actual outcome

Bookmarks with no names were given a name of the server's `<title>` and are reordered as the last bookmarks.

**Comment by marcelklehr** [comment]
The reordering is to be expected as the nextcloud app doesn't allow ordering bookmarks.
The title change is unfortunate. I'll see what I can do...

**Comment by marcelklehr** [comment]
This should be fixed in v3.0.0. Please test the beta version to confirm: #131 :)

**Comment by marcelklehr** [comment]
Will be fixed in the next beta release of v3
