### ISSUE TITLE
Bug in setting up the Sync folder

### ISSUE THREAD

**Issue by noma** [marcelklehr/floccus#134]
See steps to reproduce. 

### Software versions

* Browser: 61.0.1 (Ubuntu)
* Nextcloud: 13.0.4
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.8 (from mozilla add-ons page)

### Steps to reproduce
1. Install the app, and add an account
2. Create an empty folder in "Bookmarks Toolbar"
3. Select that folder for sync
4. Press "Sync now"
    - first error "Invalid argument ... getTree()" (I didn't write down the exact text, and cannot reproduce it any more)
-----
5. At this point I reset the Options and let the add on create a new folder
6. Syncing now worked
7. I change it back the folder I wanted to Sync (also added some bookmarks in case emptiness is a problem)
8. Syncing works, but it still uses the newly created folder from step 5.
9. Delete the account, enter everything again, choose the folder from 2.
10. "Sync now" says something about syncing from scratch (because there is something in the cloud already I guess)
11. It works, as expected

Other than that: great work! :-)

**Comment by marcelklehr** [comment]
Can't reproduce, so I'm glad it works now :)
