### ISSUE TITLE
Feature Request: Use browser's password store (if possible)

### ISSUE THREAD

**Issue by noma** [marcelklehr/floccus#135]
Would it be possible to use the browser's password store (Firefox or Chromium) instead of storing the password somewhere (if the APIs allow it, though)?

Actually, how and where is it currently stored? In plain text if there is no protection password set?

Thanks!

**Comment by marcelklehr** [comment]
Sadly, that's not possible as far as I know. Currently, credentials are stored in the extension's local storage. If you lock the extension with a password, the credentials are encrypted with the password, if you don't, they're stored in plain text.
