### ISSUE TITLE
Keine Synchronisation mit Nextcloud

### ISSUE THREAD

**Issue by dietmarolaf** [marcelklehr/floccus#136]
[floccus.zip](https://github.com/marcelklehr/floccus/files/2683721/floccus.zip)

Hallo Marcel.

### Software versions

* Browser: Chrome (auch Firefox getestet)
* Nextcloud: 10.0.5 auf einer Synology mit mariaDB5
* Nextcloud Bookmarks app: - (bisher keine in Verwendung)
* Floccus: 2.2.8 Addon unter Chrome (auch Firefox getestet

### Steps to reproduce

1. kann mich mit einer NextCloud App z.B. unter iOS anmelden und Nextcloud öffnen
2.das Gleiche auch mit Browsern wie Chrome und Firefox unter macos
3. habe unter nextcloud einen Ordner "Lesezeichen" angelegt den ich als "Server Path" gewählt habe
4. installiere ich jedoch das Addon Floccus dan bekomme ich keine Synchronisation hin
5. habe es mit allen Lesezeichen-Ordner bis hin zu nur einem neu angelegten versucht zu testen
6. Entweder Synchronisierungs- und Netzwerkfehler
7. habe noch nachträglich die App Bookmaks in Nextcloud installiert

### Expected outcome

...

### Actual outcome

...

**Comment by marcelklehr** [comment]
Hey :)

In der README steht:
> For this to work with your Nextcloud server, you need at least version v0.11 of the Bookmarks app installed

> habe noch nachträglich die App Bookmaks in Nextcloud installiert

Welche Version? Soweit ich weiß wird Nextcloud 10 nicht mehr von der Bookmarks App unterstützt. :/

**Comment by marcelklehr** [comment]
Also die Nextcloud app ist auf jeden Fall nötig, damit es funktioniert.

Was ist den der genaue Fehler bei "Synchronisierungsfehler"?

**Comment by dietmarolaf** [comment]
Ich hatte bisher auf der Synolgy:
❚ nextcloud 13.0.5 installiert
❚ mariaDB5 als Datenbank
❚ Apache 2.2
❚ unter nextcloud habe ich dann die App "Bookmarks" installiert
❚ und im Browser dann das Floccus Plug-In (Chrome / Firefox im Test)

Bekomme immer Netzwerkfehler oder, dass die Lesezeichen nicht synchronisiert werden können.
Habe im Floccus Plug-in
den Server als 
https://meine.server.com/nextcloud
eingegeben ode auch die IP-Adresse

**Comment by marcelklehr** [comment]
Falls du Chrome v68 benuzt, kann es sein, dass du von folgenden Chrome bug betroffen bist: #138 
Firefox sollte aber funktionieren :/ Um welche Firefox version handelt es sich?

**Comment by dietmarolaf** [comment]
Ja ich habe eine 68er Version. Kann also durchaus sein, dass es genau das Problem ist. Werde ich wohl etwas warten müssen. Bzw. Wenn Zeit vorhanden, dann mal mit Firefox testen.

**Comment by marcelklehr** [comment]
Ich habe eben v2.2.9 released. In der version sollte der Fehler behoben sein.

**Comment by dietmarolaf** [comment]
Hi Marcel.

Danke. werde ich am Wochenende testen. Gebe Bescheid.

**Comment by dietmarolaf** [comment]
Hallo Marcel.
Habe es nun mit Chrome nochmals getestet, intern wie als auch extern. Funktioniert schon mal. Hast mir geholfen. Jetzt versuche ich bloss noch eine 2-stufige Authentifizierung hinzubekommen. Hast du das schon mal getestet?

**Comment by marcelklehr** [comment]
Yay, das freut mich. Für third-party clients sollen laut nextcloud manual client-spezifische Passwörter genutzt werde. Wie das geht findest du hier https://docs.nextcloud.com/server/12/user_manual/session_management.html Ich habe das selbst noch nicht getestet, sehe aber keinen Grund, warum es nicht funktionieren sollte.

**Comment by dietmarolaf** [comment]
So das habe ich auch hinbekommen.
Werde dazu im Blog noch einen Artikel für die gesamte Einrichtungsprozedur schreiben.
Fehlt nur noch die Verbindung zu Safari. Selbst habe ich eine Lösung, aber für andere...
Und damit verbunden auch die Nutzung der Lesezeichen auf einem mobilen Gerät.

**Comment by marcelklehr** [comment]
> damit verbunden auch die Nutzung der Lesezeichen auf einem mobilen Gerät.
Für mobile Geräte dauert es noch bis das Addon von Firefox for Android unterstützt wird. Bis dahin kann man die Bookmarks android app von thescrabi benutzen. Siehe dazu das README der Bookmarks app https://github.com/nextcloud/bookmarks Er hat allerdings angemerkt, dass er momentan untersützung beim maintainen der App braucht...

**Comment by dietmarolaf** [comment]
Hallo Markus


Nutze Floccus nun schon geraume Zeit mit der Synchronisation WebDAV auf
eine Synology. Nach dem Letzten Update habe ich das Problem, dass ich im
Browser (Chrome und Firefox getestet) einzelne Lesezeichen löschen möchte.
Dann Synchronisiert er mit Fehlermeldung, dann nochmals, wieder alles ok,
aber die Lesezeichen sind wieder da.

Die Anmeldung hat Lese- und Schreibberechtigung. Nochmals kontrolliert.

Log-Datei habe ich mal angehangen.

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 12. August 2018 um 20:47:07, Klehr Marcel (notifications@github.com)
schrieb:

damit verbunden auch die Nutzung der Lesezeichen auf einem mobilen Gerät.
Für mobile Geräte dauert es noch bis das Addon von Firefox for Android
unterstützt wird. Bis dahin kann man die Bookmarks android app von
thescrabi benutzen. Siehe dazu das README der Bookmarks app
https://github.com/nextcloud/bookmarks Er hat allerdings angemerkt, dass er
momentan untersützung beim maintainen der App braucht...

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/marcelklehr/floccus/issues/136#issuecomment-412355605>,
or mute the thread

**Comment by marcelklehr** [comment]
Kannst du das log file nochmal über das Github user interface hochladen? Anhänge via mail akzeptiert Github leider nicht :/

Was war denn die Fehlermeldung?

**Comment by dietmarolaf** [comment]
War im Bild enthalten. Kan. Ich das da auch hochladen?

Gruß  
dos.  

http://iphoneinaktion.com  

Von: Marcel Klehr <notifications@github.com>(mailto:notifications@github.com)
Antworten: marcelklehr/floccus <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 15. Dezember 2018 at 13:38:54
An: marcelklehr/floccus <floccus@noreply.github.com>(mailto:floccus@noreply.github.com)
CC: dietmarolaf <dietmarolaf@gmail.com>(mailto:dietmarolaf@gmail.com), State change <state_change@noreply.github.com>(mailto:state_change@noreply.github.com)
Betreff: Re: [marcelklehr/floccus] Keine Synchronisation mit Nextcloud (#136)

**Comment by marcelklehr** [comment]
Hier kann man alles hochladen :)

**Comment by dietmarolaf** [comment]
Hallo Marcus. Habe ich jetzt versucht, hoffe es ist angekommen und ich habe
nichts falsch gemacht.

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 15. Dezember 2018 um 14:38:08, Klehr Marcel (notifications@github.com)
schrieb:

Reopened #136 <https://github.com/marcelklehr/floccus/issues/136>.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/marcelklehr/floccus/issues/136#event-2028473813>, or mute
the thread

**Comment by marcelklehr** [comment]
Hat nicht geklappt. Dateien kann man nur hochladen, wenn man auf github.com *im Browser* kommentiert.

Hier ist der Link dazu: https://github.com/marcelklehr/floccus/issues/136

Dann kannst du einfach deine Dateien in das Kommentarfeld per Drag-and-drop ziehen (siehe https://github.com/marcelklehr/floccus/issues/136 )

**Comment by dietmarolaf** [comment]
Danke werde ich morgen machen Marcel

Gruß  
dos.  

http://iphoneinaktion.com  

Von: Marcel Klehr <notifications@github.com>(mailto:notifications@github.com)
Antworten: marcelklehr/floccus <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 15. Dezember 2018 at 18:02:52
An: marcelklehr/floccus <floccus@noreply.github.com>(mailto:floccus@noreply.github.com)
CC: dietmarolaf <dietmarolaf@gmail.com>(mailto:dietmarolaf@gmail.com), State change <state_change@noreply.github.com>(mailto:state_change@noreply.github.com)
Betreff: Re: [marcelklehr/floccus] Keine Synchronisation mit Nextcloud (#136)

**Comment by dietmarolaf** [comment]
Hallo Marcus. So jetzt müsste es geklappt haben.

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 15. Dezember 2018 um 18:02:53, Klehr Marcel (notifications@github.com)
schrieb:

Hat nicht geklappt. Dateien kann man nur hochladen, wenn man auf github.com *im
Browser* kommentiert.

Hier ist der Link dazu: #136
<https://github.com/marcelklehr/floccus/issues/136>

Dann kannst du einfach deine Dateien in das Kommentarfeld per Drag-and-drop
ziehen (siehe #136 <https://github.com/marcelklehr/floccus/issues/136> )

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/marcelklehr/floccus/issues/136#issuecomment-447582620>,
or mute the thread

**Comment by marcelklehr** [comment]
Ich close das hier mal und verweise auf #213

**Comment by dietmarolaf** [comment]
Habe gesehen, dass es eine neue Version gibt. Konnte bisher jedoch keinen
Unterschied feststellen. Gelöschte Lesezeichen erscheinen immer wieder.
Soll ich das Plugin deinstallieren und wieder neu einrichten?

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 16. Dezember 2018 um 17:35:20, Olaf Schneider Dietmar (
dietmarolaf@gmail.com) schrieb:

Hallo Marcus. So jetzt müsste es geklappt haben.

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 15. Dezember 2018 um 18:02:53, Klehr Marcel (notifications@github.com)
schrieb:

Hat nicht geklappt. Dateien kann man nur hochladen, wenn man auf github.com *im
Browser* kommentiert.

Hier ist der Link dazu: #136
<https://github.com/marcelklehr/floccus/issues/136>

Dann kannst du einfach deine Dateien in das Kommentarfeld per Drag-and-drop
ziehen (siehe #136 <https://github.com/marcelklehr/floccus/issues/136> )

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/marcelklehr/floccus/issues/136#issuecomment-447582620>,
or mute the thread

**Comment by dietmarolaf** [comment]
Hallo Marcel. Jetzt ist erst die neue Version im Browser. Scheint zu
funktionieren. Besten Dank. Gebe Bescheid. Schöne Weihnachten

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 22. Dezember 2018 um 10:04:49, Olaf Schneider Dietmar (
dietmarolaf@gmail.com) schrieb:

Habe gesehen, dass es eine neue Version gibt. Konnte bisher jedoch keinen
Unterschied feststellen. Gelöschte Lesezeichen erscheinen immer wieder.
Soll ich das Plugin deinstallieren und wieder neu einrichten?

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 16. Dezember 2018 um 17:35:20, Olaf Schneider Dietmar (
dietmarolaf@gmail.com) schrieb:

Hallo Marcus. So jetzt müsste es geklappt haben.

Gruß
dos.

*http://iphoneinaktion.com <http://iphoneinaktion.com>*

Am 15. Dezember 2018 um 18:02:53, Klehr Marcel (notifications@github.com)
schrieb:

Hat nicht geklappt. Dateien kann man nur hochladen, wenn man auf github.com *im
Browser* kommentiert.

Hier ist der Link dazu: #136
<https://github.com/marcelklehr/floccus/issues/136>

Dann kannst du einfach deine Dateien in das Kommentarfeld per Drag-and-drop
ziehen (siehe #136 <https://github.com/marcelklehr/floccus/issues/136> )

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/marcelklehr/floccus/issues/136#issuecomment-447582620>,
or mute the thread
