### ISSUE TITLE
Firefox / X11: Extension popup is closed when clicking on password input

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#139]
Also seen in https://github.com/nextcloud/passman-webextension/issues/252
Mozilla bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1405634

It's an ibus problem with X11 on linux: https://github.com/ibus/ibus/issues/2002

**Comment by e-alfred** [comment]
It happens on Ubuntu 18.04 with Firefox installed from the repository. The Snap version is unaffected.

**Comment by marcelklehr** [comment]
Seems to be fixed now, I think.
