### ISSUE TITLE
No synchronization, no error-report (firefox)

### ISSUE THREAD

**Issue by omocinteractive** [marcelklehr/floccus#14]
Hi,
there is no synchronization and no error-report what's going wrong on firefox. Maybe a problem with #-character in password?

Greetings,
Andreas

**Comment by marcelklehr** [comment]
Hey Andreas,
could you try going to about:debugging and open the debugger for floccus? In the console tab, you should see the log messages, which should indicate what's going on. Be aware though, that the sync interval is 25mins, atm.

**Comment by marcelklehr** [comment]
A quick fix might also be to delete the owncloud bookmarks folder, which resets floccus' sync state.

**Comment by omocinteractive** [comment]
@marcelklehr: thx! i'm currently total busy. i take a look tomorrow morning.

**Comment by omocinteractive** [comment]
okay, i debugged the synchronization - no fails, but the script hangs after few hundreds bookmarks and firefox hangs. there is no directory called "owncloud" ...

![bild 083](https://cloud.githubusercontent.com/assets/20245225/26380629/02008872-4020-11e7-858e-14e83f5cbc67.png)
![bild 082](https://cloud.githubusercontent.com/assets/20245225/26380630/0200768e-4020-11e7-953e-eedbb1118e4a.png)

**Comment by marcelklehr** [comment]
How many bookmarks do have exactly? The floccus folder should be in "Other Bookmarks"..

**Comment by omocinteractive** [comment]
... "Other Bookmarks", okay - that was the "problem". The old version stored the bookmarks in the root of bookmarks and synchronize the bookmarks on start (or ?). Sorry, everything alright!

**Comment by omocinteractive** [comment]
btw. there are more than 2000 bookmarks to synchronize ...

**Comment by marcelklehr** [comment]
So, the only issue left is that firefox is freezing or is there something else?

**Comment by omocinteractive** [comment]
... oh no, no freezing ff, everything okay (see my post 3days ago) ;)

**Comment by marcelklehr** [comment]
Ah, well that's awesome :)
