### ISSUE TITLE
Can't synchronize.

### ISSUE THREAD

**Issue by arnauldb** [marcelklehr/floccus#143]
Everything installed correctly, latest versions of Nextcloud, bookmarks app, floccus addon. I use it in Irridium.

I wish to have my bookmarks (and folders) bar in Irridium synchronized with Nextcloud.

What I did:

I exported all my bookmarks (with folders) then imported them in the bookmark app in Nextcloud, where they shows (without folders structure though).

I set up the Floccus addon this way (screenshot):
http://i.imgur.com/9p92wLi.png

It says "syncing" but nothing shows up in the bookmark folder, though the Nextcloud folder was automatically created (screenshot):
http://i.imgur.com/42lbGQo.png

It is my second attempt (I tried a few months ago) and I would like to get it working, but I must have misses something...Thank you for any help.

**Comment by arnauldb** [comment]
I successfully synchronized a folder from my "Bookmarks bar" (screenshot): http://i.imgur.com/gvIVAGg.png

with these settings (screenshot): http://i.imgur.com/bfvvxwW.png

So, if I wish to synchronize my whole "Bokkmarks Bar" whith the included folder structure, I guess I need to choose "/Bookmarks bar" instead of "/Bookmarks bar/wuhan" in the options menu...am I right?

**Comment by marcelklehr** [comment]
@arnauldb Awesome. You are correct. :)

**Comment by marcelklehr** [comment]
You can use SQL to truncate oc_bookmarks and oc_bookmarks_tags, but this will remove all bookmarks from all users. The upcoming version of the bookmarks app now has an option in the settings to remove all bookmarks of the current user, though. You can install the release candidate by following the instructions over here: https://github.com/nextcloud/bookmarks/issues/522

**Comment by arnauldb** [comment]
Hum, I installed "0.11.0	0.12.0-rc7 - nightly (Unstable)" for Nextcloud 13, but no luck, there is no option in the settings for bulk delete bookmarks...

**Comment by marcelklehr** [comment]
>  "0.11.0	0.12.0-rc7 - nightly (Unstable)"

These are two different releases. The UI in the app store is a bit weird. You need to download the red link. ;)

**Comment by arnauldb** [comment]
Ok, sorry, my mistake. I downloaded it, installed it and could erase all my bookmarks. It is synchronizing now. Thank you for your Floccus/addon.
