### ISSUE TITLE
Folder structure is not preserved.

### ISSUE THREAD

**Issue by arnauldb** [marcelklehr/floccus#144]
Hello,

I finally succeeded in synchronizing my whole bookmark bar. But there is no folder structure. Is it possible to have the folders with the bookmarks inside? Currently, I have all the bookmarks but no folder.

Thank you.

**Comment by bernd-wechner** [comment]
Alas you're not clear on what settings you're using. So no-one will be able to say for sure why you see what you see. Nor is it clear what you mean. But I can offer one small experience. That is, if you're syncing to the NextCloud Bookmarks app, it does't support folders alas, though I filed an issue with it to ask for that. And so floccus uses the tag with its own syntax to record the folder structure. It's a compromise and not real nice. But they are maintained with folders on the browser.

**Comment by arnauldb** [comment]
Ok, thank you, that is what I wanted to know.
