### ISSUE TITLE
Failed Sync with sub-URL (Nextcloud 13, bookmarks v0.12.0-rc7)

### ISSUE THREAD

**Issue by ramesh45345** [marcelklehr/floccus#145]
### Software versions
* Browser: Firefox 61.0.2 (64-bit, Fedora 28)
* Nextcloud: 13.0.5 (from Docker Hub)
* Nextcloud Bookmarks app: v0.12.0-rc7 (release from Github, installed manually)
* Floccus: 2.2.9 (August 20th, 2018 from addons.mozilla.org)

Note: My nextcloud server is behind an nginx reverse proxy. There seem to be elements when I connect to it that result in a 404, but the bookmarks page (whose full URL would be along the lines of https://server-name-here:64020/nextcloud/apps/bookmarks/#all ) displays fine.

### Steps to reproduce
1. Input the following details into floccus after install: https://server-name-here:64020 for server (replace server-name-here with my private server name), username, password, and "/nextcloud" as subpath.
2. Press Sync button.

### Expected outcome
Expected successful sync.

### Actual outcome
Error Message: Failed to retrieve bookmarks from server

Add-on debug log:
```
Starting sync process for account ramesh@https://server-name-here:64020 Account.js:128:6
Fetching bookmarks 
Object { type: "nextcloud", url: "https://server-name-here:64020", username: "ramesh", password: "password-here", serverRoot: "/nextcloud", syncing: true, localRoot: "ev6PfW_j5byb", error: "Failed to retrieve bookmarks from server" }
Nextcloud.js:252:4
Error: "Failed to retrieve bookmarks from server"
_callee2$moz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/background-script.js:8274:23
tryCatchmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:6900:37
invokemoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:7138:22
methodmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:6952:16
stepmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/background-script.js:7907:183
stepmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/background-script.js:7907:361
runmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:4295:22
notifymoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:4308:30
flushmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:1398:9 Account.js:190:8
Syncing failed with Error: "Failed to retrieve bookmarks from server"
_callee2$moz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/background-script.js:8274:23
tryCatchmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:6900:37
invokemoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:7138:22
methodmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:6952:16
stepmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/background-script.js:7907:183
stepmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/background-script.js:7907:361
runmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:4295:22
notifymoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:4308:30
flushmoz-extension://a4e6e710-d17b-4386-9341-41c5d643981a/dist/js/polyfill.js:1398:9
```

I checked the Network tab of the Developer Tools, and noticed that the following URL access by floccus produces a 404, which is probably the cause of the issue: https://server-name-here:64020/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1 . After looking into this, this page legitimately doesn't exist, because it is missing the sub-URL. The correct URL should be https://server-name-here:64020/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1 , which includes the sub-URL "/nextcloud" (which does function properly on my server when accessed in a browser). Shouldn't the extension use the sub-URL when making this request?

**Comment by marcelklehr** [comment]
Hey there,
The UI is currently a bit misleading in this regard. The correct settings for your situation would be:

URL: https://server-name-here:64020/nextcloud
username: ...
password: ...
server path: *empty*

Press Sync button.

Explanation: The server path signifies the path under which your bookmarks are stored in the bookmarks app, not the http path. ;)
