### ISSUE TITLE
v3: Multi-tags bookmarks in odd way

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#147]
I just tried the new v3. Nice.

My setup is:

local folder: *root folder*
server folder: empty

And to illustrate I will offer one example. I have this link:

http://ask.metafilter.com/mefi/45181

bookmarked under:

- Menu
- - Windows
- - - Programming
- - - - C#

And it gets two tags in the NexCloud bookmarks after syncing once (which took well over a half hour) and then again (which finished very quickly) and these two tags are:

floccus:&gt;Bookmarks Menu&gt;Windows&gt;Programming&gt;C#
floccus:&gt;Bookmarks Menu&gt;BookmarksMenu&gt;Windows&gt;Programming&gt;C#

See the problem. As far as I can tell all my bookmarks are double tagged like this. 

My initial condition was:

1) Empty bookmarks app on nextcloud. I Truncated the two relevant tables in the database and tested the UI and it was nice and empty.

2) Synced my Firefox which has about 700 bookmarks.

**Comment by bernd-wechner** [comment]
FYI I just synced a third time and still only two tags per bookmark as above. Not sure if they got two on the first sync or after the second. If I find time will empty table and repeat. Must run now.

**Comment by marcelklehr** [comment]
mmh. Can you confirm  there is no bookmarks folder in your browser in your Bookmarks Menu called "BookmarksMenu"?

**Comment by bernd-wechner** [comment]
Good thought. Here's what I see in the Firefox BookMark editor:

![image](https://user-images.githubusercontent.com/7296506/44553320-65bf1f00-a770-11e8-8e71-2096a43bf851.png)

That aside, it's odd giving one bookmark two tags, or is that expected somehow if the same bookmark is found in two browser folders?

**Comment by marcelklehr** [comment]
@bernd-wechner 

Mh. The screenshot doesn't show the contents of the bookmarks menu, though :)

> That aside, it's odd giving one bookmark two tags, or is that expected somehow if the same bookmark is found in two browser folders?

That's exactly the point :) it didn't used to be allowed to have the same URL in different browser folders, but it works now in v3 via multiple path tags.

**Comment by bernd-wechner** [comment]
You are good and patient Marcus, thank you so much! You are spot on!

![image](https://user-images.githubusercontent.com/7296506/44558503-e76e7700-a787-11e8-98ab-cdc4b06bb8d9.png)

I certainly never created that subfolder double up for everything! I suspect strongly it is an artifact of an earlier experience with floccus betas! Either way I will remove it and clean up NexCloud and start again! Yay! Looking a LOT like floccus is cool and stable slowly and working. Will report back if I find anything else of course.

**Comment by bernd-wechner** [comment]
OK quick update:

I have now tested this by putting 3.01 on FF at home and work and did some back and forth. It was a tad messy with lots of dupes at first, but I tidied it up and it seems to have stabilised. As an FYI this query on the NextCloud database:

```
SELECT MAX(`oc_bookmarks`.title) AS title, COUNT(`tag`) AS count, GROUP_CONCAT(`tag` SEPARATOR "\n")
FROM `oc_bookmarks_tags` 
INNER JOIN `oc_bookmarks` 
ON `oc_bookmarks`.id = `oc_bookmarks_tags`.bookmark_id 
GROUP BY `bookmark_id` 
HAVING count > 1
```

really helped me, and methinks a nice feature in floccus  might be to add a "list duplicates" feature to the toolbar drop down, which reports such a thing. 

Also of note is that order in menus is not preserved. There may be no easy way to dot hat with the BookMarks NextCloud app given it would need a column in oc_bookmarks to store a sort key or ordering key in. Just a side note as Xmarks did preserve order. That is the menus on one browser look the same as on the other, ordering preserved. The browsers themselves typically (in my experience) do this by storing bookmarks in an ordered file (like json file) rather than an orderless database table and so they win ordering as bonus. I left a note here about that:  

https://github.com/nextcloud/bookmarks/issues/514

**Comment by marcelklehr** [comment]
Ah, great it works now :tada:

The order is indeed an issue. It is only destroyed when you sync a browser for the first time. If you then rearrange the bookmarks and sync again, it should stay in your custom order. Still, order preservation is a good feature: see #113 ;)
