### ISSUE TITLE
New permissions in v3

### ISSUE THREAD

**Issue by bodograumann** [marcelklehr/floccus#148]
I'm on Firefox 61.02 and floccus (currently 2.2.9) is requesting permissions to “Access my data for all websites”.
In recent times many addons have been subverted to grab users browsing data, so I have made a habbit of verifying that any new permissions are legitimate.
Unfortunately in this case the description of the requested permissions is pretty unclear. Also I could not find any information on new permission requirements in the Readme.

Could you please check whether these permissions are really needed and if that is the case, add an explanation to the readme?

**Comment by marcelklehr** [comment]
Ah, yes. I'll update the README.

**Comment by marcelklehr** [comment]
Here you go: https://github.com/marcelklehr/floccus#permissions

Thanks for the feedback :)

**Comment by marcelklehr** [comment]
The "new" permission is not actually new, but it was added to allow accessing http servers as well, not just https servers.

**Comment by bodograumann** [comment]
Thank you for the quick resolution :-)
