### ISSUE TITLE
Sync Error "currentSubtree.children is undefined"

### ISSUE THREAD

**Issue by akidburn** [marcelklehr/floccus#149]
Hi,

the new Version of floccus is not working, either in WebDAV mode or in Nextcloud mode.

In Firefox and Nextcloud Mode, there is the "currentSubtree.children is undefined" error.
In Chrome and Nextcloud Mode, there is the "Cannot read property 'push' of undefined" error.

In Firefox and WebDav Mode, the sync deleted all Bookmarks ???, and displayed a short lockfile error i think.

### Software versions

* Browser: Firefox 61.0.2
* Browser: Chrome 68
* Nextcloud: 13.0.5
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 3.0.1

### Steps to reproduce

1. Updated Floccus
2. Sync
3. Error
...
4. Error no matter what i do

**Comment by marcelklehr** [comment]
Mh. Can you post your configuration?

**Comment by marcelklehr** [comment]
cc @jlbprof

**Comment by akidburn** [comment]
@marcelklehr 
I am not sure what you mean by configuration.

I do have backups, both in nc and as html, dont worry.

**Comment by marcelklehr** [comment]
> I am not sure what you mean by configuration.

Ah, sorry. I mean the options in your floccus account

**Comment by akidburn** [comment]
nextcloud:

server: https://dyndns-domain..... : port /

username
password

local folder: /Lesezeichen-Menü

server folder: empty
reset cache not set

**Comment by marcelklehr** [comment]
Thank you! As the nextcloud adapter issue is adressed now, I'll close this and direct you over to #152 where a discussion is going on about the WebDAV adapter deleting all bookmarks.

**Comment by marcelklehr** [comment]
Both issues should be fixed in v3.0.2 :)
