### ISSUE TITLE
Unrecognized manifest key 'applications'

### ISSUE THREAD

**Issue by k0a1a** [marcelklehr/floccus#15]
Getting this error in Chromium 57:

Errors
Unrecognized manifest key 'applications'.
{
   "applications": {
      "gecko": {
         "id": "floccus@handmadeideas.org",
         "strict_min_version": "48.0"
      }
   },

Any help is much appreciated!

**Comment by k0a1a** [comment]
ha, but it did sync after about 20 minutes!

**Comment by marcelklehr** [comment]
Yeah, that's just a warning, it doesn't mean that it's broken. I should probably put a note into the README about the sync interval...
