### ISSUE TITLE
floccus 3.0.1 syncing makes my firefox down

### ISSUE THREAD

**Issue by ytf4425** [marcelklehr/floccus#151]
When I first ran "sync now"(I mean that there's no .xbel file),it would make my firefox down
I have 985 items in my bookmarks

**Comment by ytf4425** [comment]
Besides, I'd like to ask that could you please add the function of "Download only" and "Upload only" to ensure that my first sync won't be wrong?

**Comment by marcelklehr** [comment]
> When I first ran "sync now"(I mean that there's no .xbel file),it would make my firefox down
I have 985 items in my bookmarks

Can you specify what you mean by "down"?

> Besides, I'd like to ask that could you please add the function of "Download only" and "Upload only" to ensure that my first sync won't be wrong?

There is an option to reset the cache, which ensures the next sync will be cumulative, i.e. nothing will get deleted.

**Comment by ytf4425** [comment]
> Can you specify what you mean by "down"?

Can't operate in the whole firefox window except switch among tabs
(Repeated many times that day but everything is OK today.)

> There is an option to reset the cache, which ensures the next sync will be cumulative, i.e. nothing will get deleted.

I mean "Reject local version" and "Reject online version".

Thanks

**Comment by Hillside502** [comment]
Any joy with v3.0.4 ?
https://github.com/marcelklehr/floccus/releases
https://addons.mozilla.org/en-US/firefox/addon/floccus/

**Comment by ytf4425** [comment]
It's OK now.
Continually observing and everything should be OK if I don't reply in 5 days

**Comment by ytf4425** [comment]
![qq 20180830193801](https://user-images.githubusercontent.com/4819825/44849317-4b170980-ac8c-11e8-875d-0df8bc55e068.png)

**Comment by marcelklehr** [comment]
@ytf4425 The initial sync can be a bit heavy on the CPU, but all consecutive syncs are incremental only, so those shouldn't be too heavy. The last error you posted has been covered over here: #157 I'll release a fix shortly.

**Comment by marcelklehr** [comment]
>>Can you specify what you mean by "down"?
>
>Can't operate in the whole firefox window except switch among tabs
(Repeated many times that day but everything is OK today.)
>
>>There is an option to reset the cache, which ensures the next sync will be cumulative, i.e. nothing will get deleted.
>
>I mean "Reject local version" and "Reject online version".

Mh. This should be implicitly possible by removing the local bookmarks to reject the local version and removing the online bookmarks to reject the online version, both before ticking reset cache and triggering a sync.

**Comment by ytf4425** [comment]
> Mh. This should be implicitly possible by removing the local bookmarks to reject the local version and removing the online bookmarks to reject the online version, both before ticking reset cache and triggering a sync.

Yes it is not a necessary function but to delete the bookmarks on Chrome you need to choose them one by one, which is too troublesome. 
As floccus has the privilidge to delete them, it will be much easier to use "Reject local version" to achieve it

**Comment by marcelklehr** [comment]
> delete the bookmarks on Chrome you need to choose them one by one

You can bulk select your bookmarks in chrome (as in most file browsers) by holding shift and clicking on start and end of a range you'd like to select, or by holding control and clicking the individual bookmarks. ;)
