### ISSUE TITLE
Bookmarks gone after XBEL sync

### ISSUE THREAD

**Issue by mort74** [marcelklehr/floccus#152]
### Software versions

* Browser: Firefox 61.0.2
* Nextcloud: 13.0.5
* Nextcloud Bookmarks app: -
* Floccus: 3.0.1

### Steps to reproduce

1. Entered credentials and new bookmarks.xbel for bookmarks bar
2. Clicked "Sync"

### Actual outcome

The first sync seems to have worked fine, I had a 60kB bookmarks.xbel on my server (which I luckily copied in time). Soon after, suddently all bookmarks in the bar were gone and the bookmarks.xbel was down to the core XML (XBEL tag and highestId comment).
Any tries to restore the bookmarks by restoring the saved bookmarks.xbel and removing (before file restore) and re-adding the account didn't work ("reset cache" option didn't make any difference), the bookmarks.xbel was stripped to it's core again.

**Comment by jlbprof** [comment]
Oh dear, if the xbel file is empty and you do not have them on your browser
your bookmarks are gone.   Did you save them before you installed Floccus?

**Comment by mort74** [comment]
As written, I've got a backup of the "filled" xbel, but restoring the bookmarks with it didn't work.
If that's not possible at all, I still got the bookmarks on other PCs, and somewhere there should be the .json export I used to copy them, so no worries there. :)
I'd just like to keep my bookmarks after a successfull restore and future sync as well.

**Comment by marcelklehr** [comment]
@mort74 Could you provide debug logs?

**Comment by marcelklehr** [comment]
This should be fixed in v3.0.2 now.

**Comment by marcelklehr** [comment]
@mort74 Note, that after installing the new release, you will need to tick the checkbox for "reset cache" in the options of your account and then put a copy of the old XBEL file in place.

**Comment by akidburn** [comment]
Works Perfectly.

And consumes notably less cpu on the server.
good work.

akidburn
