### ISSUE TITLE
securing credentials

### ISSUE THREAD

**Issue by jknockaert** [marcelklehr/floccus#154]
### Software versions

* Browser: FF 61.0.2 on Macos
* Floccus: 3.0.2 from Mozilla apps store

### Steps to reproduce

1. Install flocus
2. Click flocus buton and click "Secure your credentials"
3. Enter key (twice) and click "Secure accounts"
4. Enter key (again?) and click "Unlock"
5. Now the button "Add account" doesn't work
6. After closing and reopening the flocus interface "Secure your accounts" is unchecked and "Add account" doens't work

### Expected outcome

After securing with a key flocus should just work.

### Actual outcome

No way to set up with a key.

**Comment by marcelklehr** [comment]
Ah, thanks for the feedback! This should now be fixed in v3.0.3 (could take a bit until it passes mozillians' review)
