### ISSUE TITLE
Add way to list duplicate bookmarks

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#155]
I have hundreds of bookmarks and had some inadvertent dupes. Some I actually want that way, stored in two different folders, most I did not. So I used a SQL query on my NextCloud server to seek and destroy these dupes. It looks like this:

```
SELECT MAX(`oc_bookmarks`.title) AS title, COUNT(`tag`) AS count, GROUP_CONCAT(`tag` SEPARATOR "\n")
FROM `oc_bookmarks_tags` 
INNER JOIN `oc_bookmarks` 
ON `oc_bookmarks`.id = `oc_bookmarks_tags`.bookmark_id 
GROUP BY `bookmark_id` 
HAVING count > 1
```

Not everyone is going to have the skills or time to do that though, and it might be easy enough to do the equivalent in the browser add-on directly, from a link on the toolbar drop down and/or the config page, just throw up a list of links that are found more than once with their titles and folders and that's enough to hunt them down and fix them.

If it was fancy, it would have a check box beside each dupe to flag it as desired and hide it from subsequent searches. But bells and whistles and all that, enough just to provide a list like this query provides (which on the the server end not the client end).

**Comment by marcelklehr** [comment]
Mmh. while this seems to be a useful feature, I'm not sure it is essential to syncing bookmarks. A quick search yielded the following extension which seems to provide the functionality you're looking for: https://addons.mozilla.org/en-US/firefox/addon/bookmark-deduplicator/

**Comment by jd666** [comment]
I rely on an extension that saves the current session as a bookmark tree. So a de-duplication would be detrimental, I think having it as a separate addon is the better idea.

**Comment by bernd-wechner** [comment]
I'd be fine with that. No drama at all. Part of me thinks it's nice to keep stuff well integrated and I do see dupe finding as part of the scope of syncing if only at the level of disaster recovery and debugging (if dupes happen to be created en masse). Bug totally agree non essential and in a world where the sync works flawlessly not any more important than having debug logs easily accessible is. 

Alas the recommended add on is listed as "This add-on is not compatible with your version of Firefox." and seems unmaintained, but hey it's not a person issue as I have the SQL solution above anyhow (which is one reason I LOVE floccus/Nexctloud as a solution as it grants me access to the back end for diagnostics , fixes, backup and more).

**Comment by bernd-wechner** [comment]
Here's another, also unmaintained and not working:

https://addons.mozilla.org/en-US/firefox/addon/bookmark-duplicate-cleaner/

**Comment by bernd-wechner** [comment]
And here's one that is current and seems maintained:

https://addons.mozilla.org/en-US/firefox/addon/bookmark-dupes

**Comment by marcelklehr** [comment]
I'll add a link to that addon in the readme.
