### ISSUE TITLE
Password with a € doesn't work

### ISSUE THREAD

**Issue by fragadass** [marcelklehr/floccus#156]
### Software versions

* Browser: Firefox 61.0.2 (64 bits)
* Nextcloud: 13.0.0
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 3.0.3

### Steps to reproduce

1. Put a backslash \ in your Nextcloud's user's password
2. Put the same in floccus config
3. Sync fails
4. There is a double backslash in the storage.js file

### Expected outcome

Can you encrypt the password instead ? The password is stored without any encryption, even if we put a passphrase on the extension, this is unsafe !

### Actual outcome

When I changed my password to a weaker one, it worked.

**Comment by marcelklehr** [comment]
hey @fragadass 
Interesting find! I'll investigate

> Can you encrypt the password instead ? The password is stored without any encryption, even if we put a passphrase on the extension, this is unsafe !

If you secure your credentials with a passphrase, then your password is not stored in plain text, but encrypted. If that's not the case, that'd be a bug.

**Comment by marcelklehr** [comment]
The double backslash appears to be a simple case of an escaped character as required by javascript strings (the file you mention is a javascript file). So, that's not the reason the sync fails. It could be that nextcloud has trouble with backslashes in passwords. Have you tried your password with ather clients, like the News reader app or any other third-party clients?

**Comment by marcelklehr** [comment]
I cannot replicate this with Nextcloud 13.0.5 and Bookmarks v0.12.0.

**Comment by fragadass** [comment]
Hi.

I have upgraded Nextcloud to 10.0.4 version and Bookmarks to 0.14.2 version, but I have the same problem.
I have made a few tests and found what's wrong in my password : the € (euro) symbol.

**Comment by marcelklehr** [comment]
Does the same password work in other clients, e.g. the nextcloud android app?

**Comment by fragadass** [comment]
Yes, with a calendar app (using CalDAV) and a contact one (using CardDAV).

**Comment by marcelklehr** [comment]
Thanks for not giving up and reporting this! I've found the culprit and will release the fix shortly :)

**Comment by fragadass** [comment]
Thanks for solving it ;)
I've updated the plugin and it works with my european password :D
