### ISSUE TITLE
Chrome won't download bookmarks from NextCloud

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#158]
OK, I have floccus working beautifully between Firefox instances at home and work. Thumbs up.

Now I tried my first Chrome instance. I first deleted all my local bookmarks. Clean slate. Then installed NextCloud from the Chrome store, and configured my server. I click Sync Now and it finishes fast and does nothing. 

I checked the logs, and it sees all my bookmarks on the server fine. But crucial bits just before th end sync look like this:
```
COMPARE { localItem: 
     + Bookmarks bar
   ,
  cacheItem: null,
  serverItem: undefined }
(nextcloud)CREATEFOLDER { parentId: '', title: 'Bookmarks bar' } (noop)
COMPARE { localItem: 
     + Other bookmarks
   ,
  cacheItem: null,
  serverItem: undefined }
(nextcloud)CREATEFOLDER { parentId: '', title: 'Other bookmarks' } (noop)
```

which looks suspicious. But I can't interpret it. Can provide whole log if it helps.  But it may be a use case that rings bells. New install, No bookmarks. What should happen? Server marks downloaded and installed I guess (as a special outcome of server marks downloaded, compared and merged).

**Comment by marcelklehr** [comment]
Thanks for reporting! :)
