### ISSUE TITLE
Need to protect the server password

### ISSUE THREAD

**Issue by nachoparker** [marcelklehr/floccus#159]
Hello,

First, thank you for your hard work in this addon. I have been using it for a few days and it is really nice!!

The only bad thing I see about it is sadly a serious one. I downloaded the debug log and to my surprise there it was, my server's password.

A simple `grep -r mypass` in the `~/.mozilla` folder showed me that any agent that manages read access to this folder will immediately gain access to my private cloud where I store all my sensitive private information.

What would be the best way to grant access without storing the password in plain text? Maybe the user could be required to generate a random tokens to decrypt the password that then would only be unencrypted in memory before being sent through HTTPS.

Thoughts?

**Comment by marcelklehr** [comment]
Hey nacho! Thanks for your kind words :)
The password leakage you mention is actually a regression, as the passwords are persisted in an encrypted fashion if you set a n extension passphrase, but the logging mechanism doesn't care about that, yet. I'll get on it :)

**Comment by nachoparker** [comment]
Thank you! that was fast!

my password is still in cleartext in `firefox/w24O4c.default/browser-extension-data/floccus@handmadeideas.org/storage.js`, I think it should  be somehow encrypted

**Comment by marcelklehr** [comment]
Have you set a passphrase and restarted your browser? I think, that file is only written when you close the browser.

**Comment by nachoparker** [comment]
I have, but the password is still there

**Comment by marcelklehr** [comment]
Fooo. That's tough. Which adapter? Which firefox version?

**Comment by nachoparker** [comment]
firefox 61.0.2

adapter? what is an adapter?

**Comment by marcelklehr** [comment]
Sorry. Which backend are you using? XBEL/WebDAV or Nextcloud Bookmarks? :)

**Comment by nachoparker** [comment]
aah :D 

NC bookmarks

**Comment by marcelklehr** [comment]
Which floccus version?

**Comment by nachoparker** [comment]
floccus 3.0.6

**Comment by marcelklehr** [comment]
Aah, now I get it. The logs are not cleared, of course, so the existing log data that still contain the password are of course still there. You can uninstall and reinstall the extension to fix that. (You really had my questioning myself there :D)

**Comment by marcelklehr** [comment]
> I suggest you make password protection mandatory, non optional in order to protect your users. We all know that most people will not protect their passwords otherwise.

Good idea! :)
