### ISSUE TITLE
Odd bookmark folder created - Nextcloud (me@https://myserver.net)

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#161]
I just added floccus to another Chrome instance and and an wrangling with the merge because I forgot to kill all my Chrome bookmarks, oh well. Standard issue of dupes to contend with. But of great surpise to me was the appearance on my bookarks bar of a new folder with the name:

me@https://myserver.net  (in form)

under which was a folder called BookmarksBar and all my toolbar bookmarks repeated. Hmmm. Just thought I'd flag it in case it rings any bells. 

In all honesty I probably have floccus running on a Firefox and Chrome instance in the office right now too. But what I can assure you is that I have never manually created such a folder, which why I flag it. It is clearly some invention of floccus' given it bears the name of my nextcloud account.

I do have complete logs it seems if you'd like me to submit them but as they are full of personal bookmarks I'd send them P2P rather than post on a public issue. It may be hard to diagnose and an odd one off due to some sequence of events I engaged in (when I added floccus to Chrome here I accidentally got my nextcloud password wrong for example and had to try again, not hat that should make any difference, but little things like that will have happened).

I should add, that it took over an hour to complete a sync! I do have about 700 bookmarks, but still ... that's fairly surprising ...

**Comment by marcelklehr** [comment]
If you have such a folder, it means floccus created it for you. It does that by default, if you don't select a different folder to sync. It could be that you have two nested accounts somewhere, but I doubt it, as floccus should not sync the nested ones. So, you should check the sync folder option for the account in the browser where the folder appeared. It should probably be the root folder.

**Comment by marcelklehr** [comment]
> I should add, that it took over an hour to complete a sync! I do have about 700 bookmarks, but still ... that's fairly surprising ...

It could be that your nextcloud server is throttling your requests due to failed login attempts (I've just experienced this myself with my dev instance, not pretty. 25s and more per request and no way to turn it off, afaik...)

**Comment by marcelklehr** [comment]
Did this resolve your issues?
