### ISSUE TITLE
failed GET request

### ISSUE THREAD

**Issue by Hakker** [marcelklehr/floccus#163]
### Software versions

* Browser: Firefox 61.0
* Nextcloud: 1.3.0.1
* Nextcloud Bookmarks app: Bookmarks
* Floccus: latest

### Steps to reproduce
Filled in the webdav address, my username and password.
Verified that webdav works
selected Bookmarks Menu, saved and try to sync.

### Expected outcome
Start syncing

### Actual outcome
Error!
Failed GET request

### Log
Starting sync process for account User@http://255.255.255.255:25555/remote.php/webdav/ Logger.js:10:4
Overriding title of built-in node menu________ Bookmarks Menu => Bookmarks Menu Logger.js:10:4
Fetching bookmarks Logger.js:10:4
Error: "Failed GET request"
_callee15$moz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/background-script.js:26940:23tryCatchmoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/polyfill.js:6900:37invokemoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/polyfill.js:7138:22methodmoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/polyfill.js:6952:16stepmoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/background-script.js:26124:183stepmoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/background-script.js:26124:361runmoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/polyfill.js:4295:22notifymoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/polyfill.js:4308:30flushmoz-extension://8b6efd10-af6e-4b51-ad9b-bdf7c0d7f2e3/dist/js/polyfill.js:1398:9 Account.js:170:6
Syncing failed with Failed GET request Account.js:172:6
Use of nsIFile in content process is deprecated.
NetUtil.jsm:302:12

username and ip:port obfuscated for the obvious reason.

**Comment by marcelklehr** [comment]
Did you select the WebDAV adapter when adding the account? (The account overview should show the account with a `webdav` tag instead of `nextcloud`.)

**Comment by Hakker** [comment]
ugh stupid me. You were right I was trying to use webdav where I should've used the base url of the server.

**Comment by marcelklehr** [comment]
Glad it works now :)
