### ISSUE TITLE
Bookmarklets are being removed in second sync

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#165]

**Comment by hg42** [comment]
Hi, I am a new user to floccus.
Does this issue mean, I have to worry about my bookmarklets?
I have a full folder of those in my bookmarks...
Can I protect them somehow?

**Comment by marcelklehr** [comment]
Hey Harald :)

I'm sorry you're facing this issue.

> Does this issue mean, I have to worry about my bookmarklets?
You only have to worry if you're syncing with the nextcloud bookmarks app. They might get deleted the second time floccus syncs to the same server in one browser.

> Can I protect them somehow?
A workaround would be to create a second account in floccus with credentials that don't work and select the bookmarklet folder as the folder to sync. This way the other account will ignore the folder, because it belongs to a different account and the new account will not be able to delete them, because the credentials don't work. Not pretty, nut should do the trick.

**Comment by t3mujin** [comment]
> and what does "second sync" exactly mean? the second in the same browser?

Basically when it syncs again after the bookmarklets are sent to the server on the initial sync after the bookmark has been created, when they're pulled back floccus thinks it has been removed (and they were, by Nextcloud Bookmarks). For better organization and consistence between different browsers I have split my bookmarks in two different accounts:
- One for the toolbar, where are my bookmarklets and where I use the WebDav option (that has no problems with bookmarklets),
- Another for the bookmarks library, where I sync with Nextcloud Bookmarks, and in the end these were the ones I wanted synced to Nextcloud.

**Comment by hg42** [comment]
Thanks, I am using webdav for my bookmarks. And it did it's second sync already.

**Comment by marcelklehr** [comment]
So, the bookmarks app still doesn't support bookmarklets, but at least they're not removed by floccus anymore as a result now :)
