### ISSUE TITLE
bookmarksCache is not defined.

### ISSUE THREAD

**Issue by jlbprof** [marcelklehr/floccus#166]
### Software versions

* Browser: Chrome latest
* Nextcloud: Nextcloud latest
* Nextcloud Bookmarks app:
* Floccus: 3.0.7

### Steps to reproduce

1. ... Run webdav sync
2.

### Expected outcome

...

### Actual outcome
WebDav.js:49 GET https://plex.jlbprof.com:8008/nextcloud/remote.php/webdav/bookmarks.xbel.lock 404 (Not Found)
_callee$ @ WebDav.js:49
tryCatch @ polyfill.js:6900
invoke @ polyfill.js:7138
prototype.(anonymous function) @ polyfill.js:6952
step @ background-script.js:27191
(anonymous) @ background-script.js:27191
(anonymous) @ background-script.js:27191
downloadFile @ background-script.js:27278
_callee2$ @ WebDav.js:72
tryCatch @ polyfill.js:6900
invoke @ polyfill.js:7138
prototype.(anonymous function) @ polyfill.js:6952
step @ background-script.js:27191
(anonymous) @ background-script.js:27191
(anonymous) @ background-script.js:27191
checkLock @ background-script.js:27318
_callee4$ @ WebDav.js:110
tryCatch @ polyfill.js:6900
invoke @ polyfill.js:7138
prototype.(anonymous function) @ polyfill.js:6952
step @ background-script.js:27191
(anonymous) @ background-script.js:27191
(anonymous) @ background-script.js:27191
obtainLock @ background-script.js:27467
_callee7$ @ WebDav.js:220
tryCatch @ polyfill.js:6900
invoke @ polyfill.js:7138
prototype.(anonymous function) @ polyfill.js:6952
step @ background-script.js:27191
(anonymous) @ background-script.js:27191
(anonymous) @ background-script.js:27191
onSyncStart @ WebDav.js:234
_callee9$ @ Account.js:136
tryCatch @ polyfill.js:6900
invoke @ polyfill.js:7138
prototype.(anonymous function) @ polyfill.js:6952
step @ Account.js:10
(anonymous) @ Account.js:10
Promise.then (async)
step @ Account.js:10
(anonymous) @ Account.js:10
Promise.then (async)
step @ Account.js:10
(anonymous) @ Account.js:10
(anonymous) @ Account.js:10
sync @ background-script.js:21360
_callee8$ @ Controller.js:191
tryCatch @ polyfill.js:6900
invoke @ polyfill.js:7138
prototype.(anonymous function) @ polyfill.js:6952
step @ Controller.js:5
(anonymous) @ Controller.js:5
Promise.then (async)
step @ Controller.js:5
(anonymous) @ Controller.js:5
(anonymous) @ Controller.js:5
syncAccount @ Controller.js:195
(anonymous) @ Controller.js:21
Promise.then (async)
syncAllAccounts @ Controller.js:18
(anonymous) @ Controller.js:52
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
dispatchArgs @ extensions::event_bindings:260
dispatchEvent @ extensions::event_bindings:269
Logger.js:10 https://plex.jlbprof.com:8008/nextcloud/remote.php/webdav/bookmarks.xbel.lock
Account.js:170 ReferenceError: bookmarksCache is not defined
    at WebDavAdapter._callee6$ (WebDav.js:205)
    at tryCatch (polyfill.js:6900)
    at Generator.invoke [as _invoke] (polyfill.js:7138)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:6952:21)
    at step (background-script.js:27191)
    at background-script.js:27191

Looking at the code:

      let bookmarkCache = new Folder({ id: 0, title: 'root' })
      parseXbelDoc(xmlDoc, bookmarksCache)
      this.bookmarksCache = bookmarksCache.clone()

      Logger.log('parseXbel')
      Logger.log(bookmarksCache)

It is failing on the line bookmarksCache.clone ().

Did you change the constructor for Folder?   Do we need to update the line with new Folder?

Thanx

Julian

**Comment by marcelklehr** [comment]
It was a typo:

  let bookmarkCache = new Folder({ id: 0, title: 'root' })
  parseXbelDoc(xmlDoc, bookmark**s**Cache)

:see_no_evil:
