### ISSUE TITLE
Browser updates stealing focus

### ISSUE THREAD

**Issue by mobamoba** [marcelklehr/floccus#167]
### Software versions

* Browser: Chrome, Firefox
* Nextcloud:
* Nextcloud Bookmarks app:
* Floccus:

### Steps to reproduce

1. There's something in Floccus that steals focus when Floccus updates in both Firefox and Chrome. For example, if I'm in Firefox and Floccus updates in the background, it then opens the Add-ons tab and changes focus to that tab while I'm doing other work. With Chrome, if it's minimized, Floccus, when updating itself, maximizes it and takes me to the Extensions page.

Given that literally no other Firefox Addon or Chrome Extension I have installed does this, it's some kind of bug/setting with Floccus. I have no idea how to debug this for you as it happens when Floccus background updates, but I'm hoping you know how to stop it because, as I'm sure you can imagine, it's frustrating behavior on the part of the extension.

Thanks.

### Expected outcome

...

### Actual outcome

...

**Comment by marcelklehr** [comment]
Mh. Yeah I can imagine that this doesn't have the intended effect. It was once added as a feature, but alas. Let's remove it. I'm not quite fond of unsolicited background updates, as it's sometimes necessary for the user to take action after an update, but you're right that the current behavior is useless.
