### ISSUE TITLE
"Server folder" emtpy creates "flocus:" on server

### ISSUE THREAD

**Issue by enboig** [marcelklehr/floccus#170]
I left the "Server folder" empty for no prefix, and a "floccus:" folder/tag appeared on my server and only bookmarks with this tag are synced; and bookmarks added with browser get this tag on server also. Should'nt this option sync all bookmarks?

* Browser: Firefox
* Nextcloud: 13.0.6
* Nextcloud Bookmarks app: 0.12.2
* Floccus: 3.0.8

### Steps to reproduce
I removed the extension, reinstalled it, and the problem continues

### Expected outcome
If no prefix specified, all bookmarks should sync.

### Actual outcome
Only some bookmarks sync.

Thanks for your job (and time!)

**Comment by marcelklehr** [comment]
Did this solve your issue? (I'm working on folder support for the bookmarks app, so things will hopefully be much easier soon ;) )

**Comment by enboig** [comment]
So the idea is to export my server bookmarks, import them in firefox (inside my synced folder). Wouldn't this remove any tags from my bookmarks?

**Comment by marcelklehr** [comment]
> Wouldn't this remove any tags from my bookmarks?
Floccus should preserve any tags that are not prefixed with `floccus:`, but it currently doesn't indeed, I just checked :S 

Then the only way is to select all bookmarks on the server and add the tag `floccus:`

**Comment by marcelklehr** [comment]
Fixed by https://github.com/marcelklehr/floccus/commit/32685a4082e50687b99bb312dfaa471c62ae9a83
