### ISSUE TITLE
webdav: sync success but no file in webdav

### ISSUE THREAD

**Issue by NanerLee** [marcelklehr/floccus#171]
### Software versions

* Browser: chrome  69.0.3497.100
* Webdav: nutstore
* Floccus: 3.0.8

### Steps to reproduce

1. install floccus
2. config webdav
3. sync now

### Expected outcome

sync success and there will be a xbel file in my cloud storage

### Actual outcome

sync success but no file exists in cloud storage

------------------

what's more, there is a strange phenomenon:

when i set **Bookmarks file path** as `bookmarks/bookmarks.xbel`, it will tell me a networkerror: Unable to determine status of lock file

this phenomenon is similar to this [link](https://github.com/marcelklehr/floccus/issues/131#issuecomment-415068233), but i am sure that i fill it with relative path and folders exist already on the server

**Comment by HugoHotzenplotz** [comment]
I had the same problem using the same software.
My mistake was the Bookmarks file path. On my first try i used "bookmarks.xbel". I saw a sync success, but also had no file. The reason was: missing permissions. I then made  a small modification and all was fine.

**Software:**

- Browser: chrome 69.0.3497.100
- Webdav: Synology DS3515xs (DSM 6.1.7-15284 U2, WebDAV Version (from Synology Store): 2.3.4-0025)
- Floccus: 3.0.8


**Options in Floccus:**
_WebDAV URL:_ https://FQHN:3006/
_Username:_ xx
_Password:_ xx
_Bookmarks file path:_ home/bookmarks.xbel (folder home exists)
_local folder:_ *Root folder*
_reset cache_ [x]

**Actual Outcome**
in options:
✔ all good
Last synchronized: xx seconds ago

**Comment by NanerLee** [comment]
@marcelklehr 
this is sync success but no file:

```
Starting sync process for account XXX@https://dav.jianguoyun.com/dav/
onSyncStart: begin
https://dav.jianguoyun.com/dav/bookmarks.xbel.lock
https://dav.jianguoyun.com/dav/bookmarks.xbel.lock
onSyncStart: completed
COMPARE { localItem: 
     + test
       - [Google](https://www.google.com/),
  cacheItem: 
     + undefined
   ,
  serverItem: 
     + root
    }
Checking subtree of  { localItem: 
     + test
       - [Google](https://www.google.com/),
  serverItem: 
     + root
    }
COMPARE { localItem:   - [Google](https://www.google.com/),
  cacheItem: null,
  serverItem: undefined }
CREATE     - [Google](https://www.google.com/)
onSyncComplete
    + root
      - [Google](https://www.google.com/)
fullURL :https://dav.jianguoyun.com/dav/bookmarks.xbel:
Successfully ended sync process for account 
XXX@https://dav.jianguoyun.com/dav/
```

this is change the path to `bookmarks/bookmarks.xbel`, then fail

```
Starting sync process for account 820129254@qq.com@https://dav.jianguoyun.com/dav/
onSyncStart: begin
https://dav.jianguoyun.com/dav/bookmarks/bookmarks.xbel.lock
https://dav.jianguoyun.com/dav/bookmarks/bookmarks.xbel.lock
https://dav.jianguoyun.com/dav/bookmarks/bookmarks.xbel.lock
https://dav.jianguoyun.com/dav/bookmarks/bookmarks.xbel.lock
https://dav.jianguoyun.com/dav/bookmarks/bookmarks.xbel.lock
https://dav.jianguoyun.com/dav/bookmarks/bookmarks.xbel.lock
onSyncFail
```

**Comment by jlbprof** [comment]
In webdav you need to create the directory first, then you can sync to it.
 The webdav driver does not create directories.

**Comment by NanerLee** [comment]
@jlbprof 
> i am sure that i fill it with relative path and folders exist already on the server

**Comment by marcelklehr** [comment]
I could reproduce this by not adding the nutstore folder to the bookmarks file path. The default nutstore folder is `我的坚果云/` (see the sidebar on the left, where you can add more folders), so if you want your bookmarks file in there, use `我的坚果云/bookmarks.xbel` as the bookmarks file path. Also, be sure to use your mail address as the user name. The nutstore UI is a bit confusing. Let me know if this solves your issues :)

**Comment by NanerLee** [comment]
Thanks a lot @marcelklehr! 

When i use `我的坚果云/bookmarks.xbel`or `我的坚果云/bookmarks/bookmarks.xbel` as the bookmarks file path, it works.

It is strange that the prefix -- `我的坚果云` is unnecessary for others webdav apps in offical Nutstore documents. Because it saves file in `我的坚果云` by default.

Anyway, you solves my problem, thank you !
