### ISSUE TITLE
NC14: Failed POST request

### ISSUE THREAD

**Issue by thd6n75** [marcelklehr/floccus#174]
### Software versions

* Browser: Firefox 62 and Chromium 69
* Nextcloud: 14.0
* Nextcloud Bookmarks app: 0.13.0
* Floccus: Whatever the current one on https://addons.mozilla.org/en-US/firefox/addon/floccus/ (and whatever the current one is for Chromium too)

### Steps to reproduce

1. Fresh install of NC 14 via Docker
2. Install Bookmarks plugin in NC
3. Install Floccus browser plugin in Firefox
4. Add account
5. Sync bookmarks.  Many bookmarks successfully show up in NC

### Expected outcome

Sync without errors

### Actual outcome

Eventually, Floccus stops and shows a red `!` and says  `Failed POST request`

This behavior occurs both in Chromium and Firefox.  Here's some logs from Floccus debug mode on Chromium:

```
Nextcloud.js:451
POST https://MYNC/index.php/apps/bookmarks/public/rest/v2/bookmark 504
```

```
Account.js:170
MultiError: 1 errors
    at task.then.catch.err (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/background-script.js:423:36)
```

```
Account.js:190
Error: Failed POST request
    at NextcloudAdapter._callee15$ (Nextcloud.js:471)
    at tryCatch (polyfill.js:6900)
    at Generator.invoke [as _invoke] (polyfill.js:7138)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:6952:21)
    at step (background-script.js:26125)
    at background-script.js:26125
```

**Comment by marcelklehr** [comment]
504 means [Gateway timeout](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors). I'll need to refine the error messages in the UI to provide more information for fixing things. For you this probably means that your server was overwhelmed by the amount of stress adding all the new bookmarks put on it. You should be fine if you simply let floccus sync whenever it feels like it. Over time your server should recover.

**Comment by thd6n75** [comment]
I resolved this be increasing timeouts in my nginx proxy

**Comment by marcelklehr** [comment]
Ah, that would have been my next suggestion.
