### ISSUE TITLE
Local sync proposal

### ISSUE THREAD

**Issue by lightdot** [marcelklehr/floccus#177]
When using several browsers and/or browser user profiles or on the same machine, a local sync could be more than enough.

No need to upload to a WebDAV or any other server, a sync directory would be kept and accessed locally.

Perhaps something like ~/.local/share/floccus on linux and equivalent locations on other OSes, basically behaving completely like a WebDAV storage does now.

**Comment by jlbprof** [comment]
I do not believe there is a way to access the local disk.  Am I wrong?

**Comment by lightdot** [comment]
I just did a quick search (as i should have before) and it seems that it indeed isn't possible.

Native Messaging could be used but this approach of course requires an external program to handle the data. One might as well run a local WebDAV server instead.

Which is a viable solution in any case.

**Comment by jlbprof** [comment]
https://helpcenter.onlyoffice.com/server/community/connect-webdav-server-windows.aspx

For Windows, apparently we can have a local IIS server on a non-server box.

Julian
