### ISSUE TITLE
floccus.log size and name

### ISSUE THREAD

**Issue by lightdot** [marcelklehr/floccus#178]
Just noticed that the floccus.log:
* is getting bigger and bigger
* always has the same name when saving.

Well, perhaps I just haven't used Floccus long enough to see the log recycled or limited in size... In this case please disregard this part, naturally.

I also suggest appending a browser name and a timestamp to the filename when saving the log trough the UI.

I tested Floccus in several different browsers on the same machine and this would have simplified it.

Eventually, turning the log off by default and having an on/off switch would probably be a good idea.

**Comment by marcelklehr** [comment]
Hey! Thanks for your feedback! :)

> is getting bigger and bigger
Perhaps I'll have to reduce the rotation size. Chrome simply stops allowing writes at some point, so I'd like to avoid that, of course.

> always has the same name when saving
That's a good idea! :)

> turning the log off by default and having an on/off switch

mmh. I'd rather have the log always available in case something unexpected happens. It doesn't hit performance too hard, I think.
