### ISSUE TITLE
rss-bookmarks are deleted when saved inside a folder after sync

### ISSUE THREAD

**Issue by blu-IT** [marcelklehr/floccus#182]
### Software versions

* Browser: FF 62.0.3 (64-bit)
* Nextcloud: 13.0.6
* Nextcloud Bookmarks app: 0.12.2
* Floccus: 3.0.10

### Steps to reproduce

1. Create a new bookmark folder in the bookmark menu bar
2. Create/save a rss-bookmark inside that folder

### Expected outcome

Folder and rss-bookmarks are synced with nexctcloud.

### Actual outcome

Folder (and rss-bookmark) is **deleted** (!) after sync.

This does **not** happen, when the rss-bookmark is saved **directly** into the bookmark menu bar, only when it is saved inside a folder.

**Comment by marcelklehr** [comment]
Hey, thanks for your feedback!

Unfortunately the firefox team has decided to abandon live bookmarks entirely (see https://bugzilla.mozilla.org/show_bug.cgi?id=1477667 ), which also makes them indistinguishable from any other bookmark for floccus. Unless the same behavior also occurs with normal bookmarks I'm gonna chalk this up to the aforementioned abandonment, which means I can't fix this this.

**Comment by marcelklehr** [comment]
The fix for https://github.com/marcelklehr/floccus/issues/165 should technically also fix this issue. It would be helpful if you could test this, once the new release is out.

**Comment by marcelklehr** [comment]
v3.1.7 has been released

**Comment by blu-IT** [comment]
Seems to work..., RSS-bookmarks/folder are still visible in my bookmarkbar :-)

Thanks!

**Comment by marcelklehr** [comment]
Awesome! :)
