### ISSUE TITLE
Link changes after Sync

### ISSUE THREAD

**Issue by marcohald** [marcelklehr/floccus#183]
### Software versions

* Browser: source: Chrome 69 dest: Firefox 62.0.3
* Nextcloud: 14.0.1
* Nextcloud Bookmarks app: 	0.13.0
* Floccus: 3.0.10

### Steps to reproduce

Create a Bookmark with the Link https://t.17track.net/de#nums=3DLF423238655CN
Sync bookmarks on source Browser
Sync bookmarks to destination Browser

### Expected outcome

Link should be the same

### Actual outcome

Link changes to https://t.17track.net/de#nums%3D3DLF423238655CN
And Site does not work.
The same behaviour could be seen on geizhals.de

**Comment by marcelklehr** [comment]
Thanks for reporting this!

This is actually a problem with nextcloud bookmarks, as it normalizes the URLs it stores.

**Comment by marcelklehr** [comment]
This is addressed by https://github.com/nextcloud/bookmarks/pull/587
