### ISSUE TITLE
While rearranging, bookmarks disappeared locally and put into "undefined" tag

### ISSUE THREAD

**Issue by aktentasche** [marcelklehr/floccus#184]
### Software versions

* Browser: Firefox 60.1.0esr 
* Nextcloud: 13.0.6
* Nextcloud Bookmarks app:
* Floccus: 3.0.10 via Firefox store

### Steps to reproduce
1. Move several bookmarks from the bookmarks toolbar into folders in the toolbar
(2. sync happens automatically)
3. Bookmarks disappear

### Expected outcome
Bookmarks do not disappear

### Actual outcome
First it looked like I lost a lot of bookmarks, but when I checked the bookmarks app in nextcloud, I saw they where still there but with a weird tag:

Normally it looks like this:
floccus:>MYTAG>Bookmarks Bar>wiki>Stuff

but the ones that disappeared are tagged like this:
floccus:>MYTAGundefined

I think this might be caused by the fact that I moved items while sync was still happening. Possible safety check would be to catch the situation when this happens and stop the sync process.

edit: correction, it actually looks like I lost bookmarks but will be able to reconstruct them from the debug log.

**Comment by marcelklehr** [comment]
Could you send me an excerpt of the debug log when this happened?

**Comment by aktentasche** [comment]
Yes, I will send it by mail as this is my work PC and I don't want to upload the doc here.

**Comment by marcelklehr** [comment]
I think I could reproduce the problems individually. The undefined tag was a separate issue from the disappearing bookmarks. It also didn't have anything to do with you changing things while the sync was running, but rather that you did some complex rearrangement that proved some of my assumptions in the sync algorithm to be false, causing those bookmarks to disappear or go haywire. I have added tests for these issues now, and fixed them. I will release a new version shortly.
