### ISSUE TITLE
@-symbol in username

### ISSUE THREAD

**Issue by brjhaverkamp** [marcelklehr/floccus#185]
I am just starting with the bookmark app in nextcloud.
I have set it up on nextcloud. Now I am trying the firefox add-on.
During setup I am getting the following error:
Network Error: Check your network connection and your account details.
It all looks good however, I have my account name set up as my email address "bert@bertenselena.net"

This results in the string bert@mydomain.net@mydomain.net/nextcloud.
Is the @-symbol allowed in this add-on, or does it break on this?

If so, this should be regarded as a bug report, since Nextcloud does allow such usernames.
If not, what else could be wrong. I disabled sync. (or at  least I think I did. How can you double check this?)

Regards,

Bert

**Comment by marcelklehr** [comment]
Hey @brjhaverkamp 
@-symbols in usernames shouldn't be a problem. Is there anything in the debug logs?

**Comment by marcelklehr** [comment]
Have you been able to connect to your nextcloud in the meantime? If not, feel free to comment here and I'll reopen :)
