### ISSUE TITLE
[usability] focus on the password field automatically and send password with enter

### ISSUE THREAD

**Issue by nachoparker** [marcelklehr/floccus#187]
This simple two things would make the user experience much better.

You have to click floccus, then the text box, then input the password, then grab the mouse and click on submit.

Instead it would be click foccus, then type password and hit enter.

Thanks again for floccus!

**Comment by marcelklehr** [comment]
That's a good idea. Thanks for the feedback! :)

**Comment by nachoparker** [comment]
Hi!

It seems like there was a regression, now the password field is automatically focused, but hitting enter does not try to log in. I have to grab the mouse and click the button.

Using latest FF

Thanks!
