### ISSUE TITLE
Opera support?

### ISSUE THREAD

**Issue by vrs01** [marcelklehr/floccus#19]
Hi!

Does floccus work with Opera?

Best, vrs01

**Comment by marcelklehr** [comment]
My claim that floccus works with Opera is based on their claim that they support WebExtensions (and the specfic APIs that floccus uses). I have not personally tested floccus in Opera. If you do, let me know here. :)

**Comment by vrs01** [comment]
I can install the chrome version in Opera! I will try to sync some bookmarks now.

**Comment by copynpaste** [comment]
It is working, I'm already using it :wink:

**Comment by marcelklehr** [comment]
awesome! thanks guys :)

**Comment by marcelklehr** [comment]
If you like you could open a pull request adding installation instructions for opera to the readme...

**Comment by sehucke** [comment]
Has someone tried this with the mobile version of Opera, too? :-) Otherwise, I will do ... Since Firefox still lacks the bookmarks API, I need an alternative that is privacy-friendly and allows for self-hosting the sync.
