### ISSUE TITLE
XBEL Upload to OC not possible if server running on arbitrary port

### ISSUE THREAD

**Issue by tkurbad** [marcelklehr/floccus#195]
### Software versions

* Browser: Chromium 70.0.3538.35 (Gentoo Linux)
* Nextcloud: OC 10.0.10.4
* Nextcloud Bookmarks app: 0.10.4
* Floccus: 3.1.3

### Steps to reproduce
1. Set up an owncloud server with HTTPS on an arbitrary port (in my case 7443)
2. Set up floccus to do an XBEL sync to this server (include the port in the URL)

### Expected outcome
floccus should sync my bookmarks to the owncloud file space via WebDAV.

### Actual outcome
The XBEL lock file is created, but as soon as the XBEL file itself should be uploaded, a 403 error occurs.

I cross checked with another owncloud instance of roughly the same version running on port 443. There, it works flawlessly.

Any feedback would be appreciated!

Best,
Torsten

**Comment by marcelklehr** [comment]
Are you able to access the file on that arbitrary port with a different HTTP client, e.g. curl?

**Comment by tkurbad** [comment]
Nevermind, after catching up on my reading I decided to migrate to NextCloud anyway. Will try again then with the new bookmarks plugin.

Thanks,
Torsten
