### ISSUE TITLE
Sync of bookmarks stop with "body.append is not a function"

### ISSUE THREAD

**Issue by Liam-Lior** [marcelklehr/floccus#196]
Hey there,

I've problems to sync my bookmarks. As already some bookmarks are already synced he try to update some, and that's the point where I got some errors.
Floccus: 3.1.4 (selected account type: "Nextcloud Bookmarks (v0.14+)")
Nextcloud: 14.0.3
Bookmarks Plugin in NC: 0.14.2

![bildschirmfoto von 2018-11-16 20-09-08](https://user-images.githubusercontent.com/676650/48642261-9d8adb00-e9dc-11e8-804f-3e6a64bb5ae6.png)
As shown in the screenshot the extensions try to add some data to a string with a append method which is not available for this type of data (maybe a leftover from from previous version where the URLSearchParams-object is used). This results in an exception and displays the message "body.append is not a function" within the sync popup.

**Comment by marcelklehr** [comment]
Thanks for reporting!
