### ISSUE TITLE
Invalid  Bookmark error on first sync

### ISSUE THREAD

**Issue by chhinze** [marcelklehr/floccus#197]
### Software versions

* Browser: Firefox 63.0.3 (64-Bit), Firefox sync is turned off
* Nextcloud:  14.0.3 stable
* Nextcloud Bookmarks app: 0.14.2
* Floccus: 3.1.6

### Steps to reproduce

1. install Floccus from Firefox addons store
2. connect with Nextcloud server
3. set local folder to `/Weitere Lesezeichen/Nextcloud` (which is newly created and empty)
4. Click on `sync now`
5. Sync fails with error message 

![grafik](https://user-images.githubusercontent.com/7983306/48734934-d01e2780-ecab-11e8-9d52-debd943d66e6.png)

### Expected outcome

Syncing works.

### Actual outcome

syncing fails with the error message above. Further, the message from the debug logs states

```
COMPARE { localItem: 
     + #vMqoau13dvmy[Nextcloud] parentId: undefined
   ,
  cacheItem: 
     + #undefined[undefined] parentId: undefined
   ,
  serverItem: 
     + #-1[undefined] parentId: undefined

[...]

Checking subtree
COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #2;-1[Getting started with microservices and kubernetes](http://Getting started with microservices and kubernetes - https://medium.com/p/getting-started-with-microservices-and-kubernetes-76354312b556) parentId: -1 }
(local)CREATE     - #undefined[Getting started with microservices and kubernetes](http://Getting started with microservices and kubernetes - https://medium.com/p/getting-started-with-microservices-and-kubernetes-76354312b556) parentId: vMqoau13dvmy
```

**Comment by marcelklehr** [comment]
Mmmh. Did you import those bookmarks on the server? The URL is not valid. Does it help to change the bookmark URL on the server? Thanks for the detailed report, btw!

**Comment by chhinze** [comment]
Yes, you are right. The problem is the URL not being valid. It was created with the android app, which weirdly allows me to upload such URLs. Thank you very much for the helpful answer.
