### ISSUE TITLE
Error 500. Failed PUT Request. Check your server configuration.

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#198]
### Software versions
* Browser:   FIrefox 63.0
* Nextcloud: 14.0.3.0 (NexctCloudPi  0.66.4)
* Nextcloud Bookmarks app: 0.14.2
* Floccus:  3.1.6
* Platform: Linux Mint 19

### Steps to reproduce
1. Nothing. (fully configured working Floccus stopped working 2 days ago)

### Expected outcome
It continues working. In fact it is still working fine on:

- Firefox 63 on Windows 10
- Chrome on Windows 10
- Chrome on same Linux Mint 19 box

### Actual outcome
On this Firefox 63 on the Linux Mint 19 box it now reports:

![image](https://user-images.githubusercontent.com/7296506/48809678-b64b1600-ed79-11e8-8b98-4a69bdbfd369.png)

The debug log does not show any error in the last few lines.

### My inferences

Error 500 is a typically a n internal server error, server side, so a NextCloud issue. But:

- NextCloud is working fine, three other instances of same floccus syncing with it. 
- connection is fine, Chrome on same PC is syncing to it

So a puzzles me that an error 500 is even possible. Can send debug log through if desired and helpful, but it's full of my many many bookmarks and login details o would redact it a little and prefer to send as PM than on public post. 

As an aside the Sync is real fast on Chrome and on Win 10 (Firefox and Chrome) but Firefox on Linux Sync takes a long long long time before it bombs with the Error 500. Also to best of my knowledge no system , or browser changes 2 days ago and it was working brilliantly until then. I cannot of course rule out some underlying change, a new addon or something 2 days ago, life too unclean and busy to be 100% sure, but none spring to mind.

**Comment by bernd-wechner** [comment]
> 
> 
> I'm having the same issue on Chromium, but it never worked to begin with. I had to go with XBEL sync, which has its own problem that I should report in a seperate issue.

Probably same symptom, different issue. Floccus has worked fine for ages, is working fine in three listed contexts, got itself in a knot on this one just two days ago. Floccus has an excellent debug log that can either help a willing dev diagnose this and/or which in my experience is readily added to (more logging info written to it0 in order to help diagnose such an issue. 

It could be that if Error 500 is accurate too that a look in server side logs helps, but I'd need a clue as to where to look on the NextCloud side. An experienced dev's assessment of my inferences would be good.

XBEL looks like a good standard, I wonder if Floccus uses it to communicate with the Bookmarks app  or when storing on WebDAV? A side issue mind you. I'm also not keen to abandon this seriously awesome project for another (like XBELSync) as Floccus has been working awesomely and it does have at least of late some really awesome dev support and is evolving. I'd give it some dev time if only i had some ti give and didn't face a big learning curve on its particular code base to boot.

**Comment by bernd-wechner** [comment]
I'll have to look for the "nextcloud log" to see if I can find where that is.  Tips appreciated. But I'll take a look ASAP. I have ssh and web access to the nextcloud server, just need the time to poke around. Quick acknowledgment now is all I have time for. Maybe later today.

**Comment by bernd-wechner** [comment]
I'll have to look for the "nextcloud log" to see if I can find where that is.  Tips appreciated. But I'll take a look ASAP. I have ssh and web access to the nextcloud server, just need the time to poke around. Quick acknowledgment now is all I have time for. Maybe later today.

**Comment by marcelklehr** [comment]
@bernd-wechner see https://docs.nextcloud.com/server/14/admin_manual/issues/general_troubleshooting.html#nextcloud-logfiles ;)

**Comment by marcelklehr** [comment]
@bernd-wechner Any new insights on this?

**Comment by SEWADE** [comment]
@marcelklehr 

Hi,

I have the same problem. That is the first time I try to use Floccus. Maybe I can help to forward resolving this issue!?
I've running Nextcloud on my own machine, so I have access to all needed logs.

- v3.1.15 Floccus (installed from Firefox addons)
- 0.14.2 Bookmarks
- 14.0.3.0 Nextcloud

That is what I see in the log file when I start synchronization with Floccus:

`

Error	index	Error: Call to undefined method GuzzleHttp\Client::request()

    /config/www/nextcloud/apps/bookmarks/controller/lib/http/client.php - line 41:

    OC\Http\Client\Client->get("https://mva ... g")

    /config/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Models/Link.php - line 60:

    OCA\Bookmarks\Controller\Lib\Http\Client->sendRequest(GuzzleHttp\Psr7\Request {})

    /config/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Models/Link.php - line 69:

    Marcelklehr\LinkPreview\Models\Link->fetch()

    /config/www/nextcloud/apps/bookmarks/controller/lib/linkexplorer.php - line 35:

    Marcelklehr\LinkPreview\Models\Link->getPreview()

    /config/www/nextcloud/apps/bookmarks/controller/lib/bookmarks.php - line 1127:

    OCA\Bookmarks\Controller\Lib\LinkExplorer->get("https://mva ... g")

    /config/www/nextcloud/apps/bookmarks/controller/lib/bookmarks.php - line 825:

    OCA\Bookmarks\Controller\Lib\Bookmarks->getURLMetadata("https://mva ... g")

    /config/www/nextcloud/apps/bookmarks/controller/rest/bookmarkcontroller.php - line 236:

    OCA\Bookmarks\Controller\Lib\Bookmarks->addBookmark("sebastian", "https://mva ... g", "OpenVPN unt ... s", [], "", false, [ "5"])

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OCA\Bookmarks\Controller\Rest\BookmarkController->newBookmark("https://mva ... g", [], "OpenVPN unt ... s", false, "", [], [ "5"])

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "newBookmark")

    /config/www/nextcloud/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "newBookmark")

    /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("BookmarkController", "newBookmark", OC\AppFramew ... {}, { _route: "b ... "})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "b ... "})

    /config/www/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "b ... "})

    /config/www/nextcloud/lib/base.php - line 987:

    OC\Route\Router->match("/apps/bookm ... k")

    /config/www/nextcloud/index.php - line 42:

    OC::handleRequest()
`

Regards
Sebastian

**Comment by SEWADE** [comment]
Hi,

me again.

I figured out that this issue is done after updating Nextcloud to 14.0.4.

Regards
Sebastian

**Comment by bernd-wechner** [comment]
Alas been away and off line for 10 days. No real insights aside the observation that perhaps it affects all my clients and it was an illusion that some worked. The reason I think it seemed it worked was that it's not until you add a bookmark to the client then the PUT fails. More later when I find time. First unpacking and recovering from a trip away and massive backlog of TODOs this one included. I do want to see my bookmark sync working again so I won't forget it ... and will be back as soon as I can with more diagnostics if possible. Only quick observation I have is that unlike Sebastian I'm on Nextcloud 
14.0.3.0 for now. But will be checking updates to NextCloud, its apps and Floccus soon, before continuing with diagnostic attempts.

**Comment by marcelklehr** [comment]
@bernd-wechner It could be that this is because of an emoji or some similar high-value UTF8 character (see https://github.com/marcelklehr/floccus/issues/210)

**Comment by bernd-wechner** [comment]
Alas I'm NexCloudPi and as reported on #210 it's already set up with UTF 8.

I just took another look. Here's what I tired. A bookmark Sync Now which reliably reports `Error 500. Failed PUT Request. Check your server configuration.` then on the NexCloud server in /varl/log:

```
$ sudo find . -mmin -10 -type f -exec ls -l {} +
-rw-r----- 1 root  adm   606942 Dec 13 21:51 ./apache2/nc-access.log
-rw-r----- 1 root  adm      796 Dec 13 21:45 ./apache2/nc-error.log
-rw-r----- 1 root  adm   548085 Dec 13 21:51 ./apache2/other_vhosts_access.log
-rw-r----- 1 root  adm   164243 Dec 13 21:51 ./auth.log
-rw-r----- 1 root  adm   102198 Dec 13 21:46 ./daemon.log
-rw-r--r-- 1 root  root  292876 Dec 13 21:46 ./lastlog
-rw-r----- 1 root  adm   251987 Dec 13 21:45 ./mail.info
-rw-r----- 1 root  adm   251987 Dec 13 21:45 ./mail.log
-rw-rw---- 1 redis redis 333453 Dec 13 21:50 ./redis/redis-server.log
-rw-r----- 1 root  adm    88875 Dec 13 21:46 ./syslog
```

Notice that the only real candidates here are the ones altered at 21:51.

Nothing in those log files lends any clue alas. 

In the floccus debug log there is no mention of the PUT error.

I'm feeling stuck. Can I ask a favour?

If a PUT error is encountered by floccus, log tot he debug log a transcript of the PUT transaction. What where you trying to PUT, and what did the server respond? if these appeared in the debug log it might help immensely. I'm really suffering here, floccus is so so cool! And suddenly stopped working without any clue why? Though likely related to a NexctCloud or Bookmarks app upgrade!

**Comment by marcelklehr** [comment]
@bernd-wechner Before we do that, could you also take a look at `/var/www/nextcloud/data/nextcloud.log` (or alternatively in the UI under 'Settings'/'Logging')?

**Comment by bernd-wechner** [comment]
Just updated to 64 (finally appeared in the Mint updates. No change. But the nextcloud.log file contains this as it's last line:

`{"reqId":"XBMBUX8AAQEAAEvnVw4AAACU","level":3,"time":"2018-12-14T01:03:14+00:00","remoteAddr":"192.168.0.1","user":"bernd","app":"index","method":"PUT","url":"\/index.php\/apps\/bookmarks\/public\/rest\/v2\/bookmark\/357","message":{"Exception":"Error","Message":"Class 'OCA\\FullTextSearch\\Api\\v1\\FullTextSearch' not found","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php","line":212,"function":"OCA\\Bookmarks_FullTextSearch\\AppInfo\\{closure}","class":"OCA\\Bookmarks_FullTextSearch\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php","line":44,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/bookmarks\/controller\/lib\/bookmarks.php","line":774,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/bookmarks\/controller\/rest\/bookmarkcontroller.php","line":313,"function":"editBookmark","class":"OCA\\Bookmarks\\Controller\\Lib\\Bookmarks","type":"->","args":["bernd","357","https:\/\/www.hobartcity.com.au\/Council\/Council-and-Committee-meetings\/Live-recordings-of-Council-meetings","Live recordings of Council meetings - City of Hobart, Tasmania Australia",["floccus:>Bookmarks Menu>Hobart","floccus:>Bookmarks Bar>Hobart"],"",0,null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"editBookmark","class":"OCA\\Bookmarks\\Controller\\Rest\\BookmarkController","type":"->","args":[357,"https:\/\/www.hobartcity.com.au\/Council\/Council-and-Committee-meetings\/Live-recordings-of-Council-meetings",{"tags":["floccus:>Bookmarks Menu>Hobart","floccus:>Bookmarks Bar>Hobart"]},"Live recordings of Council meetings - City of Hobart, Tasmania Australia",null,null,null,null,null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\Rest\\BookmarkController"},"editBookmark"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\Rest\\BookmarkController"},"editBookmark"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["BookmarkController","editBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"357","_route":"bookmarks.bookmark.edit_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"357","_route":"bookmarks.bookmark.edit_bookmark"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"357","_route":"bookmarks.bookmark.edit_bookmark"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/bookmarks\/public\/rest\/v2\/bookmark\/357"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/bookmarks_fulltextsearch\/lib\/AppInfo\/Application.php","Line":97,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"14.0.3.0"}`

which may contain a clue as it does reference the PUT and `"Exception":"Error"`.

**Comment by marcelklehr** [comment]
Simple fix: Disable Bookmarks_FullTextSearch.

**Comment by bernd-wechner** [comment]
Stunning, all that pain and so easily fixed. That is, it worked.

But as a good community minded kinda guy, I am rarely content with _just_ a quick fix and perforce must ask

1. do you have any idea why that app might prevent floccus from succeeding to PUT ?
2. do you think I'll be the only or last sucker to suffer this lengthy pain? And if not ...
3. do you think it worth a floccus to flocus to either:
    1. Fixing floccus or that app as needed so they work properly together?
    2. Improving the debug log in floccus to at least identify this situation and report it clearly?

Thanks for your support so far Marcel, cannot say how grateful I am really. it's been a period of uncertainty and confusion in my bookmark syncing in a very distractingly busy phase of life where I struggled to make/find time to do deeper diagnoses. But it seems resolved! Excepting the questions above I guess, which drive to making a wider, more lasting solution than a quick fix of my problem.

**Comment by marcelklehr** [comment]
> Stunning, all that pain and so easily fixed. That is, it worked.

Aah, I'm relieved then. Thanks for your foresight with those questions, I'll answer as best I can:

> do you have any idea why that app might prevent floccus from succeeding to PUT ?

The fulltextsearch app does not work well together with the latest versions of the bookmarks app. This bug of apparently causing an error of its own accord when it should just receive a hook about an updated bookmark is a new low, but nothing that surprises me.

> do you think I'll be the only or last sucker to suffer this lengthy pain?

You're not the only one already, but hopefully the last if I add a note to the README to avoid the fulltextsearch app.

> Fixing floccus or that app as needed so they work properly together?

The fulltextsearch app would need fixing, but alas, I'm currently in no position to donate that much time :/

> Improving the debug log in floccus to at least identify this situation and report it clearly?

Floccus is not able to discern this exact situation from other server-side failures, sadly, so there's not much I can do, except add a note to the floccus README, as well, perhaps.

**Comment by bernd-wechner** [comment]
-------- Forwarded Message --------
To: 	Marcel Klehr <mklehr@gmx.net>
From: 	Bernd Wechner <bernd.wechner@gmail.com>
Subject: 	Debug Log for Issue 218
Message-ID: 	<b72775de-04e7-af39-a52c-b29383f8bdb8@gmail.com>
Date: 	Thu, 27 Dec 2018 22:09:44 +1100
User-Agent: 	Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 
Thunderbird/60.2.1
MIME-Version: 	1.0
Content-Type: 	multipart/mixed; 
boundary="------------893843CE5DCA589BD40FEA3B"
Content-Language: 	en-AU



Marcel,

As per note at:

https://github.com/marcelklehr/floccus/issues/218

Find attached the debug log.

May it be of use.

I suspect it might be nice if floccus writes an error message to screen 
say, via it's setting panel, that it write the same message with any 
extra details to the log file. Even if it had not extra details, if the 
message appeared I'd see where in the timeline of messages it crops up, 
the last line or somewhere in between or wherever.

This one looks like it might just be a config issue (change?) not sure. 
I'll add more details to the issue that I have too.

Regards,

Bernd.
