### ISSUE TITLE
Getting Error: bm.folder is undefined

### ISSUE THREAD

**Issue by BeamMeUpTo** [marcelklehr/floccus#199]
### Software versions

* Browser: Firefox 63.0.3 (64-Bit)
* Nextcloud:  13.0.1.1
* Nextcloud Bookmarks app:  0.12.2
* Floccus: 3.1.6

### Steps to reproduce

1. Trying to get a full sync with root-folder
2. Getting Error: bm.folder is undefined

Two other Computers had no problem with syncing with the same configuration.

**Comment by marcelklehr** [comment]
Hey,
Which method are you using to sync? Can you provide an excerpt of the debug log containing the error? (Bottom right corner of the floccus panel)

**Comment by marcelklehr** [comment]
You both appear to be syncing to nextcloud bookmarks before v0.14 with the method that requires nextcloud bookmarks of at least v0.14. Please upgrade to v0.14.x or use the legacy method.

**Comment by BeamMeUpTo** [comment]
The Debug log showed no error except:
`
Starting sync process for account xxxxxx@https://xxx.xxx.xxx.xxx/nextcloud/
Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu
Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar
Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
Fetching bookmarks
`
I tested legacy method already with no success :(

So I upgraded Nextcloud to 14.0.4 and the bookmarks app to 0.14.x yesterday and 
now seems to be ok.....

**Comment by marcelklehr** [comment]
> So I upgraded Nextcloud to 14.0.4 and the bookmarks app to 0.14.x yesterday and
now seems to be ok.....

Awesome!

> I tested legacy method already with no success :(

Oh, what happened with the legacy adapter?

**Comment by marcelklehr** [comment]
> For me it is an awesome app and it is really annoying if it isn't working

I understand :) Thanks for the feedback!
