### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Tank-Missile** [marcelklehr/floccus#201]
### Software versions
* Browser: Chromium 70.0.3538.77
* Nextcloud: 14
* Nextcloud Bookmarks app: Not sure?
* Floccus: 3.1.11

I'm using a provider (https://cloud.disroot.org), so I'm not sure how to check the bookmarks app version. I'm not even sure if the nextcloud version (14) is completely accurate either.

### Steps to reproduce
Just attempting a manual sync will cause the error.

### Expected outcome
My bookmarks sync with my account and show up in the bookmarks app.

### Actual outcome
Cannot read property 'id' of undefined.

**Comment by marcelklehr** [comment]
Can you provide the debug log?

**Comment by Tank-Missile** [comment]
> Starting sync process for account <omitted>
> Overriding title of built-in node 1 Bookmarks bar => Bookmarks Bar
> Fetching bookmarks
> Received bookmarks from server []

This is all the log provides.

**Comment by marcelklehr** [comment]
Which sync method do you use (webdav/nc legacy/nv v0.14+)? In order to determine your bookmarks app version: Are you able to create folders in the web UI?

**Comment by Tank-Missile** [comment]
I'm using 0.14+ and I can create folders in the bookmarks app web ui.

**Comment by marcelklehr** [comment]
In case you were using the server folder feature this issue should be fixed in the next release.

**Comment by Tank-Missile** [comment]
I tried 3.1.14, but now I'm getting a different error: Folder #-1[undefined] contains an nonexistent bookmark 6

**Comment by marcelklehr** [comment]
What does the debug log say?

**Comment by Tank-Missile** [comment]
> Starting sync process for account
> Overriding title of built-in node 1 Bookmarks bar => Bookmarks Bar
> Fetching bookmarks
> Received bookmarks from server []

**Comment by marcelklehr** [comment]
mmh. For some reason, the server returns no bookmarks at all, yet, tells floccus that bookmark with id 6 is in the root folder. Are there any bookmarks visible in the bookmarks web UI?

**Comment by Tank-Missile** [comment]
There are no bookmarks in the web ui. I deleted all bookmarks prior to syncing.

**Comment by muppeth** [comment]
@Tank-Missile hi I'm an admin of disroot, cloud you perhaps contact us via support_at_disroot.org so we could examine whats going on on our end and possibly supply more details (like database query results etc) to @marcelklehr

**Comment by muppeth** [comment]
Seems like we just reproduced the error. We'll supply more information over the weekend.

**Comment by marcelklehr** [comment]
I think I've identified the bug. In multi-user environments the bookmarks app currently returns other user's bookmark IDs (but no actual data).

**Comment by marcelklehr** [comment]
This should be fixed with bookmarks v0.14.3 -- please confirm :)

**Comment by Tank-Missile** [comment]
I just gave 3.1.15 a go and my bookmarks successfully synced to my disroot account! Thank you @marcelklehr and @muppeth. I assume the bookmarks app version was updated on the website.
