### ISSUE TITLE
Error in manifest file: unrecognized manifest key "applications"

### ISSUE THREAD

**Issue by uniconstructor** [marcelklehr/floccus#202]
### Software versions

- Browser: Brave, 0.56.14 Chromium: 70.0.3538.102
- Nextcloud: 13
- Nextcloud Bookmarks app: 	0.12.2
- Floccus: v3.1.13

### Steps to reproduce

1.  install extension manually
2. click at "errors" button
3. Error message: unrecognized manifest key "applications"
### Expected outcome

No erorrs after extension install

### Actual outcome

...

### Debug log

```js
// unrecognized manifest key "applications"
"applications": {
    "gecko": {
      "id": "floccus@handmadeideas.org",
      "strict_min_version": "57.0"
    }
  },
```

**Comment by uniconstructor** [comment]
![2018-11-27 00-59-14](https://user-images.githubusercontent.com/1384545/49044743-bfa40a80-f1df-11e8-9eb1-06924fbee3f9.png)

**Comment by marcelklehr** [comment]
This is a known complication in supporting both firefox and chrome. It doesn't affect the addon's functionality.
