### ISSUE TITLE
Keep sorting by saving "Sort Index"

### ISSUE THREAD

**Issue by pablohess** [marcelklehr/floccus#205]
### Software versions
- Browser: Firefox 63.0.3
- Nextcloud: 14.0.4
- Nextcloud Bookmarks app: 0.14.2
- Floccus: 3.1.14
- Floccus sync method: nextcloud Bookmarks v0.14+

### Steps to reproduce
1.  Sort your bookmarks in your bookmarks toolbar and within the folders in your bookmark toolbar.
2. Press "sync now" within the floccus plugin.

### Expected outcome
Sync the bookmarks and keep the bookmarks as I sorted them.

### Actual outcome
The sorting is lost. I guess it's an alphabetic sort order.

### Actual outcome
I exported my bookmarks as a JSON file and found out that there is an index property:

> {
>                      "guid": "qH81n70HdpxT",
>                      "title": "GIT",
>                      "index": 8,

Maybe it's possible to sync this index as well and keep the sorting?

**Comment by marcelklehr** [comment]
> - Floccus sync method: nextcloud Bookmarks v0.14+

are you sure about this one? Does floccus create actual folders in the web UI or merely folder paths as tags?

**Comment by marcelklehr** [comment]
Closing due to unresponsiveness. Using the nextcloud bookmarks (v0.14+) adapter should preserve sort order.
