### ISSUE TITLE
Make sync preserve lack of name for bookmarks, allowing for icon based bookmark management

### ISSUE THREAD

**Issue by GreatWhiteMuffloN** [marcelklehr/floccus#209]
### Software versions

- Browser: Firefox 63
- Nextcloud: 14.0.4
- Nextcloud Bookmarks app: 0.14.3
- Floccus: 3.1.15
- Floccus sync method: nextcloud-folders/WebDav

### Steps to reproduce

I love this addon and had a NextCloud instance so I thought I'd give it a spin, works great except for the one thing that I use my bookmarks in Firefox based on icons, meaning I save bookmarks without a name so the favicon is used to save horizontal space and allow me faster easier access to larger amounts of bookmarks instantly.

### Expected outcome

Uploaded my bookmarks via both WebDav and the proper Bookmarks app sync, when syncing out from source both re-fill the name of bookmarks from the source and doesn't respect my choice of having removed them

### Actual outcome

All my bookmarks now have their names back, contrary to my wishes, thank god for diligent backups :)

**Comment by marcelklehr** [comment]
> both re-fill the name of bookmarks from the source

Are you sure that this happens with the webdav method as well? It shouldn't change the title at all. I can confirm that the bookmarks app automatically sets a title if there is none, so I'll have to figure something out.

**Comment by marcelklehr** [comment]
The next version of the bookmarks app will not have this issue :)
