### ISSUE TITLE
Normalize server url

### ISSUE THREAD

**Issue by danopz** [marcelklehr/floccus#21]
We should normalize given Server url to avoid calling of undefined routes.
We must be aware of trailing slashes, with or without index.php and so on.

I can think of this possible url structure we need to parse:
`example.com[/folders][/index.php][/random-invalid-paths][/]`

ref: #18, #20

**Comment by marcelklehr** [comment]
I agree.

**Comment by marcelklehr** [comment]
Done. I did some refactoring along the way to make this smoother ;)

**Comment by danopz** [comment]
Looks like you don't handle the case when a user don't add `index.php`, but the cloud is in a subdir:
`http://example.com/cloud/`

**Comment by marcelklehr** [comment]
Ah, yes, you're right. Should be fixed now.
