### ISSUE TITLE
Error 500. Failed POST request in FireFox (works in chrome)

### ISSUE THREAD

**Issue by roelWuyts** [marcelklehr/floccus#210]
### Software versions

- Browser: Firefox 63.0.3 (64-bit)
- Nextcloud: 14.0.4
- Nextcloud Bookmarks app: 0.14.3
- Floccus: 3.1.15
- Floccus sync method: nextcloud Bookmarks v0.14+ with folders

### Steps to reproduce

1.  installed Bookmarks app in NextCloud
2. installed Floccus in Firefox
3. created synctest bookmarks folder in the Bookmarks Toolbar
4. added a link in this folder
5. added my account details (server, username, password) and set it to sync the '/Bookmarks Toolbar/synctest' folder with the server folder '/test' on my nextcloud

### Expected outcome

After syncing I expected there to be a 'test' bookmark folder with the link in my nextcloud.

...

### Actual outcome

1. the floccus plugin shows an error: 'Error 500. Failed POST request. Check your server configuration.
2. in the bookmarks app in nextcloud, when viewing it via a webbrowser, the 'test' folder is created but did not contain an entry

Checking my apache2 serverlogs and nextcloud logs did not reveal anything special (requests get through, which was to be expected given that the folder was created successfully). 

I repeated the steps in Chrome (70.0.3538.110), where everything worked as advertised.

So it seems to be a firefox+floccus problem.
...

### Debug log

Starting sync process for account wijle@cloud.1236.be
Fetching bookmarks
Received bookmarks from server [   - #1[AnandTech: Hardware News and Tech Reviews Since 1997](https://anandtech.com) parentId: -1 ]
Filtered out the following duplicates before syncing []
COMPARE { localItem: 
     + #Gy4FLAP73pR2[synctest] parentId: undefined
       - #EWkL7iDCaC0a[floccus – Get this Extension for 🦊 Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/floccus) parentId: Gy4FLAP73pR2,
  cacheItem: 
     + #undefined[undefined] parentId: undefined
   ,
  serverItem: 
     + #1[undefined] parentId: undefined
    }
Checking subtree
COMPARE { localItem:   - #EWkL7iDCaC0a[floccus – Get this Extension for 🦊 Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/floccus) parentId: Gy4FLAP73pR2,
  cacheItem: null,
  serverItem: undefined }
(nextcloud-folders)CREATE     - #undefined[floccus – Get this Extension for 🦊 Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/floccus) parentId: 1

**Comment by marcelklehr** [comment]
Hey,
This is weird. If nextcloud hits a server-side error like that, there should be *something* about that in the nextcloud log file :/

**Comment by marcelklehr** [comment]
Floccus is not able to determine the reason for a 500 error, because that is a server-side error. It is possible to increase the verbosity of the nextcloud log in the settings UI, I think. I fin doubt, feel free to send the nextcloud log file to me, via mail.

**Comment by marcelklehr** [comment]
This is a problem with your database. Checkout the nextcloud docs on how to convert your mysql database charset to utf8mb4.

**Comment by roelWuyts** [comment]
Ah, I see, thanks (for the tip and fast response).


Kind regards,

Roel


________________________________

**Comment by prog-amateur** [comment]
Sorry but the solving is not clear. Please, could you share a link to solve this issue please ? I am a beginner, and I like floccus but I have the same error. I use Nextcloudpi. 

Thank you very much for your help.

**Comment by marcelklehr** [comment]
@prog-amateur Sorry for the brevity on my part. This is the relevant article in the docs: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by bernd-wechner** [comment]
Me too (on Nextcloudpi). And it seems the  latest releases uses MariaDB 10.1.37, meaning this is the section for us:

https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier

And yet step 1 already loses me as it doesn't say where or how that configuration is set. So off I go on a jolly hunt for it.

**Comment by marcelklehr** [comment]
@bernd-wechner This solution only applies to you, if you see the following error in your nextcloud log:

```
Error	index	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_bookmarks` ... SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\xA6\x8A F...' for column 'title' at row 1
```

**Comment by marcelklehr** [comment]
@bernd-wechner Also, you [apparently need](https://mariadb.com/kb/en/library/information-schema-innodb_sys_tables-table/ ) the `PROCESS` privilege.

**Comment by prog-amateur** [comment]
Hello Bernd, Marcel, thank you for your feedback. Please find the thread I have issue in [Nextcloud forum](https://help.nextcloud.com/t/how-to-enable-mysql-mariadb-4-byte-support/42958/5) : 

> Hello, thank you all for your help !
> 
> The log file is a bit complicated to share as it contains some private links (nothing abnormal don’t worry ^^) among many many others, so it is difficult to sort them before showing it.
> 
> **What is strange, is that since Firefox 64.0 update this morning, I have no more issue** (it shows all good - Last synchronized : 3 mn ago). I really don’t know what happened as it is the first time I install completely floccus. **The only change was Firefox update** (for your information, I am on Linux).
> 
> I keep this thread open a few days, and if there is no more issue, I will close it.

As you can see, the issue disappeared this morning ! The only difference was Firefox update this morning to version 64.0. 
Another interesting point is that Nextcloudpi's main developer says that **utfmb4 already enabled**, and he uses floccus without any issue. 

@marcelklehr : Did you have updated the WebExtension in between ? 

Thank you very much.

**Comment by marcelklehr** [comment]
I haven't updated the extension since you've opened this issue, no. I'm glad it works. :)
