### ISSUE TITLE
[Question] send a web site to a specific device like Firefox

### ISSUE THREAD

**Issue by prog-amateur** [marcelklehr/floccus#211]
Hello, this thread is not an issue but a feature question (sorry to open it as an issue). 

Do you know if this WebExtension can send a web page to a device like Firefox does ? 

![](https://blog.mozilla.org/firefox/files/2017/11/Firefox-Quantum-Built-for-Touchpng.png)

This is not a _"do want"_ request : I still can make a folder and put web pages into it if I want to read it in another device synchronized with the same Nextcloud account. This is just to be sure that this feature exists/do not exist yet. 

Thank you very much.

**Comment by marcelklehr** [comment]
This feature doesn't exist at the moment. :)

**Comment by prog-amateur** [comment]
> This feature doesn't exist **_at the moment_**. :)

Interesting, I take note! In fact, I just realized that floccus is not yet compatible with Firefox Android, so this feature is welcome. 

I hope it is one of your priorities, that would be really nice. 

Anyway, thank you very much for your feedback and for this great Web extension, I close this topic.

**Comment by marcelklehr** [comment]
Android support was one of the main reasons, I created this extension. However, mozilla is slacking on that one: https://github.com/marcelklehr/floccus/issues/3
