### ISSUE TITLE
Chromium Brave: Folder #-1[undefined] contains an nonexistent bookmark 19875

### ISSUE THREAD

**Issue by digrouz** [marcelklehr/floccus#215]
### Software versions

- Browser: Brave Version 0.57.18 Chromium: 71.0.3578.80 (Build officiel) (64 bits)
- Nextcloud: Nextcloud 14.0.4
- Nextcloud Bookmarks app: 0.14.2
- Floccus: 3.1.15
- Floccus sync method:  nextcloud Bookmarks v0.14+ with folders

### Steps to reproduce

Hello, as the latest brave is now based on chromium, I tried to install the Floccus extension to sync my bookmark.

### Expected outcome

bookmark syncs :)

### Actual outcome

I receive the following error and none bookmark were synchronized

    Folder #-1[undefined] contains an nonexistent bookmark 19875

Note that floccus work successfully in Chrome.

**Comment by Tank-Missile** [comment]
There's a bug in versions prior to 0.14.3 that caused the bookmarks app to return other user's bookmark IDs (but no actual data) in multi-user environments. All signs point to the issue I was having in #201.

**Comment by marcelklehr** [comment]
I agree, this is reminiscent of #201. @digrouz please try updating the bookmarks app :)

**Comment by digrouz** [comment]
I just updated my bookmark app and still have the same issue.

**Comment by digrouz** [comment]
Do you need the debug log ?

**Comment by marcelklehr** [comment]
@digrouz That would be useful, yes. You can also send it via mail, if you like :)

**Comment by digrouz** [comment]
I've sent it by email.

**Comment by iroedius** [comment]
I have the same error.
`Folder #-1[undefined] contains an nonexistent bookmark 7`
 When there are no bookmarks on the server the sync goes fine but as soon as I add at least one bookmark and sync that to the Nextcloud server, every sync after that returns this error.

Chromium 71.0.3578.98 on Linux (vanilla, not Brave)
Nextcloud 15.0.0
Bookmarks 0.14.3
Floccus 3.2.0 with Nextcloud Bookmarks (v0.14+) sync method

**Comment by marcelklehr** [comment]
I have a suspicion: Which database do you use on the server?

**Comment by iroedius** [comment]
PostgreSQL 11.1 here.

**Comment by marcelklehr** [comment]
I knew it.

**Comment by marcelklehr** [comment]
PostgreSQL doesn't return numbers as strings like mysql which makes a strict equality check fail. This is a one liner :)

**Comment by tomershvueli** [comment]
Just in time for the New Year! ;) however, I'm now seeing a different issue where all of my bookmarks are imported into the selected folder as siblings, and not in the hierarchal manner they were saved in. Am I missing something?

**Comment by marcelklehr** [comment]
@tomershvueli Mmh. Could you open a new issue for this and fill out the issue template? This should make troubleshooting easier :)

**Comment by digrouz** [comment]
I see the same behavior, All my bookmark are now syncing, but they are not in a folder.

**Comment by tomershvueli** [comment]
@marcelklehr I just opened up a new ticket (#221) with the new issue. Happy to help test new versions!
