### ISSUE TITLE
Feature Request: Keep Config Dialog Open if Browser Window Loses Focus

### ISSUE THREAD

**Issue by gohrner** [marcelklehr/floccus#217]
Currently, Floccus' options window is very shy - as soon as the Browser window loses focus, it disappears.

This makes it really hard to setup an account for which you have to copy and paste different information from somewhere else - like at least URL and password, and possibly also the sync file name in case of xbel file sync.

It would be nice of the options windows could stay open in this case.

**Comment by gohrner** [comment]
Ah, great, didn't think about this. Works fine - maybe the extension could somehow hint to this possibility?

**Comment by marcelklehr** [comment]
I could add a link to the panel that allows the user to open the settings in a new tab.

**Comment by gohrner** [comment]
I think this could be helpful.

**Comment by GoogleBeEvil** [comment]
maybe adding an option ui in side bar is another help way
