### ISSUE TITLE
Error: path isundefined

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#218]
Wow, another error. Cryptic message alas. Was synching fine, but today I updated my Bookmarks app on Nextcloud to  0.15.1 as per a notification request, and the NextCloud itself to NexCloudPi v0.67.8 and NextCloud 14.0.4.2. And Now I see this error:

![image](https://user-images.githubusercontent.com/7296506/50476359-f7d77c80-0a1b-11e9-929a-3c6676d27c05.png)

I checked the  debug log but I can't see an obvious answer, the term "Path is" appears nowhere, and "undefined" is all over the log. I can as ever send one along by email for diagnosis but don't know of a way to send personal info along to a developer without it going public - I noticed recently GitLab supports confidential issues that can only be seen by the submitter and project members. Neat.

**Comment by bernd-wechner** [comment]
More info I have:

- It  works on Google Chrome still
- My Firefox has Floccus 3.2.1
- My Chrome has Floccus 3.2.1
- I backed up my Firefox Bookmarks to be safe then did Reset Cache on the Floccus settings and synched, and it all worked fine again.

Conclusion is something was broken with the Firefox Cache .... how that happened and why it correlated so well with my NextCloud upgrades is a mystery. I sent the log file by email, maybe it lends a clue. Maybe not worth pursuing.

**Comment by marcelklehr** [comment]
Mh. Weird. :+1: for sending the log -- it seems I didn't get your email, though :/

**Comment by marcelklehr** [comment]
> I noticed recently GitLab supports confidential issues that can only be seen by the submitter and project members. Neat.

Yeah, that's a good idea.

**Comment by bernd-wechner** [comment]
Marcel the problem is gone, but I did send the log by email to: mklehr@gmx.net at Thu, 27 Dec 2018 22:09:44 +1100.

I did just forward it to:
 reply+006f55fa907ae8fc4e804b0e7da1cbafd2af9d28698febf592cf00000001180d2ce792a169ce16d283cc@reply.github.com

as that is the ReplyTo address on an email I got from you via github once and so might reach you.

**Comment by bernd-wechner** [comment]
I did resend it a few days ago. No luck getting it? Low priority given it works again, but I imagine I'd be curious what caused it if I had more time ;-).

**Comment by marcelklehr** [comment]
No luck. I did sort out some mail issues recently, so hopefully I'm reachable again :/

Anyway, closing this for now.
