### ISSUE TITLE
Webdav: server URL isn't normalized

### ISSUE THREAD

**Issue by eleksis** [marcelklehr/floccus#219]
Hi,
I'm trying to make floccus work with webdav on my shared hosting.

They are using port  2078 for webdav. And it looks like floccus ignores port when i pass it as part of url in settings.

WebDAV URL:
https://my-domain.com:2078

The error I get:
Network error: Check your network connection and your account details

Can someone confirm this is not supported?
And I can probably implement this, if I get some directions...

**Comment by marcelklehr** [comment]
Mmh. This should be supported.

But I just checked and noticed that the webdav adapter doesn't normalize urls, so it might work if you append a slash.

**Comment by eleksis** [comment]
Yes, that did the trick. Thank you.

**Comment by jlbprof** [comment]
Yes you will need to append a slash.
