### ISSUE TITLE
Force sync

### ISSUE THREAD

**Issue by zeigerpuppy** [marcelklehr/floccus#22]
It would be great to have a button to force floccus to sync now.
It would also be good to have an option to change the sync interval.

**Comment by marcelklehr** [comment]
See #16 for the first request ;)

**Comment by mase76** [comment]
An immediate sync on local data change would be great.

**Comment by marcelklehr** [comment]
Closing this in favor of #22

**Comment by theScrabi** [comment]
Isn't it possible to observe bookmarks on firefox, so an event will be triggered when the bookmarks got changed. So on a local change the bookmark could easily be uploadet. Without further interaction.

**Comment by theScrabi** [comment]
Here https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/onChanged

**Comment by marcelklehr** [comment]
Sorry, I linked the wrong issue. #24 is what you mean and it's planned ;)
