### ISSUE TITLE
Chromium Vivaldi - Syncing without Hierarchy

### ISSUE THREAD

**Issue by tomershvueli** [marcelklehr/floccus#221]
### Software versions

- Browser: Vivaldi 2.2.1388.37
- Nextcloud: 14.0.4
- Nextcloud Bookmarks app: 0.15.1
- Floccus: 3.2.2
- Floccus sync method: nextcloud Bookmarks v0.14+ with folders

### Steps to reproduce

1. Set up Floccus for syncing
2. When sync is complete, all of my bookmarks are in the parent directory I selected in the Extension, but not in their respective folders. This is continuing the conversation from Issue #215. 

### Expected outcome

I would have expected the bookmarks to be synced locally in the proper hierarchy that they were saved in. 

### Actual outcome

All of the bookmarks were saved in the parent directory as siblings, without any hierarchical data. 

### Debug log
Debug looked a lot like this: 
`(local)CREATE     - #undefined[MindSumo](https://mindsumo.com/home) parentId: 1715
COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #2670;-1[Course: EI Garage](https://moodle-projects.wolfware.ncsu.edu/course/view.php?id=1085) parentId: -1 }
(local)CREATE     - #undefined[Course: EI Garage](https://moodle-projects.wolfware.ncsu.edu/course/view.php?id=1085) parentId: 1715
COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #2671;-1[Interview Cake](http://interviewcake.com/tips-and-tricks) parentId: -1 }
(local)CREATE     - #undefined[Interview Cake](http://interviewcake.com/tips-and-tricks) parentId: 1715
COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #2672;-1[The Man in Seat Sixty-One - the train travel guide...](http://seat61.com) parentId: -1 }
(local)CREATE     - #undefined[The Man in Seat Sixty-One - the train travel guide...](http://seat61.com) parentId: 1715
COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #2673;-1[share passwords once](https://oneshar.es) parentId: -1 }
(local)CREATE     - #undefined[share passwords once](https://oneshar.es) parentId: 1715
COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #2674;-1[Algorithms [Algorithm Wiki]](http://will.thimbleby.net/algorithms/doku.php) parentId: -1 }`

**Comment by digrouz** [comment]
same for me with nextcloud 15 and brave browser

**Comment by marcelklehr** [comment]
Does the web UI have the correct hierarchy? If not this would indicate that things go wrong already when storing the bookmarks.

**Comment by tomershvueli** [comment]
Yep, looks like it! I've also used Floccus successfully before for syncing locally and on the server. 

![image](https://user-images.githubusercontent.com/1024355/50592233-ef5bc780-0e9b-11e9-97c2-6f880f249872.png)

**Comment by marcelklehr** [comment]
The screenshot indicates that the bookmarks were uploaded with the legacy sync method. In order for sync to work, all devices have to use the same sync method.

**Comment by tomershvueli** [comment]
Aha! Yes, that did the trick! Am I now able to sync my local bookmarks with the server using the new sync method?

**Comment by marcelklehr** [comment]
In order to use the new sync method, you should remove the relevant accounts on all devices, then delete all bookmarks in the app and then set up accounts with the new method on all devices again.

I'm currently trying to add some directions to the UI in order to make it clearer what each option does.

**Comment by tomershvueli** [comment]
Awesome! That seems to be working pretty alright for now! Thanks for your work on this, I feel much better now that my bookmarks are actually saved in the proper hierarchy. Cheers!
