### ISSUE TITLE
Special character is synced wrong

### ISSUE THREAD

**Issue by linuxrecon** [marcelklehr/floccus#222]
### Software versions

- Browser: Firefox 64
- Nextcloud: 15.0.0
- Nextcloud Bookmarks app: 0.15.1
- Floccus: 3.2.3
- Floccus sync method: nextcloud-folders

### Steps to reproduce

We are using OTRS. A lot of the users are bookmarking OTRS links to tickets. A direct link to a ticket does look like this: https://my.otrs.dom/index.pl?Action=AgentTicketZoom;TicketID=707128

1.  Bookmark a URL with a ; character. It doesn't matter if this bookmark is created within NextCloud Bookmarks or within your browser.
2. Let Floccus sync that Bookmark.
3. Try to open the bookmark within your browser.
4. The ; character (and all special characters after this one) will be transformed to something like '%3B'.

### Expected outcome

The URL shouldn't be transformed by Floccer. Otherwise the links ware mostly likely broken.

### Actual outcome

It seems like that Floccer has problems with syncing URLs with ';' in it. With that being said, adding a URL with a ';' character to NextCloud Bookmarks from the webinterface and opening the URL from the webinterface works fine. Using the AddOn FreedomMarks with Firefox also works as expected. However, FreedomMarks does not actually sync the bookmarks rather than accessing them directly through the NextCloud API.

**Comment by marcelklehr** [comment]
Thank you for the feedback! This definitely appears to be a bug. I have [opened an issue with the library used for URL normalization](https://github.com/sindresorhus/normalize-url/issues/85) in floccus and will report back here.

**Comment by marcelklehr** [comment]
I guess I will write my own normalization library...

**Comment by marcelklehr** [comment]
This should be fixed in the next release
