### ISSUE TITLE
It's not possible to move Places root folders.

### ISSUE THREAD

**Issue by Evil2000** [marcelklehr/floccus#223]
### Software versions

- Browser: 64.0.2 (64bit)
- Nextcloud: 15.0.2
- Nextcloud Bookmarks app: 0.15.1
- Floccus: 3.2.3
- Floccus sync method: nextcloud Bookmarks v0.14+ with folders

### Steps to reproduce

1.  Try to sync
2. Error shows after some seconds

### Expected outcome

Sync finishes successfully 

### Actual outcome

An error is shown since Nexcloud 15 is installed:
It's not possible to move Places root folders.

### Debug log

(local)MOVEFOLDER { id: 'unfiled_____', parentId: 'mobile______' }
Syncing failed with It's not possible to move Places root folders.

[floccus-3.2.3-2019-01-17.log](https://github.com/marcelklehr/floccus/files/2770633/floccus-3.2.3-2019-01-17.log)

**Comment by marcelklehr** [comment]
Hey,

```
+ #24[Mobile Lesezeichen] parentId: 20
         + #22[Other Bookmarks] parentId: 24
           - #125;22[***bookmark hidden***](https://***bookmark hidden***) parentId: 22
           - #124;22[***bookmark hidden***](https://**
```

You seem to have inadvertantly moved your "Other Bookmarks" folder into the "Mobile Lesezeichen" folder. Moving it out of there in the web interface should fix the error.

**Comment by Evil2000** [comment]
Oh. Yes. Seems to be right. This was not intented.
Thanks for the hint. Moving the "Other Folder" folder out of the "Mobile Lesezeichen" fixed it :-)

**Comment by TCB13** [comment]
Hello, I'm also having this issue. However I didn't move any folder. It was working fine until today the extension updated to 4.4.0.

Here are my bookmarks:

![Screenshot 2020-10-18 131424](https://user-images.githubusercontent.com/6315832/96367162-f1137f80-1143-11eb-9077-78e901a65b36.png)
![Screenshot 2020-10-18 131447](https://user-images.githubusercontent.com/6315832/96367163-f2dd4300-1143-11eb-8ced-b78fca983fc1.png)

Nothing seems out of place.

**Comment by marcelklehr** [comment]
@TCB13 Ah that would be a bug. I'll release a fix ASAP.

**Comment by marcelklehr** [comment]
This should be fixed in the latest version.

**Comment by red3333** [comment]
I just remove floccus, then reinstall it from scratch (v4.4.4). Created a new account to sync my root folder to a new folder on my nextcloud (V20) instance (chose the bookmarks.xbel version, no other sync to this file for the moment).
First sync worked well.
Since then no change to the bookmarks, but I get the "It's not possible to move Places root folders" message...

**Comment by NephtonLabs** [comment]
+1 to this. On the same versions. Sync appears to have issues. Firefox is running 68.7.0ESR if that matters.

**Comment by TCB13** [comment]
I'm also getting this again with v4.4.4 :(

**Comment by NephtonLabs** [comment]
> 
> 
> I'm also getting this again with v4.4.4 :(

Opened a new case at https://github.com/marcelklehr/floccus/issues/718 if you want to upload or add anything there to assist.
