### ISSUE TITLE
internationalization/translation

### ISSUE THREAD

**Issue by GoogleBeEvil** [marcelklehr/floccus#226]
I want translate it to my native languege, so where is the languege source?

**Comment by marcelklehr** [comment]
It's currently not possible to translate floccus. As I don't have too much time over the next few months I'll have to focus my efforts on the most important things and I'm not sure if this is one of them. Most people who selfhost a server usually know enough english to find their way around floccus, I think. Any opinions on this?

**Comment by marcelklehr** [comment]
> firefox's default folder name become english from my native languege after sync from webdav

ah, that's a side effect of normalizing the main folders across browsers. i18n would indeed solve this.

**Comment by marcelklehr** [comment]
It is now possible to translate the project over at https://www.transifex.com/floccus/floccus/ :tada:

I'm not sure if I need to invite collaborators to the project, so if you'd like to help translating, drop me a message here or via email with either your username or your email if you don't have an account, yet.

**Comment by marcelklehr** [comment]
Apparently, you need to have a public profile so that I can invite you.

**Comment by GoogleBeEvil** [comment]
have join the project on transifex
