### ISSUE TITLE
Question: switch from old (tag-based) Nextcloud adapter to new (folder-based) adapter

### ISSUE THREAD

**Issue by lorddoumer** [marcelklehr/floccus#227]
Setup: latest Nextcloud, latest bookmarks-app, latest floccus on Chrome and Firefox

Just a question: is there an automatic way to switch from the tag-based Nextcloud adapter to the folder-based adapter?
When just deleting the account (and bookmark-folder) in my browser ans start from scratch with the new adapter all bookmarks are in one folder and serverside still have the tags assigned. Is there an automatic or at least less strenuous way to switch than editing every bookmark on the server manually (with lots of bookmarks this takes a lot of time)?

**Comment by sollermun** [comment]
I manually created folders and reorganized all of my bookmarks in the folders. When I sync the folders are not showing up. Is folder based organization of bookmarks completely finished on the browser?

**Comment by marcelklehr** [comment]
Ah, I should probably have a section on that somewhere.

The recommended procedure for migrating to folders is the following

1. Back up your browser bookmarks
2. *Remove the active floccus account* for your nextcloud in *all* browsers
3. Remove all bookmarks on nextcloud (there's an option for that in the settings)
4. Setup a new floccus sync account with the adapter that says "with folders" (as opposed to "legacy") in one browser
5. Trigger a sync run to create the bookmarks and folders on the server
6. Make sure everything is as expected on the server
7. Setup floccus sync accounts in all other browsers with the "with folders"-adapter
8. Done.

**Comment by lorddoumer** [comment]
thanks @marcelklehr gonna try this as soon as I find the time to. creation-date is not important for me so this sounds like a good solution to me :)

**Comment by marcelklehr** [comment]
Did you face any problems with the above procedure?

**Comment by lorddoumer** [comment]
sorry, did the process on Sunday night but forgot to give feedback yesterday: everything worked fine - the initial upLoad to the server took about 3h and got interrupted once, which might be the cause why one folder gots duplicated - but apart from that everything worked perfect :)

**Comment by marcelklehr** [comment]
Nice! Then I'll add that to the README.
