### ISSUE TITLE
Can't find bookmark for id

### ISSUE THREAD

**Issue by Tank-Missile** [marcelklehr/floccus#228]
### Software versions

- Browser: Chromium 71.0.3578.98
- Floccus: 3.2.3
- Floccus sync method: nextcloud-folders

### Steps to reproduce

1. On one computer, move bookmarks around and create and/or delete folders.
2. On another computer, attempt to sync with the server.

### Expected outcome

Changes are reflected from the server to the browser.

### Actual outcome

Can't find bookmark for id. This is the first time I've gotten this error, but every other time the bookmarks don't sync into the correct positions. It will instead sync the old bookmark layout from the second computer to the server, overwriting new changes I made on the first computer. How exactly does floccus determine how it should modify the bookmarks from what end?

### Debug log

[floccus-3.2.3-2019-02-06.log](https://github.com/marcelklehr/floccus/files/2837001/floccus-3.2.3-2019-02-06.log)

**Comment by marcelklehr** [comment]
Hey @Tank-Missile 

Sorry for the delay. I think I might have found the underlying issue. Could you in any case disable parallel sync and retry to get a cleaner log file?

**Comment by Tank-Missile** [comment]
I didn't even realize I had parallel sync on. While my desktop has it on, my laptop has it off. Maybe that has something to do with the error. I haven't been able to reproduce it since. I should probably update the versions on both computers before continuing testing.

**Comment by marcelklehr** [comment]
It seems that [this](https://github.com/marcelklehr/floccus/commit/3b483610618a757ba84b882aaf6bd3d619aae021) fixed it :) :tada:

As always thanks for the feedback! :)
