### ISSUE TITLE
 Unable to sync on Chrome with extension: EDIT: Possible scam extension?

### ISSUE THREAD

**Issue by jcklpe** [marcelklehr/floccus#229]
### Software versions

- Browser: Chrome 71
- Nextcloud: 15.04
- Nextcloud Bookmarks app: latest
- Floccus: latest
- Floccus sync method: nextcloud folders

### Steps to reproduce

1.  download and install chrome extension
2. click add account. 
3. put in credentials
4. hit "sync button" 
5. get error

### Expected outcome

I expected it to work. I've already got it working on two different machines with firefox but it's not working on chrome for some reason. 

### Actual outcome

error

...

### Debug log

There does not appear to be a debug log in the chrome extension. 

Also this does not seem to be just my problem. 

# EDIT:

Ooooh whoops. Looks like I wasn't using the official app. This app doesn't work, and I don't know who made it. Maybe it's a scam? Guess I should have known better to double check this info before installing it: https://chrome.google.com/webstore/detail/floccus-nextcloud-sync/behlkinclcpoiijckdfjmibdpnfocefg/related?hl=en

**Comment by marcelklehr** [comment]
Ah yes. It's not a scam. Initial versions of floccus were not available in the webstore so someone put them up there, but since then the person has neglected the undertaking.
