### ISSUE TITLE
Usability: Why are New Accounts Disabled by Default?

### ISSUE THREAD

**Issue by gohrner** [marcelklehr/floccus#230]
After some Floccus update simply deleted / dropped by account, I recreated it.

The status checkmark on the overview page said "all good" and it took a while until I noticed that on the contrary "Last synchronized" said "never"...

Long story short the account simply was not "enabled", but this was somewhat confusing.

I'd consider it to be much more user-friendly
* not to display "all good" if the account actually is not used at the moment, but something like "currently disabled" instead.
* not to disable new accounts by default - if I add a new account, I normally want to use it
* give user feedback if the "Sync now" button is pressed but the account is disabled. (Or simply disable the "sync now" button while the account is disabled.) Currently, the user does not get any feedback that the "Sync now" action is being ignored. It looks as if the button press (which is still possible if the account is disabled) would do something, but apparently it does not...

**Comment by marcelklehr** [comment]
:+1: on all three! Thanks for the feedback :)
