### ISSUE TITLE
Getting Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by erdnussflips** [marcelklehr/floccus#232]
### Software versions

- Browser: Google Chrome 72.0.3626.96 (Offizieller Build) (64-Bit)
- Nextcloud: Nextcloud: 13.0.1
- Nextcloud Bookmarks app: not relevant, using webdav
- Floccus: 3.2.5
- Floccus sync method: `webdav`

### Steps to reproduce

Starting sync

### Expected outcome

Syncing works

### Actual outcome

Getting error: "Getting Failed to construct 'URL': Invalid URL"

**Comment by marcelklehr** [comment]
Damnit, try to fix one thing, something else breaks. Thanks for the quick feedback :)
