### ISSUE TITLE
Adjust time interval for periodic sync

### ISSUE THREAD

**Issue by steffenl82** [marcelklehr/floccus#233]
Hi.
The description claims that floccus "will also sync periodically to pull the latest changes from the server". Is there a way to adjust the time interval for that periodic sync?

**Comment by marcelklehr** [comment]
Hey,
Not currently, no. The hardcoded value is currently 15minutes. What do you hope to achieve by changing it?

**Comment by steffenl82** [comment]
15min is indeed a sensible value. However, I have observed several cases when the last sync was hours ago but no new sync was triggered (and I suspected the time interval being too long, which is why I was asking my question in the first place). So it seems that I *may* have a problem with my installation that the periodic sync is not correctly working. I have to do some more tests...

**Comment by bernd-wechner** [comment]
I'd love to see such a setting. In general:

1. It empowers me and I feel warm ad fuzzy ;-)
2. It makes it clear and in my face it's an interval based periodic check not a change triggered synch

Just my 2c worth I guess.

**Comment by steffenl82** [comment]
I think I know what the "problem" is: I guess that the 15 min are counted from the *start* of browser? In my tests I had to leave the browser open for at least 15 min to get an automatic sync - even if the last sync was a long time ago.

I was hoping that the time of the last sync (as can be seen when clicking in the floccus icon) was also taken into consideration, such that when you open your browser after a "long time" (i.e. >15 min), an automatic sync is immediately triggered after startup.

Would it be worthwhile to implement such a check?

**Comment by marcelklehr** [comment]
@bernd-wechner Well 2. is not completely true, as local changes do trigger a sync, just not server-side changes...

> when you open your browser after a "long time" (i.e. >15 min), an automatic sync is immediately triggered after startup.

That sounds like a good idea to me!
