### ISSUE TITLE
Syncing failed with Network error

### ISSUE THREAD

**Issue by a575606** [marcelklehr/floccus#236]
### Software versions

-All browsers, Floccus 3.2.6, Chrome / Firefox Windows 10, Nextcloud synology dsm docker

### Steps to reproduce

I had an issue upgrading from Nextcloud 15.0.2 to 15.0.4. I kept getting stuck in the upgrade procedure and so I had to try a few things until eventually got it working. All my data is restored, caldav, carddav syncs. The only thing that isn't working is bookmark sync with floccus. I can't really tell what's going on because the usernames and passwords were saved. I even set up a new app password for floccus, but it refuses to connect. All I get is the following few lines repeated over and over in the log. Any ideas? I could send you the log, but literally it's the same 4 lines repeated, nothing else. 

### Debug log

Fetching bookmarks
Syncing failed with Network error: Check your network connection and your account details
Starting sync process for account admin@cloud.domain.net
Overriding title of built-in node 1 Bookmarks bar => Bookmarks Bar

**Comment by marcelklehr** [comment]
Hey :)
Sorry for your troubles! Could you please provide the following:

Software versions
Browser:
Nextcloud:
Nextcloud Bookmarks app:
Floccus:
Floccus sync method:

**Comment by a575606** [comment]
Sure thing. Sorry was kind of in a rush last time. 

Software versions
Browser: Chrome 72.0.3626.119 (Official Build) (64-bit)
Nextcloud: 15.0.4
Nextcloud Bookmarks app: 	0.16.2
Floccus: 3.2.6
Floccus sync method: folders

**Comment by marcelklehr** [comment]
Mh, nothing suspicious there. The Error message indicates that there is a problem reaching the server. In order to find out exactly what is going wrong you can open the extension debugger as follows:

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the Network tab
* trigger a sync by clicking on `force Sync` for the floccus account of your choice
* go back to the network inspector window and check the network logs

**Comment by a575606** [comment]
Thank you so much. And sorry to waste your time. That tip helped me see what was going on, which turned out to be related to cached data in Chrome. I cleared the cache and  floccus seems to be syncing now. Will let you know if there are any other issues.

**Comment by marcelklehr** [comment]
mmh. What was the error in chrome exactly? I'd like to make sure nobody else runs into this :)

**Comment by a575606** [comment]
I think this would be an unlikely scenario for someone else to run into. What happened was I updated nextcloud from 5.0.2 to 5.0.4 and the update failed. So I had to install a new installation in order to complete the update. I think Chrome was trying to sync while I was updating and saved the wrong redirect in the cache. In Chrome, the url for my server was being redirected to https:// _/path

**Comment by marcelklehr** [comment]
Ah, ok that makes sense. Thanks! :)
