### ISSUE TITLE
json.item is undefined

### ISSUE THREAD

**Issue by f24nz** [marcelklehr/floccus#237]
When trying to sync bookmarks from the browser to the nextcloud I get this error and the bookmarks are not synced:
`json.item is undefined`

Bookmarks created in the nextcloud app, can be synced without an error.

### Software versions

- Browser: Firefox 65.0.1 and 63.0
- Nextcloud: 15.0.4
- Nextcloud Bookmarks app: 0.16.2
- Floccus: 3.2.6
- Floccus sync method: nextcloud-folders

**Comment by marcelklehr** [comment]
Can you provide a debug log? (You can send it to me vai mail, if you like. In fact, I encourage it.)

**Comment by f24nz** [comment]
Sorry, it was my fault. There was a problem with the domain redirection.

**Comment by marcelklehr** [comment]
Mh, still the error message could probably be improved :D

**Comment by f24nz** [comment]
True, I'd be glad to contribute to that. Where do I find the logfiles of floccus?

**Comment by marcelklehr** [comment]
Ah, that won't be necessary. Those would only have been necessary if there was a bug in floccus, as it stands I think I know where things went wrong.
