### ISSUE TITLE
Folder #xxx[xxx] contains an nonexistent bookmark xxx

### ISSUE THREAD

**Issue by CharlesCage** [marcelklehr/floccus#239]
### Software versions

- Browser: Chome 73.0.3683.75
- Nextcloud: 15.0.5
- Nextcloud Bookmarks app: 0.16.2
- Floccus: 3.2.8
- Floccus sync method:  nextcloud-folders

### Steps to reproduce

1.  Perform sync

### Expected outcome

Sync success

### Actual outcome

Receiving a variety of similar errors following the format described in issue header, ex: "Folder #281[Bikspo] contains an nonexistent bookmark 564." 

When I review the debug log and find the specific bookmark causing the error, I find that it's listed once in the debug log but appears twice in the Nextcloud Bookmarks section. Removing one of these (or sometimes two) will allow floccus to complete the sync -- or sometimes find another similar error, in which case resolving all as described allows a complete sync. However, the issue appears again on its own over the course of 24-48 hours.

**Comment by CharlesCage** [comment]
[floccus-3.2.8-2019-03-15.log](https://github.com/marcelklehr/floccus/files/2969103/floccus-3.2.8-2019-03-15.log)

Apologies -- please find attached debug log.

**Comment by tomershvueli** [comment]
I'm seeing this same issue as well. I'm on Vivaldi 2.3.1440.60 (Stable channel) (64-bit). Floccus version 3.2.8.

**Comment by marcelklehr** [comment]
@CharlesCage mmh. The log you provided doesn't cover the incident, I'm afraid. Could download the log again, immediately after seeing the error?

**Comment by CharlesCage** [comment]
Sure thing, and sorry for the delay.

Current specific error:
Folder #441[Video] contains an nonexistent bookmark 376

[floccus-3.2.8-2019-03-18.log](https://github.com/marcelklehr/floccus/files/2979105/floccus-3.2.8-2019-03-18.log)

Also, some additional information regarding my troubleshooting: I was able to make the issue go away by backing up bookmarks from one source, deleting all bookmarks, syncing deletions across all browsers, re-importing the bookmarks, and re-syncing across all browsers. However, the problem soon returned.

I think this is clearly related to sync. I wonder if it might have something to do with handling of lost connections during sync? 

Thanks again for your work.

**Comment by marcelklehr** [comment]
Mh. the log still doesn't contain the error :/ From what I could gather, the problem might have occured only recently, is that correct?

**Comment by marcelklehr** [comment]
I've released a patch release that should take care of the duplicates (finally). Let's see if it takes care of the error as well.

**Comment by CharlesCage** [comment]
Ok! To give it a clean slate I removed Floccus from all browsers. Exported bookmarks from Chrome instance. Deleted all bookmarks from Chrome instance. Deleted all bookmark data from Nextcloud. Updated Nextcloud Bookmarks app to 0.16.3. Installed 3.2.9 version of Floccus on Chrome instance and sync'd zero bookmarks (all good). Imported bookmarks to Chrome. Sync'd bookmarks to Nextcloud (long time, but all good). Deleted all bookmarks from Firefox instance. Installed Floccus 3.2.9 on Firefox instance, connected to Nextcloud, and sync'd (all good).

Setting an alarm to report back in a day or two with results.

Thanks again for your time and effort.

**Comment by CharlesCage** [comment]
Follow-up: I believe we can close this. I haven't had any issues so far, and because it seemed sync-related I've purposely tried interrupting sync with closing browsers, hibernating and suspending systems, etc. Seems solid.

If anything comes up, I'll file a new issue.

Hey, really want to thank you for the patch--and Floccus in general.

**Comment by marcelklehr** [comment]
Thank you for the feedback! :)
