### ISSUE TITLE
problem when there are special characters (Umlaute) in the URL

### ISSUE THREAD

**Issue by steffenl82** [marcelklehr/floccus#241]
Hi

There seems to be a problem with floccus when there are special characters (Umlaute) in the URL.

For example, I have the following link:
https://www.kodinerds.net/index.php/Thread/45285-DEFEKT-RELEASE-Rytec-EPG-Downloader-für-IPTV-Simple-PVR-Addon/?postID=225380#post225380

When I initially bookmark that link, everything seems to be OK. In the bookmark manager the link is encoded like that:
https://www.kodinerds.net/index.php/Thread/45285-DEFEKT-RELEASE-Rytec-EPG-Downloader-f%C3%BCr-IPTV-Simple-PVR-Addon/?postID=225380#post225380

However, after "some time" the link grows longer and longer, e.g.:
https://www.kodinerds.net/index.php/Thread/45285-DEFEKT-RELEASE-Rytec-EPG-Downloader-f%C3%83%C2%83%C3%82%C2%83%C3%83%C2%82%C3%82%C2%83%C3%83%C2%83%C3%82%C2%82%C3%83%C2%82%C3%82%C2%83%C3%83%C2%83%C3%82%C2%83%C3%83%C2%82%C3%82%C2%82%C3%83%C2%83%C3%82%C2%82%C3%83%C2%82%C3%82%C2%83%C3%83%C2%83%C3%82%C2%83%C3%83%C2%82%C3%82%C2%83%C3%83%C2%83%C3%82%C2%82%C3%83%C2%82%C3%82%C2%82%C3%83%C2%83%C3%82%C2%83%C3%83%C2%82%C3%82%C2%82%C3%83%C2%83%C3%82%C2%82%C3%83%C2%82%C3%82%C2%BCr-IPTV-Simple-PVR-Addon/?postID=225380#post225380

I was not able to determine the exact cause but my impression is that this happens when one is switching between different browsers (Chrome and Firefox in my case).

As a side note: floccus now even generated (without my assistance) a duplicate bookmark of that link.

I'm using floccus 3.2.8 with XBEL on WebDAV (and latest stable version of Firefox and Chrome)

**Comment by marcelklehr** [comment]
Hey!
Thanks for reporting this! v3.2.9 should fix this. Feedback is appreciated :)
