### ISSUE TITLE
Allow choosing sync method per account

### ISSUE THREAD

**Issue by Tank-Missile** [marcelklehr/floccus#243]
I'm using two providers, and the first one, as you know, has the bookmarks app available. The second provider is a backup, since relying on one provider only is bound to cause issues down the line. This second provider does not have the bookmarks app available, and so I must use the xbel sync method for it instead. However, currently you can only set the sync method globally for all accounts.

**Comment by marcelklehr** [comment]
> However, currently you can only set the sync method globally for all accounts.

Oh, that's actually not true. The selector in the main view is only used when creating a new account. I should probably make this clearer in the UI.

**Comment by Tank-Missile** [comment]
Oh, I'm an idiot for not noticing that. Is there no way to change the sync method per account after creation though?

**Comment by marcelklehr** [comment]
> Is there no way to change the sync method per account after creation though?

There is not, because all adapters require different settings. Creating a new account for the same folder shouldn't be a problem, though, I think.
