### ISSUE TITLE
Feature Request: One way sync

### ISSUE THREAD

**Issue by a575606** [marcelklehr/floccus#244]
I'm trying to find the best setup for syncing bookmarks between Nextcloud and Chrome and Firefox on my two Win10 pc's and Firefox on my Android phone.  

In addition to Floccus, I set up a Firefox Sync Server, which allows me to sync between Win10 and Android Firefox. That works great for Firefox, but because Firefox sync breaks Floccus, I have had to disable Floccus for the time being. 

Ideally I'd like to keep Nextcloud and Chrome synced as well, but I understand the challenges around multiple syncs on the same data. 

One idea I had to get around the problem was having one directional sync. I.e, adding the option to only push to or only pull from Nextcloud, for a given brownser, in addition to the current bidirectional sync option. 

Uni directional sync shouldn't create conflicts with browser sync if it's set only to push changes. So, from Firefox I could push changes to Nextcloud and pull them to Chrome. Meanwhile Firefox would stay in sync via browser sync. 

Do you think that could work? Perhaps it's something I could help with coding if you think it's a useful idea?

**Comment by Magissia** [comment]
That would solve lot of problems.

**Comment by bernd-wechner** [comment]
I certainly like the idea of being able to set any instance of floccus into "Slave" mode,, only taking updates from the server. It would be equally good to be able to temporarily change that. To say add a bookmark on a Slave save then sync it up. In the ideal (I do dream) that would be on a bookmark by bookmark basis. I could select a bookmark as say "Yes, this is  Slave instance of floccus, but this one bookmark, push it to the server".

**Comment by maverick74** [comment]
Count me as super interested in this as well!!!

**Comment by eleksis** [comment]
This feture..to have push/pull buttons..would be super helpful. Is this on horizon?

Often i want to clean my bookmarks on one device, push to server and on other devices pull/override instead of merge.

**Comment by marcelklehr** [comment]
Sorry for not responding earlier. This is definitely on the horizon. Some code on is already done, but still unreleased. It'll be a few weeks until I get back to the bookmarks/floccus ecosystem, though.

**Comment by marcelklehr** [comment]
I polished the code that's already done on this and made it available for testing as v3.4.0-beta.1. It's only the slave mode for now. Feel free to give this a try and provide feedback :) (Don't forget your backups! :smile:)

**Comment by marcelklehr** [comment]
Feel free to try our this feature in the [latest beta](https://github.com/marcelklehr/floccus/issues/338)
