### ISSUE TITLE
Lock Error: Unable to clear lock file, consider deleting Bookmarks.xbel.lock

### ISSUE THREAD

**Issue by Tank-Missile** [marcelklehr/floccus#245]
### Software versions

- Browser: Chromium 71.0.3578.98
- Floccus: 3.2.10
- Floccus sync method: webdav
- Provider: https://cloud.owncube.com

### Steps to reproduce

1. Create an an account with the webdav sync method.
2. Attempt to perform a sync.

### Expected outcome

Bookmarks.xbel generates at the root of all the folders.

### Actual outcome

The file fails to generate and I recieve the error in the title. It says to delete Bookmarks.xbel.lock, but it's nowhere to be found in my nextcloud folder or in the web interface.

### Debug log

[floccus-3.2.10-2019-03-23.log](https://github.com/marcelklehr/floccus/files/2999599/floccus-3.2.10-2019-03-23.log)

**Comment by marcelklehr** [comment]
When using the webdav adapter, make sure to provide the URL to the actual webdav share on your server. The options view shows an exemplary URL for nextcloud.

**Comment by Tank-Missile** [comment]
I just made the assumption the base URL was enough. I need to stop configuring things so late at night. It's working now. Sorry for the time waster.

**Comment by marcelklehr** [comment]
No problem :)
