### ISSUE TITLE
Folders placed before other bookmarks after sync

### ISSUE THREAD

**Issue by Tank-Missile** [marcelklehr/floccus#249]
### Software versions

- Browser: Chromium 71.0.3578.98
- Nextcloud: 3.2.10
- Floccus sync methods: nextcloud-folders and webdav

### Steps to reproduce

1. Create two accounts, one using the nextcloud-folders sync method, and the other using the webdav sync method.

2. Attempt a sync on both accounts.

### Expected outcome

The bookmarks app and the Bookmarks.xbel file are populated with the bookmarks from my browser.

### Actual outcome

The above happens, but then my bookmark folders are placed before my other bookmarks on the bookmarks bar. Oddly enough, one folder is kept in front of my other bookmarks.

### Debug log

[floccus-3.2.10-2019-03-26.log](https://github.com/marcelklehr/floccus/files/3010306/floccus-3.2.10-2019-03-26.log)

**Comment by marcelklehr** [comment]
Am I correct, when I say you're syncing the same folder with two accounts?

**Comment by Tank-Missile** [comment]
According to that, I can't have one account sync the root folder and another account sync a subfolder, although from reading the first sentence it appears I also can't sync the root folder to two different accounts. If so, that's quite an annoying problem. I'll have to workaround it somehow.

**Comment by marcelklehr** [comment]
Basically, no folder can be associated with two sync profiles / accounts, at the moment, yes.

**Comment by Tank-Missile** [comment]
I suppose for now I'll just stick with the webdav adapter in that case. Any idea why it's a problem for two accounts to sync the same folder? If it's a matter of conflicts, then perhaps each account sync could be queued.

**Comment by marcelklehr** [comment]
> perhaps each account sync could be queued.

Yeah, queuing the accounts to sync one after the other is on my todo list anyways, as it makes for much cleaner debug logs.

> Any idea why it's a problem for two accounts to sync the same folder?

I simply haven't tested this, as of yet, and didn't want the user to run into errors.

**Comment by marcelklehr** [comment]
I'll create a feature-request issue for this and close this, then :)
