### ISSUE TITLE
Setup dev environment?

### ISSUE THREAD

**Issue by theScrabi** [marcelklehr/floccus#25]
Hello,

how can I setup a dev environment for this app? Can you please give a link or a small description.

rgds schabi

**Comment by marcelklehr** [comment]
Hey!
I mostly develop in firefox and the intro of [this post](https://robertnyman.com/2009/01/24/how-to-develop-a-firefox-extension/) describes my setup.

**Comment by marcelklehr** [comment]
I probably also should have mentioned that you will need node and npm. After cloning run `npm install && npm install -g gulp` and then run `gulp` (after every change you'll need to do this...)

**Comment by marcelklehr** [comment]
I added a section for this in the readme... Closing this, but feel free to ask if you have more questions! :)
