### ISSUE TITLE
Problem in Firefox when XBEL file contains chrome internal URLs

### ISSUE THREAD

**Issue by Schteinbock** [marcelklehr/floccus#250]
### Software versions

- Browser: Firefox and Chrome
- Nextcloud: 14
- Nextcloud Bookmarks app: N/A
- Floccus: 3.2.10
- Floccus sync method: XBEL/webdav

### Steps to reproduce
1.  Created new XBEL in WebDav Account in Firefox Plugin
2. Filled in login credentials
3. Filled existing! file on dav
4. Sync now

### Expected outcome
Syncing all bookmarks contained in XEBEL file

### Actual outcome
Syncing failed with chrome:newtab/ is not a valid URL. Actually there was a corresponding URL contained in the XBEL file, propably (accidentally) created by a Chrome user  however I would have expected that either this URL would not have been saved by floccus or skipped by firefox.

### Debug log
onSyncStart: begin
https://collab.ohrner-it.com/dav/bookmarks.xbel.lock
https://collab.ohrner-it.com/dav/bookmarks.xbel.lock
Adding folder "Allgemein"
Adding folder "XDIS"
Adding folder "Buildinfrastruktur"
Adding folder "Dokumentation"
Adding folder "Issues"
Adding folder "GSEP"
Adding folder "Entwicklung allg."
Adding folder "Sysadmin"
Syncing failed with chrome:newtab/ is not a valid URL.
onSyncFail

**Comment by marcelklehr** [comment]
Confirmed. Fixed. Bugfix release outstanding.

Thank you for the feedback :gift: :)
