### ISSUE TITLE
Editing fields causes characters to disappear, not enter, or won't delete

### ISSUE THREAD

**Issue by allobrogica** [marcelklehr/floccus#251]
(Redid this issue since there were two items in one…)

When trying to add or edit any of the fields in the xbel/webdav setup screen: Whenever I enter text into any field sometimes it enters ok but usually I enter some characters and then it deletes a character I entered so I have to re-enter it. Will occur several times within any one field. Also when I try deleted characters, some will delete and then sometimes if I continue pressing delete it will just delete a few characters and then just re-delete the same characters but never finish deleting all the characters in the field. It’s very difficult to deal with entering info and ensuring the info is correctly entered. Very reproducible. I also tried on clean browsers with no extensions and in a separate user space on the Mac. Always happens with Chrome and Brave.

Floccus 3.2.11 with Chrome 73 and with Brave 61.52. MacOS 10.13.6

**Comment by enodr** [comment]
I can confirm this weird bug on Chrome Version 73.0.3683.86 (official build) (64 bits). When adding a nextcloud account when you enter text in the text fields, characters are randomly deleted. It's very annoying.

**Comment by carnyccc** [comment]
Same problem here.

Floccus 3.2.11 with Firefox 66.0.2 on Windows 10 Edu

**Comment by djwyman** [comment]
I can confirm this on Ubuntu 18.10 Firefox 66.0.2 and floccus 3.2.11  it has been kinda agravating I will type a caracter and then it gets deleted...entering a password is real fun because you don't know what has been deleted.

**Comment by allobrogica** [comment]
Btw, what I wound up doing to lessen the frustration was to copy/paste the values into each field instead of typing them in. 50% of the time the paste doesn't work either (same percentage as typing in the text), but at least it gets the job done quicker. Especially for the password field since it's hard to know whether what you type is what's in the field. The paste either fully works/pastes into the field or it doesn't at all - you can tell right away.

**Comment by Tank-Missile** [comment]
Ah, so I wasn't going crazy thinking I was the only one with this issue. It's been an issue since I started using it, but it wasn't very consistent, so I wrote it off.

**Comment by marcelklehr** [comment]
Sorry folks, the progress bar feature messed this one up :/

**Comment by marcelklehr** [comment]
Let me know if this fixed things for you :)
