### ISSUE TITLE
Item in folder ordering is not an actual child: {"id":128,"type":"bookmark"}

### ISSUE THREAD

**Issue by gohrner** [marcelklehr/floccus#252]
### Software versions

- Browser: Chromium 73.0.3683.75
- Nextcloud: XBEL/webdav
- Nextcloud Bookmarks app: XBEL/webdav
- Floccus: 3.2.11
- Floccus sync method: XBEL/webdav
  

### Steps to reproduce

Not sure - I'm just getting the following error with the new Floccus version:

  Item in folder ordering is not an actual child: {"id":128,"type":"bookmark"}

That's the same error message as in Issue #213, which is supposed to be fixed, though...

**Comment by gohrner** [comment]
```(local)REMOVE 673
ORDERFOLDER { id: 6,
  order: 
   [ { id: 7, type: 'bookmark' },
     { id: 28, type: 'bookmark' },
     { id: 42, type: 'bookmark' },
     { id: 43, type: 'bookmark' },
     { id: 128, type: 'bookmark' },
     { id: 24, type: 'folder' },
     { id: 22, type: 'folder' },
     { id: 23, type: 'folder' },
     { id: 113, type: 'folder' },
     { id: 74, type: 'bookmark' } ] }
Syncing failed with Item in folder ordering is not an actual child: {"id":128,"type":"bookmark"}
onSyncFail```

**Comment by marcelklehr** [comment]
Does the message persist across sync runs or does it only occur sporadically?  The whole log would be helpful to see what's going on with that bookmark.

**Comment by gohrner** [comment]
The message persistet for several (manual) sync attempts and always reappeared at the time when I reported the issue. Meanwhile it's "gone" however, so it somehow fixed / resolved itself after some time - no idea, why or how.

**Comment by marcelklehr** [comment]
Closing this for now. Shout if this happens again :)

**Comment by jlbprof** [comment]
FYI, I fixed it by clicking on the option "Merge bookmarks on next run" and
it has not come back.
