### ISSUE TITLE
Firefox 66.0.2 (64-Bit): Network error: Check your network connection and your account details

### ISSUE THREAD

**Issue by jakobroehrl** [marcelklehr/floccus#253]
Hi, 

thanks for the great app. 
I installed it yesterday and it works. Today I get this error:

Network error: Check your network connection and your account details 

From the log:
Fetching bookmarks
Syncing failed with Network error: Check your network connection and your account details

### Software versions

- Browser: Firefox 66.0.2 (64-Bit)
- Nextcloud: 15.0.4
- Nextcloud Bookmarks app:  0.16.4
- Floccus: 3.2.11
- Floccus sync method: nextcloud with Bookmarks

**Comment by marcelklehr** [comment]
This indicates that your server is not reachable. It might be going away with the latest release, though.

**Comment by jakobroehrl** [comment]
It's working with the new update, thanks! :)
