### ISSUE TITLE
Bookmarks Name and Order

### ISSUE THREAD

**Issue by maverick74** [marcelklehr/floccus#255]
### Software versions

- Browser:Firefox 66.0.2
- Nextcloud: v14 (not sure about it)
- Floccus:3.2.12
- Floccus sync method: nextcloud Bookmarks v0.14+ with folders

### Steps to reproduce
I have a few bookmarks to which i changed the name, but upon sync they got renamed to (apparently) their original name. And they also got reordered.

I believe both changes are part of the same problem 

But this is - correct me if i'm wrong - nextcloud's fault has it seems that nextcloud get's bookmark's name from their URL... if so, please close the bug report :)

**Comment by marcelklehr** [comment]
Nextcloud only uses the webpage title if no other title is specified. Did you change your bookmarks to have no title?

**Comment by maverick74** [comment]
No, they all have titles

**Comment by maverick74** [comment]
I think i figure it out!
What happens if one has duplicated bookmarks in diferent folders?

**Comment by marcelklehr** [comment]
Ah, yes, they'll be converged by the bookmarks app into one bookmark residing in multiple folders .

**Comment by maverick74** [comment]
so, they'll keep just one of the names, correct?

**Comment by marcelklehr** [comment]
Yes.
