### ISSUE TITLE
Unlock fails because input field is immediately unfocused and cleared on keypress

### ISSUE THREAD

**Issue by phish108** [marcelklehr/floccus#256]
### Software versions

- Browser: chrome 73.0.3683.86
- Nextcloud: 15.0.5
- Nextcloud Bookmarks app: 0.16.4
- Floccus: 3.2.12
- Floccus sync method: n/a (because its locked away)

### Steps to reproduce

1.  Lock floccus configuration with a simple password
2. Restart browser 
3. Try to unlock the floccus configuration using the password (watch how the UI uses partial passwords on keypress) 
4. fail :(

### Expected outcome

* floccus accepts the unlock password properly.

### Actual outcome

* floccus is dysfunct.

### Debug log

- [ ] Debug log provided

debug is locked away, too

**Comment by jellykells** [comment]
I'm having the same issue using the following software:
- Vivaldi 2.2.1388.37/Chrome 71.0.3578.98
- Nextcloud 15.0.5
- Nextcloud Bookmarks 0.16.4
- Floccus 3.2.12

It _is_ possible to unlock Floccus, but you have to paste your password and hit enter very quickly in order to do so.

**Comment by marcelklehr** [comment]
Please update floccus, the issue should be fixed, now.
