### ISSUE TITLE
[usability] use different icon when the password has not yet been introduced

### ISSUE THREAD

**Issue by nachoparker** [marcelklehr/floccus#257]
A simple usability suggestion: right now I don't know if I have input my password unless I click on the icon, because the "disconnected" icon is the same as the "synced ok" icon.

Using a different icon for that state would be valuable info, and more correct.

Thanks!

**Comment by marcelklehr** [comment]
Ah, great suggestion! :)

**Comment by marcelklehr** [comment]
It's so great, in fact, that it should already do this :see_no_evil: Regressions...

**Comment by nachoparker** [comment]
oh well... thanks for looking into it!
