### ISSUE TITLE
Sync does not respect the latest changes on another client or Nextcloud Bookmarks app

### ISSUE THREAD

**Issue by e-alfred** [marcelklehr/floccus#259]
### Software versions

- Browser: Vivaldi, Opera, Firefox, Chrome
- Nextcloud: 15.0.6
- Nextcloud Bookmarks app: 0.16.4
- Floccus: 3.2.15
- Floccus sync method: nextcloud-folders
  

### Steps to reproduce

1.  A lot of redundant bookmarks were created due to this bug: https://github.com/marcelklehr/floccus/issues/258
2. If I delete or change bookmarks on one client or the Nextcloud Bookmarks App directly, the will be re-synced by other clients.

### Expected outcome

The latest changes on a client or the Bookmarks app should always take precedence over an older state on another client or the server. Bookmarks that have changed or were deleted shouldn't be re-synced with an older state from another client.

### Actual outcome

Unwanted and deleted or changed Bookmarks are re-synced from other clients to the server while ignoring the fact that they were deleted or changed on another system.

**Comment by marcelklehr** [comment]
Could you try resetting the cache on all clients, syncing all clients, and then removing the bookmarks in question again?

**Comment by e-alfred** [comment]
Okay, I bit the bullet and did the following:

- Disable all Floccus clients so they stop syncing bogus bookmarks
- Remove all redundant bookmarks from the Bookmarks UI in Nextcloud (the new interface makes it really easy which is awesome!)
- Removed the bookmarks in the folder synced with Floccus on each browser
- Set the "merge bookmarks" checkmark and enabled sync in Floccus again

Now everything works again, but I think this is still a bug. The last change on any client or the server UI should take precedence over all other clients with an older state. Syncing back old bookmarks from other clients is very annoying for users actually. The only exception probably would be a deletion of all bookmarks similar to the Nextcloud sync client warning of a complete removal of everything. Maybe a recycle bin in the Bookmarks app would be another idea to mitigate this?

**Comment by marcelklehr** [comment]
> the new interface makes it really easy which is awesome!

Glad you like it :)

>  Syncing back old bookmarks from other clients is very annoying for users actually. 

I will try to replicate this, but I agree, it shouldn't do this.

**Comment by marcelklehr** [comment]
I cannot replicate this with any normal bookmarks that I delete, so this behavior probably was specific to the circumstances with the duplicates. Thanks for your feedback, as always :) :star2:
