### ISSUE TITLE
potential out-of-memory crash

### ISSUE THREAD

**Issue by SteveKeller** [marcelklehr/floccus#261]
### Software versions
- Browser: Chromium Version 75.0.3743.0
- Nextcloud: 15.0.5
- Nextcloud Bookmarks app: -
- Floccus: 3.2.16
- Floccus sync method: XBEL/webdav

### Steps to reproduce
1. Create a nextcloud account
2. Config Floccus with nextcloud account and webdav (just one chromium browser)
3. Perform a sync
4. After successful sync, lock file wasn't deleted -> sometimes only

### Expected outcome
Lock file should be deleted after successful sync.

### Actual outcome
Lock file still exists and has to be deleted manual, before new sync can success.

### Debug log
fullURL :https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel:
Successfully ended sync process for account bookmarks@nextcloud.mydomain.com
Starting sync process for account bookmarks@nextcloud.mydomain.com
onSyncStart: begin
https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel.lock
https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel.lock
https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel.lock
https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel.lock
https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel.lock
https://nextcloud.mydomain.com/remote.php/webdav/bookmarks.xbel.lock
Syncing failed with Lock Error: Unable to clear lock file, consider deleting bookmarks.xbel.lock
onSyncFail

- [x] Debug log provided

I have tested my credentials (basic auth) manual -> ok (HTTP DELETE request of lock file)
When sync fails the floccus plugin crashes.
This error only occurs sometimes. After closing the browser and reopen it works again.

Thanks for your input and help!

**Comment by marcelklehr** [comment]
> When sync fails the floccus plugin crashes.

Is this always the case, when sync fails? Is there any error message?

At first glance, my diagnosis would be: The crashes (although undesired) explain the lock file not being deleted, but you describe the lock file being present despite a successful sync run... :/

**Comment by SteveKeller** [comment]
Yes, it always the case when sync fails. -> it crashes
Only the error message in the log file as provided.

I have checked your diagnosis and it correct. After sync fails and the crash occurs, than the lock file still exists. 
But when I delete the lock file manual and reload floccus and trigger syncing , it crashes immediatly  again with the same error messages. It doesn't make any difference if the lock file exists or not.

So as you have guessed the real problem is the crash and not the deletion of the lock file.

**Comment by marcelklehr** [comment]
> But when I delete the lock file manual and reload floccus and trigger syncing , it crashes immediatly again with the same error messages.

So, when you delete the lock file manually, it sync fails with the error "Unable to clear lock file" and it crashes?

**Comment by SteveKeller** [comment]
Yes, exactly.

**Comment by marcelklehr** [comment]
Unfortunately I cannot replicate this. To get further debug information please do the following:

In order to aid in debugging, please provide client-side logs.

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and check the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and check the logs after waiting for the sync to finish

**Comment by SteveKeller** [comment]
Great guide to debug, thanks!

It turned out that floccus crashs because of a **potential out-of-memory crash** in chromium.

The exact location which cause the problem is in dist/js/node_modules/conservative-normalize-url/index.js
Line: 208

The parsing of one special url did not work because it's to long and this cause out-of-memory. So I have investigated in the special url. 
While parsing it the url looks like this: '################################..........#######/login?type=samlsso_notification.do?client_id=..........'   -> _way to many hash signs!_

I think something went wrong while syncing/converting from browser to nextcloud file.
Real problem url looks like: https://my.domain.com/#/login?type=samlsso_notification.do?client_id=.....
-> _hashes went crazy_

**Another indication for out-of-memory is the file size of bookmarks.xbel!**
I have about 700 bookmarks and my .xbel file size was about 64MB -> _probably due to the special url._

# My Solution:
1. Backup your bookmarks
2. Delete lock and booksmark.xbel file on nextcloud
3. Check if special url doesn't exists in bookmarks on chromium browser
4. Sync Floccus with option "Trigger sync from scratch"
5. Check file size of bookmarks.xbel -> now 75KB
6. Works again! :D

**Comment by marcelklehr** [comment]
Ah, yes. There was a bug that caused hash-signs to double on every sync recently. This is fixed now, so it shouldn't come up again.

**Comment by SteveKeller** [comment]
Great to hear that!

Will the next release contain this bugfix?

**Comment by marcelklehr** [comment]
This was fixed with [v3.2.15](https://github.com/marcelklehr/floccus/blob/develop/CHANGELOG.md#v3215) which was released 8 days ago :)

**Comment by SteveKeller** [comment]
Okey, interessing. I don't know either.
Anyway, now it works as expected :)
