### ISSUE TITLE
Sync the same folder with multiple accounts

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#264]

**Comment by sunjam** [comment]
Is this possible with v4.0.2?

**Comment by marcelklehr** [comment]
It is not. Floccus is still hardcoded to avoid this, as I'm afraid people will shoot themselves in the eye if this is allowed. What is your usecase for this, so I can understand the concern better?

**Comment by Tank-Missile** [comment]
A usecase for me is redundancy. If I could sync the same folder with multiple providers, it's an extra layer of keeping my bookmarks safely backed up. This way if one of the providers I use goes offline, I can still rely on the other providers to keep my bookmarks backed up.

**Comment by sunjam** [comment]
For me, I want to find a way to keep copies of my bookmarks in multiple locations as well.  In fact, I'd like to keep an update-to-date copy in Nextcloud + a local filesystem copy outside of my Nextcloud storage in case it becomes unavailable, or I just want to be a crazy person and use a bookmark application that looks for local filesystem html files.  No worries if this request is madness. :)

**Comment by marcelklehr** [comment]
I guess, it should be fine to remove the restriction now. The controller makes sure that no two accounts are synced at the same time, so I guess this should be fine.
