### ISSUE TITLE
Sync fails when self signed SSL cert not accepted

### ISSUE THREAD

**Issue by clidx** [marcelklehr/floccus#265]
### Software versions

- Browser: Chromium 72.0.3626.122
- Nextcloud: 15
- Nextcloud Bookmarks app: 0.1.7 https://apps.nextcloud.com/apps/bookmarks
- Floccus: 3.2.16
- Floccus sync method: nextcloud-folders
  

### Steps to reproduce

1.  I ran sync. Failed.
2. I went onto my nextcloud page and accepted the SSL cert warning.
3. I synced. Succeeded.

### Outcome

See above

### Debug log
````
Starting sync process for account <user>@<url>
Overriding title of built-in node 1 Bookmarks bar => Bookmarks Bar
Fetching bookmarks
Syncing failed with Network error: Check your network connection and your account details

````
Just this over and over again.
- [x] Debug log provided

I realize now this is probably desirable behaviour but when I first posted this I hadn't figured out what the cause was yet, so here it is anyway.

**Comment by marcelklehr** [comment]
This is more of a browser issue. Perhaps there is a way to tell your browser to permanently accept your self-signed certificate?
