### ISSUE TITLE
Folder #xxx[xxx] contains an nonexistent bookmark xxx

### ISSUE THREAD

**Issue by linux0uid** [marcelklehr/floccus#267]
### Software versions

- Browser:
    - Chromium Version 73.0.3683.75 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit);
    - Firefox Quantum 60.6.1esr (64-bit);
- Nextcloud: v15.0.7
- Nextcloud Bookmarks app: v0.17.0
- Floccus: for chomium - v3.2.16, for firefox - v3.2.15
- Floccus sync method: nextcloud Bookmarks v0.14+ with folders

### Expected outcome

I have try make sync from firefox and chromium. And even if first sync finished successfully after some time I had this error. On server side I did find the logging errors related to this issue. I have do sync from screech (removed flocuss from all browsers, remove all bookmarks on server) several times without success. I have run sync with both browsers together and with each of them alone. All the time sooner or later I have the same error.

### Debug log
https://cloud.steli-horizon.com.ua/s/34jeHoQWMGidAXJ

**Comment by tkurbad** [comment]
I'm seeing the same. Also, when trying to sync FF and Chromium concurrently.

**Comment by marcelklehr** [comment]
This is an artifact of two sync runs happening at the same time from two different browsers. This leads to one client observing an inconsistent server state and stopping with the above message. This should no longer happen with sparse tree syncing as introduced by the upcoming v3.3.0 (see #269 )
