### ISSUE TITLE
Bug and Suggest？have log，thank you！

### ISSUE THREAD

**Issue by zxylly1125** [marcelklehr/floccus#268]
Thank you for your project
(url)
I am using
Google Chrome version 73.0.3683.103 x64
Floccus for chrome version 3.2.16
Firefox China version 66.0.3 x64 (one touch and the official version)
Floccus for firefox version 3.2.15

The latest version is very good in chrome and can be synced in webdav. Pay tribute to you!

But there are still three questions
1, more than 2000 bookmarks, synchronization is very slow
2, sync in firefox. The progress bar has been stopped at the end and cannot be successful
3, bookmark url contains "chrome://xxxxx", in Firefox will directly interrupt synchronization.

I can check because Firefox doesn't support "chrome://" as a protocol, but I want to make a suggestion (maybe I am too arrogant, sorry! Please forgive me!)

a. Add "http://" to the url "chrome://xxxx" synchronization process so that it ends up as "http://chrome://xxxx", it can be saved, but it needs constant detection, increase or decrease content .
b. Ignore the bookmark with "chrome://xxxx" directly. If the folder changes, the bookmark that cannot be given the address will be moved to "Other Location".

If there is a wechat QR code, I can donate it to you!
Forgive me for not writing English
thank you very much!
[floccus-firefox-3.2.15-2019-04-18.log](https://github.com/marcelklehr/floccus/files/3093899/floccus-firefox-3.2.15-2019-04-18.log)
[floccus-chrome-3.2.16-2019-04-18.log](https://github.com/marcelklehr/floccus/files/3093900/floccus-chrome-3.2.16-2019-04-18.log)

**Comment by marcelklehr** [comment]
Thank you for your feedback, I've just fixed the bug with chrome:// URLs :)
