### ISSUE TITLE
v3.3.0 Beta phase 

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#269]
Hello there,

if you're up for a bit of testing in order to get an earlier glimpse at the new features of the upcoming floccus version, you're welcome to follow the guide below :)

Changes:

- Improved sync algorithm:  better performance by loading a sparse tree (i.e. only the changed parts of the server tree)
- Internationalization: German, French, Portuguese and Russian are done already, if you'd like to help, head over to #266 
- Sync interval option: You can now specify how long floccus should wait before syncing again, if no changes have happened locally
- Improved mobile support (Kiwi browser now supports floccus on android :tada:)

### Chrome (separate testing installation)
* Download the build here: https://github.com/marcelklehr/floccus/releases/tag/v3.3.0-beta.5
* Create a new folder
* Unzip the zip file there
* In chrome go to `chrome://extensions/`
* Enable developer mode
* Click `Load unpacked extension` and select the folder you created

### Chrome (direct upgrade; might not always work)
* Download the crx build here: https://github.com/marcelklehr/floccus/releases/tag/v3.3.0-beta.5
* In chrome go to `chrome://extensions/`
* Drop the `.crx` file into the page to install

### Firefox (separate testing installation; cannot upgrade)
* Download the zip build here: https://github.com/marcelklehr/floccus/releases/tag/v3.3.0-beta.5
* Unzip the zip file in a new folder
* In firefox go to `about:debugging`
* Click `Load tempoprary addon` and select the manifest file in the folder you created

Cheers! :space_invader: 
Marcel

**Comment by marcelklehr** [comment]
Beta 2 is out now.

**Comment by tkurbad** [comment]
Hi @marcelklehr,

thanks for the betas. Runs flawlessly so far for me against NC 16.0.0 with latest bookmarks app. Nice work!

I also like to internationalized and optically improved interface.

Best,
Torsten

**Comment by akidburn** [comment]
Hi,
Beta 2 works a lot faster than the normal version, though if i read the logs right there is still something iffy, because about 500 bookmarks out of 3800 are still compared one to one, not in sparse trees. And depending on the browser (firefox or chrome) there are between 5 and 50 updates to bookmarks, although i didnt change anything.

akidburn

**Comment by marcelklehr** [comment]
Thanks for the feedback @tkurbad and @akidburn!
I'll investigate the unnecessary comparisons :)

**Comment by marcelklehr** [comment]
beta 3 is out now :tada: 

@akidburn Could you try again, if this fixes your issue?

**Comment by tkurbad** [comment]
@marcelklehr I'm unable to install it. For the .crx, Chromium gives me "Invalid CRX header", when trying to install the unpacked zip, it complains about a missing Manifest in builds.

Chromium 73.0.3683.86 on Linux, if that matters...

**Comment by marcelklehr** [comment]
Mh. the invalid CRX header is probably to be expected as these are unsigned builds. The zip should work, though...

**Comment by tkurbad** [comment]
@marcelklehr was able to install it now. Problem was that I've been too far down the directory tree. However, when I click "Add Account", nothing happens, even after browser restart.

**Comment by marcelklehr** [comment]
Oh, my bad. Beta 4 should fix that as well.

**Comment by tkurbad** [comment]
@marcelklehr Works for me.

**Comment by akidburn** [comment]
@marcelklehr Works for me as well, though the performance hit in firefox is pretty damning if the speedup option is chosen, freezes most other addons and prevents loading new tabs

but the sparse trees work now

**Comment by marcelklehr** [comment]
> As I understand it, the whole local bookmark tree is hashed in one go, right?

Yes, it's a hash tree and all branches are hashed in parallel. I've serialized this, now, in beta 5
