### ISSUE TITLE
Testing phase for v1.3 (beta 5)

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#27]
Hello there,

anyone who's up for a bit of testing in order to get an earlier glimpse at the new features of the upcoming floccus version can follow the guide below:

### Chrome
* Download the build here: https://github.com/marcelklehr/floccus/releases/tag/v1.3.0-beta.5
* Unzip the zip file
* In chrome go to `chrome://extensions/`
* Enable developer mode
* Click `Load unpacked extension` and select the root folder of the floccus build

### Firefox
* Download the build here: https://github.com/marcelklehr/floccus/releases/tag/v1.3.0-beta.5
* Unzip the zip file
* In firefox go to `about:debugging`
* Click `Load tempoprary addon` and select the manifest file in the root folder of the floccus build

### Upgrading
 * Floccus will not recognize any previously setup bookmarks account, so you'll need to create a new one and click `force Sync` after the account has been validated (Don't copy over your old bookmarks from the old floccus folder, but let it fetch them from the server).

### Debugging
In order to aid in debugging, please provide client-side logs.

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice.
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

Cheers!
Marcel

**Comment by marcelklehr** [comment]
**Update:** beta2 has fixes for issues that came up in beta1. Download it here: https://github.com/marcelklehr/floccus/releases/tag/v1.3.0-beta.2

**Comment by JimmyKater** [comment]
ummm... v1.3.0-b2 doesn't sync with nc 12.0.1 under ff 55.0.1 (32) on win 7 pro sp1 (64). still.

**Comment by marcelklehr** [comment]
@JimmyKater could you provide logs? I added instructions on how to do that above ;)

**Comment by lala-rob** [comment]
Test System:
Win 10 Ent x64, Floccus v1.3.0-beta.2, NC 12.0.2
Chrome 60.0.3112.101 x64     -      Sync is working
Vivaldi 1.11.917.39 x32           -      Sync is not working

I dont know how to get logs from Vivaldi:(

**Comment by danopz** [comment]
Looks like Vivaldi has a [different API](https://github.com/marcelklehr/floccus/issues/18#issuecomment-319226423):

> I got this answer back from Vivaldi support:
>
>>    There are extensions that still doesn't work well with Vivaldi especially those that interacts with bookmarks, UI and history since Vivaldi does not use the same format as Chrome does. I will look into this extension, but it would be helpful if you contact the developer and ask for Vivaldi support. We will do the same.
>
> Seems like Vivaldi is different from the rest of the Chromium-based browsers supporting WebExtensions.

**Comment by AlexeyZonov** [comment]
Nextcloud 10.0.3, Bookmarks 0.10.1, Floccus 1.3.0-beta2, Firefox 54.0.1/win7

Sync bookmarks without tags in both directions. Set tag in FF - empty field in NC, set inside NC, do not sync or change in FF.
Floccus-1.2.0 same behavior.

Will version 1.3 work with Owncloud-10 or only Nextcloud?

**Comment by marcelklehr** [comment]
@AlexeyZonov Thank you for testing! This is expected behavior. WebExtensions don't support tags, at the moment :/

I'm afraid Owncloud will not be supported until they provide an API for manipulating the bookmarks.

**Comment by marcelklehr** [comment]
Until Vivaldi publishes their extension APIs, it's very hard to support it. At least I couldn't find them.

**Comment by D4id4los** [comment]
Greetings,

I tried Flocus 1.3.0-beta2 on Nextcloud 12.0.2, Bookmarks 0.10.1 and Chrome 61.0.316.79 but could not get it to connect to my server.

In chrome's inspect view for `dist/html/options.html` I see the line `Fetching bookmarks Object` where the content of the object is:
> password: "corect_passwd"
> type: "nextcloud"
> url: "https://owncloud.server.url"
> username: "user"
> valid: null
> _proto__: Object

And then the next line is the error message:
> Failed to load resource: the server responded with a status of 401 (Unauthorized)

for which the url displayed on the right is:
> https://owncloud.server.url/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1

In the server-side log I see the following entries:
> Error         PHP                   Undefined index: PHP_AUTH_USER at /var/www/owncloud/lib/private/AppFramework/Middleware/Security/CORSMiddlewar.php#88
> Error         PHP                   Undefined index: PHP_AUTH_PW at /var/www/owncloud/lib/private/AppFramework/Middleware/Security/CORSMiddlewar.php#89
> ...
> Error         admin_audit       $params["uid"] was mising.
> Error         no app in co...    Exception: key uid is expected to be set in $param
> Warning    core                   Login failed: '' (Remote IP: 'My.IP')

Is there any other information I can provide to help pin this down?

**Comment by marcelklehr** [comment]
Hey Daidalos,
thank you for reporting this. At first glance it looks like there might be some config issue with your web server as PHP_AUTH_USER should be set when [doing basic auth](https://github.com/marcelklehr/floccus/blob/master/src/lib/adapters/Nextcloud.js#L76). You could try accessing the url with curl, to make sure, it's not connected to floccus: `curl --basic --user "user:correct_passwd" "https://nextcloud.server.url/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1"`

**Comment by D4id4los** [comment]
@marcelklehr Thank you for your response, it pointed me the right way: Apparently some special characters in passwords will break nextclouds basic http auth, in my case it was a '$' sign.

Now that my password is free of special characters I can report that the floccus beta2 works well on Chromium 59.0.3071.104, Chrome 61.0.3163.70 and Opera 42.0.2393.137.

On Firefox 55.0.3 however it can now connect sucessfully and create the new folder but it does not sync the bookmarks, the folder remains empty. When I click the "force sync" button I can see in the Debug Console that the fetching of bookmarks is started: `Fetching bookmarks Object { ... }       Nextcloud.js:72:6` but nothing happens. No error message, exceptions or the like. 

Do you need any further information?

**Comment by marcelklehr** [comment]
@D4id4los Mhh. Could you go to the network tab in the inspector before hitting "force sync"? There should be a network request to the bookmark endpoint. Try to check what happens to that request, what the response is etc. Note to self: I should have it display those error messages.

**Comment by silence87** [comment]
Note: PHP Authentication header is case-sensitive. 
So "Authentication: basic" wouldn't really work. I got Exceptions in CORSMiddleware.php, because PHP_AUTH_USER and PHP_AUTH_PW isn't set. With "Authentication: Basic" (note the capital B char) Authentication works well. 

Additional Note: if NC installation is in a subdirectory, the normalizeServerURL wouldn't work as expected. For example: correct url is in http://10.10.10.10/nextcloud/, the normalizeServerURL strips the subdir. 

Tested with NC 11.0.5.1 (on debian8 apache2 2.4.10, php5 5.6.30), FF 52.3.0 ESR

**Comment by marcelklehr** [comment]
Thank you for those nice catches @silence87! Fixed in beta 3 :)

**Comment by e-alfred** [comment]
The beta 3 *crx file is actually the one from 1.2.0. Please upload the right one. ;)

**Comment by marcelklehr** [comment]
My bad. Fixed.

**Comment by marcelklehr** [comment]
Beta 4 is out, now. Updated the initial post to reflect this.

**Comment by marcelklehr** [comment]
Hey again,

it seems the latest beta is working quite well. That's great! Thanks for all your testing efforts!
In the meantime I've added one new feature that probably everyone was waiting for: Folder support! I'm not sure yet, how stable it is exactly, but initial tests turned out to work quite well. I still have to do some more testing, and the bookmarks app needs a new endpoint for the feature as I've implemented it to work, but I'm confident we'll see the release of a new version of the bookmarks app (and floccus afterwards) quite soon-ish. :tada:
I will probably not release another beta before that, because it would be useless without the new version of the bookmarks app.

Cheers!

**Comment by JimmyKater** [comment]
hey marcel,
great job so far. 
so what about this guess of mine: why not releasing a new version of floccus just now where everything seems to be working fine?
and then come up with a new version with said new features (i'd so love floccus&bookmarks to support folders!)?
cheers
jimmy

**Comment by marcelklehr** [comment]
@JimmyKater I guess that makes sense, yes. I'll have to untangle some commits, then :)

**Comment by e-alfred** [comment]
It would be great to have a new version even though there is no folder support yet. Which issue/PR for folder support is there in the Bookmarks app repository? Is there any activity on that side at the moment?

**Comment by marcelklehr** [comment]
@e-alfred see my recent comment in #5

**Comment by marcelklehr** [comment]
v1.3.0 is out. Have fun :)
