### ISSUE TITLE
Tags are not synchronized

### ISSUE THREAD

**Issue by MagicFab** [marcelklehr/floccus#280]
### Software versions

- Browser: Firefox ESR (60.6.1esr) on Debian 10
- Nextcloud: 15.0.4
- Nextcloud Bookmarks app: 1.0.2
- Floccus: 3.2.16
- Floccus sync method: NC bookmarks (with Folders)

### Steps to reproduce

1. Add tags to bookmarks on Firefox desktop
1. Sync bookmarks from Firefox desktop to NC
1. Search for bookmark in NC web UI
1. Check bookmark properties, tag is missing 

### Expected outcome

Tag in desktop bookmarks should be preserved when sync to NC happens.

### Actual outcome

Tags are not preserved.

### Debug log

- [ ] Debug log provided

I will provided a smaller test log when time permits.

**Comment by marcelklehr** [comment]
Hey, this is a known bug: #28 In simple terms, Mozilla doesn't let extensions access tags. It's not that simple though. It never is :)

**Comment by SenaidaHdez** [comment]
That is a real pitty. My idea was using it for sync phone-laptop and the app of Nextcloud Bookmarks only is based on tags, not folders. So, even if I now change to folders, I wouldn't be able to use it on my phone... Does it mean then that the WebDav option does not preserve the tag structure either?

**Comment by marcelklehr** [comment]
WebDAV doesn't preserve tags, either, yes.
