### ISSUE TITLE
Firefox v3.3.0 - Trigger Sync from Scratch and Speed up Sync preferences not saving

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#281]
Testing [latest v3.3.0](https://github.com/marcelklehr/floccus/issues/269) in Firefox 66.0.3 (64-bit)

When toggling on/off `Trigger Sync from Scratch` and/or `Speed up Synchronization` in preferences, those settings will not save as selected.  They'll either randomly be on or off when you re-open Floccus.

Also seeing `E018: Couldn't authenticate with the server`

**Comment by marcelklehr** [comment]
Mmmmh, these are weird ones.

`Trigger Sync from Scratch` isn't actually persisted as it clears the cache immediately.

> Also seeing E018: Couldn't authenticate with the server

Perhaps this is once again an issue with entering the password? Could you try pasting the password into the input field? Which sync method do you use? (and if applicable: which server and app version?)

**Comment by sunjam** [comment]
I was using v3.3.0 beta and was just stuck on the syncing status.  I removed the beta app, deleted all my bookmarks in the local browser, and am going to back to standard Firefox release + syncing all bookmarks over from Nextcloud Bookmarks app current release.  Issue resolved once I deleted all my local bookmarks and re-synced.

**Comment by vleeuwenmenno** [comment]
I've been getting this issue lately, any ideas what I can do about it?
It says E018: Couldn't authenticate with the server

**Comment by marcelklehr** [comment]
@vleeuwenmenno You're experiencing the following known issue #520
