### ISSUE TITLE
[Android] Kiwi Browser crashing upon trying to configure login information

### ISSUE THREAD

**Issue by 05nelsonm** [marcelklehr/floccus#285]
### Software versions

- Browser: Kiwi Browser 74.0.3729.136 [Android 8.1.0]
- Nextcloud: [NextcloudPi v1.12.0] [Nextcloud 15.0.5.3]
- Nextcloud Bookmarks app: 1.03
- Floccus: 3.2.16
- Floccus sync method: nextcloud bookmarks (with folders)
  

### Steps to reproduce

1. Install Kiwi Browser from Google Play App Store
2. Install Floccus from Chrome-extension store
3. Click 3 dots (top right)
4. Select "Extensions"
5. Select "Details" for floccus extension
6. Select "Extension options"
7. Shit doesn't work right and can't type anything, and drop downs don't work

**THE FIX:**

1. Install Kiwi Browser from Google Play App Store
2. Install Floccus from Chrome-extension store
4. Click 3 dots (top right)
5. Select floccus
6. Things work properly because it opens the menu in a separate tab and you can enter the information.

**Alternative Option**
1. Install Kiwi Browser from Google Play App Store
2. Install Floccus from Chrome-extension store
3. Click 3 dots (top right)
4. Select "Extensions"
5. Copy the ID value shown for the floccus extension
6. Enter into the URL ->>>> kiwi-extension://IDNUMBERYOUCOPPIED/dist/html/options.html
7. Things work properly because it opens the menu in a separate tab and you can enter the information

### Expected outcome

Be able to enter information from the options menu popup and not in a separate tab

### Actual outcome

Unable to enter login information from the options menu popup

### Debug log

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
mmh. This is likely a problem with kiwi :/
