### ISSUE TITLE
Tab Push

### ISSUE THREAD

**Issue by 05nelsonm** [marcelklehr/floccus#286]
Love this extension. Thank you for releasing me from browser bondage.

Missing FF's send tab to another device, though.

Would it be possible to have an option in the extension to "push your currently opened tab", such that on another device I can manually pull and open it by clicking the Floccus extension and selecting a "pull tab" option?

Kind of like a "temporary bookmark", not a full sync, just the link, then it would delete itself.

That too far of a stretch?

Again, thank you for your work, I love it.

**Comment by marcelklehr** [comment]
I've been thinking about how to implement something like this. It'll be a while until I get to this, though :)

**Comment by 05nelsonm** [comment]
> I've been thinking about how to implement something like this. It'll be a while until I get to this, though :)

Yeah, my current workaround was to have 2 accounts syncing using floccus. 1st is with NC bookmarks to sync my toolbar, and 2nd is using WebDAV to push tabs.

**Comment by marcelklehr** [comment]
It's also possible to sync two accounts with the same server, btw. Have a look at the server path option

**Comment by 05nelsonm** [comment]
> It's also possible to sync two accounts with the same server, btw. Have a look at the server path option

Yep, I love it. I use Vivaldi as my desktop browser across linux/windows machines and turned off the built in bookmark/speed dial sync, made a new Nextcloud user, and use that user to sync the speed dial bookmarks across all my Vivaldi clients.

This app really has released me from browser bondage. Also makes activity more private, so thank you.
