### ISSUE TITLE
Am seeing bookmarks duplicated regularly in mass quantities ...

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#287]
This has been happening for months I've lost track of when it started, because it's rare enough that I just fix it and move on. But it's still happening so wanted to log an issue to see if it can be diagnosed.

### Software versions

- Browser: Firefox and Google Chrome
- Nextcloud: Nextcloud version | 15.0.6.1,  NextCloudPi version | v1.12.0
- Nextcloud Bookmarks app:  1.0.3
- Floccus: 3.2.16
- Floccus sync method: Nextcloud Bookmarks with Folders

### Steps to reproduce

Nothing. It just happens ;-). 

### Expected outcome

That I don't get bookmarks duplicated en masse.

### Actual outcome

Selective bookmarks are duplicate en mass at time

### Debug log

- [x] Debug log provided (floccus-3.2.16-2019-05-11.log)

A screen image may be useful:

![image](https://user-images.githubusercontent.com/7296506/57568510-b45e3780-742b-11e9-97a2-76fcbdacf209.png)

obfuscated irrelevant bookmarks:

![image](https://user-images.githubusercontent.com/7296506/57568536-099a4900-742c-11e9-8457-81acb110a604.png)

To be clear, I see this on difference folders, on different sites, but it's always one site in a folder or two that just multiply with these # string versions. I am not bookmarking them, they are just appearing. I regularly delete them. No idea where they come from.

**Comment by marcelklehr** [comment]
I believe I've found the culprit. The next release of the bookmarks app should fix this.

**Comment by marcelklehr** [comment]
Can you confirm if this fixed things for you?

**Comment by bernd-wechner** [comment]
In time perhaps. The problem of course is that it was intermittent. I can't see it on the browser I'm now (FF on Windows 10) which I cleaned up when I filed this. I just went to Chrome on same box and it does, butt hat's legacy, that I haven't cleaned up, so I've cleaned that up now. Then the waiting game begins. Basically if a month or two pass and I've not seen the problem recur I'd be happy to drop back in and say, yep, fixed! This sadly was not a problem I had good steps to reproduce, just an intermittent observation affecting fairly random sites out of the blue, but a subset of the total.

If from your code check you think you have steps to reproduce it I can try.  I mean it might be that visiting a given bookmark or simply adding a given type of bookmark is what triggered it?

**Comment by marcelklehr** [comment]
I believe this would occur only with URLs that contain a fragment portion (`#fragment`) and is possibly triggered by new updates to floccus, which reset the cache. So, to trigger something like this, you might want to reset the cache (trigger sync from scratch) and hit sync.

**Comment by marcelklehr** [comment]
Any news?

**Comment by bernd-wechner** [comment]
Sadly no, have been far too busy to pay much heed to this. But that said, your prompt is welcome (arrives by email as I have a watch on the thread) and what I can do is confirm:

1. I've not seen the problem recur.
2. Scanning my bookmarks quickly I find one (https://calendar.google.com/calendar/render#main_7) that seems to fit your causality description and it's not been duplicated.

Perhaps that suffices as a confirmation?

**Comment by marcelklehr** [comment]
Good enough for me :) If it ever pops up again, just shoot an issue ;)
