### ISSUE TITLE
Extension does not work on Firefox 57

### ISSUE THREAD

**Issue by gradinaruvasile** [marcelklehr/floccus#29]
Hi,
i installed Floccus on FF 57 but i could not get it to work. I clicked on the icon, filled the authentication and server info but when i clicked on the save button nothing happened, the pop up UI did not change. Tried both vrtsion 1.2 and 1.3 beta 2.

**Comment by marcelklehr** [comment]
Hi :)

In the 1.3 beta there should be a status indicator telling you either `checking` / `connected` / `error` (or something similar). Also, you can trigger a sync manually via the aptly named `force sync` button. This should trigger a status message that reads `syncing`.

If none of this seems to work, you can have a look at the log, by opening `about:debugging` and opening the debug console for floccus (there'll be some messages not associated with floccus, but hopefully you'll see some errors that have your URL in them. Alternatively you can also go to the network tab and then trigger a sync again to see what happens to the network request.)

**Comment by marcelklehr** [comment]
Also, I just release beta3, which fixes some additional bugs that could have been causing problems for you.

**Comment by gradinaruvasile** [comment]
Well. This one works, i mean it actually shows some activity in the UI.

BTW i discovered that there were about 5-6 "Owncloud" folders, half synced. So the previous one did work after all in the background just i had no indication in the UI.
