### ISSUE TITLE
[Feature Request] Cancel Sync

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#290]
I'm testing current stable app as well as 3.3.0 beta in both firefox and chrome.  I'm wondering if there is a way to force quit or kill an [in progress sync](https://github.com/marcelklehr/floccus/issues/190).  I've tried to unclick enable, but it doesn't seem to work.  If this feature does not already exist, I'd like to request.  Thanks either way!

**Comment by marcelklehr** [comment]
Done :)
