### ISSUE TITLE
floccus + kiwi + subfolders

### ISSUE THREAD

**Issue by humarf** [marcelklehr/floccus#292]
I read that kiwi as first mobile browser will support the floccus plugin. That's why I tried kiwi + floccus on my android tablet. Installation and set up went fine. Unfortunately all bookmarks are synced to the chosen sync folder in kiwi without recognizing any subfolders. It's a flat list now. Is this as expected? If not how to get subfolder replicated, please?

### Software versions

- Browser: kiwi browser
- Nextcloud: 15.0.7
- Nextcloud Bookmarks app: 1.0.3
- Floccus: 3.3.0.1
- Floccus sync method: nextcloud Bookmarks v0.14+ with folders

**Comment by marcelklehr** [comment]
Hey,
This is not as expected. Are you aware that you are using a beta version of floccus? Have you tried the latest stable release?

**Comment by humarf** [comment]
Hello,

I am aware of that. First I tried stable release from chrome webshop. There was the same problem. Then I thought since mobile sync is brand new it only works with latest beta version. But I got the same result.

Is there any debug information that I can provide to find out what's wrong?

**Comment by marcelklehr** [comment]
You can provide the debug logs. There's a link in the bottom right corner of the floccus panel. Out of a hunch: Which sync method do you use on your desktop?

**Comment by humarf** [comment]
I am using the "with folders" sync methond.

I had a look at the log file of floccus. I think it's about undefined parent id but on server side. Here is one example:

`COMPARE { localItem:   - #143[Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr](https://www.amazon.de) parentId: 140,
  cacheItem:   - #143[Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr](https://www.amazon.de) parentId: 140,
  serverItem:   - #6;-1[Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr](https://www.amazon.de) parentId: -1 }
Bookmark unchanged`

Comparing this to the log from desktop version parent ID is there:

`COMPARE { localItem:   - #124[Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr](https://www.amazon.de) parentId: 13,
  cacheItem:   - #124[Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr](https://www.amazon.de) parentId: 13,
  serverItem:   - #6;/Shopping[Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr](https://www.amazon.de) parentId: /Shopping }
Bookmark unchanged`

**Comment by marcelklehr** [comment]
The log file from your desktop would indicate that you are not using the folder sync on your desktop, but the legacy sync method, which creates folders as tags on the server. I recommend changing either client to match the other and you'll be fine. ;)

**Comment by marcelklehr** [comment]
(Also see: https://github.com/marcelklehr/floccus#switching-from-tag-based-to-folder-based-syncing)

**Comment by humarf** [comment]
That was it. I had to delete the desktop account and recreate it. 

Thanks a lot.
