### ISSUE TITLE
local folder not correctly shown in overview

### ISSUE THREAD

**Issue by tessus** [marcelklehr/floccus#293]
### Software versions

- Browser: Firefox 66.0.5
- Nextcloud: 15.0.7
- Nextcloud Bookmarks app: 1.0.3
- Floccus: 3.2.16
- Floccus sync method: nextcloud-folders
  

### Steps to reproduce

I have a local folder called `A&B / C`.

1.  Pick above local folder in the options for a sync account: `/Bookmarks Toolbar/A&B \/ C`

### Expected outcome

If you click on the floccus icon in Firefox (`open floccus options`), you should see the folder `A&B / C`.

### Actual outcome

You only see `C`. Where the red block is, only the text `C` is shown.

<img width="458" alt="Screen Shot 2019-05-14 at 22 45 49" src="https://user-images.githubusercontent.com/223439/57745351-d6112600-769a-11e9-844f-d88796b38639.png">

### Context

This is not a huge issue, but I thought I should create a bug report nonetheless. I assume there is some sort of parsing going wrong and/or there is an issue with `&` or `/` in the name.

### Debug log

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Ah, yes, this is a bug.

**Comment by tessus** [comment]
Don't worry, this is not critical, I just wanted to let you know. I'm sure you have more important things to tackle first...

**Comment by tessus** [comment]
Oh, just saw that you have fixed this already. Thanks.
