### ISSUE TITLE
strange bookmarks duplicates

### ISSUE THREAD

**Issue by Reveanime** [marcelklehr/floccus#294]
### Software versions

- Browser: Chrome 74.0.3729.157
- WebDav: [Nutstore](https://www.jianguoyun.com)
- Nextcloud: 
- Nextcloud Bookmarks app: 
- Floccus:  3.3.0.1
- Floccus sync method: XBEL/webdav
  

### Steps to reproduce

1. When I search  bookmarks on Bookmark Manager, there are duplicate bookmarks.

![image](https://user-images.githubusercontent.com/20869550/57827436-ea0f7180-77d9-11e9-8e3e-557d10e8d83d.png)

2. When I show them in folder, I find them are the same bookmark. No duplicate bookmarks exist in the folder.

![image](https://user-images.githubusercontent.com/20869550/57827610-85084b80-77da-11e9-8c81-04d3ec868d01.png)

3. When I use the extension ' [Bookmarks clean up](https://chrome.google.com/webstore/detail/bookmarks-clean-up/oncbjlgldmiagjophlhobkogeladjijl) ' to find duplicated bookmarks, the result is that all of my bookmarks are duplicate.

![image](https://user-images.githubusercontent.com/20869550/57828024-7884f280-77dc-11e9-9a92-d2c4eadc504b.png)

### Actual outcome

- **So, are my bookmarks duplicate?** How can I solve this problem?

### Debug log

- [floccus-3.3.0-beta.1-2019-05-16 ] Debug log provided

**Comment by marcelklehr** [comment]
Are you aware that you are using a beta version of the upcoming release v3.3.0-beta.1?

**Comment by marcelklehr** [comment]
In any case, this is very strange.

**Comment by Reveanime** [comment]
Finally, I found my bookmarks folders were duplicate. The issue was solved after I deleted the duplicate folder。

**Comment by marcelklehr** [comment]
Phew, I'm glad this is solved :)
