### ISSUE TITLE
[Feature Request] Login Flow

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#297]
I'd like to request [Single Sign On](https://portal.nextcloud.com/category/authentication/single-sign-on-x28%3bsso-x29%3b/5/) support for Floccus, so Nextcloud users can sign on using their basic account credentials rather than needing to generate a one time password.  On mobile devices SSO will use a pre-existing Nextcloud client app to verify credentials.  It would be a slick enhancement.  Thanks for reading, and great job on the application!

SSO

**Comment by marcelklehr** [comment]
As far as I know, SSO shouldn't stop you from logging in with your normal credentials. 2-factor authentication will do that. Is that what you mean.

Using the main nextcloud app on mobile to login from floccus probably won't work, as the extension is sandboxed and cannot access android APIs.

I can look into whether it's possible to implement the login flow with a web extension, but I'm not too confident. Do you know of other nextcloud-related browser extensions that allow this?

**Comment by sunjam** [comment]
The Nextcloud Talk app for Android allows you to login with your
credentials + supports 2 factor.
https://github.com/nextcloud/talk-android

**Comment by marcelklehr** [comment]
> The Nextcloud Talk app for Android allows you to login with your credentials + supports 2 factor.

Ah, but that's a native android app. I'm talking about browser extensions like floccus.

**Comment by sunjam** [comment]
Good point.  Question posted to the forums [here](https://help.nextcloud.com/t/is-it-possible-log-into-nextcloud-browser-extensions-using-regular-credentials-and-2-factor-instead-of-one-time-passwords/55001).

**Comment by marcelklehr** [comment]
the [v2 flow](https://docs.nextcloud.com/server/18/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2) should be workable with floccus.

**Comment by sunjam** [comment]
This is huge!  Thank you!

**Comment by marcelklehr** [comment]
You can test this feature now in https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.4 :)
