### ISSUE TITLE
Icon keeps blinking

### ISSUE THREAD

**Issue by sanderboom** [marcelklehr/floccus#303]
Thanks for the great software!

### Software versions
- Browser: FF 66.0.5 (64-bit)
- Nextcloud: 16.0.0
- Nextcloud Bookmarks app: 1.0.5
- Floccus: 3.2.16
- Floccus sync method: `nextcloud-folders`
### Steps to reproduce

1.  Set up floccus sync

### Expected outcome

Everything works - no flashing icon.
### Actual outcome

Everything works, but icon flashes.
Video: 

![Peek 2019-05-27 09-32](https://user-images.githubusercontent.com/5956570/58403464-05dd0800-8063-11e9-81ee-6c430acfcb79.gif)

### Debug log
- [ ] Debug log provided

Edit: add video.

**Comment by marcelklehr** [comment]
Mh. Can you provide debug logs? (Preferably via mail? -- see http://github.com/marcelklehr)

**Comment by marcelklehr** [comment]
Closing due to lack of feedback.

**Comment by sanderboom** [comment]
> Closing due to lack of feedback.

Well, I did send you debug logs like you requested. Check for mail on 29 May 2019, 10:11.

**Comment by marcelklehr** [comment]
My bad, I did find that email, just now, I'm sorry. The logs don't show anything suspicious, *but* I do remember fixing something some time in the weeks running up to the v3.3.0 release that was probably the cause of this flickering. Can you confirm that the problem is gone with v3.3.0?

**Comment by sanderboom** [comment]
> My bad, I did find that email, just now, I'm sorry.  

No worries.

I reinstalled (v3.3.0.6 now) and haven't seen any blinking, I consider this fixed. Thanks.
