### ISSUE TITLE
FR: Custom sync timing

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#304]
Hi
It would be nice if one can change the frequency of the syncs. I feel like this is syncing way too many times and using too much cpu during these syncs. I might need to run it once in every hour or so for instance instead of every couple mins like ti does now.

**Comment by marcelklehr** [comment]
Good news! This has been implemented in the code already and will be released soon ;)

**Comment by gerroon** [comment]
Awesome thanks
