### ISSUE TITLE
Firefox, error reading manifest file

### ISSUE THREAD

**Issue by bhlevca** [marcelklehr/floccus#308]
### Software versions

- Browser: Firefox
- Nextcloud: does not matter
- Nextcloud Bookmarks app: 
- Floccus: 3.3.0.5
- Floccus sync method: does not matter
  

### Steps to reproduce

1.  Load the temporary manifest file for 3.3.0.5
2.  Get the following error:

Reading manifest: Error processing browser_action.chrome_style: An unexpected property was found in the WebExtension manifest.

### Expected outcome

no error
...

### Actual outcome

...

### Debug log

- [ []] Debug log provided

**Comment by marcelklehr** [comment]
Thank you for your feedback. This is a known complication that stems from the necessity to support both Chromium and Firefox. However, this doesn't seem affect the extension's functionality, as far as I know.
