### ISSUE TITLE
Missing spacing in beta version

### ISSUE THREAD

**Issue by bykidi** [marcelklehr/floccus#309]
Spacing is missing in beta5, russian locale
![изображение](https://user-images.githubusercontent.com/1337953/59103343-45df9d00-8937-11e9-8fa2-b68c48bff8f0.png)

**Comment by marcelklehr** [comment]
This is fixed in transifex, I hope it will soon be pushed to this repo.

**Comment by marcelklehr** [comment]
Fixed.
