### ISSUE TITLE
Cannot install from CRX

### ISSUE THREAD

**Issue by ctr49** [marcelklehr/floccus#313]
### Software versions

- Browser: Chromium 74.0.3729.157 (also tried with Chrome 74.0.3729.169) on macOS
- Floccus: 3.3.0 (also tested with 3.3.0-beta5)

  

### Steps to reproduce

1.  Download CRX from release page
2. Drag and drop CRX into extensions view

### Expected outcome

Extension being installed.

### Actual outcome

Error message: "CRX_HEADER_INVALID"

### Debug log

This is pre-install so I don't have a debug log.

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
This is to be expected with the standard chromium builds as they require a valid signature by the Chrome webstore. You will need to install it from the webstore directly. The download packages in this repo are more a nice-to-have for people with special needs, in most cases, the downloads from AMO or the chrome webstore are to be preferred.
