### ISSUE TITLE
High cpu?

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#314]
Hi

I feel like this add-on uses high cpu during syncronization against Nextcloud. 

When the sync starts it Firefox 67 starts using around %25 of my cpu on Win 10

It would be nice if the cpu usage goes down, given that most of the time the whole bookmarks database is almost the same. I add couple bookmakrs every day, so this add-on using such cpu regularly seems to be very wasteful.

thanks

**Comment by marcelklehr** [comment]
Hey,
performance has been an issue I've been working on off and on for some time.
Relevant factors are the browser (firefox seems to be less performant) as well as the number of bookmarks.

**Comment by marcelklehr** [comment]
Closing in favor of #190

**Comment by gerroon** [comment]
Hi

Is it possible that this bug has returned? It tops the cpu useage among others frequently. I am using 4.1.0 on Linux Firefox 74

thanks

**Comment by marcelklehr** [comment]
mmh, is that during sync?

**Comment by gerroon** [comment]
Hi

No when it is idle. I set the sync period to 300

**Comment by marcelklehr** [comment]
The fix for #448 has not been altered since then: https://github.com/marcelklehr/floccus/blame/develop/src/lib/Controller.js#L114

I suspect the increased usage may stem from the fact that we [rolled back a storage performance improvement in v4.1](https://github.com/marcelklehr/floccus/issues/459)

**Comment by gerroon** [comment]
That makes sense. The cpu usage is lower than when I originally reported, however it seems to be generally higher among the other processes. It bounces back between low to medium.  It would be nice if it is using resources only when there is a sync.

**Comment by marcelklehr** [comment]
I think I have found another avenue to improve this. I've reopened #448 in the meantime :)
