### ISSUE TITLE
Not logging in

### ISSUE THREAD

**Issue by popcorn9499** [marcelklehr/floccus#32]
Tried on both chrome and firefox and it didnt seem to work. I installed on firefox from the webstore and tried on chrome via the addon in github i tried 1.3.0-beta.5 on chrome with the same result of it just didnt even let me login to my nextcloud account. Im not sure what you need from my end but id gladly give all the info i can

**Comment by marcelklehr** [comment]
Hey there!
Can you tell me what the status message below the account info input boxes says, after you have completed entering your account info?

**Comment by popcorn9499** [comment]
My nextcloud version is v12.0
bookmarks app v0.10.1
I am stuck at login. https://i.imgur.com/sr4Pqla.png It doesnt seem to want to let me into the nextcloud server or something not too sure if this helps but nextclouds log has a error in it as well.  https://i.imgur.com/kHDYvo3.png Not sure if that helps at all hopefully I can be of more use

**Comment by marcelklehr** [comment]
Aha. Thank you! The error in the nextcloud log looks a bit odd. Can you check your reverse proxy configuration? (There's a superfluous slash in the error message...)

**Comment by popcorn9499** [comment]
Thank you. sorry I didn't notice that. I think im slowly learning apache2. It connected now. Should i be seeing the bookmarks in my nextcloud bookmarks app? If so in how long? In theory i should be seeing my upload being used to send the bookmarks right?

**Comment by marcelklehr** [comment]
Only the bookmarks in thee Nextcloud folder will be synced with nextcloud. You should find it somewhere inside the "Other Bookmarks" folder.

**Comment by popcorn9499** [comment]
Ok so two things I figured i should say. One chrome is removing the extention other than that it works fairly well. The other is couldnt you use like a beginning or ending prefix that would mark the bookmark as a in said folder. Not the best method but i figured it might fix the issue temporarily

**Comment by marcelklehr** [comment]
"One chrome is removing the extention" -- I'm sorry, I don't understand.

Regarding folders: We're working on long-term solution at the moment, but as always in the open source world don't expect things to move too fast ;)

**Comment by popcorn9499** [comment]
I ment by chrome removing the extension. Because its not on the store they disable the extension and make it unable to be enabled again. But ya I am happy to see this coming along. I might try to figure out javascript and understand how this works so i can modify that for my own use case. Ill see tho. That would just be a temporary fix for that but like i said I should be able to figure it out enough to do that. Thanks for your support.

**Comment by marcelklehr** [comment]
You're welcome :)

-- Mmmh. I can install and disable and enable and reinstall floccus just fine in chrome :/

**Comment by popcorn9499** [comment]
Weird. Might just need to reinstall my install of chrome. however I found the issue only happened after reloading chrome.
