### ISSUE TITLE
URL syncing issues (encoding, GET parameters)

### ISSUE THREAD

**Issue by syscrh** [marcelklehr/floccus#328]
### Software versions

- Browser: Firefox 60.8.0 ESR, Vivaldi 2.6.1566.44
- Nextcloud: 16.0.3
- Nextcloud Bookmarks app: -
- Floccus: 3.3.2
- Floccus sync method: WebDAV
  

### Steps to reproduce

1. Create a bookmark
2. Sync it to another browser
3. Compare the URLs between the source browser and the destination browser

### Expected outcome

Both URL strings are identical

### Actual outcome

The URLs are different:
1. GET-parameters have a different order (which is quite annoying, since I use these URLs as templates, and some sites even break because of the reordering), e. g.
original (Firefox): https://www.google.com/search?tbm=isch&tbs=isz:l&num=100&hl=en&gl=au&q=Floccus
after sync (to Vivaldi): https://www.google.com/search?gl=au&hl=en&num=100&q=Floccus&tbm=isch&tbs=isz%3Al

2. Some URLs are no longer usable, because of broken characters:
original (Firefox): https://google.com/maps/@0,0.0,0m/?force=canvas
after sync (to Vivaldi): https://google.com/maps/%400%2C0.0%2C0m/?force=canvas

(also happens with German umlauts in URLs on sites like https://geizhals.eu)

It makes no difference which browsers are getting synced or in which direction the syncing happens. E. g. two Firefox instances experience the same issues.
It also doesn't help to switch from WebDAV to the Nextcloud Bookmarks app.

**Comment by marcelklehr** [comment]
Thank you for the feedback. URL normalization has been an issue for a while, since I chose to go with a handwritten normalizer. I've now decided to switch to plain WHATWG URL validation and normalization, which should prevent such issues in the future.

**Comment by andrius-finnplay** [comment]
FF and Chrome has old versions.
Version
    3.3.2
Size
    2.35 MB
Last updated
    a month ago (Jun 16, 2019)

**Comment by marcelklehr** [comment]
I know, I know. I don't get as much done as I would like to, these days :)

**Comment by syscrh** [comment]
Both issues seem to be fixed with floccus 3.4.0.2. Thank you very much for fixing it so quickly!
