### ISSUE TITLE
Hope to support Chinese

### ISSUE THREAD

**Issue by qq1642787610** [marcelklehr/floccus#329]
Hope to support Chinese
There may be more users in China.

**Comment by marcelklehr** [comment]
Unfortunately I don't speak Mandarin, but anyone who does is welcome to [help translate](https://github.com/marcelklehr/floccus/issues/266) ;)

**Comment by qq1642787610** [comment]
All right

**Comment by GoogleBeEvil** [comment]
translating to zh-cn on tansifex .老铁，我早就在transifex上面翻译着呢 ，有能力一起来

**Comment by qq1642787610** [comment]
The rest of the Chinese translation is over.

**Comment by marcelklehr** [comment]
Thank you! :)
