### ISSUE TITLE
memory leak on firefox while using webdav

### ISSUE THREAD

**Issue by GoogleBeEvil** [marcelklehr/floccus#334]
Step to reproduce:
1.set usename and password  for floccus
2.sync all local bookmarks to webdav  with check "Speed up synchronization"
these 2 steps works  well  and no memory leak.

3.delete all local bookmarks and then try sync back bookmarks from webdav (checked Trigger sync from scratch,also check Speed up synchronization) .memory usage will grow till fiiefox gets stucked 16GBram,and firefox use 12GB. 

btw:4000 bookmarks  in my local folder,maybe the number of bookmarks lead this , one more thing i use debian testing x64,firefox 68.0.1

**Comment by GoogleBeEvil** [comment]
and for  firefox get stucked,the bookmarks fails to be sync back

**Comment by marcelklehr** [comment]
Does this also happen when disabling speedup?

**Comment by GoogleBeEvil** [comment]
yes ,so this  isnt speedup matter.just connect to webdav even you dont click sync ,just export and delete all your bookmarks,then restore bookmark by import , ,ram grows

**Comment by marcelklehr** [comment]
> just export and delete all your bookmarks,then restore bookmark by import , ,ram grows

In this case I dare say the problem is not with floccus, as floccus doesn't interfere with normal browser imports.

**Comment by marcelklehr** [comment]
If the browser is not the problem, this migt be fixes in the [latest beta](https://github.com/marcelklehr/floccus/issues/338)

**Comment by GoogleBeEvil** [comment]
i dont know  which side lead this ,but once floccus  installed ,it appears. sync function is ok,but with webdav login in , import bookmark.json will memory leak.need  to do  more test.is there any log file that floccus created in firefox profile folder?

**Comment by marcelklehr** [comment]
I recommend creating a new profile, installing floccus (preferably the beta version linked above, so that you have the latest code). Then you can follow the steps for debugging outlined [here](https://github.com/marcelklehr/floccus/issues/338)

**Comment by GoogleBeEvil** [comment]
have tested  the  beta version with newly created profile,same result.
log file,seems nothing wrong
http://paste.debian.net/1094337/

**Comment by marcelklehr** [comment]
This sync run caused a memory leak?! That's odd.

**Comment by GoogleBeEvil** [comment]
actully， i dont think sync cause memory leak ,but the "import  bookmark.json from local file" function conflict with  " webdav matters ".ionly sync bookmark would not cause memoryleak,and if i delete my webdav account from floccus,then  import boookmark.json,it wont memory  leak.
Maybe the webdav service  provider or  ISP，whatever u call it，conflict with floccus，though it is hardly possible。
btw：i  use  jianguoyun.com as webdav ftp. I should try another webdav provider ,maybe.

**Comment by marcelklehr** [comment]
Thanks for the details! I think I know what the problem is.

**Comment by marcelklehr** [comment]
Could you try [the new beta](https://github.com/marcelklehr/floccus/issues/338) and report back?

**Comment by GoogleBeEvil** [comment]
seems  fixed the problem ，but still have some issue,it get stucked and no response  while testing ,though only just one time ,maybe it's the network problem.need further test

**Comment by marcelklehr** [comment]
Any news?

**Comment by GoogleBeEvil** [comment]
just close this .  it do have some other  issues,but  no related with this memory leak issue.actually ,i forget what the "other  issues" is...maybe is the "merge local and webdav bookmarks  and sync back",after i read the wiki and make sure how to reproduce it ,i will open new issues

**Comment by GoogleBeEvil** [comment]
BTW, the memory leak seems solved
