### ISSUE TITLE
Can't access bookmarks when password is set without password

### ISSUE THREAD

**Issue by elfacht** [marcelklehr/floccus#335]
### Software versions

- Browser: Firefox
- Floccus: 3.3.2

### Steps to reproduce

1.  Check checkbox to set floccus password
2. Keep passowrd fields empty
3. Try to login without password

### Expected outcome

Some sort of option to access my bookmarks when accidentially no password is set.

### Actual outcome

Can't access my bookmarks because I accidentially did not choose a password.

### Debug log

Can't access the log because this occurs:

![Screenshot 2019-07-23 um 13 41 46](https://user-images.githubusercontent.com/529443/61709472-a3954080-ad4f-11e9-8b7e-5efec17ec068.jpg)

**Comment by marcelklehr** [comment]
Did you try to submit the form using enter or using the button? You can right click on the panel and select 'inspect' to open the console for the unlock screen. Any potential error should be logged there.

**Comment by elfacht** [comment]
@marcelklehr I did try both. Unfortunately I already re-installed the plugin, so I'm not able to check the console.

**Comment by marcelklehr** [comment]
Alrighty. Trying to reproduce this, I was able to access floccus using the submit button, so I'm closing this for now. The fix for the Enter key will be in the next release.
