### ISSUE TITLE
Problems found using v3.4.0-beta.2

### ISSUE THREAD

**Issue by qq1642787610** [marcelklehr/floccus#339]
Problems found using v3.4.0-beta.2

![image](https://user-images.githubusercontent.com/34671663/62263628-8ea36600-b44f-11e9-8e25-3a89b1879177.png)
1.Translation is incomplete.

![image](https://user-images.githubusercontent.com/34671663/62263647-9ebb4580-b44f-11e9-8c48-e10fee2a8438.png)
2.After the Sogou browser installs the plugin, cannot select the sync folder.

**Comment by marcelklehr** [comment]
Re 1: yes, the translations for this feature are still pending, but I didn't want to wait with testing -- the final release will hopefully have all translations :)

Re 2: Did this work in v3.3? i.e. is this a regression?

**Comment by qq1642787610** [comment]
Other versions seem to be also, should be browser incompatible

**Comment by marcelklehr** [comment]
You could still try to investigate what is actually happening, so that this may be fixed: A right click on the panel and a click on 'Inspect' should hopefully reveal the console with an error message

**Comment by bzxgcs** [comment]
I use floccus 4.13.1. Though it can read the folder tree, It still can't find the root path of bookmark in sogou browser.

**Comment by marcelklehr** [comment]
@bzxgcs Can you please open a new issue, filling out the complete issue template? That would be most helpful :)
