### ISSUE TITLE
Sync All Accounts button

### ISSUE THREAD

**Issue by 05nelsonm** [marcelklehr/floccus#340]
Would it be possible to implement a "Sync All Accounts" button at the top of the extension drop down?

**Comment by marcelklehr** [comment]
How many accounts do you have? :D

**Comment by marcelklehr** [comment]
Or more specifically, why do you think you need this? All accounts should sync automatically at regular intervals.

**Comment by 05nelsonm** [comment]
Hey Marcel, I have 4 accounts, but I think the time could be better spent on other things. Will close the request, as I don't think the value add will be worth it.
