### ISSUE TITLE
E019

### ISSUE THREAD

**Issue by Klaus15** [marcelklehr/floccus#341]
### Software versions

- Browser: Chrome 75.0.3770.142
- Nextcloud: 16.0.3
- Nextcloud Bookmarks app: 1.1.1
- Floccus: 3.3.2.
- Floccus sync method: nextcloud Bookmarks v0.14+
  

### Steps to reproduce

1.  Created connection to nextcloud, configured sync
2. Started syncing
3. Syncing with small folder no problem
4. Syncing with bigger folder takes pretty long
5. eventually floccus states the error "Syncing failed with E019: HTTP Status 500. Anfrage vom Typ GET  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log"
### Expected outcome

Looks like it does not like certain string combinations of my booksmarks

### Actual outcome

...

### Debug log

- [x] Debug log provided

I've already reinstalled bookmarks app in nextcloud, truncated its tables. I also renamed the relevant tables in mysql to force their recreation which unfortunately did not happen after reinstalling the bookmarks app. So I restored them to their original name.

gmp, intl, mbstring are already installed on my system

**Comment by marcelklehr** [comment]
Thanks for your feedback! Since this is a server-side error, could you check the nextcloud log for errors and post the associated one here?

**Comment by Klaus15** [comment]
Hi Marcel, 
thanks for having a look into this!
This seems to be the offending line in nextcloud.log: 
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_bookmarks` (`url`, `title`, `user_id`, `public`, `added`, `lastmodified`, `description`) VALUES(?, ?, ?, ?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), ?)' with params ["https:\/\/www.amazon.de\/Victure-Unterwasserkamera-170%C2%B0Fischaugen-Linse-Ersatzbatterien-Halterungs-Kit\/product-reviews\/B07L311D7M\/ref%3Dcm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews", "Amazon.de:Kundenrezensionen: Victure Action Cam 4K 20MP WiFi Touch Screen Ultra Full HD 30 Meters Unterwasserkamera Einstellbare 170\u00b0Fischaugen-Linse EIS Sports Kamera 2\u00d71350mAh Ersatzbatterien and Halterungs-Kit", "kluus", 0, ""]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1
	0.	/var/www/html/ocl/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 184: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exceptio ... 1", Doctrine\DBA ... ]}) 

Maybe I'm still using old table settings in nextcloud? Is there a way to "reinitialize" the tables for the bookmarks app?

Thanks, Klaus

**Comment by marcelklehr** [comment]
You can drop all bookmarks_* tables *and* remove the relevant migration entry from oc_migrations in order to recreate the tables from scratch.

**Comment by Klaus15** [comment]
Hi Marcel,
that did the trick! After removing  the tables, cleaning relevant part of oc_migrations and reinstalling the bookmarks app via nextcloud web-interface everything is working as before. Very much appreciated and thanks for the quick help!
Cheers, Klaus

**Comment by marcelklehr** [comment]
Awesome, I'm glad it works :)
