### ISSUE TITLE
Readme.md has misleading remote.php/webdav URL resulting in E019: HTTP status 404. Failed GET request

### ISSUE THREAD

**Issue by stefan123t** [marcelklehr/floccus#343]
### Software versions

- Browser: FF 68.0.1
- Nextcloud: 16.0.3
- Nextcloud Bookmarks app: bookmarks 1.1.1
- Floccus: latest
- Floccus sync method: ?

### Steps to reproduce

1. installed bookmarks 
2. installed floccus

Looking at the picture of the floccus Readme.md it is suggested to add remote.php/webdav/ to my nextcloud URL. Apparently this is not necessary anymore, once I used https://myserver.dns/nextcloud/ for adding the Sync to floccus it worked flawlessly.

### Expected outcome

It took me quite some time to find the correct string to enter. If the picture would be up to date the currently required setup is easy and a real no-brainer.
Please update the Readme.md for this otherwise fine piece of software.
Thank you very much!

### Actual outcome

E019: HTTP status 404. Failed GET request. Check your server configuration and log.

**Comment by marcelklehr** [comment]
I agree that the picture might be misleading, but for a different reason: It depicts a different sync method: The one depicted in the screenshot uses the webdav endpoint and thus needs the webdav URL, whereas most people will probably want to sync with the bookmarks app, which requires a different sync method, the options for which look different.
