### ISSUE TITLE
Sync (Import) in Firefox aborts when Separator is encountered

### ISSUE THREAD

**Issue by hlagh** [marcelklehr/floccus#344]
### Software versions

- Browser: Firefox 68.0.1
- Floccus: 3.3.2
- Floccus sync method: webdav (LoFloccus)
  

### Steps to reproduce

In Firefox:

1.  Create a bookmark folder containing a separator somewhere between other bookmarks
2.  Sync this folder to LoFloccus
3.  Import/Restore the sync to **\*newly created\***

Note: My intention is to sync to a browser on a different machine. This is simply the quickest way to reproduce the error.

### Expected outcome

I should have a duplicate of the synced folder under "Nextcloud (floccus@127.0.0.1)"

### Actual outcome

Sync aborts with error:
- Invalid bookmark: {"title":"","type":1,"url":"data:","parentGuid":"7HCkt79W9RiF"}

Note: Import works when I remove the following line from the .xbel file:
 >         <bookmark href="data:" id="1xx"><title/></bookmark>)

### Debug log

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Separators have not been explicitly supported thus far, but I think this is now possible.

**Comment by marcelklehr** [comment]
Closing in favor of #186
