### ISSUE TITLE
Syncing localhost bookmark with Nextcloud fails. 

### ISSUE THREAD

**Issue by plutocrat** [marcelklehr/floccus#346]
### Steps to reproduce
 -   Add a bookmark containing http://127.0.0.1/ -- In my case I was using Syncthing on http://127.0.0.1:8384/
  -  Hit Sync.
   - Fail. "Syncing failed with E019: HTTP status 500. Failed GET request. Check your server configuration and log."

-  Delete bookmark, and sync succeeds.

### Server configuration
Latest 16.x version of nextcloud. Latest version of Bookmarks, Floccus. Opera browser, latest version.

**Comment by plutocrat** [comment]
Found another. An IP on my local network -- the router admin page. eg. 
http://10.46.56.78/ 
Sync stops. Remove bookmark. Resync. All OK. 
Apache server throws a 500 but nothing in nextcloud log or apache error log.

**Comment by marcelklehr** [comment]
To be honest, it is quite unlikely that there is no error being logged if you get a 500. just to be sure: the nextcloud log is available at `.../nextcloud/data/nextcloud.log`. I think it is quite likely that you are missing a php extension. See the list of requirements here: https://github.com/nextcloud/bookmarks#install

**Comment by plutocrat** [comment]
Absolutely sure there was nothing in nextcloud.log or apache error log. I do this kind of thing for a living! :-) 
Anyway, your guess was correct. After installing the gmp module, i actually _did_ get an error message in the nextcloud.log, which reminded me to restart apache (ahem), and then I was able to sync 127.0.0.1 bookmarks. I think it may be numeric bookmarks, in fact, as one on my local subnet also triggered it. 
So, problem solved by 'apt install php7.2-gmp'
