### ISSUE TITLE
E016: Zeitüberschreitung einer Anfrage. Überprüfen Sie die Server-Konfiguration

### ISSUE THREAD

**Issue by BeamMeUpTo** [marcelklehr/floccus#350]
Hi Marcel,

leider habe ich wieder ein Problem mit dieser Fehlermedlung:

`E016: Zeitüberschreitung einer Anfrage. Überprüfen Sie die Server-Konfiguration
Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu
Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar
Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
Syncing failed with E016: Zeitüberschreitung einer Anfrage. Überprüfen Sie die Server-Konfiguration
`
### Software versions

- Browser: FF 68.0.1
- Nextcloud: 15.0.10
- Nextcloud Bookmarks app: 1.1.1
- Floccus: 3.3.2
- Floccus sync method: nextcloud Bookmarks v0.14+ 
  
### Steps to reproduce

Synchronisierung starten und es kommt immer diese Fehlermeldung!

Ich hatte vorher das Problem, dass auf meinem Server noch php7.0 lief, welches ja nach der App Aktualisierung nicht mehr lief. (Hatte diverse URL normalizer Fehler!)

Ist jetzt auf php7.3 geupdated (URL normalizer Fehler weg stattdessen --> E016) und sollte ja nun laufen... max_execution_time schon auf 3600 hochgesetzt, aber trotzdem E016...

Hast Du einen Idee??
Beam

**Comment by marcelklehr** [comment]
Zunächst wäre es interessant herauszufinden, welcher Request timeoutet. Dazu kannst du die folgenden Schritte machen, um die Netzwerkkommunikation zu beobachten:

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* go to the network tab
* go to floccus options and trigger a sync
* go back to the inspector window and observe

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab
* go to floccus options and trigger a sync
* go back to the inspector window and observe

**Comment by BeamMeUpTo** [comment]
Kannst Du daraus was erkennen?

![floccus-Error-FF-debug](https://user-images.githubusercontent.com/45270879/62942886-8d702280-bdd9-11e9-86fc-7361948408e8.png)

**Comment by marcelklehr** [comment]
Ah, Ich brauche den Netzwerk-Tab

**Comment by BeamMeUpTo** [comment]
Ich hoffe das ist das richtige Bild ;)

![floccus-Error-FF-Netzwerkanalyse-debug](https://user-images.githubusercontent.com/45270879/62951253-ec3d9800-bde9-11e9-9d35-29633ceea5ce.png)

Mit der letzten Zeile erscheint im FF Floccus Addon das Ausrufezeichen mit dem Fehler. Nach einer Weile probiert er es dann erneut.

**Comment by marcelklehr** [comment]
Mmmh. Kannst du das mit der neuest Beta-Version (#338 ) nochmal probieren? Das sollte dort  hoffentlich repariert sein.

**Comment by BeamMeUpTo** [comment]
Teste gerade 3.4beta - still running ;)

![floccus-Error-FF-Netzwerkanalyse02-debug](https://user-images.githubusercontent.com/45270879/62961324-d6859e00-bdfc-11e9-8fbd-c044cedeb3e6.png)

**Comment by BeamMeUpTo** [comment]
Ja, ich habe viele Lesezeichen, aber bei einem gibt es immer die 500!

Ein Zoneminder Lesezeichen! Danach wird wieder von Anfang an synchronisiert!?

![floccus-Error-FF-Netzwerkanalyse04-debug](https://user-images.githubusercontent.com/45270879/62972780-1bb5ca00-be15-11e9-861a-28331ad7c7ce.png)

**Comment by marcelklehr** [comment]
Dir fehlt die gmp php extension.

**Comment by BeamMeUpTo** [comment]
Woran hast Du das jetzt gesehen?

**Comment by marcelklehr** [comment]
HTTP 500 mit einer IP als URL, das hab ich schon öfter gesehen ;)

**Comment by marcelklehr** [comment]
Viele Lesezeichen hast du genau? :thinking:

**Comment by BeamMeUpTo** [comment]
1273 ;) 
Entstanden duch Strg+A im Lesezeichenmanager und in kate eingefügt = 1273 Zeilen - sieht plausibel aus 8)  ;)

**Comment by BeamMeUpTo** [comment]
3.4.0 Beta lief jetzt das erste Mal komplett durch - knapp eine Stunde mit Beschleuniger Funktion auf einem rpi3b+. Yippie ;)

Gibt es eine elegante Methode die 3.4.0 Beta dauerhaft zu nutzen? Irgendwo hatte ich gelesen, dass sie aber nur manuel geupdatet werden kann.

Wann wird denn so in etwa der Release Termin für die 3.4 sein?

Danke für deine hervorragende Hilfe
Thomas - Beam

**Comment by marcelklehr** [comment]
> 1273

1h Stunde für 1000 Lesezeichen kommt mir etwas viel vor. War das der initiale Sync Run? Wie lange dauert es jetzt?

3.4.0 wird released sobald [der Milestone](https://github.com/marcelklehr/floccus/milestone/1) fertig ist.
