### ISSUE TITLE
Tags are not sync to Firefox from Nextcloud. Is that possible?

### ISSUE THREAD

**Issue by SenaidaHdez** [marcelklehr/floccus#351]
Hello!

Some people already commented the sync of tags is not working, which I get.
You commented on previous posts that Firefox does not allow you to get the tag data. But! Can you import tag data from Nextcloud to Firefox? Is that possible at all?

Thanks!

**Comment by marcelklehr** [comment]
Neither is possible, I'm afraid. :/
