### ISSUE TITLE
Error syncing

### ISSUE THREAD

**Issue by InfamousUser** [marcelklehr/floccus#355]
### Software versions

- Browser: Chrome 76.0.3809.132
- Nextcloud: Nextcloud 16.0.4
- Nextcloud Bookmarks app: 2.0.3
- Floccus: 3.4.0.5
- Floccus sync method: Nextcloud best
  

### Steps to reproduce

1.  Install Chrome extension
2. Use Chrome extension

### Expected outcome

Extension does what it's supposed to.

### Actual outcome

Extension syncs some of the bookmarks (I don't know ho to verify how much it actually copied.

### Debug log
Debug log contains a lot of "#undefined" entries.

- [ ] Debug log provided

I don't see a field to actually enter the actual message you want to actually submit so here it is:

On one PC the sync worked properly. On second PC (I wiped bookmarks on the server between tries) it ends with an error:
"E019: HTTP status 403. Failed GET request. Check your server configuration and log. E019: HTTP status 403. Failed GET request. Check your server configuration and log."
It did transfer the majority or all of the bookmarks but I have no way to verify as it doesn't finish.

**Comment by marcelklehr** [comment]
This also appears to be a server-side issue. Status 403 means that the server refuses to respond for some reason. Perhaps some part of your server infrastructure identifies the floccus requests as flooding and bans your client. In any case, as the error message indicates, you should check your nextcloud and http server log. Feel free to report back here, if you're still stuck. :)

**Comment by InfamousUser** [comment]
Okay I have to say I did check twice the logging on Nextcloud server at the time and there was nothing new. This time I have 3 errors, not sure if all three are related. One is:

`Error | Undefined offset: 0 at /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Parsers/HtmlParser.php#95`

The other two are:

`Fatal | Sabre\DAV\Exception\BadRequest: expected filesize 1024000 got 745472/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:OCA\DAV\Connector\Sabre\File->put(null)/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 45:OCA\DAV\Connector\Sabre\Directory->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:OCA\DAV\Upload\UploadFolder->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php- line 525:Sabre\DAV\Server->createFile("uploads/di/ ... 9", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/lib/Server.php - line 316:Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 163:require_once("/var/www/ne ... p")`

and

`Error | Sabre\DAV\Exception\BadRequest: expected filesize 1024000 got 745472/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:OCA\DAV\Connector\Sabre\File->put(null)/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 45:OCA\DAV\Connector\Sabre\Directory->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:OCA\DAV\Upload\UploadFolder->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php- line 525:Sabre\DAV\Server->createFile("uploads/di/ ... 9", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/lib/Server.php - line 316:Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 163:require_once("/var/www/ne ... p")`

**Comment by InfamousUser** [comment]
Okay I have to say I did check twice the logging on Nextcloud server at the time and there was nothing new. This time I have 3 errors, not sure if all three are related. One is:

Error | Undefined offset: 0 at /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Parsers/HtmlParser.php#95

The other two are:

Fatal | Sabre\DAV\Exception\BadRequest: expected filesize 1024000 got 745472/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:OCA\DAV\Connector\Sabre\File->put(null)/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 45:OCA\DAV\Connector\Sabre\Directory->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:OCA\DAV\Upload\UploadFolder->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php- line 525:Sabre\DAV\Server->createFile("uploads/user/ ... 9", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/lib/Server.php - line 316:Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 163:require_once("/var/www/ne ... p")

and

Error | Sabre\DAV\Exception\BadRequest: expected filesize 1024000 got 745472/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:OCA\DAV\Connector\Sabre\File->put(null)/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 45:OCA\DAV\Connector\Sabre\Directory->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:OCA\DAV\Upload\UploadFolder->createFile("00000000000 ... 9", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php- line 525:Sabre\DAV\Server->createFile("uploads/user/ ... 9", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/lib/Server.php - line 316:Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 163:require_once("/var/www/ne ... p")

**Comment by InfamousUser** [comment]
Glad I'm not the only one!

**Comment by marcelklehr** [comment]
@iLoveVaccines I agree, your error is likely unrelated, please check your nextcloud log.

**Comment by marcelklehr** [comment]
@InfamousUser It would help if you could provide the actual version numbers as requested in the issue template.

**Comment by marcelklehr** [comment]
> Error | Undefined offset: 0 at /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Parsers/HtmlParser.php#95

This could be the culprit, but in that case you should get a 500 status, I think.

**Comment by iLoveVaccines** [comment]
> @iLoveVaccines I agree, your error is likely unrelated, please check your nextcloud log.

OK, sorry. I am new to this stuff. I will see if I can access it.

**Comment by marcelklehr** [comment]
@iLoveVaccines No worries, everyone is new at some point :)

**Comment by InfamousUser** [comment]
Okay, I have updated the OP with versions. I was using the older Bookmarks app release, that just got updated yesterday, I switched to that and now it no longer syncs anything. It succeeds and syncs nothing.

Log says:
`Starting sync process for account user@server.domain.tld
Received folders from server []
COMPARE { localItem: 
     + #4553[undefined] parentId: undefined
   ,
  cacheItem: 
     + #undefined[undefined] parentId: undefined
   ,
  serverItem: 
     + #-1[undefined] parentId: undefined
    }
Skipping subtree
Successfully ended sync process for account user@server.domain.tld`

**Comment by InfamousUser** [comment]
I have updated the OP with versions but in the meantime I saw the Bookmarks app got updated to new major version so I've deleted all the bookmarks, removed the Bookmarks app from Nextcloud, re-added it, reinstalled the browser extension and reconfigured it, seems to be updating now properly now. I will report back if any more issues but looks to no longer exist with new Nextcloud app version.
