### ISSUE TITLE
Feature request: Retain bookmark order when syncing

### ISSUE THREAD

**Issue by InfamousUser** [marcelklehr/floccus#356]
Would it be possible to retain bookmark sorting when syncing with Floccus?
I have my bookmarks somewhat sorted by relative order of the bookmarks. When reviewing the bookmarks on the server I do not see a way to view them without being resorted.

**Comment by marcelklehr** [comment]
That is actually a server-side issue. The order is stored on the server but not yet reflected in the server-side UI.

**Comment by InfamousUser** [comment]
Should I open this issue on the Nextcloud app page? By yet do you mean it will be fixed?

**Comment by marcelklehr** [comment]
It's a feature that would make a lot of sense, but is at the same time not trivial to implement, which is why I've been putting it off. I expect to fix it eventually, though. :)

**Comment by InfamousUser** [comment]
Alright, thanks for the info. :)
I'll add it on the other one.
