### ISSUE TITLE
OneDrive setup

### ISSUE THREAD

**Issue by mruac** [marcelklehr/floccus#357]
### Software versions

- Browser: Opera GX
- Floccus: 4.7.17
- Floccus sync method: XBEL/Webdav
  

### Steps to reproduce

1.  Add account > XBEL file in WEBDAV share
2. Configure the account; using the WebDAV URL found from https://blogs.msdn.microsoft.com/robert_mcmurray/2014/09/30/using-the-webdav-redirector-with-onedrive-part-1-standard-security/

- WebDAV URL: https://d.docs.live.net/CID (CID can be found in the URL of your OneDrive account when logged in.
- Username: email address used to log in to OneDrive
- Password: password used to log in to OneDrive
- Local folder: Root folder

3. Save, then Sync now

### Expected outcome

My bookmarks are synced to OneDrive, which I can then sync to my phone and other browsers.

### Actual outcome

Syncing failed with E023: Unable to clear lock file, consider deleting bookmarks.xbel.lock manually.

No bookmarks.xbel.lock file is found in my OneDrive account after attempting to sync.

### Debug log

- [done] Debug log provided

**Comment by marcelklehr** [comment]
> WebDAV URL: https://d.docs.live.net/CID (CID can be found in the URL of your OneDrive account when logged in.

Make sure you a have slash at the end of your webdav URL.

**Comment by mruac** [comment]
Same error still happens even with the added forward slash at the end of the URL.

**Comment by marcelklehr** [comment]
Wait, your floccus version is v4.7.17 :thinking: ? That's not even released yet...

**Comment by marcelklehr** [comment]
Do the same credentials work when using some other webdav client?

**Comment by mruac** [comment]
Sorry, for some reason the extension detail preview shows v4.7.17 and the details page shows v3.4.0.5

The same credentials and url works in WinSCP, following this guide: https://winscp.net/eng/docs/guide_microsoft_onedrive
though the it does not ask to use https and uses a port number instead.

Using the same process also works in Windows explorer's network drive.

**Comment by marcelklehr** [comment]
So, I checked and onedrive expects the WLID1.0 authentication scheme to be used. Currently floccus only supports Basic auth.

**Comment by mruac** [comment]
Damn, Looks like onedrive is not supported then. I'm not willing to set up a new cloud storage account or set up a webdav server, so I guess this isn't for me.

Thank you for your help, your project is very interesting!

**Comment by marcelklehr** [comment]
You could use LoFloccus to sync to a local file that you then sync via the official onedrive client.
