### ISSUE TITLE
Cannot read property 'forEach' error with Chrome extension

### ISSUE THREAD

**Issue by hardtopnet** [marcelklehr/floccus#358]
Hi, I encountered an error while trying to sync my nextcloud instance bookmarks with my chrome browser. With Firefox & FF extension it works as intended but seemingly not with Chrome extension.

Steps:

* download Chrome extension version 3.4.0.5
* setup parameters for own nextcloud server
* error is returned
* logs read:
> Starting sync process for account xxx@xxx.xxx [REDACTED]
> Fetching bookmarks
> Syncing failed with Cannot read property 'forEach' of undefined
see developer console output as attachment
![{05845315-AE19-481A-82E6-72B0CD49A7BB} png](https://user-images.githubusercontent.com/54667527/63934468-b5a78480-ca5b-11e9-9faf-728da4718bac.jpg)

Again, same parameters work with Firefox.

> nextcloud URL read as : https://<xxxx.xxx>:/cloud/ [REDACTED]
> no server folder specified
> local folder is default
> NextCloud 13 on a Synology DSM
> bookmarks app version 0.12.2
> extension version 3.4.0.5
> old Nextcloud installation
> format of entries in my bookmark app is:
```
floccus:>Network
floccus:>Development>WPF
```

Is it something with the Chrome extension or did I just forget something ?

**Comment by marcelklehr** [comment]
Ah, you're using the wrong sync method. You should use the legacy method.

**Comment by hardtopnet** [comment]
Well it doesn't seem so. I tried legacy just to be sure & doesnt work.

What is strange is the "new" method works with my FireFox extension although my bookmarks app is 0.12.2 (??)
But the Chrome one does not, whether on "new" or "legacy".

bookmark app version 0.12.2
![bookmarks](https://user-images.githubusercontent.com/54667527/63951494-23fd3e80-ca7e-11e9-80af-454fe4b3efad.jpg)

chrome extension version 3.4.0.5
![extension ch](https://user-images.githubusercontent.com/54667527/63951496-23fd3e80-ca7e-11e9-857c-6615d6f6b832.jpg)

firefox extension version 3.4.0.5
![extension FF](https://user-images.githubusercontent.com/54667527/63951497-23fd3e80-ca7e-11e9-8c7b-fd8ab36be665.jpg)

execution error with chrome & new sync method
![floccus ch](https://user-images.githubusercontent.com/54667527/63951498-23fd3e80-ca7e-11e9-9a84-b9717e239a9c.jpg)

execution error with chrome & legacy sync method
![floccus ch legacy jpg ](https://user-images.githubusercontent.com/54667527/63951499-23fd3e80-ca7e-11e9-8b3e-e75c7e654d3c.jpg)

execution succeeds with firefox & new sync method (although my bookmarks app is 0.12.2 ?)
![floccus ff](https://user-images.githubusercontent.com/54667527/63951503-2495d500-ca7e-11e9-9fa5-73386a3e1b3b.jpg)

**Comment by marcelklehr** [comment]
> execution succeeds with firefox & new sync method (although my bookmarks app is 0.12.2 ?)
> ![image](https://user-images.githubusercontent.com/986878/63953117-02ea1d00-ca81-11e9-8564-2a53d95db5c1.png)

You *are* using the legacy method in firefox, which used to be the default, but is not anymore. This is indicated not by the large blue button, which is only for *creating new accounts*, but by the protocol identifier `nextcloud://` underneath your folder name. The new method is called `nextcloud-folders://`.

So, the old method is the way to go, but since it doesn't work either at the moment, let's figure this out as well. What is the error message in chrome in this case?

**Comment by hardtopnet** [comment]
indeed I suppose I should use the old method, I was just confused with the fact it works in FF ;-)

I created a new account with legacy method, and it works indeed. I was just switching the dropbox value without creating a new account. That's why it wasn't working.

Still remains the mystery of the working FF case, but that's not a real isse though :-)
thanks a lot for the feedback !

**Comment by marcelklehr** [comment]
> Still remains the mystery of the working FF case, but that's not a real isse though :-)

The mystery is a case of bad UX, I suspect. While the blue button in firefox indicates the new method (which would be used for new accounts in this case), you have an existing account that still uses the old default method, that is now the legacy method. The fact that this is confusing is valuable feedback, though, and I'll revise this part of the UI.
