### ISSUE TITLE
no sync possible with errorcode

### ISSUE THREAD

**Issue by JimmyKater** [marcelklehr/floccus#359]
**Describe the bug**
somehow my sync between floccus and nextcloud won't work anymore - as it's not yet superimportant to me i was watching the failing snycs for weeks now... and was hoping that v3.4.x was somehow solving the problems. but it didn't.
as i don't have changed anything (except for maybe doing an upgrade of nc from v15.0.9 to 16.0.2 some weeks ago - could be that this was causing the problem, i really don't know) i'm lost. i even don't know if it would be a bookmarks-error or a floccus-related thing. i don't want to x-post it until further notice.

this is the error (sorry in german) that floccus gives me
E019: HTTP Status 500. Anfrage vom Typ POST fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log

this is one of several entries of nextcloud.log (the given internal ip is the one of my network-printer)
[index] Error: Error: Call to undefined function gmp_init() at <<closure>>

 0. /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/IPv4Address.php line 95
    Rowbot\URL\IPv4Address::parseIPv4Number("192", false)
 1. /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/Host.php line 105
    Rowbot\URL\IPv4Address::parse("192.abc.xyz.208")
 2. /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/BasicURLParser.php line 893
    Rowbot\URL\Host::parse("192.abc.xyz.208", false)
 3. /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/BasicURLParser.php line 299
    Rowbot\URL\BasicURLParser->hostState("/")
 4. /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/URL.php line 74
    Rowbot\URL\BasicURLParser::parseBasicUrl("https://192.abc.xyz.208/#", null)
 5. /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php line 12
    Rowbot\URL\URL->__construct("https://192.abc.xyz.208/#")
 6. /var/www/nextcloud/apps/bookmarks/lib/Bookmarks.php line 928
    OCA\Bookmarks\UrlNormalizer->normalize("https://192.abc.xyz.208/#")
 7. /var/www/nextcloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php line 308
    OCA\Bookmarks\Bookmarks->addBookmark("Andreas", "https://192.abc.xyz.208/#", "HP PageWide Pro 477dw MFP", ["floccus:"], "", false, [-1])
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Bookmarks\Controller\Rest\BookmarkController->newBookmark("https://192.abc.xyz.208/#", {tags: ["floccus:"]}, "HP PageWide Pro 477dw MFP", false, "", ["floccus:"], null)
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmarks\Co ... }}, "newBookmark")
10. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... }}, "newBookmark")
11. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("BookmarkController", "newBookmark", OC\AppFramework\ ... {}, {_route: "bookma ... "})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "bookma ... "})
13. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
14. /var/www/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/bookmarks/public/rest/v2/bookmark")
15. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

POST /index.php/apps/bookmarks/public/rest/v2/bookmark
from *deletend value* by *deleted value* at 2019-08-30T11:08:36+00:00

**Desktop (please complete the following information):**
 - OS: Win 10 pro (64) (v1809)
 - Browser FF 68.2.2 (64)
 - Floccus version: 3.4.0.2
 - Floccus sync method: don't know

**Server (please complete the following information):**
 - OS: Raspbian GNU/Linux 9 \n \l (via nextcloupi v1.16.0.)
 - Nextcloud version: 16.0.2.
 - Bookmarks app version: 1.1.1

**Debug log**
- [x] Debug log provided: uploaded at 13h17...

**Comment by marcelklehr** [comment]
> Call to undefined function gmp_init() 

The fix is rather easy: Install the php-gmp extension :)

**Comment by JimmyKater** [comment]
ummm... question is: when did you start using it? 
why isnt it already installed as a default? 
IS it default at all? 
could bookmarks check if it's installed and if not install it (b/c it seems to be needed)?

**Comment by marcelklehr** [comment]
A recent switch to a different URL normalization library necessitated additional php extension requirements: https://github.com/nextcloud/bookmarks#install . The bookmarks app cannot install php extensions for you, sadly.

**Comment by JimmyKater** [comment]
> The bookmarks app cannot install php extensions for you,
oh wow. so as much as i understand the need of freshening up the code (i looked into your link you provided just above, thank you!) i think it's not the best way to just auto-update bookmarks app and let users run into problems because of missing dependencies. 

i hope you're in coordination with main devs of nc-server about this problem. since i think THEY would be able to install missing libraries.

though thanks for the extremly good work with floccus and bookmarks. and its not meant ironic in any way.
