### ISSUE TITLE
Apparently, local IP adresses in bookmarks cause sync error (on server side?)

### ISSUE THREAD

**Issue by JDrewes** [marcelklehr/floccus#364]
I have more than 100 bookmarks in several folders and subfolders that sync fine between multiple computers and my nextcloud.

However, if I add a bookmark with a local IP address (e.g. my router at home), then sync fails with this error message in floccus:

E019: HTTP status 500. Failed GET request. Check your server configuration and log.

And this in the nextcloud log:

  | Error: Call to undefined function gmp_init()/var/www/owncloud/apps/bookmarks/vendor/rowbot/url/src/IPv4Address.php - line 94: Rowbot\URL\IPv4Address::parseIPv4Number("192", false)/var/www/owncloud/apps/bookmarks/vendor/rowbot/url/src/Host.php - line 105: Rowbot\URL\IPv4Address::parse("192.168.1.8")/var/www/owncloud/apps/bookmarks/vendor/rowbot/url/src/BasicURLParser.php - line 860: Rowbot\URL\Host::parse("192.168.1.8", false)/var/www/owncloud/apps/bookmarks/vendor/rowbot/url/src/BasicURLParser.php - line 301: Rowbot\URL\BasicURLParser->hostState(":")/var/www/owncloud/apps/bookmarks/vendor/rowbot/url/src/URL.php - line 73: Rowbot\URL\BasicURLParser::parseBasicUrl("http://192.168.1.8:81/", null)/var/www/owncloud/apps/bookmarks/lib/UrlNormalizer.php - line 12: Rowbot\URL\URL->__construct("http://192.168.1.8:81/")/var/www/owncloud/apps/bookmarks/lib/Bookmarks.php - line 441: OCA\Bookmarks\UrlNormalizer->normalize("http://192.168.1.8:81/")/var/www/owncloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php - line 226: OCA\Bookmarks\Bookmarks->bookmarkExists("http://192.168.1.8:81/", "jan")/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Bookmarks\Controller\Rest\BookmarkController->getBookmarks("bookmark", "", 0, "bookmarks_sorting_recent", "jan", null, "or", "", [], 10, false, null, "http://192.168.1.8:81/")/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... }}, "getBookmarks")/var/www/owncloud/lib/private/AppFramework/App.php - line 126: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... }}, "getBookmarks")/var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("BookmarkController", "getBookmarks", OC\AppFramew ... {}, { _route: "b ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "b ... "})/var/www/owncloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "b ... "})/var/www/owncloud/lib/base.php - line 975: OC\Route\Router->match("/apps/bookm ... k")/var/www/owncloud/index.php - line 42: OC::handleRequest()

Is this a bug in floccus or in nextcloud?

I recently upgraded my nextcloud server (16.04 running on Debian Stretch) to php 7.3 (to keep floccus/Bookmarks app working), all other nextcloud functionality doesn't seem to exhibit any problems.

I'll be grateful for any pointers!

Jan
-- | --

**Comment by marcelklehr** [comment]
You'll need to install the gmp php extension

**Comment by JDrewes** [comment]
Thank you for the fast response!

Is this mentioned in some documentation somewhere?

Cheers,

Jan

**Comment by marcelklehr** [comment]
> Is this mentioned in some documentation somewhere?

Yes, https://github.com/nextcloud/bookmarks#install . Newer versions of the app also prevent you from installing when the dependency requirements aren't met.
