### ISSUE TITLE
Shaarli support

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#365]
Hi

Please do not hate me for asking for this but it would be so neat if Floccus can actually sync with Shaarli backend. Basically whatever you bookmar in the browser is submitted to Shaarli and in return the Shaarli bookmarks are also synced back to Floccus.

thanks

**Comment by bernd-wechner** [comment]
Wondering why anyone would hate you for such a simple request. But given your concern, I guess you won't hate anyone (least of all Marcel, a clear champ) if they said, this was not a priority. I won't speak for anyone else, floccus is admirably FOSS and Marcel would take a Pull Request with the fix gladly too I'm sure. But don't forget that you could also file an issue with Shaarli to support Floccus (presumably with its XBEL/WebDAV support):

https://en.wikipedia.org/wiki/XBEL

**Comment by marcelklehr** [comment]
While I probably won't find time to implement them myself, I generally welcome additional sync backends, indeed. I'll add some documentation on how to go about implementing something like that, soon :)

**Comment by marcelklehr** [comment]
I just looked into this and it appears shaarli only supports tags for organizing links, which floccus currently doesn't have access to in the browser, so at present a floccus backend for shaarli doesn't make sense, IMHO.
