### ISSUE TITLE
sync error E019 an E017 http status 500

### ISSUE THREAD

**Issue by johnnydvc** [marcelklehr/floccus#369]
Hi,
I'm unable to sync with my nextcloud instance.

floccus gives me:

> E019: HTTP Status 500. Anfrage vom Typ GET fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log E019: HTTP Status 500. Anfrage vom Typ GET fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log E019: HTTP Status 500. Anfrage vom Typ GET fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log E017: Netzwerk-Fehler: Überprüfen sie Ihre Netzwerkverbindung und die eingegebenen Konto-Daten

the nextcloud logs are:

> [index] Error: ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) at <<closure>>
> 
>  0. /var/www/html/lib/composer/composer/ClassLoader.php line 322
>     Composer\Autoload\includeFile("/var/www/html/a ... p")
>  1. <<closure>>
>     loadClass("Rowbot\\URL\\BasicURLParser")
>  2. /var/www/html/apps/bookmarks/vendor/rowbot/url/src/URL.php line 72
>     spl_autoload_call("Rowbot\\URL\\BasicURLParser")
>  3. /var/www/html/apps/bookmarks/lib/UrlNormalizer.php line 12
>     __construct("https://extensions.gnome.org/")
>  4. /var/www/html/apps/bookmarks/lib/Bookmarks.php line 441
>     normalize("https://extensions.gnome.org/")
>  5. /var/www/html/apps/bookmarks/lib/Controller/Rest/BookmarkController.php line 226
>     bookmarkExists("https://extensions.gnome.org/", "j")
>  6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
>     getBookmarks("bookmark", "", 0, "bookmarks_sorting_recent", "j", null, "or", "", [], 10, false, null, "https://extensions.gnome.org/")
>  7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
>     executeController(OCA\Bookmarks\Co ... }}, "getBookmarks")
>  8. /var/www/html/lib/private/AppFramework/App.php line 118
>     dispatch(OCA\Bookmarks\Co ... }}, "getBookmarks")
>  9. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
>     main("BookmarkController", "getBookmarks", OC\AppFramework\ ... {}, {_route: "bookma ... "})
> 10. <<closure>>
>     __invoke({_route: "bookma ... "})
> 11. /var/www/html/lib/private/Route/Router.php line 297
>     call_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
> 12. /var/www/html/lib/base.php line 987
>     match("/apps/bookmarks/public/rest/v2/bookmark")
> 13. /var/www/html/index.php line 42
>     handleRequest()
> 
> GET /index.php/apps/bookmarks/public/rest/v2/bookmark?url=https%3A%2F%2Fextensions.gnome.org%2F
> from 89.245.113.159 by j at 2019-09-11T16:33:51+00:00

**Comment by marcelklehr** [comment]
Hey @johnnydvc 
Your PHP version doesn't seem to be supported by the bookmarks app. You need at least php v7.1

**Comment by johnnydvc** [comment]
I don't exactlyknow how, but I seem to have fixed the issue.
Thanks
