### ISSUE TITLE
Sync folder is called "Nextcloud (bob@http://example.org)" when setting up 1.3.0 beta 5 on Opera Next 51.0.2781.0

### ISSUE THREAD

**Issue by e-alfred** [marcelklehr/floccus#37]
Hello,

I set up Floccus 1.3.0 Beta 5 in Opera Next 51.0.2781.0 and Nextcloud 12 with Bookmarks app 0.10. After setting up an account, the folder where all the bookmarks are synced is called "Nextcloud (bob@http://example.org)". The bookmarks are synced to that folder successfully though.

**Comment by marcelklehr** [comment]
Hey there,

glad it works. I've fixed that just [recently](https://github.com/marcelklehr/floccus/commit/16dbc751a369b6d1323e9b3bfaf816edae2da7dc). Thanks for reporting, though :)
