### ISSUE TITLE
3.4.1 Where is the UI

### ISSUE THREAD

**Issue by jlbprof** [marcelklehr/floccus#370]
**Describe the bug**
Today Floccus updated to 3.4.1, and immediately I cannot change account information, set options or force a sync.  The UI has pretty much gone away.   The one button there "Add Account" does not respond.

**To Reproduce**
1. Comes out of the box this way.

Further, I added Floccus to Firefox, it only has 3.4.0.5 and works fine.
I downloaded Floccus 3.4.1 to a fresh Chrome install, I can click the Add Account button, and select WebDav.  I then go to set the url and as soon as I type in the url it immediately is set back to https://example.com.

**Expected behavior**
I would like to be able to edit options, force syncs etc.

**Screenshots**
[Screenshot](https://imgur.com/a/oX2WiLR)
![brave_KFqfSHwpU3](https://user-images.githubusercontent.com/9746421/64915811-7785b280-d735-11e9-8c18-7f5e9e87831e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Brave, A Chrome clone (latest)
 - Browser Version
   Brave - Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
   Chrome - Version 77.0.3865.75 (Official Build) (64-bit)
   Firefox - 69.0 (64-bit
 - Floccus version: 3.4.1  (3.4.0.5 for Firefox)
 - Floccus sync method: WebDav.

**Server (please complete the following information):**
 - OS: CentOS7 (Siteocity, cPanel account)

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ X ] Debug log provided 
loaded via above url (floccus-3.4.1-2019-09-15.log)

**Additional context**
N/A

**Comment by marcelklehr** [comment]
Rolling back and re-evaluating. Thanks for the quick feedback everyone!
