### ISSUE TITLE
floccus v3.4.1 with Android Kiwi Browser: Unable to enter account data

### ISSUE THREAD

**Issue by TeslaBargain** [marcelklehr/floccus#371]
A fresh installation of Kiwi Browser (vImpala.123) on Android 9 + floccus v3.4.1, I can not edit the account data when trying to add an account.

The sample data that it comes up with simply stays when trying to delete / overwrite / cut / paste, which means the

Nextcloud URL: https://example.org
Username: bob
Password: ******

and the "Server folder" field (empty by default) can not be modified as any changes are reverted right after an attempt to change them.

I have tried on three different phones (OnePlus 5 and OnePlus 6 running LineageOS 16 for microG, and a ZTE Blade V10 with the latest stock firmware) and they all show the same behavior. None of the phones is logged into a Google account, so there is no bookmarks syncing with Google (and Kiwi Browser does not even show an option to sync).

**Comment by j-autuick** [comment]
I am experiencing this as well--demonstrated by the following video:
https://cloud.little-beak.com/s/bcLPXmXeRk9jrz6
I wasn't able to articulate it as well as you ( @TeslaBargain )

However, I am experiencing this on Brave and Chrome, on macOS X Mojave.

I tried:
Removing the extension (on both browsers), resetting the browser, and even flushing everything on it that is possible to flush. The buggy extension behavior remains. 

It seems to work on systems that are already setup, though. 

Don't know what is causing this behavior. Will investigate in any direction that seems worthwhile.

**Comment by 05nelsonm** [comment]
Same. Was the latest update.

Seems to only be occurring with Chrome based browsers, as Gecko based browsers seem unaffected.

**Comment by TeslaBargain** [comment]
I can confirm that by removing v3.4.1 and installing 3.4.0 instead everything works as expected. Upgrading from v3.4.0 to v3.4.1 removes previously stored settings and the same problem (unable to edit account data) comes back.

**Comment by j-autuick** [comment]
@TeslaBargain 
Yeah, works fine with firefox, so it appears to only be Chromium based new setups.

**Comment by marcelklehr** [comment]
I'm rolling back the v3.4.1 release as we speak.

**Comment by bureaucrat359** [comment]
I have the same effect with 3.5.0 on Ubuntu 19.04 with Firefox (69.0.2+build1-0ubuntu0.19.04.1), can't edit account data when setting up...

**Comment by marcelklehr** [comment]
@bureaucrat359 Thanks for reporting! Fixed now.
