### ISSUE TITLE
3.4.1 update removed accounts/doesn't work

### ISSUE THREAD

**Issue by 05nelsonm** [marcelklehr/floccus#372]
**Describe the bug**
the latest update removed all account information, as well as will not allow me to add new accounts on any browser.

**To Reproduce**
1. install update
2. get REKT

**Expected behavior**
Update shouldn't remove any account information and just work

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 && Android 8.1
 - Browser: Vivaldi && Kiwi Browser
 - Browser Version ;atest
 - Floccus version: 3.4.1
 - Floccus sync method: Nextcloud Folders && WebDav

**Server (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Nextcloud version: 16.04
 - Bookmarks app version: 2.1.1
 - [ ] Debug log provided

**Additional context**
extension does not work in Vivaldi Browser for Ubuntu, or Kiwi Browser for Android.

even after removing and reinstalling, you cannot enter any information because it constantly reverts back to the provided examples.

**Comment by TeslaBargain** [comment]
https://github.com/marcelklehr/floccus/issues/371

**Comment by marcelklehr** [comment]
I'm rolling back the v3.4.1 release.
