### ISSUE TITLE
The "Index out of bounds" during synchronization. 

### ISSUE THREAD

**Issue by ratermir** [marcelklehr/floccus#374]
Synchronization worked well, but after some changes in bookmarks on both server side and client side it stopped working with the error message "Account.js:201 Syncing failed with Index out of bounds."

I can't tell more on it because I made a lot of changes to the bookmarks (they were rearranged, some deleted, some moved ...)

Nextcloud 16.0.3 docker, php-fpm 7.3.7, mysql, bookmarks app 2.1.1

I am attaching log from synchronization.
[fnaicdffflnofjppbagibeoednhnbjhg-1568807938492.log](https://github.com/marcelklehr/floccus/files/3626427/fnaicdffflnofjppbagibeoednhnbjhg-1568807938492.log)

**Comment by ratermir** [comment]
I have additional info on this issue: 
When I chosen "Always overwrite and revert local changes", next sync stood "frozen" for approx. 10 minutes (then I cancelled it).

Then I deleted all local bookmarks, checked on "Trigger sync from scratch" in the config and started sync - it passed successfully. 

Subsequent "normal" sync again ended with the error described above.

**Comment by marcelklehr** [comment]
Thanks for the feedback, this appears to be a problem with the *slave* sync strategy. I will look into this.

**Comment by marcelklehr** [comment]
You appear to have enabled parallel syncing (the speedup sync option). Could you disable that and reproduce a log file with the error? That  would be immensely helpful.

**Comment by oparoz** [comment]
Just had the exact same problem on 17 & 18, without using parallel processing. All I did was move folders around in the chrome-based browser.
On Nextcloud, I saw several duplicated folders, some empty.
Should I re-open this ticket?

**Comment by matharuajay** [comment]
yes i have same problem without parallel processing and i just moved around some bookmarks folder in chrome

**Comment by marcelklehr** [comment]
This has been addressed among other deep issues in the recent release of v4.0.0. Thanks for your patience. :)
