### ISSUE TITLE
Cancel button saves

### ISSUE THREAD

**Issue by InfamousUser** [marcelklehr/floccus#375]
**Describe the bug**
Pressing "Add account" and then "Cancel" adds the account anyway. 
It also saves the account with empty credentials and/or URL when pressing save instead. Weird.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 8.1
 - Browser [e.g. chrome, safari] Chrome
 - Browser Version [e.g. 22] 77
 - Floccus version: [e.g. 3.2.2] 3.4.2
 - Floccus sync method: [e.g. webdav, nextcloud legacy or nextcloud folders] Nextcloud best

**Server (please complete the following information):**
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

**Comment by marcelklehr** [comment]
Yep, confirmed. Thanks for the feedback!

**Comment by InfamousUser** [comment]
@marcelklehr This did not get fixed. This is still present with 3.5.1 release.

**Comment by marcelklehr** [comment]
Sorry for quietly closing this. This behavior is indeed expected as the options view currently doesn't know whether it's a new account or not.

**Comment by marcelklehr** [comment]
Now, there's a screen before you get to actually edit the options. If you cancel that screen, you won't get a leftover account.
