### ISSUE TITLE
Nice work, but...

### ISSUE THREAD

**Issue by azimut2000** [marcelklehr/floccus#38]
Hello Marcel !

Very nice plugin ! and it's the only one that can sync bookmark between Firefox and Netxcloud (last version 12 at home !).

My computer : Windows 10 and Firefox 57.00

I try to test your plugin since a long time, but it has never work for me.... This is the first version (1.3 on Firefox) that work (almost) fine on my computer ! I'll try Chrome version another day... But it must work too now i think !

I have again some errors in sync but it's a good start... and i don't know how to LOG what appens ?

There is as well a strange display when i come for the first time in the option page of this plugin (on the bottom of the page) : the button "add  account" does not appear very well on Windows (i'll try on Linux tomorrow).

Domage as well that i can't sync bookmark on my personnal bar in Nextcloud - it's the place where i have all my bookmark :-(

May be in a next version, by having possibility to change the path ? 

Thank's again !

**Comment by marcelklehr** [comment]
Hey!
thanks for your kind words

You can see the sync log in firefox by
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice.
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

Also, when the options page displays an error status, you can hover over it, to see a general description of the error.

**Comment by marcelklehr** [comment]
I've released two new bugfix versions that should make your experience much more stable :)

**Comment by marcelklehr** [comment]
Feel free to reopen or shout at will, if you still have issues.
