### ISSUE TITLE
Floccus duplicates bookmarks on the server

### ISSUE THREAD

**Issue by ratermir** [marcelklehr/floccus#382]
Floccus creates duplications of the bookmarka. I use it for syncing between two instances and it halppens that dome bookmarks are duplicate many times on the server. 
I didn't observer any "logic" in this - some folders are multiplied (some of them even 10x), but most of then isn't.
It happens mainly on folders. In data downloaded from server i saw these bookmark folders have even the same ID.  
I don't know who manages these IDs (whether client or server), but I suppose the ID should (or must?) be unique. So there should be a way how to avoid duplications of IDs (don't create new item with already existing ID, but merge them instead?).

I captured some data - it is attached in #383

**Comment by marcelklehr** [comment]
Mmh, I have a theory about why this is happening. Could you try to produce a debug log for a sync run that creates duplicate folders? I know this is probably not easy, but would help a lot :)

**Comment by ratermir** [comment]
Ok, I'll try to capture it during christmas holiday (until then I am really busy).

**Comment by marcelklehr** [comment]
In the process of debugging #401 I stumbled into this as well, and I'm fairly certain how to avoid it. (Background: Recent floccus versions are able to bulk import a whole folder into the bookmarks app, if, however, said folder is too large to be handled before the reverse proxy timeout, or the php execution timeout, floccus will think it failed, when it actually (partially) succeeded, causing duplicate folders.) The way out of this is to avoid bulk imports for folders with too much content.

**Comment by marcelklehr** [comment]
This should be fixed in v3.5.3
