### ISSUE TITLE
Firefox Android 

### ISSUE THREAD

**Issue by tobias-coder** [marcelklehr/floccus#388]
**Describe the bug**
Hallo,

Ich will das addon unter einem Android A3 2017 und GalaxyTab s2 benutzen.
In beiden Systemen lässt sich das Addon installieren und die Auswahl 

[Nextcloud Bookmarks] [Konto hinzufügen] führt zu keiner weiteren Aktion.

Das Addon funktioniert bei mir auf mehreren Ubuntu desktops und syncronisiert mit der NextCloud ohne Probleme

**To Reproduce**

**Expected behavior**
Config des Servers Oberfläche

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Firefox
 - Browser 68.1.1
 - Floccus version: 3.4.0.5
 - Floccus sync method: nextcloud

**Server (please complete the following information):**
 - OS: ubuntu 18.04.
 - Nextcloud version: 17.0.0 stable
 - Bookmarks app version: Bookmarks 2.2.0

**Comment by marcelklehr** [comment]
Das Problem ist bereits [be](https://github.com/marcelklehr/floccus#android)[kannt](https://github.com/marcelklehr/floccus/issues/3). ;)
