### ISSUE TITLE
Lost account?

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#391]
Hi

I just installed the Github release of 3.4.1 and I lost my existing accounts :( 

I am uisng FIrefox 69 on Debian

**Comment by marcelklehr** [comment]
The problem, in a nutshell, was that soem changes in v3.4.1 broke floccus on Firefox. v3.4.2 is thus a rollback of the first release and is not on addons.mozilla.org because it is essentially the same as 3.4.0 ;)
