### ISSUE TITLE
Cannot Add Account (force-autofill "https://example.org" and "bob")

### ISSUE THREAD

**Issue by subatomiq** [marcelklehr/floccus#392]
Cannot add account due to aggressive auto-fill action
all three sync types have the same problem in text fields, 
anything typed is immediately cleared and replaced with the following text:
------------------------------------------
Nextcloud URL: https://example.org
Username: bob
Password: ******
------------------------------------------

Click "Add Account" and attempt to create a new account

**Expected behavior**
the ability to actually type in a text field to add an account

**Desktop:**
 - OS: Win10 (same behaviour on multiple computers)
 - both Firefox and Chrome addons
 - *ALL* Floccus sync methods

**Comment by marcelklehr** [comment]
Confirmed. Fixed. Thank you :)
