### ISSUE TITLE
Does not work in Kiwi

### ISSUE THREAD

**Issue by ociviol** [marcelklehr/floccus#395]
On Huawei Mediapad M5 tablet, when trying to type in credentials Kiwi freezes, keyboard in unresponsive.
Impossible to configure the addon.

**Comment by marcelklehr** [comment]
Could you fill out the [issue template](https://raw.githubusercontent.com/marcelklehr/floccus/develop/.github/ISSUE_TEMPLATE/bug_report.md), please? :)

**Comment by crashcoq** [comment]
![Screenshot_20191212-125944_Kiwi Browser](https://user-images.githubusercontent.com/8464834/70710431-7554d500-1cdf-11ea-9f22-de70a4b89c0f.jpg)

Hello
I can't edit any option on kiwi browser
I  can't delete any string.

Cordially 
David

**Comment by marcelklehr** [comment]
Mh, I can't replicate this. It works fine on my phone :/
Have you tried opening the floccus panel in a new tab?

**Comment by crashcoq** [comment]
I have open with the menu and it works
But directly in extension,  not working

**Comment by urdaddy85** [comment]
do not edit floccus on the extensions page！open a new tab，click the up-right setting button，roll down to the bottom，you can find floccus logo，then you can edit the account info.
