### ISSUE TITLE
arse Error: <html xmlns="http://www.w3.org/1999/xhtml"><body><parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Extra content at the end of the document </div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></body></html>

### ISSUE THREAD

**Issue by bsed** [marcelklehr/floccus#402]
arse Error: <html xmlns="http://www.w3.org/1999/xhtml"><body><parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Extra content at the end of the document </div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></body></html>

**Comment by marcelklehr** [comment]
Could you please fill out the issue template?
