### ISSUE TITLE
sync fails if title is longer than 140 characters

### ISSUE THREAD

**Issue by tom-ch1** [marcelklehr/floccus#407]
Syncing a bookmark with a title longer than 140 characters causes an unrecoverable error. 

140 characters is too short for the title field.

Workaround: I increased the size of the field manually in the db and the error is fixed.

Underlying problem: floccus probably can't determine why the http request fails (http 500 error is returned). It could, however, try again with title truncated to 140 characters

**Comment by marcelklehr** [comment]
This would probably be better handled in the server app.

**Comment by tom-ch1** [comment]
do you use an api of the bookmarks app or just webdav?

**Comment by marcelklehr** [comment]
That depends on your use of floccus. Floccus supports both, but I suspect this problem was triggered by the use of the API.

**Comment by marcelklehr** [comment]
It turns out that the bookmarks app has been using a title length of 4096 bytes for some time now. It's possible that that migration only affected new instances.

**Comment by tom-ch1** [comment]
On Sat, 2019-11-23 at 12:42 -0800, Marcel Klehr wrote:
> It turns out that the bookmarks app has been using a title length of
> 4096 bytes for some time now. It's possible that that migration only
> affected new instances.

Are you sure you checked the title field? I only installed the
bookmarks app a couple of days ago. It is possible though that I had it
installed long ago, then uninstalled it and reinstalled only recently.

In that case, the questions are
- whether or not an uninstall should drop the bookmarks table.
- whether or not an install sould migrate the database schema

**Comment by marcelklehr** [comment]
It is indeed possible that preexisting tables from an old installation failed to be migrated. An uninstall currently still doesn't drop the tables. This should be a good idea, though. I'll open an issue for this.
