### ISSUE TITLE
Syncing failed with parentGuid must be valid

### ISSUE THREAD

**Issue by wohali** [marcelklehr/floccus#414]
**Describe the bug**
I'm syncing one NextCloud account to 2 machines (desktop, laptop). Both target the same folder on the server (/personal). This results in:

```
2019-12-01T02:26:06.900Z Syncing failed with parentGuid must be valid
(x120 times)
No bookmarks found for the provided parentGuid
(x6 times)
```

**To Reproduce**
1. Install floccus on 2 computers
2. Set them both to sync to the same nextCloud account, into the same folder.
3. Sync and wait...

**Expected behavior**
Syncing should be successful.

**Screenshots**
Debug log provided below...

**Desktop (please complete the following information):**
 - OS: both Windows 7 x64 and Linux
 - Browser: Firefox
 - Browser Version 68esr (Linux) and 70 (Windows)
 - Floccus version: 3.5.1
 - Floccus sync method: NextCloud Folders

**Server (please complete the following information):**
 - OS: Debian 10
 - Nextcloud version: 16.0.5 (will also test 17.0.1)
 - Bookmarks app version: 2.3.1
Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
Uploaded as "2computers1account.log"
- [X] Debug log provided

**Additional context**
I believe I may have lost bookmarks this way :(

**Comment by marcelklehr** [comment]
I'm sorry for your troubles. Thank you for the feedback and the diligently filled out bug report :)

Do you have native bookmark syncing enabled?

**Comment by marcelklehr** [comment]
Also, could you try disabling the sync-speedup? Besides ruling it out as the root cause, this would make reading the logs much easier :)

**Comment by wohali** [comment]
HI @marcelklehr , sorry for the delay.

After some repeated syncing, the issue went away.

I connected a third computer today for the first time, using the same approach. I left off sync-speedup this time. Everything worked fine the first time.

I'll keep an eye on things to see if this recurs, but it may be a "first time" problem that I'll no longer be able to reproduce....

**Comment by marcelklehr** [comment]
The issue was probably caused by moving folders, while the sync was running.
