### ISSUE TITLE
I cant save any settings in FF 71

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#419]
HI

I install FF 71 on Linux and added Floccus from the Github release page. For some reason I cant save any setttings or accounts, I press ave it still shows as bob@example.com thing. 

I tried the settings page, settings as new tab and from the drop down with no luck as if the save button is broken.

Please bear in mind that I have been using this addon on multiple devices for a year or so , so it is not like I do not know how to get it working :(

**Comment by jayceroot** [comment]
Hi,
For me it's the same exactly. I tried to do the same on vivaldi (chromium based) and it works. 
So it's propably a problem due to te update FF 71.

**Comment by fezie** [comment]
This seems to be a compile bug in firefox 71 itself.
On Debian this is fixed with 71.0-2
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946547

As I read somewhere on Fedora this has been already fixed too.

**Comment by gerroon** [comment]
71.0-1 sure was a complete shitstorm release.

**Comment by marcelklehr** [comment]
Ooph, good to know that kind of thing doesn't only happen to me :smile:

**Comment by marcelklehr** [comment]
@all-contributors Let's add @gerroon for reporting bugs :)
