### ISSUE TITLE
Automatic Backup for bookmarks per seperate Folder as HTML

### ISSUE THREAD

**Issue by v3nd3tta1337** [marcelklehr/floccus#42]
Hello Guys,

As this is a stalemate position between the devs of the nextcloud bookmarks and you guys,
just do a KISS implementation by adding a sync for a seperate, manual-importable format of Bookmarks and Folders: HTML.
IMO the bookmarks Extension for NextCloud is useless and can therefore be discarded.

So just add a method to have a "Bookmarks" Folder within the base directory and then save a floccus-bookmarks.html in it.

Regards.

**Comment by filippomicheletti** [comment]
I agree with @v3nd3tta1337 : the lack of folder support make completely unuseful the Chrom/Chromium extension.
OK, the vertical hyerarchical organization of bookmarks adopted by Google in its browser is not the best, all we know that tags work better (and all we loved Google products for using them so why having opted for folders in managing Chrome bookmarks remains a mistery) but this is the reality, Chrome uses folders and without them is completely unuseful to have an unique "Nextcloud bookmarks" folder with hundreds of links inside.
I've seen that something in folder support has been done in the past with the Owncloud bookmarks application but I don't know which is the relations with the Nextcloud one.

**Comment by marcelklehr** [comment]
Thank you for your thoughts on this!
For now, I'm focusing my efforts on integrating with the nextcloud bookmarks app, as I've decided to work on improving it as well, because there is a lot of potential. It is possible to extend floccus to allow the user to choose from multiple sync backends, however.
I still agree with you, though: Without folders floccus is not very useful, which is why I have been working on adding support for syncing folders. You can already test the first beta version of that feature over here: #46 ;)

**Comment by filippomicheletti** [comment]
Really nice!
I've just installed the beta version you suggested and I get an error during syncing, here ther is what the debug console says:

Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
Nextcloud.js:110Error: Failed to retrieve bookmark from ownCloud
    at NextcloudAdapter._callee2$ (chrome-extension://djejpebekaoommcjfeaiipdikmdjkblg/dist/js/background-script.js:5106:23)
    at tryCatch (chrome-extension://djejpebekaoommcjfeaiipdikmdjkblg/dist/js/polyfill.js:6150:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (chrome-extension://djejpebekaoommcjfeaiipdikmdjkblg/dist/js/polyfill.js:6424:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (chrome-extension://djejpebekaoommcjfeaiipdikmdjkblg/dist/js/polyfill.js:6183:21)
    at step (chrome-extension://djejpebekaoommcjfeaiipdikmdjkblg/dist/js/background-script.js:4819:191)
    at chrome-extension://djejpebekaoommcjfeaiipdikmdjkblg/dist/js/background-script.js:4819:361

I'm on Chromium 52.0.2743.116 built on Debian stretch/sid, running on Debian buster/sid (64-bit) and my Nextcloud server is running a (little bit old) version 11.
What I've tried was just to copy a folder containing some bookmarks from my Chromium bookmarks to the Nextcloud folder created by floccus. I noticed also that on the cloud Bookmarks app the bookmarks contained in the folder that I copied have been synced and a tag named "floccus-path:folder_name" have been created... not perfect but good!
Can I help you in some way to solve these problems?

**Comment by marcelklehr** [comment]
Ah, I forgot to point out that you need the latest changes of the bookmarks app repository as well :/ So, in order to make it work, you'll remove the nextcloud/apps/bookmarks directory and git clone the repo into nextcloud/apps/ again.

**Comment by e-alfred** [comment]
This looks awesome. Does it sync all existing bookmarks from a browser? How does it handle linking multiple browsers with existing bookmark trees like for example duplicates?

**Comment by marcelklehr** [comment]
You still get a dedicated floccus folder, unfortunately, since preexisting bookmarks are indeed a bit of a pickle.

**Comment by filippomicheletti** [comment]
@marcelklehr I updated nextcloud to the last (stable) version (12.04) and removed the bookmarks app substituting it with the last version got from git (even if I haven't been able to find the version number there I've seen from the apps manager it should be the 0.10.1) but the folder naming problem still remains. All the folders I create or copy from my browser bookmarks are synced by floccus and named as "__floccus-path:foldername/" .
Have I done something wrong?

**Comment by marcelklehr** [comment]
As I said: "The floccus-path tags are intentional, since it's currently the only way to retain folder information." ;) I hope everything else works as expected :)

**Comment by marcelklehr** [comment]
As there are now efforts to add an alternative backend to floccus (see https://github.com/marcelklehr/floccus/issues/86) I'm closing this, for now. Thanks for your input, everyone! :)
