### ISSUE TITLE
Purged bookmarks in FF

### ISSUE THREAD

**Issue by enoch85** [marcelklehr/floccus#425]
**Describe the bug**
I just noticed like 20 of my ~300 bookmarks are gone!

**To Reproduce**
1. Use the bookmarks app in Firefox as usual and sync it with Nextcloud

**Expected behavior**
Bookmars shouldn't be purgedif a sync fails.

**Desktop (please complete the following information):**
 - OS: Ubuntu Budgie 18.04
 - Browser Firefox
 - Browser Version  70.0.1 
 - Floccus version: 3.5.3
 - Floccus sync method: Webdav I think

**Server (please complete the following information):**
 - OS:Ubuntu 18.04
 - Nextcloud version: 17.0.2 (maybe happened earlier, noticed it now)
 - Bookmarks app version: 2.3.4

**Debug log**
https://is.gd/PcrAdP

- [X] Debug log provided

**Additional context**
Just a question really, are deleted/purge bookmarks easy to get back?

**Comment by marcelklehr** [comment]
Hello @enoch85 
I'm sorry you ran into trouble with missing bookmarks.

> Just a question really, are deleted/purge bookmarks easy to get back?

With the webdav method, there is no way to get back deleted bookmarks. For the bookmarks app, a trash bin to recover bookmarks from is planned. If you are looking for the contents of the folder called "Github", you can still find them in the logs :tada:

**Comment by enoch85** [comment]
>  if you are looking for the contents of the folder called "Github", you can still find them in the logs

Thanks!

> a trash bin to recover bookmarks from is planned

That would have saved me this time. Would be nice to see in the near future, like tomorrow. :D

Also, it would be nice if you warned the user somehow on big sync changes before they happen - or fix this bug so that it never happens again.

Thanks for a great app!

**Comment by marcelklehr** [comment]
> That would have saved me this time.

If you are indeed using the webdav sync method, that wouldn't have saved you either. But using the bookmarks app sync method that would have saved you.

> Also, it would be nice if you warned the user somehow on big sync changes before they happen - or fix this bug so that it never happens again.

I will analyse you log further to find out what caused this exactly.

**Comment by 7usr7local** [comment]
I seemed to have that issue to. Hard to reproduce, so I cannot provide logs (yet).
However, when I ticked "Trigger sync from scratch" in the options, a lot of them seemed to have come back. Worth to know, I am syncing with two firefoxes on two different desktop systems at the same time - maybe there is some kind of race condition. Whether everything was restored or some are still missing I cannot say, as I have no second source to compare with. 
Anyway, @enoch85, trying that checkbox might be worth a try in your case too - and your experience with that might give @marcelklehr some clues on the issue itself.
(Doing a bookmark backup on the firefox side beforehand is hopefully needless to say ...)

**Comment by enoch85** [comment]
I've actually disabled Floccus after this happened.

I'm happy to test when a fix is released.

**Comment by marcelklehr** [comment]
@enoch85 v4.0.0-alpha.1 is available for testing, now :) see https://github.com/marcelklehr/floccus/issues/439

**Comment by marcelklehr** [comment]
I'm happy to announce that v4.0.0 has just been released, which should fix this. I'm closing this for now. Feel free to shout if this comes up again!
