### ISSUE TITLE
E018: Impossible de s'authentifier sur le serveur

### ISSUE THREAD

**Issue by raspifr** [marcelklehr/floccus#428]
**Describe the bug**
When I try to synchronize my bookmarks I receive this message (in french):
E018: Impossible de s'authentifier sur le serveur

The account is good (user/password used to connect on Nextcloud, I have only one account on it) and the URL (external URL, not internal) seems to be good (https://www.my_domain.fr:/remote.php/webdav/).

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Browser Version 71.0
 - Floccus version: 3.5.3
 - Floccus sync method: webdav

**Server (please complete the following information):**
 - OS: Synology
 - Nextcloud version: 17.0.2
 - Bookmarks app version: 2.3.4

**Comment by marcelklehr** [comment]
> https://www.my_domain.fr:/remote.php/webdav/

Is that extra colon in there a typo?

**Comment by marcelklehr** [comment]
Also, you could try creating an app password for floccus in nextcloud and use that, to see if your password might be causing trouble for some reason.

**Comment by raspifr** [comment]
Sorry, the URL is https://www.my_domain.fr:12345/remote.php/webdav/.

I used app password and now I have another error:
E019: Statut HTTP: 404 Requête GETen erreur. Vérifiez votre configuration serveur et votre journal

**Comment by marcelklehr** [comment]
Are you sure you are using the webdav sync method?

**Comment by raspifr** [comment]
If the URL used is good I think I use webdav sync method.
I use webdav on my Nextcloud for Calendar and Contacts without issue.

**Comment by marcelklehr** [comment]
Floccus offers multiple different sync methods, though, which don't necessarily work with webdav URLs. You need to have selected the webdav account type.

**Comment by raspifr** [comment]
OK but how I can select webdav account type? In Floccus configuration?

**Comment by marcelklehr** [comment]
When creating a new account, you'll be asked to choose an account type. The account type also shows up at the head of the account options.

**Comment by raspifr** [comment]
OK, perfect.
It's seems to be good. I have a file named "bookmarks.xbel".
Question: can it be possible to "restore" an old bookmarks if needed? I choosed "Always overwrite and revert local changes" because bookmarks will not be shared.

**Comment by marcelklehr** [comment]
"Always overwrite and revert local changes" will always revert changes you make in your browser. You will not be able to restore those changes unless you make a manual back up.

**Comment by raspifr** [comment]
Yes, it's what I want: keep only changes made in my browser. But with automatic synchonization if I loose an URL on my browser I won't find it on bookmarks on my Nextcloud after synchronization, if I understood.
So, perhaps the good way for me will be to synchronize manually "when I want" and to backup the file "bookmarks.xbel" 1 time per day.
Perhaps too that a new possibility given by Floccus to keep a history of the file "bookmarks.xbel" chosen by user (the last 10 or other). It's just an idea (I'm a backup expert).

**Comment by marcelklehr** [comment]
If you always want to keep the changes made on your own browser you can use "Always overwrite and revert server-side changes", but that's only really useful if the server-side is changed by other clients. If all you have is one client nothing will change on the server anyway.

Floccus is explicitly not concerned with backups. You could write a script that periodically backups bookmarks.xbel on your server (check out this link: https://www.qed42.com/blog/using-curl-commands-webdav), or wait until the bookmarks app has support for restoring deleted bookmarks and switch to the bookmarks app sync method once it does.
