### ISSUE TITLE
Syncing failed with E019: HTTP Status 500. Log says Integrity constraint violation: 1048 Column 'user_id' cannot be null

### ISSUE THREAD

**Issue by richardk2016** [marcelklehr/floccus#434]
**Describe the bug**
New installation. First sync does not complete. Shows error "Syncing failed with E019: HTTP Status 500. Anfrage vom Typ POST  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log"

**To Reproduce**
1. Install Bookmarks App on server
2. Install floccus on Chrome
3. Enter valid creds and click 'Sync now'

**Expected behavior**
Sync

**Desktop (please complete the following information):**
 - OS: Win 10 1909
 - Browser Chrome
 - Browser Version 79.0
 - Floccus version: 3.5.3??
 - Floccus sync method: Nextcloud legacy

**Server (please complete the following information):**
 - OS: Linux shared hosting
 - Nextcloud version: Owncloud 10.1.1
 - Bookmarks app version: 0.10.6

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
2020-01-14T10:41:53.395Z Starting sync process for account bXXX
2020-01-14T10:41:53.403Z Using normal strategy
2020-01-14T10:41:53.410Z Overriding title of built-in node 1 Lesezeichenleiste => Bookmarks Bar
2020-01-14T10:41:53.411Z Overriding title of built-in node 2 Weitere Lesezeichen => Other Bookmarks
2020-01-14T10:41:53.412Z Fetching bookmarks
2020-01-14T10:41:54.548Z Received bookmarks from server []
2020-01-14T10:41:54.604Z Filtered out the following duplicates before syncing [... parentId: 13 ]
2020-01-14T10:41:54.606Z (local)REMOVE 32
2020-01-14T10:41:54.606Z (local)REMOVE 44
2020-01-14T10:41:54.643Z COMPARE { localItem: 
     + #0[undefined] parentId: undefined, hash: undefined
       + #1[Bookmarks Bar] parentId: 0, hash: undefined
         - #11[G](https://www.google.de/) parentId: 1
		 
...[BOOKMARKS DELETED FOR PRIVACY]

           - #112[SharePoint look book](https://lookbook.microsoft.com/) parentId: 107,
  cacheItem: null,
  serverItem: undefined }
2020-01-14T10:44:11.509Z (nextcloud)CREATEFOLDER { parentId: '', title: 'Bookmarks Bar' } (noop)
2020-01-14T10:44:11.515Z COMPARE { localItem:   - #11[G](https://www.google.de/) parentId: 1,
  cacheItem: null,
  serverItem: null }
2020-01-14T10:44:11.518Z (nextcloud)CREATE     - #undefined[G](https://www.google.de/) parentId: /Bookmarks Bar
2020-01-14T10:44:11.520Z Fetching bookmarks to find existing bookmark
2020-01-14T10:44:11.879Z Syncing failed with E019: HTTP Status 500. Anfrage vom Typ POST  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log
2020-01-14T11:05:51.011Z Starting sync process for account bXXX
2020-01-14T11:05:51.022Z Using normal strategy
2020-01-14T11:05:51.035Z Overriding title of built-in node 1 Lesezeichenleiste => Bookmarks Bar
2020-01-14T11:05:51.036Z Overriding title of built-in node 2 Weitere Lesezeichen => Other Bookmarks
2020-01-14T11:05:51.037Z Fetching bookmarks
2020-01-14T11:05:51.371Z Received bookmarks from server []
2020-01-14T11:05:51.462Z COMPARE { localItem: 

...[BOOKMARKS DELETED FOR PRIVACY]

           - #112[SharePoint look book](https://lookbook.microsoft.com/) parentId: 107,
  cacheItem: null,
  serverItem: undefined }
2020-01-14T11:05:51.495Z (nextcloud)CREATEFOLDER { parentId: '', title: 'Bookmarks Bar' } (noop)
2020-01-14T11:05:51.500Z COMPARE { localItem:   - #11[G](https://www.google.de/) parentId: 1,
  cacheItem: null,
  serverItem: null }
2020-01-14T11:05:51.501Z (nextcloud)CREATE     - #undefined[G](https://www.google.de/) parentId: /Bookmarks Bar
2020-01-14T11:05:51.501Z Fetching bookmarks to find existing bookmark
2020-01-14T11:05:51.853Z Syncing failed with E019: HTTP Status 500. Anfrage vom Typ POST  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log

- [x] Debug log provided

**Additional context**
From owncloud.log:

{"reqId":"Xh2a8ZD5mI3eXXXXXX","level":3,"time":"2020-01-14T11:41:53+01:00","remoteAddr":"93.1.1.1","user":"bXXX","app":"index","method":"POST","url":"\/kXXX\/index.php\/apps\/bookmarks\/public\/rest\/v2\/bookmark","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\NotNullConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `xxx_bookmarks` (`url`, `title`, `user_id`, `public`, `added`, `lastmodified`, `description`) VALUES(?, ?, ?, ?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), ?)' with params [\\\"https:\\\\\\\/\\\\\\\/www.googleXXX\\\\\\\/\\\", \\\"G\\\", null, 0, \\\"\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `x...', Array)\\n#2 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `x...', Array, Array)\\n#3 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\\n#4 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/apps\\\/bookmarks\\\/controller\\\/lib\\\/bookmarks.php(536): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/apps\\\/bookmarks\\\/controller\\\/rest\\\/bookmarkcontroller.php(191): OCA\\\\Bookmarks\\\\Controller\\\\Lib\\\\Bookmarks->addBookmark(NULL, 'https:\\\/\\\/www.goo...', 'G', Array, '', false)\\n#7 [internal function]: OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController->newBookmark('https:\\\/\\\/www.goo...', Array, 'G', false, '')\\n#8 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): call_user_func_array(Array, Array)\\n#9 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController), 'newBookmark')\\n#10 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController), 'newBookmark')\\n#11 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('BookmarkControl...', 'newBookmark', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/bookmarks...')\\n#15 \\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/index.php(54): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/VXXX\\\/wXXX\\\/kXXX\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":112}"}

**Comment by marcelklehr** [comment]
Please note that you will need at least bookmarks app v0.11, which is only available for nextcloud, afaik.

**Comment by richardk2016** [comment]
@marcelklehr Owncloud is provided. No way to get Nextcloud. Any sync-bookmark-tool recommendation where no public cloud is involved and GDPR is met? I welcome any help. Browsers used include Chrome, Firefox, Edge, Edge Chromium, Chromium, Brave, Opera and Safari. Mac and Windows. Plus iOS and Android.

**Comment by marcelklehr** [comment]
Google might know more :)

**Comment by richardk2016** [comment]
Google is like Jon Snow - it knows nothing. In respect on this subject. So sad that so many users are left behind. Thank you anyway.
