### ISSUE TITLE
WebDAV: Folder to move into doesn't exist E009

### ISSUE THREAD

**Issue by TCB13** [marcelklehr/floccus#436]
Hi,

I'm having a problem with webdev sync. I believe it happened after version 3.5.3 but it can also be an update of my browser, not really sure. What else can I do?

**Floccus**: 3.5.3
**Browser**: Brave | 1.2.43 Chromium: 79.0.3945.130
**Error**: Folder to move into doesn't exist E009

Here is the webdav server working in Cyberduck and as you can see the folder is available and the xbel file is there:

![image](https://user-images.githubusercontent.com/6315832/73017487-d65fe480-3e17-11ea-821d-6f3069741d62.png)

My configuration:

![image](https://user-images.githubusercontent.com/6315832/73017448-c21be780-3e17-11ea-9282-bcdfaeb211e9.png)

Here some logs:

````
2020-01-23T19:30:54.463Z MOVEFOLDER { id: 59, newParentId: undefined }
2020-01-23T19:30:54.465Z MOVEFOLDER { id: 68, newParentId: undefined }
2020-01-23T19:30:54.465Z MOVEFOLDER { id: 72, newParentId: undefined }
2020-01-23T19:30:54.465Z MOVEFOLDER { id: 80, newParentId: undefined }
2020-01-23T19:30:54.466Z MOVEFOLDER { id: 85, newParentId: undefined }
2020-01-23T19:30:54.466Z MOVEFOLDER { id: 95, newParentId: undefined }
2020-01-23T19:30:54.466Z MOVEFOLDER { id: 98, newParentId: undefined }
2020-01-23T19:30:54.467Z MOVEFOLDER { id: 100, newParentId: undefined }
2020-01-23T19:30:54.467Z MOVEFOLDER { id: 107, newParentId: undefined }
2020-01-23T19:30:54.467Z MOVEFOLDER { id: 137, newParentId: undefined }
2020-01-23T19:30:54.469Z Syncing failed with E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
E009: Folder to move into doesn't exist
2020-01-23T19:30:54.472Z onSyncFail
2020-01-23T19:31:54.226Z Starting sync process for account floccus@127.0.0.1
2020-01-23T19:31:54.237Z onSyncStart: begin
````

**Comment by marcelklehr** [comment]
Hey @TCB13 

Have you recently moved folders out of the synced bookmarks folder?

**Comment by TCB13** [comment]
Hey @marcelklehr I think not. As you can see I'm syncing the root folder, so it should be impossible to move anything outside it.

**Comment by marcelklehr** [comment]
Oh, that's right.

**Comment by marcelklehr** [comment]
The problem might be parallel syncing then. :thinking:  Could you turn the speedup option off and try again?

**Comment by TCB13** [comment]
It is already disabled...

![image](https://user-images.githubusercontent.com/6315832/73025801-2777d480-3e28-11ea-9412-12b0ef9e8e9d.png)

**Comment by TCB13** [comment]
If the issue was somehow moving folders around what could I do to fix it?

**Comment by marcelklehr** [comment]
I've been able to replicate this with a test case and will publish a fix shortly.

**Comment by TCB13** [comment]
Thank you!

**Comment by marcelklehr** [comment]
This is turning out tougher than I thought, as fixing this requires significant changes to the syncing process. Currently, diffing and applying the changes is done in one go, but this creates issues when moving items into a folder that has not been created yet, so I'm separating them into two steps, now. (Just as an update :) )

**Comment by marcelklehr** [comment]
@TCB13 v4.0.0-alpha.1 is available for testing, now :) see #439

**Comment by TCB13** [comment]
Doesn't seem to happen with floccus v3.5.2. I download that version manually installed and it worked just fine. I believe whatever is causing this issue was some change after that particular version.

**Comment by marcelklehr** [comment]
v4.0.0 has been released and fixes this issue. :)
