### ISSUE TITLE
Help testing: v4.0.0-alpha.3

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#439]
Hello everyone,

in light of two recently reported bugs that demonstrated some deeper issues with the syncing algorithm (#425, #436). I have taken to refactoring the syncing process used by floccus. The preliminary fruits of this endeavor are ready to be tested as part of the v4.0.0-alpha.2 *pre*-release.

If you would like to help test this new generation of floccus,

1. make a backup of your bookmarks
2. download and install the respective extension file
3. take it for a spin

### Notes
Your previously configured accounts are currently not being migrated to the new version, yet. I will implement this for the final release, though. The legacy nextcloud sync backend is deprecated and no longer supported as it violates some invariants, which is hard to work around.

If you have any questions, remarks, and most importantly observations from testing the new version, please leave a comment *in this issue*. 

Cheers,
Marcel

**Comment by luixxiul** [comment]
Would you please provide what to test as a checklist so that we could notice what might be wrong?

**Comment by marcelklehr** [comment]
The main changes are in the sync algorithm, so moving things around etc. to provoke the algorithm would be great :)

**Comment by TCB13** [comment]
![image](https://user-images.githubusercontent.com/6315832/73610362-36038000-45ce-11ea-85e9-cb7656465ae1.png)

Not having much luck loading extensions to Brave here, I'll try to get around this.

**Comment by TCB13** [comment]
Loaded the extension unpacked to get around the warning. Now:

![image](https://user-images.githubusercontent.com/6315832/73610444-2fc1d380-45cf-11ea-99a8-08a5c84f65e2.png)

Do I need to delete my xbel file from previous version?

**Comment by TCB13** [comment]
^ deleted previous xbel, removed and added the account again, keeps giving me the same error.

**Comment by TCB13** [comment]
So, small update. The issue I reported at #436 doesn't seem to happen with floccus v3.5.2. I download that version manually from here , installed and it worked just fine. I believe whatever is causing this issue was some change after that particular version.

**Comment by Ornias1993** [comment]
Last version on firefox gave these warnings on Nextcloud-Folders (non-legacy) sync:

> E020: Could not parse server response. Is the bookmarks app installed on your server?
> JSON.parse: unexpected character at line 1 column 1 of the JSON data

No setting managed to get passed these errors.

Version 4.0.0-alpha.1 xpi, loaded into firefox dev (signing override) seems to be syncing just fine.

**Comment by marcelklehr** [comment]
@TCB13 Awesome! We have a new error message. That's progress. The bug that you ran into with v3.5.3 likely was in v3.5.2 as well, but may not have manifested in your situation (one of the changes was an [async control flow correction](https://github.com/marcelklehr/floccus/compare/v3.5.2...v3.5.3#diff-7a75bc5ccc8b66f72352e97eb5c8bdd5R164), which may have lead to you experiencing the race condition that was there all along).

**Comment by Ornias1993** [comment]
I'll correct myself:
It looked to run fine, but it doesn't.
It doesnt sync.
On firefox dev. it ends up being no debug log at-all
on firefox esr. it ended to up with a bunch of panics.

So we have 1 version (3.*) that either eats bookmarks  or doesn't work at all.
and 1 version (4.*) that doesn't work at all period.

It seems the QC is so far off that i'll look for other solutions.

**Comment by TCB13** [comment]
> So, small update. The issue I reported at #436 doesn't seem to happen with floccus v3.5.2. I download that version manually from here , installed and it worked just fine. I believe whatever is causing this issue was some change after that particular version.

Update: I noticed that floccus v3.5.2 is able to sync but my bookmarks got duplicated on the XBEL file. On the browser they are fine, no duplications. Newer versions seems to have fixed that issue but maybe they also added the syncing problem.

**Comment by marcelklehr** [comment]
@TCB13 Could you send me the log for the new error you're getting in v4.0.0-alpha.1?

**Comment by marcelklehr** [comment]
Nevermind, I've just successfully replicated this :muscle:

**Comment by marcelklehr** [comment]
@TCB13 v4.0.0-alpha.2 should have a fix for the new error.

**Comment by TCB13** [comment]
Here is what I'm getting with 4.0.0v2:

![image](https://user-images.githubusercontent.com/6315832/74421140-753e9600-4e44-11ea-9ba0-2033a0794f68.png)

**Comment by marcelklehr** [comment]
Could you send me the logs of this, please? :pray:

**Comment by TCB13** [comment]
I would but it kinda contains a dump of all my bookmarks and not much information except for this:
```` 
2020-02-13T17:48:29.666Z Bookmark unchanged
2020-02-13T17:48:29.668Z Syncing failed with a.moved is not a function
a.moved is not a function
a.moved is not a function
a.moved is not a function
````

**Comment by marcelklehr** [comment]
@TCB13 The logs are quite integral for me to trace what happened. To mitigate privacy concerns, however, you could anonymize the logs by replacing all instances of `[.*?]` with `[XXX]` and all instances of `(.*?)` with `(XXX)`. That should remove all sensitive information (please be sure check, though).

**Comment by marcelklehr** [comment]
@TCB13 Any possibility of a redacted debug log?

**Comment by TCB13** [comment]
Hey @marcelklehr I've been really busy and I'll get that for you soon. Anyway I've noticed that this mess might be caused by using browsers with different languages. I've noticed that I have duplicate bookmarks for the "other bookmarks" folder because in one of my computers that folder has another name (since the browser isn't in English). I'll try to sort this mess out soon.

**Comment by marcelklehr** [comment]
> I've been really busy and I'll get that for you soon. 
Awesome :)

> I've noticed that I have duplicate bookmarks for the "other bookmarks" folder because in one of my computers that folder has another name (since the browser isn't in English). I'll try to sort this mess out soon.

Mmh, there are measures in place to prevent this (i.e. by normalizing the names of the root folders), but those might fail if you're not using Chrome or Firefox.

**Comment by TCB13** [comment]
> normalizing the names of the root folders

Under Firefox I can't rename those folders. They just pick whatever language the browser is running and that's it.

**Comment by TCB13** [comment]
I'm using Brave and Firefox... should work fine in both I guess.

**Comment by TCB13** [comment]
@marcelklehr did you get my email?

**Comment by marcelklehr** [comment]
Thanks for sending the log! It looks like there's an inconsistent cache state that could be responsible. My recommendation would be to try

1. back up your bookmarks
2. Trigger a sync from scratch in the account settings (this might cause duplicates and other unwanted effects, if the versions on server and client differ a lot. Expect to either clean that up, or start with a clean slate on the server and do a sync from scratch then).

Hopefully this fixes the error.

**Comment by TCB13** [comment]
@marcelklehr I tried removing the server file, browser extension re-sync everything and eventually it always ends up in the issue I sent you. I really believe it was related to the folder mess caused by different browser languages and/or some issue with Brave.

Since I wasn't very happy with Brave, today I moved to Firefox in all my machines (running in English). I have installed v3.5.3 from the Firefox extras page and cleaned my bookmarks. So far everything seems to sync properly. I'll report back and/upgrade to 4.x if I notice any issues.

**Comment by marcelklehr** [comment]
> In a week I'll report back how my Firefox and v3.5.3 are behaving. After that (or if I get sync issues) I'll upgrade to 4.x and see how it goes.

Great. There are definitely bugs in v3 that are fixed in v4-alpha, though. As I was vexed by not being able to reproduce your error, I created a fuzz test that hits the sync algorithm with random mutations of the bookmarks tree and was able to tease out some more bugs, which are likely related to your error. Thus, say hello to [v4.0.0-alpha.3](http://github.com/marcelklehr/floccus/releases/tag/v4.0.0-alpha.3).

**Comment by TCB13** [comment]
> As I was vexed by not being able to reproduce your error,

I strongly believe it was related to the browser language. My desktop had everything in English and the laptop had the OS and Brave in Portuguese. I guess that's what messed up my bookmarks. 

Right now I'm running Firefox and the OS in English and everything is syncing properly so far.

**Comment by marcelklehr** [comment]
I have finally been able to purge all bugs I could find using fuzz testing and am happy to announce the release of v4

**Comment by Ornias1993** [comment]
@marcelklehr Whats currently the compatibility with Nextcloud?

**Comment by marcelklehr** [comment]
@Ornias1993 Nothing has changed on that front. These are all the combinations that are regularly tested: https://travis-ci.org/marcelklehr/floccus/builds/657290209

**Comment by TCB13** [comment]
So... Apparently my Firefox upgraded automatically to 4.0.1 and now I'm getting this:

>> It's not possible to move Places root folders.

**Comment by marcelklehr** [comment]
Ah, I see. v4.0.2 fixes this.

**Comment by sunjam** [comment]
Hi, Firefox automatically upgrade to 4.0.2 and now I'm seeing `Last synchronized: 3 minutes ago Warning! This legacy account type is deprecated and will soon be removed. Please switch to the new nextcloud sync method. Improved performance and accuracy await you.`

I'm unsure on what switching to the new sync engine means, but I'm happy to do so.  Just want to confirm how to stop using the deprecated method.  I've been running Floccus for a long time... only options I've filled out are url/user/pw/root directory for sync.

**Comment by TCB13** [comment]
> Ah, I see. v4.0.2 fixes this.

4.0.2 under Firefox seems to freeze when the sync starts. Tried to remove the account and added again, same result.

**Comment by marcelklehr** [comment]
@TCB13 Can you specify 'freeze'? As in unresponsive? What exactly freezes?

**Comment by TCB13** [comment]
@marcelklehr progress bar stuck at the beginning and no recent logs.

**Comment by TCB13** [comment]
@marcelklehr I notice that there was a lock file, I removed it and now it is working properly.

**Comment by marcelklehr** [comment]
Ah, I see. It would have notified you after a while, I think.
