### ISSUE TITLE
[Feature request] Backup settings

### ISSUE THREAD

**Issue by junpet** [marcelklehr/floccus#442]
A nice Backup and Import button, so we could export/import settings easily.

**Comment by marcelklehr** [comment]
This is a duplicate of #422 (Feel free to shout, if you feel that it isn't.)

**Comment by junpet** [comment]
Sorry for duplicating. I only searched for the term `setting`, not the `export` nor `import`. :(

**Comment by marcelklehr** [comment]
No harm done :)
