### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by dsiminiuk** [marcelklehr/floccus#446]
**Is your feature request related to a problem? Please describe.**
No backups exist I am aware of.

**Describe the solution you'd like**
If your bookmarks are lost for any reason there is no way to go back to a previous version. I would like the plugin to rename the existing file with a date/time stamp on the WebDAV share and save that last n (configurable) files.

**Describe alternatives you've considered**
If the existing file on the WebDAV share can be renamed and then deleted on a push operation, the deleted file would show up in the NextCloud recycle bin where it could be recovered. You could change the plugin to overwrite local, restore the file, rename it back, and sync. That would restore bookmarks from a catastrophic loss.

**Additional context**
Maybe this can be done already but I don't see how.

**Comment by leggewie** [comment]
I don't know, this sounds a bit like bloat and feature creep.  Proper Backup solutions are already out there.

If you are using NextCloud for the backend then you can already very easily restore any previous [version](https://docs.nextcloud.com/server/15/user_manual/files/version_control.html) in the web front-end.

**Comment by dsiminiuk** [comment]
Yup, I see the old/previous versions now.
