### ISSUE TITLE
High energy impact in Firefox

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#448]
Hi

I am using FF 72.0.2 on Debian against Nextcloud 17 Everything works except that the extension seems to have the highest energy impact according to the FF Task Manager (more-> Task Manager)  among the extensions I have. The thing is that this is the case when it is not syncing anything( I set it to every 3 hours). 

I disabled the extension and my laptop's fans are tamed. I am wondering if anyone debug this part of the extension (high usage when no sync is done) at all?

**Comment by marcelklehr** [comment]
Confirmed and fixed. The process that updates the status badge in regular intervals was responsible. Thanks for your feedback! :)

**Comment by gerroon** [comment]
Thanks, will you be relesing to the ad-on channel or do I need to use the github release to try it?

**Comment by marcelklehr** [comment]
It's not part of any release, yet. It will definitely be in the final 4.0.0 release, but finalization of that may still take some time, so I'll probably backport this to v3 soon-ish.

**Comment by weiwang11** [comment]
This still occurs on 4.3.0

Firefox uses around 20-25% of my cpu with floccus enabled. Without it is 1-5%.
