### ISSUE TITLE
Strategic thoughts on bookmark (and other) syncing

### ISSUE THREAD

**Issue by TRSx80** [marcelklehr/floccus#45]
Somehow I came across this project while looking for something else. I thought I would take a moment to respectfully offer my thoughts, as I have been trying to solve this very same problem for a number of years now.

If you back out and consider the problem of sync on a strategic level, at the end of the day it seems we are depending on others (Mozilla, Google, etc.) to do some things, in order to do what we want. I mean, just a quick look at the issues reported and readme here shows that we are waiting for Mozilla to support certain functionality on FF Mobile, and on and on. It has always been this way, and I suspect always will be. Because reasons. Look at even Mozilla now (as one of your striked-out, half joking comments indicated "pulled a Google" lol) but I have seen this same thing going on over and over since I first started playing with computers on a TRS-80 all those years ago (hence the moniker). And recent changes Mozilla have been making with FF (removing extensibility, trying to make it Chrome, etc.) are alarming to me and so I see no end in sight to this sort of behavior as it seems the nature of the beast that whenever some group achieves a certain size, market share, or whatever it always just seems to me to start going south and they forget what got them there and start doing stupid things. I'm sure there is some witty quote or name for this phenomenon, which now seems to me to be almost a universal law of nature, but it escapes me at the moment.

So a few years ago, I started thinking about this very same problem, namely: how can I remove my dependence on others as much as possible? What format would be universally syncable across platforms, devices, browsers, etc? And once I started thinking that way, I started thinking in terms of just writing my bookmarks in simple text / HTML. I keep these in a folder (called, Bookmarks) in a Mobile folder in NextCloud that is synced across all my devices. I can edit these files in a simple text editor from any platform, save the changes, and have them propagate to all my other devices. Yes it takes a few moments longer than being able to just click on something. But the tradeoff is universal freedom in what you want to include: notes, link title, description, structure (instead of folders you can just make different pages of cross linked HTML in whatever structure you prefer), etc., etc...

If you extend this philosophy to other areas, you end up using todo.txt and/or OrgMode or similar tools for your to do list, because those are also just text files, which can be edited from anywhere and synced. It's also easy to use existing tools like Diff should anything ever get out of sync somehow. And other text processing and scripting tools for advanced usage, for those so inclined and knowledgeable (currently beyond me, but it's there for later, or others to do). This is also following the Unix philosophy of sort of more granularity in tools. Text files are pretty much a universal format.

You also gain some basic knowledge in HTML. It's not hard to learn the basics at all, don't be afraid. :) Personally, I value skill development, however you do have to slow down a bit and be prepared to be a little more patient and invest a little time if you are going to reap the rewards. However, such is life. ;) If you are under the gun and need something RIGHT NOW, this way might not be for you, but consider coming back to it later when you have some time (I follow GTD, so I would tag it with "Someday/Maybe" ;) ).

After using plain HTML text files for a while, I eventually evolved into using a TiddlyWiki (after finding AndTidWiki for Android, which is crucial as half of my workflow, personally, is on mobile). This has the advantages of being slightly simpler to use and giving lots and lots more formatting and cross linking options, as well as keeping your bookmarks together with all your other notes, thoughts, etc. It's just a different way of thinking, but I read some info that supported this is supposed to be closer to the way the brain associates information (tagging, multiple different paths / links between various small bits of info, instead of a hierarchical tree structure). Anyway, in the old days they used to call this a Commonplace Book. Think like DaVinci's notebooks or something. Except now with tagging, cross links, searchable, etc...

At any rate, I did not make this post to offend anyone, discount their work, or necessarily dissuade them from pursuing this course of action. I just wanted to point out that at the end of the day you are putting yourself in a position where you are counting on others (Mozilla, Google, etc.) to a very large degree to be able to do what you want to do. And after banging my head against this very same wall for decades, I finally realized that perhaps a different course of action would work better for me. In fact I have gone fully Free Software and open protocol route and have never been happier but that's another story for another day. Anyone reading this may or may not agree, I just thought I would offer up my thoughts for whatever they are worth.

Merry Christmas everyone!

TRS-80

**Comment by dsiminiuk** [comment]
My goals are simpler than yours. I am trying to find a way to replace the functionality that X-Marks provides in Chrome and it's derivatives. I don't care about syncing to Android. I'd like the same sync X-Marks does but on my NextCloud server instead of theirs. Floccus is getting very close. The only thing I don't like about it so far is the need to have a separate root folder distinct from the browser's root bookmarks. I have no need to sync to multiple NC instances, just simple sync to one. It's an interesting project.

**Comment by marcelklehr** [comment]
@TRSx80 Thank you for your thoughtful comment! Regarding the phenomenon of projects or groups moveing into undesirable directions compared to those originally conceived, I think it is closely related to the notion of [simple maximizers](http://nxhx.org/maximizing/). I'm also very interested in ways to bring the unix philosophy back to modern day computer usage, I think it's very sad that we've lost it.
Inevitably, when creating software, one needs to decide the time frame of usefulness of the software. A sustainable long-term solution is probably not useful to everyone immediately, but has many advantages in the long run. My goal with this project is to scratch an itch, though. It's supposed to be an immediate (hah, the irony, considering the time that has passed since I've started this) solution to a closely confined problem. Still, I completely agree with you, the solution might not be what people actually *need* in contrast to what they want. :)

**Comment by marcelklehr** [comment]
I'm closing this, as I feel we've come closer to the described workflow with WebDAV syncing and the advances of chrome-based mobile browsers that are starting to implement web extension support :Tada:

**Comment by dsiminiuk** [comment]
The root folder works great!
I have usability issues.
It doesn't sync only the changes (adds, deletes, renames, moves) but rather syncs the entire library every time.
I also don't know if there are any automatic sync executions or if I must manually execute a sync each time. It seems manual but I am not certain.

**Comment by marcelklehr** [comment]
@dsiminiuk please open a new issue ;)
