### ISSUE TITLE
Bookmark Manager rearranging bookmarks causes problems syncing

### ISSUE THREAD

**Issue by jlbprof** [marcelklehr/floccus#453]
**Describe the bug**
I share bookmarks between my home machine and my work machine.   I use Brave a Chromium based browser.  I use WebDav.

I use the Bookmark Manager to rearrange and clean up my bookmarks from time to time and it causes all sorts of problems when trying to sync this out.

I also set Floccus to "Always overwrite and revert local changes", because I made the changes on the "other" computer.   Here I mean, I do not care what is locally, I just want what is on the webdav server to be here on this version of Chrome.

I get all sorts of errors and it seems to be because of it trying to rearrange the local bookmarks from the server bookmarks.

I have tried to debug this via the developer console, but I cannot find the offending data, it has been awhile since I looked at your code, but I was hoping to find a global variable that contains both what the local browser thinks the bookmarks are and what the webdav server thinks the bookmarks are and try to figure out how to repair this.

Attached find the current logs.

**To Reproduce**
Bring up the Bookmark Manager move bookmarks around, including deleting folders, and moving folders underneath other folders.

**Expected behavior**
It should do the one way sync without problems.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Back and forth between Windows 10 and MacOS (latest on both)
 - Browser Brave / Chromium, (Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit))
 - Floccus version: 3.5.3
 - Floccus sync method: Webdav on a cPanel account

**Server cPanel WebDav

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
Attached

- [ YES] Debug log provided on external site.

**Additional context**

I know you are about to release V4, so this may be moot.   But on the one way syncs it would seem to be better if you just deleted the local bookmarks and inserted all the downloaded ones.   Is that possible?

**Comment by marcelklehr** [comment]
> But on the one way syncs it would seem to be better if you just deleted the local bookmarks and inserted all the downloaded ones. Is that possible?

That would certainly be possible, albeit less efficient. Would you be amendable to trying out the v4 pre-release after doing a backup?

**Comment by jlbprof** [comment]
I will try again this evening.

**Comment by marcelklehr** [comment]
v4 has just been released with lots of fixes, most probably also one for this issue.
