### ISSUE TITLE
Issue with newParentFolder

### ISSUE THREAD

**Issue by cortopy** [marcelklehr/floccus#454]
**Describe the bug**
I've just started to get errors for one of my sync folders in Firefox (Chrome is ok). 

**To Reproduce**
In Firefox, I have the following sync jobs with a nextcloud account:

- From local "/Bookmarks Toolbar" to remote "/personal/Bookmarks Bar"
- From local "/Bookmarks Menu" to remote "/personal/Bookmarks Menu"

The second one runs without an issue but the first one keeps outputting these two errors in the logs:

```
2020-02-25T09:52:39.301Z (nextcloud-folders)MOVEFOLDER { id: '1905', parentId: undefined }
2020-02-25T09:52:39.432Z Syncing failed with newParentFolder is undefined
```

**Expected behavior**
All jobs sync ok

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser Firefox
 - Browser Version 73.0b11 
 - Floccus version: 3.5.3
 - Floccus sync method: nextcloud

**Server (please complete the following information):**
 - OS: Ubuntu
 - Nextcloud version: 18.0.1
 - Bookmarks app version: 2.3.4

**Comment by marcelklehr** [comment]
> Floccus sync method: nextcloud

This means you are using the legacy method which creates tags on the server. Is this correct?

In any case, I would like to persuade you to

a) switch from the legacy method to the one using folders, which fixes some syncing problems already
b) try out the v4 pre-release to see if this is fixed in the upcoming release (which I think it is). Also

**Comment by cortopy** [comment]
thanks @marcelklehr for looking into this! I'm already using the new api. Or at least I think so. When I go into the options of my sync jobs the title is "nextcloud-folders options". Isn't that the new method?

**Comment by marcelklehr** [comment]
@cortopy Yes, that's good. One less thing to worry about!

**Comment by cortopy** [comment]
but it's not working?

**Comment by marcelklehr** [comment]
> In any case, I would like to persuade you to
> [...]
> *b)* try out the v4 pre-release to see if this is fixed in the upcoming release (which I think it is), after doing a backup, of course!

**Comment by marcelklehr** [comment]
I'm happy to announce the release of v4.0.0 which should fix this issue as well. Thanks for being patient :) And please shout if this should come up again.
