### ISSUE TITLE
Account disappeared and can not be created again in Firefox running in private mode

### ISSUE THREAD

**Issue by bugariu** [marcelklehr/floccus#459]
OS: Kubuntu 18.04
Firefox: 73.0.1 (64-Bit)
Floccus: 4.0.2
Counterpart: Nextcloud 18.0.1
Last known working version: ca. one month ago? Not exactly sure...

Firefox is running here exclusively in private mode. The already existing account in floccus disappeared suddenly (noticed today). Unfortunately I can't say when it disappeared, since icon looks like always...
Creating a new account is possible but is not present any more when restarting Firefox.
Also all existing bookmarks seem to have been duplicated in the main bookmark folder. Dunno when this happened because I didn't scroll down the list for a very long time. ;-)

Please drop a note if more information needed.

**Comment by marcelklehr** [comment]
Oh no! That is an unintended side-effect of switching to indexedDB/localstorage for data storage.

> Also all existing bookmarks seem to have been duplicated in the main bookmark folder. Dunno when this happened because I didn't scroll down the list for a very long time. ;-)

That likely was some time last year. That bug should be fixed now, though.

**Comment by PeterPaul1234** [comment]
I have the same Problem with the actual Floccus and FF74 with Windows, Arch & Debian.
I can create a new account and use it, but after restarting FF the account disappeared.
I use FF in private mode with the option that it should clean personal data when closing it.

**Comment by Mohammed-Al-Haidary** [comment]
Hi,

I'm having the same issue as well. I have FF in permanent private mode and it clears private data when closing. My Floccus account dissappears right after restarting FF.
This seems to be a novel issue and I don't remember this happening before.

Floccus is a great software, please continue to work on it, we are with you!
Thank you in advance.

**Comment by marcelklehr** [comment]
Hey,
A quick fix for this is to disable permanent private mode :/
I'm uncertain what exactly the difference is between permanent private mode and manually configuring full privacy. Perhaps, a switch from permanent private mode to manually configured privacy settings will work here, without any privacy casualties?

**Comment by Mohammed-Al-Haidary** [comment]
Sure, that's an ok temporary fix.
It's best if Floccus is made to work in permanent private mode 🙏

**Comment by PeterPaul1234** [comment]
It works for me  but as Mohammed-Al-Haidary says it would be great to use permanent private mode in the future even if its not hat big of a difference compared to the self configuration.
THX for your fast help. 
Stay healthy!

**Comment by mlshapiro** [comment]
@marcelklehr  I will take a look to see if there is any information about using localForage in permanent private mode. Is the primary storage interface in https://github.com/marcelklehr/floccus/blob/develop/src/lib/AccountStorage.js ?

**Comment by marcelklehr** [comment]
@mlshapiro Great! Yes, that's it.

**Comment by mlshapiro** [comment]
@marcelklehr finally had a chance to take a look at this. It does look like switching to IndexedDB/localForage caused this issue (da085e030ddd152493d4976ad3631a41040e9f28, 5739a5ca79872d0188cc04fd381bffcc58192c77). Was there a reason for this change? I can create a PR to fix this issue, but it would again go back to using the extension storage.

**Comment by wohali** [comment]
Same problem, same issue. Looking forward to a fix!
