### ISSUE TITLE
v4.0.2 legacy account type is deprecated... please switch to the new nextcloud sync method

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#461]
Hi, Firefox automatically upgraded Floccus to 4.0.2 and now I'm seeing `Last synchronized: 3 minutes ago Warning! This legacy account type is deprecated and will soon be removed. Please switch to the new nextcloud sync method. Improved performance and accuracy await you.`

I'm unsure on what switching to the new sync engine still entails, but I'm happy to do so. Just want to confirm how to stop using the deprecated method. I've been running Floccus for a long time... only options I've filled out are url/user/pw/root directory for sync.

I checked through documentation and didn't see exact steps for transitioning to the new method.  Thanks for the major update!

**Comment by marcelklehr** [comment]
Hey @sunjam :wave: 

The steps for the migration are documented over here: https://github.com/marcelklehr/floccus#switching-from-tag-based-to-folder-based-syncing
