### ISSUE TITLE
Missing SeparationLines (Trennlinie) in Firefox

### ISSUE THREAD

**Issue by moosburger** [marcelklehr/floccus#462]
It is possible in firefox to add separationlines between bookmarks. Only one will be synced, the others deleted during sync. 
After sync following Error occurs
Invalid bookmark: {"title":"","type":1,"url":"data:","parentGuid":"fGggLm7UVyus"}
This means separator in one folder.

**Comment by marcelklehr** [comment]
Separation lines are not supported as of yet. see #186
