### ISSUE TITLE
Is anyone can tell me how to sync through onedrive?

### ISSUE THREAD

**Issue by wang123sd** [marcelklehr/floccus#465]
I want to use this addon to sync bookmarks through Onedrive, but failed many times in setting up the pannel, who can help me ?

**Comment by marcelklehr** [comment]
You will need to install https://github.com/TCB13/LoFloccus and then setup floccus to sync to it using XBEL over WebDAV. The LoFloccus folder should be in your OneDrive folder for it to be synced via one drive.
