### ISSUE TITLE
Nextcloud folder sync shoves bookmarks into cache folder instead of user folder

### ISSUE THREAD

**Issue by tphillip913** [marcelklehr/floccus#469]
When trying to use floccus to sync bookmarks to my local server's Nextcloud instance the individual bookmarks are always saved to nextcloud/appdata/cache and never to a folder in the logged in user's space including the root folder. There doesn't seem to be any errors in Nextcloud's logs and floccus isn't producing a debug log for some reason but floccus/nextcloud is determined to save all the bookmarks into the above directory.

Any suggestions on how to get floccus to spit out its debug log so I can have some idea where to look? And if you've seen this behavior before I'm all ears on who to resolve it. :)

1 - Install floccus in the latest Firefox 
2 - Set floccus to use Nextcloud Folders
2 - Give floccus proper user credentials
3 - Set the server folder to any folder including blank
4 - Check the "Trigger sync from scratch" box
5 - Do a full sync

A clear and concise description of what you expected to happen:
Every individual bookmark should be copied into the user's root Nextcloud folder

What actually happens is all the individual bookmarks are copied to nextcloud/appdata/bookmarks/cache folder

 - OS: Windows 10 Pro 1909 all patches
 - Browser Firefox 
 - Browser Version 74
 - Floccus version: 4.0.2
 - Floccus sync method: nextcloud folders

**Server**
 - OS: unRAID 6.8.3 
 - Nextcloud version: 18.0.2 provided as docker image from Linuxserver.io
 - Bookmarks app version: 2.3.4

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
I click on the debug log URL in Floccus and nothing happens

**Comment by marcelklehr** [comment]
This is a misunderstanding. The 'Nextcloud folders' adapter doesn't sync with your nextcloud files. It syncs with folders in the bookmarks app. The legacy adapter wasn't able to deal with folders and used tags. Hence the new adaper is called 'Nextcloud folders'. You can sync to the nextcloud file system via webdav, but then you'll have to select the "XBEL file in webdav share" option. I'll try to clear this up in the UI.
