### ISSUE TITLE
Nextcloud sync causes bookmarks to disappear and reapper in random order when merging

### ISSUE THREAD

**Issue by tphillip913** [marcelklehr/floccus#470]
**Describe the bug**
When using either Nextcloud Folders of WebDAV during the sync process you can watch in the Bookmark sidebar your bookmarks disappear and by the end of the sync process reappear in random order. Even subfolders have the bookmarks in random order.

So far I cannot tell if anything is being lost, but watching the process is disconcerting and the random sort order afterwords is annoying. The sort order seems to be different every time the sync runs.

**To Reproduce**
1 - Install the latest floccus and the latest Nextcloud (On a server with or without the Bookmarks addin, depending if you want to see it with Nextcloud folder sync or WebDAV)
2 - Set up floccus with the proper credentials and if necessary the proper WebDAV URL
3 - Select "Merge" on what type of sync you like
4 - Run the sync 

**Expected behavior**
Best case: I should see nothing at all but bookmarks appear or disappear if they've been added or deleted by another client syncing to the same Nextcloud account
Worst case: What I'm seeing now but with sort order preserved

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909 fully patched
 - Browser Firefox
 - Browser Version 74.0
 - Floccus version: 4.0.2
 - Floccus sync method: e.g. webdav,  and nextcloud folders

**Server (please complete the following information):**
 - OS: unRAID 6.8.3
 - Nextcloud version: 18.0.2
 - Bookmarks app version: 2.3.4

**Debug log**
None generated

**Additional context**
The sync does seem to work in both cases. I can find the XML file in the proper place when using WebDAV and I can see the bookmarks when looking at the Bookmarks in Nextcloud when using Nextcloud Folders.

The behavior and random sort order is perplexing to me.

**Comment by marcelklehr** [comment]
Thank you for providing feedback! I will look into this, soon.

**Comment by marcelklehr** [comment]
I've been able to replicate this and will publish a fix along with the next release.
