### ISSUE TITLE
Preserve time stamps for imported bookmarks

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#48]
When bulk importing bookmarks into floccus, by drag and dropping them into the firefox other bookmarks directory created by floccus extension, all creation dates are switched to the current time and date.  Any way to preserve the previous time stamps?

**Comment by marcelklehr** [comment]
Hey :)

are you talking about the timestamps on the bookmarks in the browser or the ones in nextcloud? The ones in the browser should not change, I believe, but the ones in nextcloud are inevitably created when you drop something into the floccus folder... :/

**Comment by marcelklehr** [comment]
Please disregard the above comment, and tell me which version of floccus you're using :D

**Comment by sunjam** [comment]
[I’m using version 1.3.3 from the Firefox Quantum app store.](https://addons.mozilla.org/en-US/firefox/addon/floccus/)

**Comment by marcelklehr** [comment]
How do you get the creation date of a bookmark in the firefox ui? Do you perhaps mean the modification date which becomes apparent in the "recently bookmarked" section of the bookmarks menu?

**Comment by marcelklehr** [comment]
@sunjam I'd gladly try to troubleshoot / fix this, if you'd answer my questions ;)

**Comment by sunjam** [comment]
Okay, you are correct on me seeing the modification date rather than the creation date.  That is confusion on my end as it is not something I normally view in a bookmark manager.  I would prefer to be able to hide the modification date column within the Bookmarks app.  Or, to automatically apply a hide-able tag with the date added to the bookmark as just yyyy-mm-dd.  I’m used to seeing the url location displayed as it was in Firefox 52.  Pardon the digression... Here is the old layout in “Firefox for Show all Bookmarks”:

Columns at the top - Name, Tags, Description, Url Location, Mod Date.
![912096a0-f879-46a6-881f-a9c6a186907a](https://user-images.githubusercontent.com/1787238/36612142-8afd8c4a-188a-11e8-9e04-2aae419c6b36.png)
You can re-organize columns by drag-n-drop
![7b575486-8e17-4876-ab2a-816d2b6bea6f](https://user-images.githubusercontent.com/1787238/36612642-0a8e33b4-188c-11e8-825c-c46489e2c822.png)
And hide / show various aspects of your bookmarks
![cd2d422a-e149-4053-882d-3efe5848cd00](https://user-images.githubusercontent.com/1787238/36613538-99544a64-188e-11e8-8f0c-10c624ebce9e.jpeg)
And sort how the bookmarks are displayed
![8fc485db-b7b1-4b58-afbb-eb3c3bee1826](https://user-images.githubusercontent.com/1787238/36613574-c1b1e142-188e-11e8-86a7-2b5b70d439e0.jpeg)
At the bottom of the app you have basic editing functions
![df1b44ca-292e-4c33-a608-081bfbc68b9d](https://user-images.githubusercontent.com/1787238/36612731-425101f0-188c-11e8-967e-5c1e8e4230a5.png)
And if you click “More” you see all available editing functions.
![0905d64c-9d43-4084-a3b3-1f44311e4322](https://user-images.githubusercontent.com/1787238/36612732-426c5cfc-188c-11e8-9173-7bb4dd69c41d.png)
Note how the visual spacing between bookmarks is very compact in that first image so you can browse very quickly, with an option to insert blank spaces “separators” as needed
![7eb2f672-d828-48fb-9dfd-099ee47bbdd7](https://user-images.githubusercontent.com/1787238/36613661-087ea4ca-188f-11e8-8bdc-ac066c839608.png)

**Comment by marcelklehr** [comment]
I can't do much about the way firefox displays bookmarks, sadly (unless you're talking about the nextcloud bookmarks app). I can tell you, however, that the upcoming version of floccus will not update bookmarks if they have not been changed, which should fix at least the incorrect modification timestamps. ;)

**Comment by sunjam** [comment]
I'm thinking about the layout and functionality of the Nextcloud Bookmarks
app as a whole.  Floccus is not the same thing, but I use them together
constantly... :)

**Comment by marcelklehr** [comment]
Ah, thanks for sharing your thoughts! You've probably already seen https://github.com/nextcloud/bookmarks/pull/424. It completely overhauls the ui of the bookmarks app on the server, removing the modification date from the UI in the process. Feel free to leave feedback over there, too. :) (the screenshots hopefully give an impression of how it feels, in case you don't want install and build it yourself)
