### ISSUE TITLE
Netcloud bookmarks

### ISSUE THREAD

**Issue by gfish69** [marcelklehr/floccus#483]
I cannot get floccus to sync with my Nextcloud. I have created a separate password for bookmarks under Nextcloud security. I assumed this was needed as I use TOTP. I installed bookmarks in Nextcloud and copied url to floccus. Thanks in advance for any help! see below for details:
error:
E019: HTTP status 404. Failed GET request. Check your server configuration and log.
url:
https://"mydomain"/apps/bookmarks/public/rest/v2/bookmark?folder=-1&format=rss&page=-1

**Comment by dbrand666** [comment]
I found your question while searching for the same problem. I was able to fix it by adding /cloud to the end of my server url, i.e.:
https://myserver.mydomain.mytld/cloud

**Comment by marcelklehr** [comment]
@gfish69 Sorry for the delay. You have pasted the RSS URL into the floccus options. That's the wrong URL. `https://"mydomain"/` is enough. Floccus will figure out the rest :)
