### ISSUE TITLE
Setup and usage of Desktop companion App LoFloccus for files in LAN-only

### ISSUE THREAD

**Issue by pstein** [marcelklehr/floccus#485]
I am interested in syncing my bookmarks with a file in local inhouse-LAN only.

As far as I read I need the companion desktop app LoFloccus. Is this Companion App working on both Win7 and Win10?

The description implies furthermore that I have to copy the resulting file  at first to the partner computer (e.g. Notebook) in order to sync it with remote browser on this remote computer.

What if I have a shared folder on ComputerA which is directly accessible from ComputerB (in inhouse-LAN)?

I guess no copy operation is necessary here. Correct?
Do I need the Desktop companion App at all in such a scenario?

I can imagine that Floccus could use a simple (*.json or text) file to read and write all bookmarks of the current browser. After process is finished the file lock is removed and therefore accessible from a second computer+browser for syncing.

Is this possible?

Thank you
Peter

**Comment by marcelklehr** [comment]
Hello Peter,

the reason for the companion app is that floccus cannot by itself access the file system. Thus the companion app creates a local server that floccus connects to and stores the data in the filesystem where you want them. You will need the companion app on every computer with floccus. How you get the data file to that computer is up to you. You could use dropbox, syncthing, or an inhouse LAN shared folder.

**Comment by TCB13** [comment]
@pstein check this out https://github.com/TCB13/LoFloccus the latest release implements your use case. Enjoy!
