### ISSUE TITLE
Syncing failed with r is undefined

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#487]
**Describe the bug**
Syncing fails with r is undefined Not sure what else I can say. This has been working fine for me without errors for quite sometime, I believe that some recent updates broke it or broke it partially.

**To Reproduce**
Set it up with NC 18
Install the addon on Firefox 74

**Expected behavior**
proper sync

**Desktop (please complete the following information):**
 - OS: Debian 
 - Browser Firefox 74
 - Floccus version: 4.0.4
 - Floccus sync method: Nexcloud

**Server (please complete the following information):**
 - OS: Debian
 - Nextcloud version: 18
 - Bookmarks app version: 2.3.4

```
2020-04-06T16:06:59.804Z Received initial folders from server [ { id: '10',
    title: 'Tabs',
    parent_folder: '5',
    children: [ [Object] ] },
  { id: '9', title: 'FOLDER', parent_folder: '5', children: [] } ]
2020-04-06T16:07:02.134Z Loading sparse tree as necessary
2020-04-06T16:07:02.315Z LOADCHILDREN     + #5[undefined] parentId: undefined, hash: XXXe45f8f3741719105dadd8d0d8dddc882d482a7e9d7d4bc79dbc379774cXXX
      + #5[Firefox] parentId: 5, hash: undefined
        + #10[Tabs] parentId: 5, hash: undefined
          + #11[[Folder Name]] parentId: 10, hash: undefined

        + #9[FOLDER] parentId: 5, hash: undefined

2020-04-06T16:07:04.722Z Syncing failed with r is undefined

```

**Comment by marcelklehr** [comment]
Can you confirm, whether this is fixed in the latest release?

**Comment by gerroon** [comment]
I actually readded my sync profile and the erro has gone, might be the fix or just readding. It is fixed as of now. Thanks
