### ISSUE TITLE
sync fails: TypeError: this.fromFolder is undefined

### ISSUE THREAD

**Issue by fermat2a** [marcelklehr/floccus#491]
**Describe the bug**
Syncing between my firefox and nextcloud worked quite good, but since adding a nex bookmark I get an error each time it tries to sync:

```
2020-04-09T10:15:20.835Z (nextcloud-folders)UPDATE     - #40;undefined[Openbooks. Rheinwerk-Bücher kostenlos online lesen. Ein Service des Rheinwerk Verlags](https://www.rheinwerk-verlag.de/openbook/?lid=anleser3&utm_source=mailing&utm_medium=email&utm_campaign=km.rw.brand.zeitfuerweiterbildung.openbooks.20.04&utm_content=brand&utm_term=zeitfuerweiterbildung.openbooks) parentId: undefined
2020-04-09T10:15:20.836Z Fetching single bookmark
2020-04-09T10:15:22.420Z { [Error: 1 errors] list: [ [TypeError: this.fromFolder is undefined] ] }
2020-04-09T10:15:22.421Z [TypeError: this.fromFolder is undefined]
2020-04-09T10:15:22.421Z Syncing failed with this.fromFolder is undefined
```

Full output is uploaded.

In firefox the link disappeared and it is also not available in Nextcloud. But the error comes with each try to sync.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 19.10
 - Browser firefox
 - Browser Version 75.0
 - Floccus version: 4.0.4 from 6th April 2020
 - Floccus sync method: nextcloud

**Server (please complete the following information):**
 - OS: Ubuntu Linux 19.10
 - Nextcloud version: 18.0.3
 - Bookmarks app version: 2.3.4

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [yes] Debug log provided

**Additional context**

**Comment by fermat2a** [comment]
Oh, I was wrong. The bookmark exist in firefox. I sync folder "private" in the Nextcloud app to to folfer "Nextcloud" in my bookmarks. I placed the link in a subfolder "Books" there. There are now 2 Subfolders with the name in Nextcloud, one of it only has the missing Bookmark inside.

On Nextcloud server I cannot see a second folder with same name and I cannot find the Bookmark there. But I can see it under "Resent Bookmarks".

I shifted the bookmark from the current Books Folder into the old Books Folder in Firefox and started a new sync. Now it succeeded and I can see the Bookmark in Nextcloud app also. So, my problem is solved. But I keep this ticket open, as there is still the bug, that for any reason floccus created this copy of the Folder it could not sync...

**Comment by marcelklehr** [comment]
Hello @fermat2a :wave: 
Thanks for your detailed feedback! I have been able to isolate and replicate the problem and have produced a fix. The problem was creating a new bookmark in a folder that has been deleted on the other end. :)

**Comment by fermat2a** [comment]
Hi floccus,

thanks.

Dp you have an idea why it was changed on the other end? I didn`t delete it and my bookmarks are chanded only by your plugin...

Bests

Sascha


10.04.2020 15:34:34 Marcel Klehr <notifications@github.com>:

**Comment by marcelklehr** [comment]
> Dp you have an idea why it was changed on the other end? I didn`t delete it and my bookmarks are chanded only by your plugin...

I suspect the following chain of events: Initially your Books folder seems to have resided in the root folder. Then you created a new Books folder somewhere deeper and moved the bookmarks there, removing the original books folder. On the other computer you added a new bookmark to the original Books folder. Sync and boom. -- The root problem being that floccus cannot track folders if you recreate them instead of moving them intact. This could also have happened because of native Firefox bookmarks sync, in case you don't have that disabled.

**Comment by fermat2a** [comment]
Hello,

I did not do so. My Folder Structure is same since about a year. I only syn one computer. But the last days I installed the Nextcloud bookmarks app. Tis one seems not to know about Folders. Do you think this could be root cause?

Bests

Sascha

10.04.2020 20:00:10 Marcel Klehr <notifications@github.com>:
