### ISSUE TITLE
Bookmark Duplication

### ISSUE THREAD

**Issue by rmanibus** [marcelklehr/floccus#493]
**Describe the bug**
I notice that after some time of running flocus on firefox 76 and nextcloud 18, a lot of folders are duplicated.
(200ko increase in firefox bookmark backup over an initial 800ko)

**Screenshots**

![image](https://user-images.githubusercontent.com/10419172/79112070-0dda8f00-7d7e-11ea-94c4-d405764144a3.png)

**Desktop (please complete the following information):**
Windows 10
Flocus 4.1.0 on firefox 76

Accelerated sync
Merge local and remote changes

**Server (please complete the following information):**
Server nextcloud 18.03
Bookmark app  2.3.4

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

**Comment by rmanibus** [comment]
![image](https://user-images.githubusercontent.com/10419172/79112283-7fb2d880-7d7e-11ea-9a6f-8adf3256fed7.png)

it seems to happen over the time: 6 april, + 300, 8 april + 300 again. (the last one is a restore to a previous point)

**Comment by marcelklehr** [comment]
This should be fixed with v4.1.0 (released yesterday). If it continues to happen, let me know.

**Comment by rmanibus** [comment]
thanks, I will retry a sync from zero !

**Comment by marcelklehr** [comment]
You will sadly have to sort out the duplicate folders yourself, though...

**Comment by rmanibus** [comment]
No worries, I have backups. I might have lost a few but it's not a big deal.

**Comment by rmanibus** [comment]
Seems stable for now, Thank you very much !
