### ISSUE TITLE
Brave Chromium: initial sync is "successful" but nothing is written

### ISSUE THREAD

**Issue by jdmallen** [marcelklehr/floccus#495]
**Describe the bug**
I use [Brave browser](https://brave.com/) and Nextcloud v14. I'm able to install and run this extension, but syncing "successfully" to my Nextcloud does not actually write any bookmarks to it.

**To Reproduce**
1. Install extension to Brave
2. Add legacy Nextcloud account
3. Sync

**Expected behavior**
It syncs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave 
 - Browser Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
 - Floccus version: 4.1.0
 - Floccus sync method: nextcloud legacy

**Server (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - Nextcloud version: 14
 - Bookmarks app version: 1.1.2

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
```
2020-04-15T11:05:12.422Z Starting sync process for account jdmallen@nextcloud.myserverdomain.com
2020-04-15T11:05:12.424Z Using normal strategy
2020-04-15T11:05:13.924Z Received initial folders from server []
2020-04-15T11:05:14.654Z Loading sparse tree as necessary
2020-04-15T11:05:14.655Z COMPARE { localItem: 
     + #1706[undefined] parentId: undefined, hash: 7fd8e0f003dc9ebca97c658f0a569e1758894f9c27166bdf34ee9c429572eda1
   ,
  cacheItem: 
     + #1706[undefined] parentId: undefined, hash: 7fd8e0f003dc9ebca97c658f0a569e1758894f9c27166bdf34ee9c429572eda1
   ,
  serverItem: 
     + #-1[undefined] parentId: undefined, hash: 7fd8e0f003dc9ebca97c658f0a569e1758894f9c27166bdf34ee9c429572eda1
    }
2020-04-15T11:05:14.655Z Skipping subtree
2020-04-15T11:05:14.672Z Successfully ended sync process for account jdmallen@nextcloud.myserverdomain.com
```

**Comment by marcelklehr** [comment]
Hey @jdmallen 

Two things: Why are you using the legacy sync method? With your setup you could safely be using the new method.

Secondly, did you select a folder to sync upon creating the account? If you didn't floccus will create a new empty one for you. It doesn't sync anything you don't tell it to sync. :)

**Comment by jdmallen** [comment]
Yeah, I totally misread the Local Folder section of Add Account. I assumed it was going to create a new folder on the _server_, but that's not the case. I chose Legacy because the normal one didn't do anything else. It works fine once I selected my actual bookmarks directory. Thanks!
