### ISSUE TITLE
folders

### ISSUE THREAD

**Issue by kewlfft** [marcelklehr/floccus#5]
is there a way to sync bookmark folders within the owncloud folder?

**Comment by marcelklehr** [comment]
Hi there!

The owncloud bookmarks app doesn't provide folders, afaik, so that's why I didn't implement that, yet. I know it's pretty shitty without folders and tags (firefox doesn't have tags, owncloud/nextcloud should, I think, might be worth implementing a conversion between tags and folders in fx) :/
Still for as-you-type suggestions it's quite useful, as it is.

**Comment by kewlfft** [comment]
all right this is understandable we are limited by owncloud here. This works pretty well but does not replace a full sync.

**Comment by pmorch** [comment]
Oh, no! My primary use case is to be able to sync the contents of the Bookmarks Toolbar. And so I can't use nextcloud for that, I presume.

**Comment by trueshanti** [comment]
maybe push the feature: https://github.com/nextcloud/bookmarks/issues/13#issuecomment-299255460

**Comment by marcelklehr** [comment]
One short term solution is to provide a floccus option to choose the folder you'd like to sync yourself, instead of having to use the built-in one.

The long term solution is definitely to push the feature, which shouldn't be too hard, knowing the database model of nextcloud/bookmarks. First up is making the REST API work, though, which is coming along reasonably well.

**Comment by brantje** [comment]
We could convert the folders structure to tags imo.
And still send the structure to the server for syncing reasons.

**Comment by marcelklehr** [comment]
@brantje How would you convert tags back to a fodler hierarchy? Converting folders to tags looses the hierarchy.

**Comment by copynpaste** [comment]
We could just create tags like `my/folder/structure`, but this would be ugly

**Comment by nodiscc** [comment]
Firefox _does_ support tags: https://support.mozilla.org/en-US/kb/categorizing-bookmarks-make-them-easy-to-find

**Comment by marcelklehr** [comment]
Not  all browsers support tags, though, and the goal is to be cross browser. Also, it's not ideal imo, to convert the user's carefully constructed folder hierarchy to tags and then dump the hierarchy, if this is what you're suggesting.

**Comment by MA3o** [comment]
If I get @danopz point right, he means that you can "hide" the folder structure in a tag that contains the full path, e.g. a tag named "path/to/some/subfolder/". That would fit into the tag-organization of the bookmarks app while still leaving the actual folder structure and hierarchy of all bookmarks reproducable. The browser extension would have to parse that tag and reconstruct the hierarchy out of it.

The downside is that this will flood your bookmarks-app with alot of tags that the user did not create on his own. This could impair the user experience quiet a bit, espacially when you have alot of subfolders and suddenly after installing floccus some 100s of new tags appear in the bookmark app.

An easy and cheap solution to this would be to add "hidden" tags to the bookmarks app. If the bookmarks app automatically ignores / hides all tags that start with, say, a dollar sign ($), a double underscore (__) or whatever abstract symbol combination that is usually not used by a normal user, we could just hide all the new tags created by the method above. That shouldn't be too hard to implement and keeps the bookmarks user experience where it is right now with minimal restrictions.

**Comment by marcelklehr** [comment]
Yeah, setting a tag for the whole path makes more sense. It's still a hack, though.

**Comment by MA3o** [comment]
There won't be a non-hack solution without changes in the bookmarks app, I guess. The Issue regarding folder support on their project seems more or less quiet the past weeks. Is it the plan to wait until the feature is added? 

One could ask the same question regarding other browserdata sync like history and open tabs. Are there any ideas about how to realize that? "Full" browser sync with nextcloud is a very desirable feature for me, and even though I have no clue about programming browser extensions, I could imagine to help with the PHP backend.

**Comment by danopz** [comment]
ref: nextcloud/bookmarks#13

**Comment by arminbw** [comment]
I like the idea of being able to choose the folder to be synced. I [made a little FF addon, which acts as a read-it-later-like depot for links](https://addons.mozilla.org/de/firefox/addon/pile-lightweight-bookmarking/). Used together with floccus it could work as a lightweight private alternative to Pocket/Instapaper/etc.

**Comment by e-alfred** [comment]
@arminbw Sounds like a good idea, quickly bookmarking things to read them later would give Nextcloud Bookmarks/Floccus a great additional use case.

**Comment by mikeziri** [comment]
@marcelklehr is the folder structure parsing from a tag (/path/to/bookmarks/) doable for you?
meaning:
from nextcloud/bookmarks api > browser: converting each bookmarks tag of a path to a tree structure in the browser
and from browser > nc/bookmarks api converting each bookmarks path to a tag path

**Comment by marcelklehr** [comment]
@mikeziri yep, that should be doable. And although it's a hack, it's probably the quickest way to achieve folder sync in the short term, as the bookmarks app is undergoing some general overhaul at the moment the duration of which is no easy to determine, even though it's also me who does the work :joy:. I'll release v1.3 soon-ish and will work on this afterwards, I think.

**Comment by mikeziri** [comment]
cool ! I cloned your repo and am already trying this on the pullBookmarks function on lib/adapters/Nextcloud.js . compiled with gulp and added the extension to chrome. it's a bit hardcoded as I don't know too much about this new ecmascript notation and chrome extensions apis. but will try to figure it out.

**Comment by marcelklehr** [comment]
Ok, so as pointed out in #27 I've implemented folder to tags sync in a separate branch, which I'll be refining after the release of v1.3.

**Comment by marcelklehr** [comment]
Fixed in version 2.0.0 :tada: :)
