### ISSUE TITLE
Similar Bookmarks in one and the same Folder gets lost and stucks the sync

### ISSUE THREAD

**Issue by LxGuru** [marcelklehr/floccus#505]
**Describe the bug**
If there are the two bookmarks http://foo and https://foo in the same folder, only the https://foo gets synced.
Every further sync gets stuck.

**To Reproduce**
1. Create in Firefox in an otherwise empty folder the two bookmarks http://foo and https://foo.
2. Trigger a first sync with "Trigger sync from scratch" checked to a Nextcloud Bookmark Server into an empty Sync-Folder.
3. See that the sync succeeds very fast but only the https://foo bookmark appears.
4. Trigger a second sync.
5. See that this sync never finishes.

**Expected behavior**
1. Both (http AND https) bookmarks should appear at Nextcloud.
2. The second (and further) sync should finish, perhaps with an error message (timeout?).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.1
 - Browser Firefox 68.7.0esr (64-bit) (Firefox for openSUSE Leap)
 - Browser Version 68.7.0esr
 - Floccus version: 4.1.0
 - Floccus sync method:  nextcloud folders

**Server (please complete the following information):**
 - OS: Ubuntu, 20.04 LTS (Focal Fossa)
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 2.3.4
 -- VM as shown here: ([https://www.hanssonit.se/nextcloud-vm/](https://www.hanssonit.se/nextcloud-vm/))

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the 
...
- [ ] Debug log provided: no

**Additional context**
It took many test to strip it down to the conditions described above.
Using this simple test conditions there should be no performance problem.
In my environment I used my own nexrcloud server. There http... and http... lead to different pages so assuming http... and https are equal in the result is definitively wrong.
_Where is the error, floccus, firefox or nextcloud/bookmarks?_

**Comment by marcelklehr** [comment]
Thank you for drilling this down to a set of simple reproduction instructions. Unfortunately I cannot reproduce it, however.

I've created a new folder to sync. Inside this folder I created a folder with `http://foo` and `https://foo`. Synced to an empty server this is successful, *both* bookmarks are synced, a second sync is successful as well. :/

**Comment by LxGuru** [comment]
I've retested with the same (incorrect) result.
Perhaps you are one level too deep.
I'll retest in a view days with my Windows Firefox box
Can it depend on windows or linux running floccus?

**Comment by LxGuru** [comment]
Did you really add too identical URLs where only the protocol is different?
Looking at df7e4ad above, I'm afraid you used two different URLs. (https://ur.l/ and http://ur2.l/)
Additionally your URLs end with a slash (/), mine didn't.

**Comment by marcelklehr** [comment]
Alright, I had abandoned my attempt to reproduce this programmatically and tried it in a real browser instead, but I'll happily go back to the test code so we're able to agree on how to reproduce.

**Comment by marcelklehr** [comment]
My current attempt doesn't reproduce it either:
-> PASSED : should handle duplicate URLs with different protocols (12.578s)

If you can read that code, can you check if I'm missing something? https://github.com/marcelklehr/floccus/pull/532/files

**Comment by marcelklehr** [comment]
Notable difference from your setup is only the firefox version from what I can tell. :thinking:

**Comment by LxGuru** [comment]
As I can see (I'm not experienced in JS), you tested correctly. BUT
- how did you test the real result at the nextcloud server?
- how did you do a second sync without any changes on/at the bookmarks in FF?

In MY test description, please see step 3)
   The sync runs with "All good", BUT the result at nextcloud isn't complete.
Please also do step 4) and 5) of MY test description.

This may bee somewhat academic but I fell into this trap and especially the second (never ending) sync made the handling troublesome.

**Comment by marcelklehr** [comment]
This is the first sync run: https://github.com/marcelklehr/floccus/pull/532/files#diff-9bcb6da8d4d78e0722ed775ff5b765b2R666-R668

And this is the second sync run: https://github.com/marcelklehr/floccus/pull/532/files#diff-9bcb6da8d4d78e0722ed775ff5b765b2R672-R673

> The sync runs with "All good", BUT the result at nextcloud isn't complete.

Does this happen everytime, or do I need to try multiple times until I get that?

**Comment by LxGuru** [comment]
I'm very sorry but I can't reproduce this error any more.
Two things I changed:
- I created a fresh user (at Win and at Linux)
- I accepted updates on all client and server machines.
Now I can reproduce the error only at an older version of Nextcloud which is not the one I mentioned in my original report.
I give up and apologize for your work you did.

**Comment by marcelklehr** [comment]
Awesome. One more bug down. Don't worry, all's fine :)
