### ISSUE TITLE
Exception: Argument passed must be of the type string, null given

### ISSUE THREAD

**Issue by autrui** [marcelklehr/floccus#508]
**Describe the bug**
After updating Bookmarks to version 3.0 my Nextcloud log tells me that every Floccus sync produces this error:

`Exception: Argument 2 passed to OCA\Bookmarks\Db\SharedFolderMapper::findByFolderAndUser() must be of the type string, null given, called in bookmarks/lib/Service/HashManager.php on line 136`

Since the error didn't occur with Bookmarks v2.3.4 I thought at first the error has to be caused by the NC Bookmarks app.
BUT the iOS App _nextBookmark_ produces no such errors.
If I'm wrong and the problem is exclusively caused by the new version of Bookmarks please let me know.

**To Reproduce**
Just update the NC bookmarks app to v3.0 final and sync your Firefox using Floccus.

**Expected behavior**
No error log entries.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 75.0
 - Floccus version: 4.1.0
 - Floccus sync method: Nextcloud Bookmarks (the first one)
        Path prefix for server folder was and is empty.

**Server (please complete the following information):**
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0 final

**Comment by marcelklehr** [comment]
It is indeed a bookmarks app bug. I will release a fix shortly.

**Comment by marcelklehr** [comment]
You can update the bookmarks app now :)

**Comment by autrui** [comment]
Thanks, I did. There's a new error message now using v3.0.2:
> Exception: Call to undefined method OCA\Bookmarks\Service\Authorizer::userId()

details [here](https://github.com/nextcloud/bookmarks/issues/994)
