### ISSUE TITLE
Add Floccus to Nextcloud app store

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#509]
[Now possible to add Floccus as a third party app in the Nextcloud store so people can more easily find it](https://github.com/nextcloud/appstore/issues/95#issuecomment-621959723).

![](https://user-images.githubusercontent.com/4741199/80734694-d440ac80-8b0f-11ea-9d61-2f8b02722e64.png)

**Comment by marcelklehr** [comment]
https://apps.nextcloud.com/apps/floccus :tada:
