### ISSUE TITLE
Looking for someone to maintain a Chrome WebStore entry

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#51]
So, I've never been fond of paying anything in order to distribute free software. Thus I haven't published floccus on the chrome webstore.

Apparently, though, somebody else has already published a version of floccus on the Chrome WebStore: https://chrome.google.com/webstore/detail/floccus-nextcloud-sync/behlkinclcpoiijckdfjmibdpnfocefg
However, it is outdated and doesn't seem to be maintained.

So, my question is: Does anyone already have a chrome webstore account and would take on the responsibility of publishing and updating an entry for floccus in there? Alternatively, you may also consider throwing money at me, if you really want to see this :)

**Comment by marcelklehr** [comment]
Update: Apparently the person who published floccus on the web store updated their entry. Richard, if you read this, I'd appreciate if you reached out to me, as I'd be happy to endorse your entry if we can reach some kind of agreement on how it is maintained :)

**Comment by e-alfred** [comment]
As I said, I could do that, but I don't think it makes sense if there are multiple offers of the same extension competing there as it just irritates users after all.

**Comment by marcelklehr** [comment]
Thanks to the generous donations of two anonymous users, I've got my own develop account now and have just published floccus on the chrome web store.

Official Floccus version in the chrome webstore: https://chrome.google.com/webstore/detail/floccus-nextcloud-sync/fnaicdffflnofjppbagibeoednhnbjhg
