### ISSUE TITLE
Please enable proper hiding of the icon in the extension toolbar

### ISSUE THREAD

**Issue by leggewie** [marcelklehr/floccus#510]
Thank you for Floccus.

It is really neat that it runs nicely in the background and does its job without any fiddling around.  As such, I don't think the extension needs to be in the extension toolbar.  I'd love to be able to save that screen real estate and instead configure the app via the extension page itself.

I hope I'm making myself clear on what my request is.  If not, please do not hesitate to ask.

![image](https://user-images.githubusercontent.com/2387015/80776528-e435ac00-8b62-11ea-8870-0fe5cedfcbf1.png)

**Comment by marcelklehr** [comment]
Hello @leggewie 
As far as I know, you can tug away extension icons in firefox, but not in chrome. There is no way for floccus to do this on its own, sadly.
