### ISSUE TITLE
Connection error - JSON parse

### ISSUE THREAD

**Issue by serioustk** [marcelklehr/floccus#52]
I just downloaded the Firefox extension, entered my cloud URL and user data and got an error! 
Mouse over the error showed: ```JSON.parse: unexpected character at line 1 column 1 of the JSON data```

Tested with floccus Firefox plugin 1.3.4, 1.3.3 and 1.3.2.

**Comment by marcelklehr** [comment]
Hey @serioustk 
Thanks for reaching out! Which version of nextcloud and nextcloud bookmarks is installed on the server?

**Comment by serioustk** [comment]
Hey @marcelklehr 
Thank you for your quick response!

> Which version of nextcloud and nextcloud bookmarks is installed on the server?

I was not aware that I also had to install the nextcloud extension and did not find this information in the Firefox addon description. So I was under the impression the needed folders will be created automatically.

I installed the bookmarks extension and everything works fine now, thank you for your help!
