### ISSUE TITLE
E018 after Bookmarks v3 update

### ISSUE THREAD

**Issue by BDeliers** [marcelklehr/floccus#520]
**Describe the bug**
Since I updated Nextcloud to 18.04, I cant' sync anymore. I have error E018 : unable to authenticate to the server.

**To Reproduce**
Configure bookmarks account with your Nextcloud 18.04 login and password, then click Synchronize

**Expected behavior**
It's supposed to sync but it doesn't and gives error E018

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu 20.04
 - Browser Firefox
 - Browser Version 75.0
 - Floccus version: 4.1.0
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Ubuntu 18.04LTS
 - Nextcloud version: 18.04
 - Bookmarks app version: 3.0.7

**Debug log**
2020-05-05T10:17:11.098Z Starting sync process for account user@www.server.com
2020-05-05T10:17:11.102Z Using normal strategy
2020-05-05T10:17:11.112Z Overriding title of built-in node unfiled_____ Autres marque-pages => Other Bookmarks
2020-05-05T10:17:12.542Z Fetching bookmarks
2020-05-05T10:17:13.939Z Syncing failed with E018: Impossible de s'authentifier sur le serveur

- [x ] Debug log provided

**Comment by vleeuwenmenno** [comment]
Same problem here using Brave (Chrome) E018: Couldn't authenticate with the server

**Comment by Omaha2002** [comment]
Can't sync anymore although different error message:

E019: HTTP status 400. Failed PATCH request. Check your server configuration and log.

**Comment by marcelklehr** [comment]
@Omaha2002 This is a different error and should be solved by updating the bookmarks app to the latest version. Otherwise, please open a new issue here.

**Comment by BDeliers** [comment]
Issue solved : problem was from Nextcloud. Bookmarks update to 3.0.11 makes it work again.
