### ISSUE TITLE
make available for pale moon browser

### ISSUE THREAD

**Issue by zsbolyoczki** [marcelklehr/floccus#523]
Pale Moon is a fork of Firefox and can run lot's of Firefox plugins.
It would be nice to have floccus as well.

**Comment by marcelklehr** [comment]
Hey @zsbolyoczki :)

I'm not sure what would be necessary for floccus to work on Pale moon. What's the current status here? Is it not installable from addons.mozilla.org? Does Pale moon have its own addon store? Or does floccus not work correctly? Does it throw errors?

**Comment by zsbolyoczki** [comment]
Hi,

Sorry for not wasn't clean enough. :)

I can't install floccus to pale moon from https://addons.mozilla.org/en-US/android/addon/floccus/" because it says "Only with Firefox - Get Firefox now".

Can you make the addon available as standalone file?

Thank you!

**Comment by marcelklehr** [comment]
I see. All builds are made available here on github: https://github.com/marcelklehr/floccus/releases

**Comment by Virgus** [comment]
Hello @marcelklehr, I've been testing floccus and it's great but I'd also like to be able to use it with Palemoon and SeaMonkey (and all the Mozilla forks that are still using the old legacy extensions format, like in add-ons used prior to Firefox version 57).
I'm not a programmer but I have some skills, I'd be happy to help to have a "floccus-build-v4.6.4-legacy.xpi" build.

In your opinion would it be theoretically doable or are there technical requirements that would make this impossible ?

**Comment by EchedeyLR** [comment]
@marcelklehr The main problem here is not simple availability, but that Pale Moon doesn't support Web Extensions and is not going to add support in a future (at least not in short or medium degree).

uBlock Origin solved that with the help of a Pale Moon developer and has a *legacy* version with support for Pale Moon.

**Comment by marcelklehr** [comment]
Hey @Virgus  and @EchedeyLR 

Sorry for the late reply. I understand now why floccus doesn't work on Pale Moon. It's a similar situation with Safari. In the foreseeable future I will not have time to work on extending floccus to work with legacy Mozilla addon APIs. I'm sorry.

**Comment by EchedeyLR** [comment]
My idea was just to clarify the real problem with that, don't worry.

Could you re-open the issue to see if someone is interested to pick it and solve it?
