### ISSUE TITLE
"Other favorites" are empty

### ISSUE THREAD

**Issue by Whissi** [marcelklehr/floccus#524]
**Describe the bug**
"Other favorites" are empty in Microsoft Edge.

**To Reproduce**
1. I set up Floccus in Mozilla Firefox (I added an "Nextcloud Bookmarks" account, set "Local folder" to "Root folder", set "Server folder" to "/test" and checked "Trigger sync from scratch" checkbox and manually forced the first sync).
2. I verified that my bookmark structure is shown correctly on server. I.e. I went to https://nextcloud.example.org/apps/bookmarks, clicked "test" folder and verified "Bookmarks Bar", "Bookmarks Menu", "Mobile Bookmarks" and "Other Bookmarks" folder (they were present and "Bookmarks Bar" and "Bookmarks Menu" contain all my bookmarks).
3. I opened Microsoft Edge and installed Floccus from Microsoft Extension Store.
4. I added the account the same way like I added the account in Firefox.
5. After initialize sync I see all the bookmarks from "Bookmarks Bar" as expected in "Favorites bar" but all the other bookmarks, i.e. content from "Bookmarks Menu" is missing.

**Expected behavior**
After reading https://github.com/marcelklehr/floccus#usage I would assume that this should work out of the box because of

> Syncing the root folder: If you want to sync all bookmarks in your browser you need to select the topmost untitled folder in the folder picker. (In case you're wondering: Syncing the root folder across browsers from different vendors is now possible out of the box, because the built-in folder names are now normalized).

Or do I still have to do the manual mapping from the paragraph below?

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser: Microsoft Edge
 - Browser Version: 83.0.478.28
 - Floccus version: 4.1.0
 - Floccus sync method: nextcloud folders

**Debug log**
I am not attaching debug log for now because it contains all my bookmarks. So yes, I see that it worked on boomarks from "Bookmarks Menu" folder. However, I don't see them.

If you really need this I'll try to reproduce with test data I can share.

**Comment by marcelklehr** [comment]
Hello @Whissi 
Thanks for your feedback. Microsoft Edge support is sort of experimental in that I cannot test it myself. It would be interesting to know what the root folders in Edge look like.

For this information please

* go to `edge://extensions`
* enable development mode in the bottom left corner
* and try to find a way to open the debugger for the floccus extension (Most likely something like `Inspect background page`).
* In the console tab of the debugger run the following code `(chrome.bookmarks.getTree(function(t) {console.log(t[0].children.map(f => ({id: f.id, title: f.title})))}))` and paste the output here.

**Comment by Whissi** [comment]
I just tried on Google Chrome 84.0.4143.7 and it's exactly the same which brings me back to my first question: Is documentation up to date and should using root folder across Firefox and Chrome just work or do I still need to use multiple accounts to set up manual mapping like written below the paragraph saying I could just use root folder sync?

```
> (chrome.bookmarks.getTree(function(t) {console.log(t[0].children.map(f => ({id: f.id, title: f.title})))}))
< undefined
(2) [{…}, {…}]
0: {id: "1", title: "Favorites bar"}
1: {id: "2", title: "Other favorites"}
length: 2
__proto__: Array(0)
```

**Comment by marcelklehr** [comment]
Using the root folder should just work, except with folders like the Bookmarks Menu from firefox, which of course doesn't exist in Chrome.

**Comment by Whissi** [comment]
OK, looks like I need to adjust my configuration: For years I used "Bookmarks Menu" as folder for my normal bookmarks. While Firefox proposes "Other bookmarks" by default, I always changed to "Bookmarks Menu" because that's the folder you will access when clicking the icon or use the menu ([ALT] -> Bookmarks).

To access "Other Bookmarks" you have to go one level deeper.

I moved my bookmarks from "Bookmarks Menu" to "Other bookmarks" and Edge/Chrome will now show these bookmarks. Let's see how this will work in practice. :)

Thank you for your response.
