### ISSUE TITLE
Performance / Syncing freezes browser UI

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#53]
There have been a number of reports from people who experienced this.

I'm going to investigate this and try to mitigate the problem. As a last option, floccus could wait with syncing until the browser is idle, so that the user hopefully won't notice.

**Comment by marcelklehr** [comment]
@SoftwareEngineer How many bookmarks do you have?

**Comment by SoftwareEngineer** [comment]
@marcelklehr I have about 300 bookmarks and 30 folders

**Comment by marcelklehr** [comment]
heh, I figured as much and tried it with 600 -- the JS heap of my browser peaked at 1.3GiB :tada:... Should be fixed on the develop branch, now.
