### ISSUE TITLE
Help needed: v4.2.0 beta

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#531]
Hello everyone,

it's time for a new release. The focus of my work has been the user experience this time: The code for the floccus UI has been largely untouched since v1.0 and it was never too beautiful to begin with. This is now in the past, however, as I've refactored the whole UI using vuetify and Vue.js under the hood to address many annoyances with the old UI.

![Untitled](https://user-images.githubusercontent.com/986878/82225043-ea7aa500-9924-11ea-9903-e4756803bd2b.png)

Please find the beta version for testing here: https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.4

### Chrome (separate testing installation)
* Download the build here: https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.4
* Create a new folder
* Unzip the zip file there
* In chrome go to `chrome://extensions/`
* Enable developer mode
* Click `Load unpacked extension` and select the folder you created

### Chrome (direct upgrade; might not always work)
* Download the crx build here: https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.4
* In chrome go to `chrome://extensions/`
* Drop the `.crx` file into the page to install

### Firefox (separate testing installation; cannot upgrade)
* Download the zip build here: https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.4
* Unzip the zip file in a new folder
* In firefox go to `about:debugging`
* Click `Load tempoprary addon` and select the manifest file in the folder you created

Cheers! :space_invader:

**Comment by DerDanilo** [comment]
Cool, just found this awesome tool. Will try to test the beta within the next weeks. Hope this timeframe is still of help.

**Comment by ggeorgg** [comment]
I just loaded the addon as temporary addon in firefox and started a sync with nextcloud server. It just worked with no issues. The UI looks nice by the way. 
Thanks for your work!
