### ISSUE TITLE
Allow sync to local flat file 

### ISSUE THREAD

**Issue by Friptick** [marcelklehr/floccus#538]
**Is your feature request related to a problem? Please describe.**
One big problem with this addon is that it harvests login credentials. Yes, the software is source-available. No, the developer almost certainly does not have nefarious purposes. But for something so sensitive as a personal Nextcloud installation, for example, this situation is really very sub-optimal. And unfortunately AFAIK Firefox does not offer addons a means of delegating the authentication to a site, as with OAuth, or to the browser itself.

A solution for this frequent problem is for the user to use a third-party sync tool like Syncthing, already trusted and installed locally. But Firefox keeps its data in an opaque database, which makes syncing a chore. 

**Describe the solution you'd like**
Offer a new option to keep bookmarks synced with a local flat file. In XBEL format, or JSON or whatever is best. The user can then take charge of syncing this file using other tools.  

**Describe alternatives you've considered**
Looked for an addon offering this functionality. Was surprised not to find any.

Thanks for considering.

**Comment by marcelklehr** [comment]
I understand the concern. This is already supported by using the companion desktop app [LoFloccus](https://github.com/TCB13/LoFloccus).
