### ISSUE TITLE
Fails to sync existing Firefox bookmarks to new nextcloud config

### ISSUE THREAD

**Issue by mjeveritt** [marcelklehr/floccus#541]
**Describe the bug**
Firefox add-on fails to sync existing bookmarks to a new nextcloud instance. I have copied my existing 'Bookmarks Toolbar' and 'Other bookmarks' folders into my new 'nextcloud <xyz>' folder, but Floccus refuses to sync these to the server (and no show up from the web interface). Debug log supplied which seems to indicate a problem with a parent hash?

**To Reproduce**
Steps to reproduce the behaviour:
1. Open floccus, configure new Nextcloud account, Save
2. Open Bookmarks manager/Library, click and drag to copy 'Bookmarks Toolbar' and 'Other Bookmarks' as children of 'Nextcloud Bookmarks' folder
3. Attempt to 'Sync'
4. Nothing happens.
4. Open debug log - see error

**Expected behaviour**
Existing bookmarks folders are replicated to the Nextcloud server, and are visible in the web interface as children of a new parent folder pertaining to this computer/setup.

**Screenshots**

**Desktop (please complete the following information):**
 - Gentoo Linux
 - Firefox 68.2.0esr (64-bit)
 - Floccus version: 4.1.0
 - Floccus sync method: NextCloud webdav

**Server (please complete the following information):**
 - OS: Hetzner StorageShare
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.13

**Debug log**
`Issue541-floccus-4.1.0-2020-05-31`

- [ X ] Debug log provided

**Comment by marcelklehr** [comment]
Hello @mjeveritt!
Can you verify that you have selected the correct folder in the floccus settings? The selected folder seems to be empty.

**Comment by mjeveritt** [comment]
![image](https://user-images.githubusercontent.com/11815838/83352818-3a566480-a346-11ea-89ce-0ed05ef2ba01.png)

**Comment by mjeveritt** [comment]
> Also, if you're using the webdav sync method, your bookmarks will _not_ turn up in the bookmarks app, but will be stored in an XBEL file on the server.

How does this work, and why does it need the Bookmarks applet, yet not implement browsing capability, that seems weird?!

**Comment by marcelklehr** [comment]
That's probably unclearly communcated in the README. Floccus either needs Nextcloud bookmarks to sync with nextcloud bookmarks, or it needs a webdav server, if you want to sync via webdav. WebDAV is not an alternative protocol to communicate with the bookmarks app. It's an alternative method to sync your bookmarks.

**Comment by mjeveritt** [comment]
Ah, completely my bad here .. I've conflated webdav With nextcloud bookmarks (not legacy) .. so forgive me for that confusion. So yeah, bookmarks should be all the way through. Clearly I need some more :coffee: coffee :-/

**Comment by marcelklehr** [comment]
ok. Regarding the actual problem, it seems that copy-pasting root folders in firefox, does weird things. Try copy-pasting the actual contents, or, better yet, sync the root folder directly.

**Comment by mjeveritt** [comment]
> ok. Regarding the actual problem, it seems that copy-pasting root folders in firefox, does weird things. Try copy-pasting the actual contents, or, better yet, sync the root folder directly.

Aha, that's what I was aiming to achieve from the get-go .. so what should one have put in the 'Local folders' then??

**Comment by mjeveritt** [comment]
Having this as a pre-set 'second' default option might be helpful for newbies like myself ;) the 'create new folder' idea isn't naturally intuitive ...

**Comment by mjeveritt** [comment]
Also, if you are unable to support copy/pasta folders, you probably want to error out cleanly somehow :wink: just sayin'
Thanks already for the pointers! :smile:

**Comment by marcelklehr** [comment]
Yeah, I've been thinking about this myself. I tend to feel like people should opt-in to which bookmarks they are syncing, as syncing can be potentially destructive if you don't know what you're doing, and/or don't have backups. I'll think about how best to handle this in the new UI.

> if you are unable to support copy/pasta folders

heh, this is the first time I'm hearing about this. Normal copy-pasta is supported, but I think nobody has tried to copy-paste the root folders, yet. :smile:

**Comment by mjeveritt** [comment]
> Yeah, I've been thinking about this myself. I tend to feel like people should opt-in to which bookmarks they are syncing, as syncing can be potentially destructive if you don't know what you're doing, and/or don't have backups. I'll think about how best to handle this in the new UI.
> 
Oh yeah, been bitten by that problem since I first started syncing devices years ago, so I get ya point.

~~Just to check, how do I specify the root 'All Bookmarks' folder .. does that just pop up in the selection box of the config dialogue ...~~
Found it all, and it looks all perfect now:
![screenshot-nextcloud-bookmarks-01](https://user-images.githubusercontent.com/11815838/83354475-d7b69600-a350-11ea-9333-5ed3a2deeb9a.png)

**Comment by mjeveritt** [comment]
One final comment/observation, ok two:-
* Can you rename 'Untitled Folder' to something like 'Root folder' or 'All bookmarks' in the Selection dialogue?
* I see you **need** the preceding '/' on the server folder name for it to work - surely it would make sense to prepend this in the software, or is there a use-case where this is undesirable/unwanted?

_I spotted that there is a comment about sharing the root folder in the config dialogue now!_

**Comment by mjeveritt** [comment]
>     * I see you **need** the preceding '/' on the server folder name for it to work - surely it would make sense to prepend this in the software, or is there a use-case where this is undesirable/unwanted?
> 
Aha, you do need absolute/relative paths for the situation you describe in the Options where you are doing the Reverse of what I am doing .. per-computer subfolders of a 'master' repository.
I actually see merit in this method, but somehow I need to invert my hierarchy .. or perhaps I don't if I start by only sync'ing one way at a time .............. :thinking:

**Comment by marcelklehr** [comment]
> Aha, you do need absolute/relative paths for the situation you describe in the Options where you are doing the Reverse of what I am doing .. per-computer subfolders of a 'master' repository.

mmmh, no. I think you were right the first time. The new UI has validation for these things ;)
