### ISSUE TITLE
Chromium manual installation does not work

### ISSUE THREAD

**Issue by gerroon** [marcelklehr/floccus#545]
**Describe the bug**
Chromium fails to unpacked extension

```
Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.
Could not load manifest.

```

**To Reproduce**
Download .crx
Unzip to a folder
Load  unpacked in Chrmiums's extension page

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium
 - Browser Version 84.0.4123.0 (Developer Build) (64-bit)
 - Floccus version: floccus-build-v4.2.0-beta.2

**Comment by marcelklehr** [comment]
Confirmed.

**Comment by marcelklehr** [comment]
See https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.3

**Comment by gerroon** [comment]
Thanks, installation works but the login settings are not saved if I just enter user/pass. it is only saved when I use the Nextcloud loginflow thing. However the issue is the currently logged in user might not be the one that will be used in Floccus.

thanks

**Comment by marcelklehr** [comment]
Aha. thanks for reporting this!

**Comment by marcelklehr** [comment]
https://github.com/marcelklehr/floccus/releases/tag/v4.2.0-beta.4 fixes this :)
