### ISSUE TITLE
Windowns does not display normally at 120 DPI and cannot see the right button or click the right button.

### ISSUE THREAD

**Issue by star2k** [marcelklehr/floccus#549]
Windowns does not display normally at 120 DPI and cannot see the right button or click the right button.
----------------------------------------------------
windowns在120 DPI下，显示不正常，无法看见右侧按钮，也无法进行右侧按钮点击。

<a href="https://sm.ms/image/zGAtcdUDq48yS7N" target="_blank"><img src="https://i.loli.net/2020/06/04/zGAtcdUDq48yS7N.png" ></a>

**Desktop (please complete the following information):**
 - OS: [windows 10 ltsc]
 - Browser [firefox]
 - Browser Version [77.0.1 ]
 

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

**Comment by marcelklehr** [comment]
This is an unsolved bug in firefox and has already been reported: #108

The intermediate solution is to not put floccus into the tuck-away menu (or whatever they call that :sweat_smile: )
