### ISSUE TITLE
This bookmark doesn't belong to the current account

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#55]
Firefox v52.6.0

log says ` SERVERCREATE undefined`  right before the error.

**Comment by marcelklehr** [comment]
Probably Firefox version related.

**Comment by bodograumann** [comment]
I don’t know anything about addon-development, but is there something I can do to help you debug the issue?

**Comment by marcelklehr** [comment]
I have only had this problem on Firefox with version 52, which suggests to me it's related to the firefox version. If you have the same error, could you provide your firefox version? If so, it would be interesting to know if updating firefox solves this.

**Comment by bodograumann** [comment]
I am using v52.6.0 as well and experiencing the problem there. In contrast, with Firefox 59.0.1 syncing to the same account works.

**Comment by marcelklehr** [comment]
Thanks for the info! Then, the firefox team has changed the bookmarks API behavior in between those versions :/ I'll update the requirements for floccus.

**Comment by bodograumann** [comment]
There is compatibility table on MDN:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks

It seems the only thing not supported on Firefox 52 is `BookmarkTreeNodeType` (`A String enum which describes whether a node in the tree is a bookmark, a folder, or a separator.`), but there is no support in chrome for this either.

Any other changes can probably be found on bugzilla. Unfortunately the site is currently unavailable...

**Comment by marcelklehr** [comment]
Thanks! I know about the MDN docs (life saver!), but unfortunately the mozilla people themselves were often unsure how the APIs should behave, having taken the API from the very rudimentary Chrome extension docs. That's why I'm guessing it took them some time to get the API close to the chrome one. I don't think supporting firefox v52 should be a big priority for me, though, as there's a new ESR release coming up this spring.
