### ISSUE TITLE
all accounts automatically enabled when floccus is updated

### ISSUE THREAD

**Issue by tessus** [marcelklehr/floccus#551]
**Describe the bug**
All accounts are automatically enabled when floccus is updated.

**To Reproduce**
1. disable all accounts in floccus
2. wait until the add-on is updated 
3. all accounts will be enabled

**Expected behavior**
The accounts should stay disabled.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Browser Version 77.0.1
 - Floccus version: 4.2.0.5
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Linux
 - Nextcloud version: 17.0.6
 - Bookmarks app version: 3.1.0

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
Nothing relevant in the log.

**Comment by marcelklehr** [comment]
With the latest update you should be able to permanently disable the accounts again.

**Comment by tessus** [comment]
Nope. They were all disabled. Then I updated to 4.2.1 and all of a sudden they were all enabled. This is an update issue only. It seems that the update sets all account to `enabled`.

**Comment by tessus** [comment]
Unless you mean this will only work for the next update. e.g. 4.2.2. Then I will have to wait to test it.

**Comment by tessus** [comment]
@marcelklehr this issue is not fixed. as soon as floccus is uodated all accounts are automatically enabled.
