### ISSUE TITLE
Bookmarks removed after sync

### ISSUE THREAD

**Issue by ajkain** [marcelklehr/floccus#552]
**Describe the bug**
I choose a local bookmarks folder in Floccus and when I sync, the file bookmarks.xbel is exactly created on the WebDAV server, but if I close and restart the browser, and then resync, the bookmarks in my local folder are removed.

**Desktop:**
 - OS: Kubuntu 18.04
 - Browser Chrome (native sync disabled)
 - Browser Version 83.0.4103.97
 - Floccus version: 4.1.0
 - Floccus sync method: WebDAV

**Server:**
 - OS: webdav.drivehq.com (commercial WebDAV server)

**Debug log**

- [ x ] Debug log provided

**Comment by marcelklehr** [comment]
Hello @ajkain 
I'm sorry for your troubles. I will try to troubleshoot with your help.

It seems that either the file is not where floccus thinks it is or it is empty. Can you verify the the XBEL file exists at `bookmarks/bookmarks.xbel` as well as the file's contents?

**Comment by ajkain** [comment]
The file is in `/bookmarks` folder on the webdav server and it's not empty.
I have uploaded it at your private url.
Thanks

**Comment by marcelklehr** [comment]
Does this only happen, when you close and restart the browser?

**Comment by marcelklehr** [comment]
What happens when you `curl -u "username:password" <yourserver>/bookmarks/bookmarks.xbel`?

**Comment by ajkain** [comment]
Yes when I close and restart Chrome.
I have uploaded the curl output.

**Comment by marcelklehr** [comment]
I have identified a possible cause for this. What's the http status code for this request: `curl -vv -u "username:password" <yourserver>/bookmarks/bookmarks.xbel`

**Comment by ajkain** [comment]
New upload, I hope you have identified the problem, thank you.

**Comment by marcelklehr** [comment]
It seems like your server deletes the file :thinking:

**Comment by marcelklehr** [comment]
@ajkain Can you verify this? Is this solved? Otherwise, you could also give me a test account on your server to do some debugging.

**Comment by ajkain** [comment]
The server didn't delete the file, anyway I gave up. Now I'm using another server (webdav.yandex.com) and it works like a charm. I hope it lasts.
