### ISSUE TITLE
Missing tag/release for 4.2.0.

### ISSUE THREAD

**Issue by nirvdrum** [marcelklehr/floccus#553]
**Describe the bug**

There currently is not a tag or release for the 4.2.0 release. The extensions has a "read release notes" link, which points to the [release](https://github.com/marcelklehr/floccus/releases/tag/v4.2.0) and shows a GitHub 404 page.

**Comment by marcelklehr** [comment]
Thanks for reporting! Fixed :)

**Comment by nirvdrum** [comment]
Thanks for the quick fix.
