### ISSUE TITLE
[4.2.0.5] FF Developer Edition 78: E027 error

### ISSUE THREAD

**Issue by elfacht** [marcelklehr/floccus#556]
**Describe the bug**
After changing the server WebDavURL (credentials kept the same) following error occures:

_E027: Der Synchronisierungsprozess wurde unterbrochen _

The debug link doesn't respond, opens nothing. After clicking on „activate“, the switch will return to deactivate status.

**To Reproduce**
1. Install version 4.2.0.5 on Firefox Developer Version
2. Change WebDavURL of existing account

**Expected behavior**
Browsers with prior versions still work fine with the same credentials. I'm running the extension on the regular Firefox and Chrome with the same versions.

**Screenshots**

![Screenshot 2020-06-05 um 10 59 20](https://user-images.githubusercontent.com/529443/83857946-0602ef80-a71c-11ea-9220-06ee2cee2fc1.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox Developer Version 
 - Browser Version: 78
 - Floccus version: 4.2.0.5
 - Floccus sync method: WebDav (Synology NAS)

**Debug log**
n/a

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Does it help to remove the account and recreate it?

**Comment by elfacht** [comment]
@marcelklehr The new version fixed that, but #554 still occurs.
