### ISSUE TITLE
Error "Cannot read property 'filter' of undefined"

### ISSUE THREAD

**Issue by capricorn72** [marcelklehr/floccus#559]
- Zorin OS, based on 18.04.1-Ubuntu
- Chromium Browser Version 83.0.4103.61
- Floccus Version 4.1.0
- Sync Target: nextCloud
- nextCloud: 18.0.5
- Bookmarks: 3.1.1
- Debuglog: 2020-06-08T06:44:21.846Z Syncing failed with Cannot read property 'filter' of undefined
- Tested "Neue Synchronisierung von Grund auf auslösen" - same error
- Disabled "Synchronisierung beschleunigen" - same error

**Comment by marcelklehr** [comment]
This is fixed in v4.2.x

**Comment by capricorn72** [comment]
Great. In Chrome Store, there is still V4.1.0. Will it be replaced soon?

**Comment by marcelklehr** [comment]
... but that still has not passed review in chrome, I realize. I expect that to happen within the next few days.

**Comment by marcelklehr** [comment]
Is out now.
