### ISSUE TITLE
Saving settings is inconsistent

### ISSUE THREAD

**Issue by Tank-Missile** [marcelklehr/floccus#561]
I've been having a few issues since the latest update (4.2.1), so I decided to do a fresh install of the extension on both my mobile and desktop browser. I also deleted all bookmarks off the servers I use. However, while I can create a new account, I noticed it does not save my settings in a consistent manner. For instance, if I set the Nextcloud URL, Username, and Password, and then click the save button, none of those settings will be saved. All of them will revert to their defaults after saving and closing the page. I did notice that if I only change the Nextcloud URL, it will save. Then changing my username and password work... though I noticed that workaround does not consistently work either. I noticed this issue occuring on both Kiwi Browser and Chromium.

**Comment by marcelklehr** [comment]
@Tank-Missile v4.2.3 attempts to mitigate this.

**Comment by Tank-Missile** [comment]
@marcelklehr Gave v4.2.3 a whirl, but the same issue is still happening.

**Comment by Tank-Missile** [comment]
@marcelklehr v4.2.4 appears to fix the issue. Thanks for the all the hard work!
