### ISSUE TITLE
New account setup renders first account as bob@example.org

### ISSUE THREAD

**Issue by dsiminiuk** [marcelklehr/floccus#565]
Installing for the first time v4.2.2

Click on the Floccus icon, click the PLUS sign to add an account
Enter your server name
Enter your user name
Click on the NC Flow button to authenticate via the browser.
Authenticate and close the browser tab
Set Server path
Set Local bookmarks path
Set Sync behavior to overwrite local (first time)
Set Dangerous tasks to First time sync

Click Save

Close the tab in the browser

Click on the Sync Now button

Experience the error below.

![Image 1](https://user-images.githubusercontent.com/5713547/84328808-a7d57280-ab48-11ea-9b5d-8bfef21faad7.jpg)

Windows 10 Pro
SRWare (Chromium) Version 81.0.4200.0
Floccus 4.2.2
Sync to NC Bookmarks
NC 18.0.6
Bookmarks 3.1.1

[X] Debug log provided: floccus-4.2.2-2020-06-10.log

This issue started with 4.2.0. If you add your account again it seems to be fine just the first attempt is messed up.

**Comment by Tank-Missile** [comment]
[Seems to be the same issue as mine.](https://github.com/marcelklehr/floccus/issues/561)

**Comment by r4taw2mg** [comment]
Same here floccus 4.2.2 LoFloccus 1.1.2 in Waterfox 2020.6

Works with old Floccus 3.5.1 in Waterfox Classic 2020.6 with same server.

**Comment by nunnsby** [comment]
Have the same issue. As described in #561 

Additional testing has also shown that on creating the second account (actual) account for me, even if I select the Root (/) as the Bookmarks location (folder mapping), it usually defaults to entering _/Bookmarks Bar/floccus (user@site.url)_ as the actual mapping. I then have to go and reset it to point to the Root (/). Maybe related to a default setting somewhere?

**Comment by dsiminiuk** [comment]
@marcelklehr 4.2.3 works much better! Easy addition of the account.

Thank you

**Comment by dsiminiuk** [comment]
Not so fast. On a different PC.
Removed v4.2.2
Installed 4.2.3
Setup account in the usual way.

![Image 1](https://user-images.githubusercontent.com/5713547/84444178-c9952f00-ac06-11ea-8aab-96bc30af5494.png)

If I click the gear icon none of the settings I just saved are there.

Another hint. If I set the configuration page as desired, click the SAVE button.
If I refresh the page, the values revert to the default bob@example.org.

**Comment by dsiminiuk** [comment]
I tried again and used the username password method of authentication to avoid the NC Flow method and it worked.

I have another PC I need to update and I'll try that first time and let you know what happens.

**Comment by dsiminiuk** [comment]
Adding with proper user/pass (not Flow) on the 2nd PC avoided this issue. lLl is good.
Will try on another laptop.

**Comment by zsbolyoczki** [comment]
The issue stil exists.
I have my own account and also bob which keeps generating sync warnings in the browser (Librewolf).
Is it possible to get rid of it somehow?

**Comment by marcelklehr** [comment]
It's possible to remove accounts in the account settings.

**Comment by marcelklehr** [comment]
@all-contributors Please add @dsiminiuk as a contributor for testing and ideas
