### ISSUE TITLE
Sync breaks with HTTP status 500

### ISSUE THREAD

**Issue by wols** [marcelklehr/floccus#567]
**Desktop**
 - OS: Gentoo Linux
 - Browser: Firefox
 - Browser Version: 77.0.1
 - Floccus version: 4.2.2
 - Floccus sync method: nextcloud folders

**Server**
 - OS: Gentoo Linux
 - Nextcloud version: 15.0.4
 - Bookmarks app version: 2.3.4

**Debug log**
```
# Bookmark
# URL
http://2014.kes.info/archiv/online/01-02-70-redundanz.htm

# Server
# Log
<CLIENT> - <USER> [11/Jun/2020:15:07:24 +0000] "GET /index.php/apps/bookmarks/public/rest/v2/bookmark?url=http%3A%2F%2F2014.kes.info%2Farchiv%2Fonline%2F01-02-|
70-redundanz.htm HTTP/1.1" 500 5334

# CLIENT
# floccus v4.2.2 debug log
2020-06-11T15:07:24.871Z { [Error: 1 errors] list: [ { [Error: 1 errors] list: [Object] } ] }
2020-06-11T15:07:24.872Z { [Error: 1 errors]
  list: [ [Error: E019: HTTP Status 500. Anfrage vom Typ GET  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log] ] }
2020-06-11T15:07:24.873Z [Error: E019: HTTP Status 500. Anfrage vom Typ GET  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log]
2020-06-11T15:07:24.873Z Syncing failed with E019: HTTP Status 500. Anfrage vom Typ GET  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log
```

**Additional context**
There is a basic problem with URL starting with digits or in the form IP (http://1.2.3.4/)?

**Comment by marcelklehr** [comment]
HTTP 500 Errors always indicate a server-side problem. Bookmarks app version 2.3.4 requires the gmp library, which is probably what fails in your environment. In any case, please check your nextcloud log.

**Comment by wols** [comment]
Sorry for late feedback:

- rebuild PGP with `gmp`
- update to nextcloud-16.0.1
...no more 'status 500'
now with...
- floccus-4.2.5

THX!
