### ISSUE TITLE
Option to exclude folders from sync

### ISSUE THREAD

**Issue by DerDanilo** [marcelklehr/floccus#576]
**Is your feature request related to a problem? Please describe.**
When syncing the root folder to my personal server it works all fine. But as soon as one also activates additional subfolders to be synced to different other servers it can become quiet messy when not taking care of selecting the right folder.

**Describe the solution you'd like**
- Allow to exclude certain folders from any sync by providing a list of strings manually
- Add an option to sync settings that excludes this folder automatically from any parental sync job

**Describe alternatives you've considered**
None currently, it's quiet messy. 

**Additional context**
Please write me if this is required.

**Comment by marcelklehr** [comment]
> Add an option to sync settings that excludes this folder automatically from any parental sync job

This used to be default, and I think I'll change this to be the default again. Still, I agree that an option would be good.

**Comment by DerDanilo** [comment]
The problem is also that the root folder sync will sync all bookmarks if none are excluded, which will then sync those bookmarks to within other browser who are not supposed to have "subfolder bookmarks" (addtional sync accounts).

**Comment by marcelklehr** [comment]
Fixed by reverting the original switch to include nested account by default. Will need to develop an option.
