### ISSUE TITLE
Error to sync! SOLVED

### ISSUE THREAD

**Issue by ibanmda** [marcelklehr/floccus#58]
Hi!

I have installed floccus 2.0 in Firefox and Chromium. Does connect to the server (Nextcloud 13.0.1) right! 
But the new bookmarks of chromium/firefox  not are in the subfolder. It is empty... 

What's the mistake?

Thanks

**Comment by marcelklehr** [comment]
Hey there :)
Thank you for reporting this! Let me confirm what you did and the status of floccus at the moment:
1. You have installed floccus and entered your nextcloud credentials, I assume. Did you do a fresh install of floccus or did you upgrade? Which version of the bookmarks app is installed on your nextcloud?
2. You clicked on 'Sync now' -- are there any bookmarks in your nextcloud already?
3. I assume you were expecting bookmarks to be created in your browser. Where did you expect those to appear? Did you set a specific folder or did you let floccus create one? If the latter, was the folder actually created?
4. Does the floccus UI show any errors? If so, hover over the error status to reveal the specific error message and post it here.
5. What happened on the server? Did anything change there?

We'll get to the bottom of this :)

**Comment by norlag** [comment]
same problem :/

**Comment by marcelklehr** [comment]
@norlag I'm sorry you ran into this problem. Would you perhaps be able to answer my above questions? :)

**Comment by norlag** [comment]
yes sorry.
1. fresh install on firefox, bookmarks version 0.11.0 on nextcloud
2. yes i already have bookmarks on my nextcloud
3. i was expecting to add a new bookmark on my personal bar
4. i only have a error message, no more information https://i.imgur.com/LxRC8p3.png
5. I changed nothing

**Comment by marcelklehr** [comment]
@norlag Thanks! :+1: :) Could you hover over the error status to reveal the specific error message and post it here?

**Comment by norlag** [comment]
lol i think its my fault https://i.imgur.com/qsrmA58.png

**Comment by marcelklehr** [comment]
mh. If you have not changed any settings, there shouldn't be any duplicates as it just copies your bookmarks from the server, which doesn't have duplicates by design. Could you check your floccus folder?

**Comment by norlag** [comment]
on the browser ?

**Comment by marcelklehr** [comment]
Yep, in your bookmarks.

**Comment by norlag** [comment]
the folder exists but it is empty, but i think its because i changed the folder to sync to the bookmarks toolbar.

**Comment by norlag** [comment]
I found a way to make it work : 
Options -> Reset -> Choose folder -> bookmarks toolbar
and then it works but only one time, i have to do it again to make it work

**Comment by marcelklehr** [comment]
Is the error again mentioning existing duplicates? Is there only one duplicate pair? Does floccus create those duplicates or have they been there before? What happens if you remove a duplicate?

**Comment by norlag** [comment]
Is the error again mentioning existing duplicates? yes
Is there only one duplicate pair? no
Does floccus create those duplicates or have they been there before? they where there before
What happens if you remove a duplicate? nothing, same problem with another bookmark

**Comment by marcelklehr** [comment]
Are those duplicates part of your bookmark organization scheme or just mistakes? The only short-term solution I can propose right now, is going through your bookmarks and sorting out duplicates.. :/

**Comment by marcelklehr** [comment]
@ibanmda Did you have the same issue?

**Comment by ibanmda** [comment]
Hey there! 

My problem was that the adress has not contained the symbol of "/" in the end of:

`http://localhost/nextcloud`

Sorry for the inconvenience! Solved! 

I have one more question! How I can set the folder default into Chromium? In my navigator I have not the 'options'  icon inside of the floccus config. In firefox i have not problems to do it.

Regards.

**Comment by marcelklehr** [comment]
No problem :) Glad it works now!
