### ISSUE TITLE
Sync does not work - Foldermapping

### ISSUE THREAD

**Issue by rkoehler2017** [marcelklehr/floccus#582]
I've a Mainbrowser Firefox
Installed floccus
This is the structure of my Favs
![grafik](https://user-images.githubusercontent.com/31540737/85506685-22929900-b5f1-11ea-940b-98ded07bbc4a.png)
This is floccers Foldermapping Structure
![grafik](https://user-images.githubusercontent.com/31540737/85506745-41912b00-b5f1-11ea-8fb1-d3cb13e8a9aa.png)
I'm choosing 
![grafik](https://user-images.githubusercontent.com/31540737/85506791-5241a100-b5f1-11ea-98d5-3ae51333664d.png)
then saving and starting Sync

In Edge i've deleted all Bookmarks, installed Floccus and start to sync
This is the Structure on Edge after the sync
![grafik](https://user-images.githubusercontent.com/31540737/85507772-2fb08780-b5f3-11ea-96da-52d6bbf2a53e.png)
The Root from FF has now the name Floccus and is placed unter FavoritesBar and not in the root
And the Favoritesbar was not synced

Next Try, on FF i choosed
![grafik](https://user-images.githubusercontent.com/31540737/85508082-ac436600-b5f3-11ea-9d7e-ea20fd540ee6.png)
Now only the Favoritesbar was correct synced
I found this in the log
2020-06-24T06:31:17.036Z We're not allowed to change any direct children of the absolute root folder. Skipping.

So should or must i create a new structure?
All my Browsers are portabel.

**Comment by rkoehler2017** [comment]
now i copied all Favs from LesezeichenMenü to Weitere Lesezeichen, not sync works with Edge Chromium, Brave
![grafik](https://user-images.githubusercontent.com/31540737/85510929-56bd8800-b5f8-11ea-93e2-c809f911755d.png)

Left Edge, right Brave
![grafik](https://user-images.githubusercontent.com/31540737/85511102-879dbd00-b5f8-11ea-9faf-5307f7cce807.png)

**Comment by marcelklehr** [comment]
Is this solved for you now?

> In Edge i've deleted all Bookmarks, installed Floccus and start to sync

You probably need to select the root folder in "Lokaler Ordner" in Edge as well.

**Comment by marcelklehr** [comment]
I assume this is solved. Feel free to shout here if it isn't.
