### ISSUE TITLE
bookmarks.xbel.lock - Web Dav - can not be deleted

### ISSUE THREAD

**Issue by rkoehler2017** [marcelklehr/floccus#584]
I have now distributed Floccus on several browsers and different PCs.
Since yesterday the file bookmarks.xbel.lock is locked and can't be deleted even with the WebDav frontend.
It would be nice if Floccus would notice this and report an error.
At the moment it looks like this
![grafik](https://user-images.githubusercontent.com/31540737/85651457-5f6d9700-b6a8-11ea-913c-ceea2ff32635.png)

Logfile:
2020-06-25T03:47:05.194Z https://sd2dav.1und1.de/sync/bookmarks.xbel.lock
2020-06-25T03:49:36.999Z https://sd2dav.1und1.de/sync/bookmarks.xbel.lock
2020-06-25T03:52:57.569Z https://sd2dav.1und1.de/sync/bookmarks.xbel.lock

**Comment by marcelklehr** [comment]
> Since yesterday the file bookmarks.xbel.lock is locked and can't be deleted even with the WebDav frontend.

This is weird.

> It would be nice if Floccus would notice this and report an error.

It should show an error after a little more than 1h of trying currently. It might make sense to crank that down to 30minutes

**Comment by marcelklehr** [comment]
Time-til-error is now reduced. Not being able to delete the file is likely the fault of 1un1.de
