### ISSUE TITLE
popup interface cropped

### ISSUE THREAD

**Issue by brainchild0** [marcelklehr/floccus#585]
# Issue

As shown in the screen capture, the content of the popup in the interface appears cropped, making part of the pane inaccessible.

No sequence of operations is required to reproduce in my browser.  The behavior reproduces whenever the popup is accessed through the mechanism given by the browser.

---

![Screenshot from 2020-06-28 03-14-25](https://user-images.githubusercontent.com/34869175/85940930-8a94f800-b8ed-11ea-81d0-e992252aa90c.png)

# Environment 
- **Operating system:** Linux Mint 20, Cinnamon 4.6.6
- **Browser:** Firefox 77.0.1
- **Sync target:** Nextcloud server
- **Version:** 4.2.5

**Comment by marcelklehr** [comment]
This is a known issue with firefox: #108
