### ISSUE TITLE
Floccus "Debug Logs" button does nothing

### ISSUE THREAD

**Issue by asabbagh** [marcelklehr/floccus#593]
**Describe the bug**
Clicking on the "Debug Logs" button does nothing. It does not show any debug logs.

**To Reproduce**
1. Click on 'Debug Logs'

**Expected behavior**
Debug logs are shown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Browser Version 78.0.1
 - Floccus version: 4.2.5
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Shared hosting, some flavour of Linux
 - Nextcloud version: 16.0.8
 - Bookmarks app version: 2.3.4

**Debug log**
Debug log button does nothing!

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Mh, that's weird. Maybe downloads are saved to the downloads folder for you automatically. Can you check that folder?

**Comment by asabbagh** [comment]
Could not find any debug logs in the download folder.

**Comment by cracket** [comment]
I have similar problem with floccus ver 4.3.0 running on FF 79 on Ubuntu Linux with WebDav account. After error with sync the UI shows status "Syncing" along with greyed out button "Cancel Sync".  "Debug Logs" button is blue and changes mouse cursor, so I assume it is active, but does not cause any action. 

Tried to enable about:debugging for floccus and read out console errors from "This Firefox" (sorry I'm not a js expert, so not sure if they are relevant) which I attach below:
```

Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). options.js:7:125206


UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:831
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:688


Uncaught (in promise) Error: An unexpected error occurred undefined
    dispatch moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:26
    (Async: promise callback)
    dispatch moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:26
    dispatch moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:26
    dispatch moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:20
    onGetLogs moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:20
    onGetLogs self-hosted:935
    Ut moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    a moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    Ut moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    $emit moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    click moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:20
    click self-hosted:935
    Ut moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    a moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    _wrapper moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    (Async: EventListener.handleEvent)
    ue moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    oi moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    _e moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    x moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    ln moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    _update moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    e moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    get moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    ma moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    mount moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    $mount moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    init moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    g moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    g moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    g moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    ln moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    _update moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    e moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    get moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    ma moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    mount moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    $mount moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    init moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
    m moz-extension://4fa3ce81-4f85-45d9-85c7-6e5bf28c8079/dist/js/options.js:7
```

I assume the button should work no matter if synchronization is in progress?

**Comment by asabbagh** [comment]
@cracket is right. It looks like the floccus extension is using the default content security policy (since it doesn't appear to set one in [manifest.json](https://github.com/marcelklehr/floccus/blob/develop/manifest.json)). The default CSP doesn't allow for `eval` to be used, [according to Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy). And that is what the error is complaining about, the line in options.js:

`buffer = eval('require(\'buffer\').Buffer')`

I don't know where options.js is in the repo... (is it created by webpack??)

**Comment by marcelklehr** [comment]
@asabbagh thanks for the research!

**Comment by marcelklehr** [comment]
> UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831

This seems suspicious. Perhaps the database is corrupt for some reason. Could you try reinstalling floccus?

**Comment by asabbagh** [comment]
I just tried uninstalling and reinstalling floccus.

Immediately after installing I clicked the Debug Logs button but nothing happened. I tried a sync, and it failed (server error 503). But now the Debug Logs button successfully downloaded a log file. A 2nd sync attempt, same failure and error, and the Debug Logs still works and gives a log file. 3rd attempt the sync succeeded, and the button still works too.

So yes it is possible that it was some sort of database corruption. It's not clear why the button did nothing the first time I clicked it before any syncs were completed, but perhaps that is intended behaviour.

**Comment by sixtyfive** [comment]
Hi @marcelklehr, trying to figure out the JSON parsing problem, I also noticed that the "Debug Logs" button does nothing. It's all good now since reinstalling Floccus solved _that_ problem, but if something like it ever happens again, it would surely be helpful to see debug logs and be able to post them here.

**Comment by marcelklehr** [comment]
@sixtyfive Oh, that's not good. Please open a new issue with your installation details, so I can reproduce.

**Comment by sixtyfive** [comment]
too late ... shouldn't have tried the reinstallation idea so quickly. if it ever happens again i'll investigate more! sorry, marcel!
