### ISSUE TITLE
Floccus sync should show progress indicator

### ISSUE THREAD

**Issue by asabbagh** [marcelklehr/floccus#594]
**Is your feature request related to a problem? Please describe.**
Since the Floccus sync is so slow, it would be nice if it displayed some sort of progress indicator, for example number of bookmarks synced / number of bookmarks remaining.

**Describe the solution you'd like**
A progress indicator of some sort.

**Describe alternatives you've considered**
Have not tried any alternatives.

**Comment by marcelklehr** [comment]
Floccus does have a progress indicator at the top of the card of the account being synced. Once the actual sync process has started it will turn into a progress bar.

**Comment by asabbagh** [comment]
If I'm not mistaken, what Floccus currently has is an indicator of ongoing sync activity, however it does not indicate the current progress of that sync (e.g. 50%, 60% etc.).
