### ISSUE TITLE
Exclude subfolders from sync

### ISSUE THREAD

**Issue by james-testified** [marcelklehr/floccus#597]
**Is your feature request related to a problem? Please describe.**
I'm using floccus to sync my bookmarks toolbar folder (Firefox 78.0.1), which contains several bookmarks and subfolders with additional bookmarks. I'd like to exclude some folders from the sync. In an earlier version of floccus, this could be achieved by adding additional accounts for each subfolder that should be excluded. However, the new version of floccus (v4.2.5) seems to ignore the additional accounts and always syncs all subfolders within the specified local folder.

**Describe the solution you'd like**
Provide an option (e.g. check box) in the account settings to exclude certain subfolders (and/or even individual bookmarks) from the sync.

Example:
Bookmarks toolbar (= specified as local folder in floccus account settings)
[X] Bookmark A
[X] Bookmark B
[  ] Folder A <-- this folder and all its bookmarks should be excluded
[  ] Folder A,  Bookmark C
[  ] Folder A,  Bookmark D
[X] Folder B 
[X] Folder B, Bookmark E
…

Just let me know if you need additional information. 
Thanks for the great app!

**Comment by marcelklehr** [comment]
In the upcomding version there will be an option for subfolder accounts to decide whether other accounts should ignore this folder or sync it as well.
