### ISSUE TITLE
Trying to remove a non-existing item from OrderTracker - moving subfolders around

### ISSUE THREAD

**Issue by maurerle** [marcelklehr/floccus#598]
**Describe the bug**
Sync failes. I have a folder which has another Folder in it and after I moved some links into a new top level folder and moved the new top level folder (Blogs) into another folder I get the error message

`Trying to remove a non-existing item from OrderTracker: bookmark:372;37 Trying to insert an already existing item into OrderTracker: bookmark:Cf-GTOvBQ6Rj Trying to insert an already existing item into OrderTracker: bookmark:uj7YJd4aKTde Trying to insert an already existing item into OrderTracker: bookmark:K1k5b_DDZQlj`

I already tried exporting the data from the bookmarks app and mak a fresh sync, which worked yesterday but today I get the error again. 

It worked fine for a long time, so thank you!
Will try to investigate further but maybe you know more about this problem

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 
 - Browser Version 78.0.2
 - Floccus version: 4.2.5
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: debian10
 - Nextcloud version: 18.0.6
 - Bookmarks app version: 3.2.4

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [x ] Debug log provided
floccus-4.2.5-2020-07-10-maurerle

**Additional context**

**Comment by maurerle** [comment]
I seems to me, that after throwing the error "trying to remove a non-existing item" the item which should be removed must not be removed again (as it is not there on the server). This would fix issuing the same exception on every sync.
But I didn't look into code.

**Comment by Tank-Missile** [comment]
I'm getting a slightly different message: ```Trying to insert an already existing item into OrderTracker: folder:64```
[Here's the debug log](https://github.com/marcelklehr/floccus/files/4915835/floccus-4.2.5-2020-07-14.log). I'm not sure if this is a different issue.

**Comment by marcelklehr** [comment]
I'm sorry for the delay on my part. I've been tracking this bug for a while and added this assertion in the last release in order to pin it down. Luckily, you found the error now and I can start reproducing and fixing it :tada:

**Comment by marcelklehr** [comment]
@Tank-Missile Please be aware that the floccus logs contain a large portion of your bookmarks data, and publishing them on github is likely not a good idea.
