### ISSUE TITLE
Make Floccus compatible with Owncloud

### ISSUE THREAD

**Issue by Chamomile11** [marcelklehr/floccus#617]
There are many folks out there who have to use Owncloud. It would be super nice if you could add Owncloud support in Floccus (given that Bookmarks app is also available). Thank you!

**Comment by marcelklehr** [comment]
tl;dr: the goal would be to attain feature parity with nextcloud bookmarks for oc bookmarks. I'm not available for that, but it's all open source -- be the change you want to see in the world :heart:
