### ISSUE TITLE
Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this!

### ISSUE THREAD

**Issue by phreaker0** [marcelklehr/floccus#62]
### Software versions

* Browser: Chromium Version 65.0.3325.181 (Offizieller Build) Built on Ubuntu , running on Ubuntu 18.04 (64-Bit)
* Nextcloud: v13.0.1
* Nextcloud Bookmarks app: v0.11.0
* Floccus: 2.0.1

### Steps to reproduce
1. Reseted sync
2. Enabled sync again
3. Deleted all entries in the folder (bookmark toolbar)
4. Copied all bookmarks from a backup folder to the bookmark toolbar folder (sync root)
5. sync failed with "Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this!: url=<censored>

### Expected outcome

sync completes successfully

### Actual outcome

In the debug log is a get request to "/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1" which returns one array element with the exact url from the error message

**Comment by marcelklehr** [comment]
Thanks for reporting this! This will be fixed in the next releaese (which should be soon).

**Comment by phreaker0** [comment]
just tested with 2.0.5 and everything is fine again, thx!

**Comment by pablohess** [comment]
I still have this problem:
url=https://fontawesome.com/v4.7.0/
