### ISSUE TITLE
Support syncing javascript bookmarks

### ISSUE THREAD

**Issue by SuperSandro2000** [marcelklehr/floccus#621]
**Is your feature request related to a problem? Please describe.**
I have some bookmarks which contain javascript and I like them to be synced, too.

**Describe the solution you'd like**
Sync bookmarks like ``javascript:(function(){var%20url%20=%20location.href;var%20otherWindow=window.open('about:blank','_blank');otherWindow.opener=null;otherWindow.location='https://freshrss.example.comi/?c=feed&a=add&url_rss='+encodeURIComponent(url);})();``

**Describe alternatives you've considered**
Syncing them manually.

**Additional context**

**Comment by marcelklehr** [comment]
This is only not supported with the nextcloud bookmarks app. There's an open feature request on that repo for this. If you'd like to dabble a little, I'd be happy to guide you through implementing this, but it's not a priority for me.

**Comment by SuperSandro2000** [comment]
Found the issue https://github.com/nextcloud/bookmarks/issues/832

I am not sure how much work this is and which parts need escaping and what not. I didn't really work on larger php projects yet.
