### ISSUE TITLE
Error E018

### ISSUE THREAD

**Issue by InfamousUser** [marcelklehr/floccus#628]
**Describe the bug**
Extension displays "Couldn't authenticate with the server" error after finishing bookmark sync.
 
`2020-08-08T18:02:26.007Z { [Error: 1 errors] list: [ { [Error: 1 errors] list: [Object] } ] }
2020-08-08T18:02:26.008Z { [Error: 1 errors] list: [ { [Error: 1 errors] list: [Object] } ] }
2020-08-08T18:02:26.008Z { [Error: 1 errors]
  list: [ [Error: E018: Couldn't authenticate with the server] ] }
2020-08-08T18:02:26.008Z [Error: E018: Couldn't authenticate with the server]
2020-08-08T18:02:26.009Z Syncing failed with E018: Couldn't authenticate with the server`

I've reinstalled Floccus, cleaned all bookmarks on the server, added the account to Floccus and triggered a fresh sync, it went to sync all bookmarks (I assume all got synced, maybe not) and then display the error a few minutes later.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Browser Version [e.g. 22]: 84
 - Floccus version: [e.g. 3.2.2] 4.2.6
 - Floccus sync method: [e.g. webdav, nextcloud legacy or nextcloud folders]: Nextcloud Bookmarks

**Server (please complete the following information):**
 - OS: [e.g. centOS 7] Ubuntu 18.04.4
 - Nextcloud version: [if applicable] 19.0.1
 - Bookmarks app version: [if applicable] 3.3.3

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

**Comment by marcelklehr** [comment]
Could you please fill out the template, specifically the software versions you are using?

**Comment by InfamousUser** [comment]
Apologies, filled.

**Comment by marcelklehr** [comment]
An news?

**Comment by InfamousUser** [comment]
Sorry, been busy with something else, will try to retest this soon.

**Comment by InfamousUser** [comment]
> If that doesn't help you can try checking the network requests:
> 
> #### Firefox
> * Go to `about:debugging`
> * click on `debug` button next to floccus entry
> * go to the network tab in the inspector tab
> * trigger a sync by clicking on `sync now` for the account of your choice.
> * check the failing network requests
> 
> #### Chrome
> * Go to `chrome://extensions`
> * enable `Developer mode`
> * click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
> * go to the network tab in the inspector window
> * trigger a sync by clicking on `sync now` for the account of your choice
> * check the failing network requests


Okay, that narrowed it down pretty quickly. It is a firewall blocking it due to the bookmark being a potentially unwanted content site, which is bound to happen to at least one of the bookmarks with thousands of them on the system. There's several of these.

What fascinates me is that, from what I undestand, the firewall managed to pick it up even though the browser wasn't actually accessing that site, but simply sending the URL as a data to another site. It presents a dialogue to continue at own risk, but it is not possible to see the dialogue since the exchange is completely internal, it's visible in that inspector window though. Looks like the sync will never complete due to the error too.

Can this transfer somehow be encapsulated to not trigger this? I don't want to remove all of them since not all are dangerous, but I also don't want to turn off protection, I want to be warned, but a bookmark transfer being blocked is ridiculous when I'm not even accessing the site, merely pointing to it.

**Comment by marcelklehr** [comment]
I'm glad we got it figured out :)

> Can this transfer somehow be encapsulated to not trigger this?

I think handling this is outside the scope of this extension. I recommend to either remove the bookmarks, switch to a different "firewall" or turn it off.
