### ISSUE TITLE
pathSegment is undefined - Which one? What to do now?

### ISSUE THREAD

**Issue by Dubidubiduu** [marcelklehr/floccus#63]
### Software versions

* Browser: 
* Nextcloud: 13.0.1
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.1 (Firefox 59.0.2 - 64bit)

### Steps to reproduce

1. Created a new bookmark with tag "Test"
2. Floccus got in hiccup and gave me an pathSegment is undefined message

### Expected outcome
1. floccus should tell me the exact problem, i.e. what bookmark is making problems

### Actual outcome
1. pathSegment is undefined message, now i know what this means, but i prefer a hint to tags and the bookmark
2. I still don´t know what to do, deleted the tag, still got this message
...

**Comment by marcelklehr** [comment]
Thanks for reporting this!
This is most likely due to a floccus tag without a leading `>` or something similar.
