### ISSUE TITLE
bookmark remote file not changed

### ISSUE THREAD

**Issue by zecritter** [marcelklehr/floccus#650]
bookmark file was not changed on remote WebDAV server since 2020-08-24

It not changed even in case 
- synchronization strategy is "Always overwrite and revert remote changes"
- "Trigger Sync from Scratch" is enabled

in ALL cases floccus report sync success, debug file contains no errors and end with
2020-08-... onSyncComplete
2020-08-... Successfully ended sync process for account ...

 - OS: ArchLinux, rolling, up to date
 - Browser: Chromium
 - Browser Version: 85.0.4183.83 (Official Build) Arch Linux (64-bit)
 - Floccus version: 4.0.3
 - Floccus sync method: webdav

WebDAV server URL: https://webdav.4shared.com

**Comment by zecritter** [comment]
Sorry, typo:  Floccus version: **4.3.0**

**Comment by marcelklehr** [comment]
Can you check the account settings if the correct local folder is selected?

**Comment by zecritter** [comment]
Yes, local folder is correct. Actually I start investigate, because some new bookmarks in my browser was lost. May be i'll create new empty profile in chromium, install and configure the only extension - floccus, do some simple operations with bookmarks and log my actions. If something went wrong, I'll report here with floccus debug file.

**Comment by wxy4th** [comment]
I have the same problem. The bookmarks of 360 in my desktop and chrome in my laptop all changed, and floccus in the two browsers all synced, yet the bookmarks are still different. I never changed the account setting. It used to be OK.

**Comment by marcelklehr** [comment]
Can you try again with the latest version (v4.4.x)?

**Comment by marcelklehr** [comment]
It is likely that this is resolved with v4.5.0, I've been able to reproduce and fix a similar issue (see #824) :)
