### ISSUE TITLE
Does floccus bypass my nextcloud 2FA setup?

### ISSUE THREAD

**Issue by aelisya** [marcelklehr/floccus#658]
hello i have seen that floccus have successfully logged himself to my Nexcloud, my question is how does it do that
since there is passwordless and 2fa enabled on my servers.

Does that mean the bookmarks app (so the API for floccus) bypass totally my security in two step ? (i understand technical language i just want to understand the security mechanism for this connection))

**Comment by marcelklehr** [comment]
Hello @aelisya 
By signing in once to setup floccus (possibly with 2fa) , a token ("app password" in nextcloud speak) is created for floccus, which it uses to connect to your nextcloud. You can review and revoke all your app passwords in your personal settings in nextcloud.

I hope this clears things up.
