### ISSUE TITLE
Initial "Add Account" does not work

### ISSUE THREAD

**Issue by spachner** [marcelklehr/floccus#66]
First installed floccus. After clicking "Add Acount" nothing happens.

### Software versions
MacOS 10.11.6

* Browser: Firefox 
* Nextcloud: 59.0.2
* Nextcloud Bookmarks app: 
* Floccus: 2.0.2

### Steps to reproduce

1. Install add-in
2. click "Add Account"

### Expected outcome
A login window should apprear for nextcloud

### Actual outcome
Log contents:

TypeError: Argument 1 of StructuredCloneHolder.deserialize is not an object.[Weitere Informationen]  ExtensionChild.jsm:897:24
...

**Comment by marcelklehr** [comment]
Hey @spachner 
Thank you for reporting this. I don't have a Mac at hand but I cannot reproduce this with Fx v59.0.2 on Linux and a fresh profile. Have you had floccus installed in that profile before? The particular error you mentioned doesn't appear to be related to floccus, but rather to something internal to firefox. You added `...`, does that mean there is more in the log? Could you paste the complete log, with possibly sensitive information removed?

**Comment by spachner** [comment]
Hi,

thanks for you quick answer. No, when I click on „add account“ the only line which is added to browser's console is

TypeError: Argument 1 of StructuredCloneHolder.deserialize is not an object.[Weitere Informationen]  ExtensionChild.jsm:897:24

When I start the „run test“ everything seems to work and all has a checkmark. 

And this is weird now, after a numerous count of unsuccessful clicks on „add account“ and many restart of Firefox finally the login window appears.The console shows reproducible.

Invalid chrome URI: /

Hmm, you can close the ticket.

regards

spachner

**Comment by marcelklehr** [comment]
Mh. Glad it works now. Somebody else had the same problem recently, though, so I'm a bit concerned. Still you probably can't investigate further as the problem is gone, now, so I'll close, for now.

Happy syncing :)

**Comment by BenLangers** [comment]
I currently have the same issue on one specific device (Raspberry Pi with Firefox 68.8.0esr, floccus V4.2.0). I have seen the next screen with server options once, but nothing showed below the 'untitled folder' section. After that, I cannot continue after selecting Nextcloud Bookmarks, 'Add Account' does nothing anymore. If there is anything I can test, just let me know!
