### ISSUE TITLE
High CPU usage on Vivaldi/Chrome - Firefox OK

### ISSUE THREAD

**Issue by bhlevca** [marcelklehr/floccus#661]
**Describe the bug**
When synchronisation starts htop shows 2 threads with 100% CPU usage for Vivaldi browser on Linux
When I kill the floccus plugin, CPUcomes back to normal.

**To Reproduce**
1. Go to - Start sync
2. Start htop
3. watch CPU going up
4. disable the pluging from the plugin manager
5. CPU is going down

**Expected behavior**
Smallt CPU impact and not 100% on 2 threads that bring the browser to a crawl

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OpenSuse Tumbleweed
 - Browser : Vivaldi, Brave
 - Browser Version 

Vivaldi | 3.3.2022.45 (Stable channel) (64-bit)
-- | --
Revision | a05c4d885c8da0745ffe551e567e84b9fb6a5889
OS | Linux
JavaScript | V8 8.5.210.20
Flash | 32.0.0.207 /home/bogdan/.config/google-chrome/PepperFlash/32.0.0.207/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.106 Safari/537.36

 - Floccus version: 4.3.0

 - Floccus sync method: webdav

**Server (please complete the following information):**
 - OS: Opensuse tumbleweed latest
 - Nextcloud version: Nextcloud 19.0.1
 - Bookmarks app version: N/A using xbel

**Debug log**
N/A

- [ ] Debug log provided

**Additional context**
N/A

**Comment by johannes-schliephake** [comment]
I can confirm identical behavior but using Firefox.

**Desktop:**
 - OS: macOS
 - Browser: Firefox
 - Browser Version: 82.0.2
 - Floccus version: 4.4.4
 - Floccus sync method: Nextcloud folders

**Server:**
 - OS: Ubuntu
 - Nextcloud version: 19.0.2
 - Bookmarks app version: 3.3.4

**Comment by marcelklehr** [comment]
@johannes-schliephake I recommend updating the bookmarks app

**Comment by marcelklehr** [comment]
I cannot do much about performance specific to one browser sadly. I am constantly trying to improve performance, but some browsers will probably always be worse than others.

**Comment by bhlevca** [comment]
The problem seems to be only with the webdav file. The connection to the
nextcloud bookmark app although slower is way more reliable. I believe the
locking mechanism is  the weak piece

**Comment by bhlevca** [comment]
The problem seems to be only with the webdav file. The connection to the nextcloud bookmark app, although slower, is way more reliable and responsive . I believe the locking mechanism is  the weak piece, but also the problem with the duplication and order of the directories is gone.

**Comment by fazlerabbi37** [comment]
Facing this problem both in Google Chrome 91.0.4472 and Firefox 89.0.2 on Ubuntu 20.04 with Nextcloud 22.0.0 (docker) and Bookmark 4.2.2. In both case, the system becomes unusable during sync. In case of Firefox, the system was back to normal once the sync is done, but in Google Chrome the system goes in a zombie state.
