### ISSUE TITLE
Help test v4.4.0

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#666]
Hello there,

if you're up for a bit of testing in order to get an earlier glimpse at the new sync algorithm in the upcoming floccus version, you're welcome to follow the guide below :)

Changes:

- New sync algorithm:  Completely rewritten to fix various bugs that came up in recent months
- Internationalization: German, French, Portuguese and Russian are done already, if you'd like to help, head over to #266 

### Chrome (separate testing installation)
* Download the build here: https://github.com/marcelklehr/floccus/releases/tag/v4.4.0-rc1
* Create a new folder
* Unzip the zip file there
* In chrome go to `chrome://extensions/`
* Enable developer mode
* Click `Load unpacked extension` and select the folder you created

### Chrome (direct upgrade; might not always work)
* Download the crx build here: https://github.com/marcelklehr/floccus/releases/tag/v4.4.0-rc1
* In chrome go to `chrome://extensions/`
* Drop the `.crx` file into the page to install

### Firefox (separate testing installation; cannot upgrade)
* Download the zip build here: https://github.com/marcelklehr/floccus/releases/tag/v4.4.0-rc1
* Unzip the zip file in a new folder
* In firefox go to `about:debugging`
* Click `Load tempoprary addon` and select the manifest file in the folder you created

## Reporting bugs and feedback
Please add general feedback in the comments below. Specific errors or issues should go into a new issue along with the version you're using.

Cheers! :space_invader: 
Marcel

**Comment by trojkat** [comment]
@marcelklehr Many thanks for all your efforts!

I've just tested v4.4.0-RC1 on Firefox. Sadly I got the same issue as in #647 
```
2020-10-05T20:42:04.029Z { [Error: 1 errors]
  list: [ [Error: E022: Folder #948[self-hosted] supposedly contains non-existent bookmark 2155] ] }
2020-10-05T20:42:04.030Z [Error: E022: Folder #948[self-hosted] supposedly contains non-existent bookmark 2155]
2020-10-05T20:42:04.030Z Syncing failed with E022: Folder #948[self-hosted] supposedly contains non-existent bookmark 2155
2020-10-05T20:42:04.407Z onSyncFail
```

**Comment by marcelklehr** [comment]
@trojkat The database is probably still corrupt from an old floccus sync run. Can you try the old "delete all bookmarks" and reset cache in floccus, or alternatively `occ maintenance:repair`? After that this should not occur anymore.

**Comment by trojkat** [comment]
`occ maintenance:repair` did the trick, thanks!

**Comment by spicemint** [comment]
this fixed it for me :+1:

**Comment by gerroon** [comment]
I still have the same issue even after occ maintenance:repair

I am using FF 81 Linux x64, Floccus 4.4.2, NC 19, Bookmark 3.4.4
