### ISSUE TITLE
Invalid Bookmark: {„guid“:“unified___________“}

### ISSUE THREAD

**Issue by spachner** [marcelklehr/floccus#67]
### Software versions

* Browser: Firefox 59.0.2
* Nextcloud: 13 (ocloud)
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.2

### Steps to reproduce

1. Added credentials for my nextcloud server (ocloud) and a newly created app password for Floccus
2. Added new bookmarks and wait for successful sync

### Expected outcome

...There should be any activity at the nextcloud server and of cource no sync error in Floccus

### Actual outcome

2 sync error in Floccus: It shows "Error! 2 errors"

Console log
Response { type: "basic", url: "https://spachner.ocloud.de/index.ph…", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, bodyUsed: false }  background-script.js:7109:17
Response { type: "basic", url: "https://spachner.ocloud.de/index.ph…", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, bodyUsed: false }  background-script.js:7109:17
Response { type: "basic", url: "https://spachner.ocloud.de/index.ph…", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, bodyUsed: false }  background-script.js:7109:17
Response { type: "basic", url: "https://spachner.ocloud.de/index.ph…", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, bodyUsed: false }  background-script.js:7109:17
Fetching bookmarks Object { type: "nextcloud", url: "https://spachner.ocloud.de", username: "spachner", password: "*deleted*", localRoot: "root________", syncing: true, error: "2 errors" }  background-script.js:6851:17
Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope undefined
Received bookmarks from server Array [ Object, Object ]  background-script.js:6952:17
LOCALUPDATE Object { id: "1", localId: "8MEMXBCEuYIf", url: "https://kinexon.com/", title: "Kinexon – Precision Technologies", path: "/" }  background-script.js:5794:17
LOCALUPDATE Object { id: "2", localId: "c0YTOI0DTMqh", url: "https://www.google.de/intl/de/docs/…", title: "Google Docs", path: "/" }  background-script.js:5794:17
Successfully ended sync process for account spachner@https://spachner.ocloud.de  background-script.js:4654:17
Starting sync process for account spachner@https://spachner.ocloud.de  background-script.js:4606:17
The same URL is bookmarked twice locally: "https://www.google.de/intl/de/docs/about/"  background-script.js:4779:29
The same URL is bookmarked twice locally: "https://kinexon.com/"  background-script.js:4779:29
Syncing failed with Error: 2 errors
Stack-Trace:
MultiError@moz-extension://270e8b9e-923c-9c4b-ac5c-6605dc17eb57/dist/js/background-script.js:14:9
next/<@moz-extension://270e8b9e-923c-9c4b-ac5c-6605dc17eb57/dist/js/background-script.js:133:36
run@moz-extension://270e8b9e-923c-9c4b-ac5c-6605dc17eb57/dist/js/polyfill.js:4295:22
notify/<@moz-extension://270e8b9e-923c-9c4b-ac5c-6605dc17eb57/dist/js/polyfill.js:4308:30
flush@moz-extension://270e8b9e-923c-9c4b-ac5c-6605dc17eb57/dist/js/polyfill.js:1398:9
  background-script.js:4662:17
Unchecked lastError value: Error: Missing host permission for the tab  ExtensionCommon.jsm:425
Invalid chrome URI: /Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope undefined
Invalid chrome URI: /
Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope undefined
Invalid chrome URI: /
Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope undefined
Invalid chrome URI: /
Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope undefined
Invalid chrome URI: /
Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope undefined
Invalid chrome URI: /
Error: Promised response from onMessage listener at init@moz-extension://050e5af1-bc32-1c45-ba4e-4c3a97999023/dist/browser-core.js:24482:5 went out of scope

**Comment by marcelklehr** [comment]
Do you have Firefox Sync enabled?

**Comment by spachner** [comment]
No,  I don't.

Am 2. April 2018 4:50:21 nachm. schrieb Marcel Klehr 
<notifications@github.com>:
Do you have Firefox Sync enabled?

**Comment by spachner** [comment]
Hi,

things are getting weird. I tried on a second machine running the very same Firefox version. And: Everything seemed to work. Immediately Floccus said: „All good“ instead of the any error. I also saw bookmarks on the nextcloud. Promising.

Then I tried again on the problematic machine and stuck again with errors but now different ones. I attached a screenshot



The error insists. And changing the Sync folder does not work either anymore. I am able to select a folder as usual, but the entry remains *newly created*

hmm

regards

Stefan

**Comment by marcelklehr** [comment]
@spachner Mh. I can't see the screenshot -- attaching files via email doesn't seem to make them appear in the github comments :) (time for another feature request for the github team!)

**Comment by spachner** [comment]
Sorry, my fault:

There ist written:

X Error! 
Invalid Bookmark: {„guid“:“unified___________“}
Sync folder
*newly created*

Stefan

**Comment by marcelklehr** [comment]
Changing the sync folder should work in the latest version again.

According to [this changeset](https://hg.mozilla.org/releases/mozilla-beta/rev/03975fa2422ae2b9ebc0455e47cbdb708611a15f#l36.24), the error message means that a folder (specifically the "Unified bookmarks" folder doesn't exist, for some reason). You could try [creating a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and trying it there.

**Comment by spachner** [comment]
Hi,

thanks for your effort. The good news are that after installing the new version of floccus the bookmarks are synced to nextcloud! Great. 
The bad news are that there is still an error shown in the plug-in (something similar as before like  Invalid Bookmark: {„guid“:“menu“}" or similar. I cannot reproduce the error text, since after restarting of Firefox the plugin does not show up anymore. There is only as very small window shown so that nothing can be read.

Hmm

regards

Stefan

**Comment by spachner** [comment]
Hi again,

now I started Chrome (current version 65.0.3325.181) and tried to sync back the next could bookmarks. Got these errors:

✘ Error!OptionsSync now
Can't modify the root bookmark folders. Can't modify the root bookmark folders. Can't modify the root bookmark folders. Can't modify the root bookmark folders. Can't modify the root bookmark folders.

Stefan

**Comment by marcelklehr** [comment]
You appear to be trying to sync the root folder between two different browsers. This is not yet possible. See https://github.com/marcelklehr/floccus/issues/69

**Comment by thacid** [comment]
I join the conversation because i think my issue is related. I have somewhat the same error and the sync work:
Invalid bookmark:
{"guid":"mobile_____"}
In floccus option, choose folder, i have a folder "mobile". I don't find this folder in firefox bookmark.
It's a freshly created profile on Firefox 57.0b12 (64 bits), linux Fedora os. The nextcloud bookmark app is empty. So i think the problem is on firefox side.

**Comment by marcelklehr** [comment]
@thacid Which folder did you select to sync with floccus?

**Comment by spachner** [comment]
The root /

Am 7. April 2018 11:49:38 nachm. schrieb Marcel Klehr 
<notifications@github.com>:
@thacid Which folder did you select to sync with floccus?

**Comment by mmalisz** [comment]
@marcelklehr, I've got the same issue as @thacid since 2 or 3 days.
However, I don't have a folder named mobile.

- Firefox 59.0.2 (Linux, amd64),
- NextCloud 13.0.0,
- Bookmarks 0.11.0,
- Floccus 2.0.6 (not sure if the error began to be displayed after or before upgrading from 2.0.5),
- synced root folder (/).

**Comment by thacid** [comment]
@marcelklehr The root / like said spachner as in this [screenshot](https://addons.cdn.mozilla.net/user-media/previews/full/199/199444.png?modified=1521320989) in the mozilla addon page.
If i set one account for each directory(Bookmark menu, bookmark toolbar, other bookmark) no more error. Even if i create an account and set sync folder to this mobile hidden directory i don't have any error. I don't know why firefox create this directory, it's weird and useless somehow. And it's a new profile like i said, and empty nextcloud bookmark app, so no migration between chrome or android.

**Comment by marcelklehr** [comment]
I've finally been able to reproduce this and have a fix :tada:

**Comment by marcelklehr** [comment]
This should be fixed in the latest release :)

**Comment by mmalisz** [comment]
Works like a charm! Thanks!

**Comment by aktentasche** [comment]
I have this issue after migrating from Chrome to Firefox, with floccus v3.0.0-beta-1

any workarounds?

Had some issues before with bookmarks disappearing locally and an infinite "Syncing..." so I deleted the nextcloud account and all bookmarks. Maybe create a new firefox profile?

**Comment by marcelklehr** [comment]
@aktentasche Could you open a new issue for this? Also, in that issue, please also add the sync folder you selected :)
