### ISSUE TITLE
Can flocus adapt to the mobile fiefox?

### ISSUE THREAD

**Issue by leonardoql** [marcelklehr/floccus#676]
**Is your feature request related to a problem? Please describe.**
 
![Screenshot_20201014-002939](https://user-images.githubusercontent.com/58587784/95889062-8a453d80-0db4-11eb-9979-722d4535b762.jpg)
 
  Now I often use chrome and Android Firefox, but the two bookmarks and other data can not be synchronized, and the current Android Firefox can install a considerable part of the extension plug-in, after a friend recommended that I install flocus, but still can not easily achieve chrome and Android Firefox bookmark synchronization, because I must often open the computer Firefox, to synchronize data.

**Describe the solution you'd like**

  Could you please adapt flocus to the Android Firefox extension plug-in so that Android Firefox can successfully install flocus so that more users can sync their data?

**Describe alternatives you've considered**

  No.

**Additional context**

  No.

**Comment by marcelklehr** [comment]
Hello  @leonardoql 
Thank you for your feedback. Support for Android is a long-standing issue (see #3). The problem is that firefox for android doesn't support addons that interact with bookmarks, yet. However, I'm confident, that this will change soon. So, stay tuned :)
