### ISSUE TITLE
Unable to activate Chrome extension

### ISSUE THREAD

**Issue by 1stone** [marcelklehr/floccus#68]
### Software versions

* Browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Nextcloud: 13.0.0
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.3

### Steps to reproduce
1. Downloaded latest (2.0.3) floccus.crx file.
2. Unpacked CRX file with 7z in a newly created directory.
3. Installed extension in Chrome via "load unpacked" from that directory. (AFAIK the only method to enable a manually installed extension, that is not listed in Google's store)
4. Clicked "Extension options" within extension details of floccus, to add account.

### Expected outcome
I expected to see a configure dialog (similar to the firefox extension), that would allow to add an nextcloud account.

### Actual outcome
A rather small popup appears with "(floccus logo) Floccus (nextcloud Sync)", but containing nothing more than a close button (X).
The extension afterwards shows an error link in the extension overview page, that shows the following error message: `Unrecognized manifest key 'applications'.`

**Comment by gcstang** [comment]
Same here also.

**Comment by marcelklehr** [comment]
Ah, thanks for the quick feedback! You should be able to install it by simply dropping the .crx into the extensions page. Still, the behaviour you described is a bug. I've just pushed a new patch release that fixes it. :)

**Comment by 1stone** [comment]
Thanks for providing a patch so fast.

Dropping the .crx into the extensions page will install the extension **disabled**, since it is not listed in the Google store. So far I found no way to enable it with recent Chrome versions afterwards.

Other posts indicate, that such extensions can now only be installed via "load unpacked".
If that is invalid information, I would be interested to hear about a way to enable "dropped" extensions.

**Comment by marcelklehr** [comment]
Mh. I'm running Chrome Version 65.0.3325.181 (Official Build) (64-bit)
It might work on my machine because of some kind of option, perhaps? I'll investigate.

**Comment by marcelklehr** [comment]
See https://www.howtogeek.com/120743/how-to-install-extensions-from-outside-the-chrome-web-store/

**Comment by marcelklehr** [comment]
Apparently "Extensions hosted outside of the Chrome Web Store can only be installed by Linux users." This is not a problem, though, since you can now get the latest floccus version in the webstore :)
