### ISSUE TITLE
Can't modify the root bookmark folders -- Implement folder mapping

### ISSUE THREAD

**Issue by 1stone** [marcelklehr/floccus#69]
### Software versions

* Browser: Version 65.0.3325.181 (Official Build) (64-bit)
* Nextcloud: 13.0.0
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.4

### Steps to reproduce
1. Installed extension into chrome
2. Added account data
3. Selected "Untitled folder" (root) for the Sync folder
4. Clicked "Sync now" to perform initial sync.

### Expected outcome
- Field "Sync folder" should show "/" (After step 3)
- Bookmarks should be synced completely

### Actual outcome
- Field "Sync folder" shows `*newly created*`, no matter which folder is actually selected.
- Sync results in error: `Can't modify the root bookmark folders.` (3 times)

### Remarks
- Are there limitations (or special considerations) when fully syncing firefox bookmarks with Chrome on root level?
- How is initial sync performed? Browser to server? Server to Browser? Or merged from both sources?

**Comment by marcelklehr** [comment]
I've fixed the sync folder display in yet another release (:see_no_evil:) just now. Initial sync merges both browser and server, but if you're syncing the whole tree, there should not be any bookmarks on the server, because they will end up in the root folder which is not accessible to the end user (it contains the `bookmarks bar` and the `other bookmarks` folders). Maybe that's why you're missing some of your bookmarks.

**Comment by 1stone** [comment]
Hmm... I suppose that I'm doing something wrong then...
I'm trying to establish a full sync (on root level) between Firefox and Chrome, but from what your are saying (_"... end up in the root folder which is not accessible to the end user ..."_) I assume that this is not actually possible?
Could you give a suggestion how such a "full sync" can be achieved?

Looking at the folder selection dialog, I see the following available folders for
- Chrome:
```
Untitled folder
|- Bookmarks bar
|- Other bookmarks
```
- Firefox (DE locale installation):
```
Untitled folder
|- Lesezeichen Menü _(EN: bookmark menu)_
|- Lesezeichen-Symbolleiste _(EN: bookmarks bar)_
|- Weitere Lesezeichen _(EN: other bookmarks)_
|- mobile
```

That looks quite different and is probably the reason why this can't be synced on root level.
But how is this configured correctly then, when at least the following sub-folders should be synced:

| Chrome | Firefox |
|---------|---------|
|Bookmarks bar|Lesezeichen-Symbolleiste|
|Other bookmarks|Lesezeichen Menü|

Would I need to setup multiple (identitcal) accounts for each single folder sync?

**Comment by marcelklehr** [comment]
I assume that is the problem. For now, it's only possible to sync one root folder per browser, sadly. Multiple identical accounts would probably not work either, because they would all sync to the same nextcloud account and thus merge your different folders into one. Folder mapping is not yet implemented, but is on the todo list.

**Comment by 1stone** [comment]
Uhh... ok,
So if I understand that correctly, there needs to be a single, distinct folder (on root level) that can be synced throughout different browsers.
Referring to my situation above, I would be able to sync **either** my "bookmarks bar" **or** "other bookmarks", but not both between Chrome and Firefox.

Please confirm or suggest otherwise:
To be able to sync **all** my bookmarks between browsers, I would need to consolidate them into a single root-folder location, so effectively either the "bookmarks bar" or "other bookmarks".

**Comment by marcelklehr** [comment]
You're correct. As long as there's no configurable folder mapping this is the only way, I'm afraid.

**Comment by marcelklehr** [comment]
@1stone Thank you for taking the time to explain your background and the current situation in this field. I'm confident that folder mapping will be possible within the next month or so, but I can't promise anything, of course. It's ready when it's ready :)

@eRJe79 Thanks for chiming in and also for supporting this project :sparkles: :)

**Comment by eRJe79** [comment]
You're welcome! Thanks for all the effort you put in this project.

For now I have just moved my "other bookmarks" folder to the toolbar and only sync that folder with Floccus. It's actually a very acceptable workaround for me.

**Comment by marcelklehr** [comment]
You can now configure the server path to sync to in floccus v2.2.0 :)
