### ISSUE TITLE
Nextcloud API Error on v4.4.1

### ISSUE THREAD

**Issue by dsiminiuk** [marcelklehr/floccus#692]
Installed 4.4.1 over top of 4.4.0.1 (Developer mode)

**Describe the bug**
On sync down (pull from server) error:
"Nextcloud API error: {"status":"error","data":"Could not find folder"}"

**To Reproduce**
Click Sync down from server button

**Expected behavior**
Should overwrite local bookmarks

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Vivaldi (Chromium)
 - Browser Version 3.4.2066.76
 - Floccus version: 4.4.1
 - Floccus sync method: nextcloud bookmarks

**Server (please complete the following information):**
 - OS: Ubuntu 16
 - Bookmarks app version: 3.4.3

Note: Please write down the actual version numbers instead of writing 'latest'.

**Comment by dsiminiuk** [comment]
I see an update for Bookmarks to 3.4.4.

Nextcloud API error: {"status":"error","data":"invalid children order: To many children"}

**Comment by dsiminiuk** [comment]
I had to wipe and upload fresh to Nextcloud but I got it working.

The upgrade to 4.4.0 went without a hitch. 4.4.0 to 4.4.1 not so much.

**Comment by marcelklehr** [comment]
v4.4.0 had a bug which likely caused this :(
