### ISSUE TITLE
Tabs sync in different windows

### ISSUE THREAD

**Issue by jeanlyc** [marcelklehr/floccus#693]
Having Firefox running with two windows,  the second window also syncs the tabs from the server (after the sync delay). 
Is there a way to prevent this?

**Comment by jeanlyc** [comment]
Short update: I have to check this again, might also be the correct behavior if sync option "merge" is selected. 
(Then the question would be: once I synced tabs from the server and close one of those: is that closed tab than synced back to the server?)

**Comment by marcelklehr** [comment]
> once I synced tabs from the server and close one of those: is that closed tab than synced back to the server?

It is not. The implementation of the tabs API in the browser doesn't allow tracking them, sadly.

**Comment by jeanlyc** [comment]
Thank you for the update - this clarifies the observed behavior. 
Closing this.
