### ISSUE TITLE
Sync just hangs since update to 4.4.0

### ISSUE THREAD

**Issue by FuzzyMistborn** [marcelklehr/floccus#695]
**Describe the bug**
Not sure how to describe this since I'm seeing slightly different behavior on different machines (mostly Windows but one Linux and all Firefox).  In general, the sync appears to just hang (it never stops showing the blue <----> on the icon) and on one machine it's created like....30 different copies of every bookmark.

**To Reproduce**
Just....enable the add on/extension and try to sync.

**Expected behavior**
Working sync

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows/Linux
 - Browser [e.g. chrome, safari] Firefox
 - Browser Version [e.g. 22] 81.02
 - Floccus version: [e.g. 3.2.2] 4.4.0.1
 - Floccus sync method: [e.g. webdav, nextcloud legacy or nextcloud folders] Nextcloud folders

**Server (please complete the following information):**
 - OS: [e.g. centOS 7] Ubuntu
 - Nextcloud version: [if applicable] 20
 - Bookmarks app version: [if applicable] 3.4.4

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

Really the only thing in the log I see is this:

2020-10-20T13:40:44.143Z Starting sync process for account xx@url
2020-10-20T13:40:45.168Z onSyncStart: begin
2020-10-20T13:40:45.169Z https://URL/remote.php/webdav/.floccus-.lock

**Additional context**

**Comment by marcelklehr** [comment]
Hello! Thank you for your feedback!

The duplicate entries should be fixed in the latest version. That was a glitch with the v4.4.0 release. To fix, 1) wipe the server bookmarks and 2) trigger a sync from scratch in the "dangerous" section of the account settings.

To get it to sync again remove the hidden lock file `.floccus-.lock` in the root of your nextcloud files. (Enable "Show hidden files" in the files app settings)

**Comment by FuzzyMistborn** [comment]
Perfect thank you, deleting the .floccus-.lock seems to have fixed it.
