### ISSUE TITLE
Unable to Sync. API Error after Bookmarks-Update to 3.4.4

### ISSUE THREAD

**Issue by lightlike** [marcelklehr/floccus#696]
**Describe the bug**

I get the error
`Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: folder:76"}`
when trying to sync to Nextcloud after the 3.4.4 Update of Bookmarks.
Root-Bookmarks do not get synced. Rest seems fine.

**Expected behavior**
Should sync without any API errors

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Browser Version: 81.0.2 (64-Bit)
 - Floccus version: 4.4.1
 - Floccus sync method: Nextcloud Bookmarks

**Server (please complete the following information):**
 - OS: OMV 5 (Usul) Docker
 - Nextcloud version: 19.0.4
 - Bookmarks app version: 3.4.4

**Debug log**

No recent log output

- [ ] Debug log provided

**Additional context**

I have a javascript bookmark that had some problems in the past.

**Comment by TheFrenchGhosty** [comment]
Using "Trigger sync from scratch", then syncing fixes this issue.

**Comment by lightlike** [comment]
That worked like a charm. Thanks.
