### ISSUE TITLE
NextCloud 11 Support

### ISSUE THREAD

**Issue by Yamakasi** [marcelklehr/floccus#7]
Hi I was just coming up your nice plugin and I wondered if this should be working on Nextcloud 11 at the moment ?

Would be nice to know and see where it stores it.

**Comment by marcelklehr** [comment]
Hi!
It doesn't work at all, at the moment, sadly. The mechanism I used to create the bookmarks no longer works (it was a hacky mechanism, admittedly, so no real surprise there). The actual problem is that the bookmarks app doesn't offer a useful API for programmatic CRUD access to the bookmarks (See my PR for this: https://github.com/nextcloud/bookmarks/pull/322; there's also a PR that does the same thing, but is about a year old. A bit frustrating...).

I guess I should update the README to reflect this...

**Comment by Yamakasi** [comment]
Hi yes I just read that but as there were no conflicts reported I hoped it would :)

What do you think we can do here because this would be awesome to have (again)!

**Comment by marcelklehr** [comment]
The maintainer of nextcloud/bookmarks seems responsive, so I'd say it's possible to get the new CRUD methods for the REST API rather soon-ish. You could leave a comment on the PR supporting it :)

**Comment by Yamakasi** [comment]
This sounds good, which PR are you refering too ?

**Comment by marcelklehr** [comment]
https://github.com/nextcloud/bookmarks/pull/322

**Comment by Yamakasi** [comment]
OK, this seems to be merged now ? Any status ? I'm curious!

**Comment by marcelklehr** [comment]
The status for this is the following: The bookmarks app needs a refactoring reconciling the two (public and private) REST APIs. Additionally, it appears that the following issues await addressing until the next version of the bookmarks app can be released: https://github.com/nextcloud/bookmarks/milestone/3

**Comment by poVoq** [comment]
at the moment with my recently installed Nextcloud11 it works fine. Not sure if the above errors were fixed or why it works for me.

**Comment by marcelklehr** [comment]
@poVoq interesting. Does creating and deleting bookmarks propagate both ways (from server to browser and vice versa)?

**Comment by poVoq** [comment]
no actually I just noticed that it only works one way (nextcloud to firefox). Sorry for causing confusion there.

**Comment by marcelklehr** [comment]
Status update: I'm confident, we will see the update to the bookmarks app before the end of this year. \</sarcasm> tbh, I have no idea how long it will take, from my perspective things are ready, however the maintainer has a lot on his plate, so it will take some time before the review process is completed.

**Comment by jkaberg** [comment]
@marcelklehr I see you'r an maintainer for the NC bookmark app now. Any ETA on this? 😸

**Comment by marcelklehr** [comment]
@jkaberg Yes, I am :tada:. I still can't just push my stuff to master and be done with it, though, heh :) That wouldn't be the right approach and wouldn't lead to good software being released. Still I'm confident we'll have a new release soon-ish. Hopefully before July.

You can follow the process of getting the new API ready over here: https://github.com/nextcloud/bookmarks/pull/338

**Comment by marcelklehr** [comment]
:tada: Nextcloud bookmarks v0.10 was released yesterday. As was floccus v1.2.0. This means: Floccus works again! Happy syncing everyone :)

**Comment by Gerii** [comment]
How long does it usually take for an update to appear on addons.mozilla.org?

**Comment by marcelklehr** [comment]
I have no idea. Atm, AMO tells me "Queue Position: 266 of 289" :/

**Comment by 9662** [comment]
> Atm, AMO tells me "Queue Position: 266 of 289" :/

And now? 😜

**Comment by marcelklehr** [comment]
265 of 295, so that gives us a rate of about three per day...

**Comment by Rinma** [comment]
Can you not provide a xpi package by yourself to download for those who want to install it earlier ?

**Comment by marcelklehr** [comment]
Sadly most Firefox versions will not install addons that aren't signed by Mozilla...

On May 17, 2017 9:13:43 AM GMT+02:00, Marvin Dalheimer <notifications@github.com> wrote:
>Can you not provide a xpi package by yourself to download for those who
>want to install it earlier ?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/marcelklehr/floccus/issues/7#issuecomment-302006052

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kaistian** [comment]
You can create one yourself in Linux like this
```
wget https://github.com/marcelklehr/floccus/archive/v1.2.0.zip -O /tmp/floccus-1.2.0.zip
unzip -o /tmp/floccus-1.2.0.zip -d /tmp
cd /tmp/floccus-1.2.0
zip -r -FS ~/floccus-1.2.0.xpi *
```

To make it work in newer Firefox you'll need following changes in `about:config`
Set `xpinstall.signatures.required` to false and create an new String with name `xpinstall.whitelist.add` with an empty value.

```

**Comment by marcelklehr** [comment]
It's just been approved.
