### ISSUE TITLE
setup a minimal WebDav without full server and Docker? "net use W: \\192.168.0.177\wd

### ISSUE THREAD

**Issue by pstein** [marcelklehr/floccus#702]
I want to avoid setting up a full WebDav server or a full Docker environment for just using Floccus.

So if I define a shared folder with a command like

net use W:   \\192.168.0.177\wd

on a 64bit Win7 Pro (NOT server) system will this be sufficient?

The folder "wd" is on my computer with the local IP 192.168.0.177

I could connect from my notebook to my Desktop computer and let Floccus sync the bookmarks via
inhouse-LAN to the shared folder.

Does this work?

Peter

**Comment by marcelklehr** [comment]
> Does this work?

I don't know. I haven't tried it. I doubt it though, because I assume, windows will use SMB rather than webdav. I recommend LoFloccus, which is known to work.
