### ISSUE TITLE
invalid children order: A child is missing: folder:1327

### ISSUE THREAD

**Issue by tessus** [marcelklehr/floccus#705]
**Describe the bug**
When syning to server (revert upstream), I receive the error:
`invalid children order: A child is missing: folder:1327`

**To Reproduce**
1. Sync (always revert upstream...)

**Expected behavior**
Sync w/o error

**Screenshots**
<img width="458" alt="image" src="https://user-images.githubusercontent.com/223439/97067042-ab154c00-1587-11eb-880b-597f5f7ea30f.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Browser Version 82.0
 - Floccus version: 4.4.2
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Linux
 - Nextcloud version: 18.0.10
 - Bookmarks app version: 4.3.3

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
Uploaded `gh-issue-705.floccus-4.4.2-2020-10-23.clean.log`

- [x] Debug log provided

**Additional context**
I had this error once before. I read in one of the issues that removing the bookmarks on the server helped. It did. But then after a consequent sync, this error showed up again.

**Comment by marcelklehr** [comment]
There are some fixes out now for floccus and the bookmarks app. Can you try updating floccus, bookmarks app, then running maintenance:repair and possibly a sync from scratch? :pray:

**Comment by tessus** [comment]
Great. Will do in my lunch break in about 2.5h.

**Comment by tessus** [comment]
Thanks, it worked. Sorry that I haven't replied earlier. I did not even had lunch break today. It was just crazy.

Here's what I did:

1. updated the bookmarks app to 3.4.6
2. floccus was already at latest version 4.4.3
3. `occ maintenance:repair`
```
 - Remove superfluous shared bookmark folders
     - Removed 0 superfluous shares
 - Remove orphaned bookmark shares
     - Removed 0 orphaned shares
     - Removed 0 orphaned public links
 - Remove orphaned bookmark tree items
     - Removed 111 orphaned bookmarks entries
     - Removed 2046 orphaned folders entries
     - Removed 337 orphaned children entries
     - Removed 0 orphaned bookmark folders
     - Removed 311 orphaned bookmarks
 - Update bookmark group shares
     - Removed 0 users and added 0 users to 0 groups
     - Removed 0 shares
```
4. set `sync from scratch` flag
5. sync

**Comment by marcelklehr** [comment]
Thanks for the feedback! I'm glad it works now :)

**Comment by tessus** [comment]
Thank you for the fix! 🎉 ❤️
