### ISSUE TITLE
"The bookmark root cannot be modified" on sync

### ISSUE THREAD

**Issue by jimbolaya** [marcelklehr/floccus#707]
**Describe the bug**
When I try to sync to my local firefox, I get an error and repeated "The bookmark root cannot be modified" in the error box.

**To Reproduce**
Do nothing if automatic sync is enabled. This error happens automatically

or 

Sync manually and see the error.

**Expected behavior**
I expect the bookmarks to be synced.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser: Firefox
 - Browser Version: 82.0
 - Floccus version: 4.4.2
 - Floccus sync method: nextcloud (not sure what legacy vs folders is, but I have folders on my nextcloud bookmarks app)

**Server (please complete the following information):**
 - OS: Debian Buster
 - Nextcloud version: 18.0.10
 - Bookmarks app version:  3.4.4

**Debug log**
- [ X] Debug log provided

**Comment by jimbolaya** [comment]
Uploaded debug log name: issue-707-floccus-4.4.2-2020-10-25.log

**Comment by wohali** [comment]
Getting this now too, and floccus is once again putting unfixable problems into the Nextcloud bookmarks DB, see my updates to https://github.com/marcelklehr/floccus/issues/647.

**Comment by f-fouad** [comment]
I am also affected with this bug for a while now. Around 2 weeks, I don't recall exactly.

Clent Side :

    OS: Arch Linux
    Browser: Firefox
    Browser Version: 82.0
    Floccus version: 4.4.3
    Floccus sync method: nextcloud folders syncing the root folder

Server side : 

    OS: Debian Buster
    Nextcloud version: 19.0.4
    Bookmarks app version: 3.4.6

The debug log wouldn't open in Floccus.

**Comment by marcelklehr** [comment]
@jimbolaya As per your debug log:

Browser's don't allow modifying the root of the bookmarks tree.

Your browser has the following folders in its root.

node menu________ Bookmarks Menu => Bookmarks Menu
node toolbar_____ Bookmarks Toolbar => Bookmarks Bar
node unfiled_____ Other Bookmarks => Other Bookmarks

But floccus is receiving the following folders from the server:

2020-10-25T13:45:35.101Z Received initial folders from server [ { id: 142,
    title: 'Bookmarks Menu',
    parent_folder: 230 },
  { id: 164,
    title: 'Bookmarks Bar',
    parent_folder: 230 },
  { id: 193,
    title: 'Other Bookmarks',
    parent_folder: 230 },
  { id: 194,
    title: 'Mobile Bookmarks',
    parent_folder: 230 },
  { id: 215, title: 'Trash',  parent_folder: 230 },
  { id: 231, title: '', parent_folder: 230 }]

So, floccus tries to create those folders. But the browser won't let it. That triggers your error.

**Comment by marcelklehr** [comment]
Did this used to work for you?

**Comment by wohali** [comment]
@marcelklehr Yes, for me it did, prior to 4.4.x. Do I need to open a new ticket?

**Comment by marcelklehr** [comment]
@wohali Nope, v4.4.4 is out already :)
