### ISSUE TITLE
Updated to 4.4.2 and nothing is working on multiple clients

### ISSUE THREAD

**Issue by dsiminiuk** [marcelklehr/floccus#709]
**Describe the bug**
Sync doesn't work at all. Progress bar sits at 5% (?) and never moves, never times out (or I'm not patient enough) :)
Clicking the "Debug Logs" button does not render a log file.

**To Reproduce**
Setup/import account, click sync or upgrade to 4.4.2.
Makes no difference what settings you use, merge local, merge remote, trigger from scratch (dangerous).
Firewall is disabled.

**Expected behavior**
Sync would happen

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Browser Version 3.4.2066.86
 - Floccus version: 4.4.2
 - Floccus sync method: nextcloud legacy

**Server (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Nextcloud version: 18.0.10
 - Bookmarks app version: 3.4.5 (updated today but made no difference)

**Debug log**
CAN'T PRODUCE IT! see above.

![image](https://user-images.githubusercontent.com/5713547/97313714-f1db9e00-1834-11eb-8eae-4fb0d88e1af3.png)

**Comment by marcelklehr** [comment]
Are you sure you're using "nextcloud legacy"? Your screenshot reads "nextcloud-folders". The legacy sync method was deprecated starting in v4.0 and has been removed in v4.4.x.

If the debug log is not available you can debug via browser tools as follows:

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and copy the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by marcelklehr** [comment]
It just occurred to me that you may likely experience an uncleared lock. To clear it, you can go to your nextcloud files, enable the display of hidden files and delete all files named `.floccus-xxxxx.lock`.

**Comment by dsiminiuk** [comment]
I'm using Nextcloud Bookmarks, sorry.

chrom://extensions redirects to vivaldi://extensions/

Already in developer mode, that's how I uploaded the crx file.

Regarding your lock file idea, that could be the case. It would explain why nothing is moving on all my browsers. Now to figure out how to display hidden files...

**Comment by marcelklehr** [comment]
> Now to figure out how to display hidden files...

It's in the settings of the files app, bottom-left corner. ;)

**Comment by dsiminiuk** [comment]
Yup there it is and there is the .lock file. Thank you. Let me test and see if I can get my sanity back.

**Comment by marcelklehr** [comment]
Perhaps an automatic process for removing the lockfile after a certain amount of stale time is in order.

**Comment by dsiminiuk** [comment]
By the way, by the time I went to clear the lock file there was an error on the sync dialog that said the same thing, "consder clearing (it)". Perhaps on the next iteration you can change the timeout or check the age of the lock file and show the error a little sooner than what felt like forever.

Progress, sync started working again but I have an error... 
```
Nextcloud API error: {"status":"error","data":"invalid children order: To many children"}
```
I'll try a trigger from scratch to clear the server list.

**Comment by dsiminiuk** [comment]
Deleted bookmarks on the server, forced upload from the client.
Got this the first time
```
Nextcloud API error: {"status":"error","data":"invalid children order: To many children"}
```
Set the client to merge then got this error.
```
Error in invocation of bookmarks.move(string id, object destination, optional function callback): No matching signature. Error in invocation of bookmarks.move(string id, object destination, optional function callback): No matching signature. Error in invocation of bookmarks.move(string id, object destination, optional function callback): No matching signature. Error in invocation of bookmarks.move(string id, object destination, optional function callback): No matching signature. Error in invocation of bookmarks.move(string id, object destination, optional function callback): No matching signature.
```

**Comment by dsiminiuk** [comment]
then 
```
Cannot map parentId:2975
```

**Comment by dsiminiuk** [comment]
Tried closing the browser, then clicking the Upload button.
```
Nextcloud API error: {"status":"error","data":"Could not find folder"}
Nextcloud API error: {"status":"error","data":"Could not find folder"}
Nextcloud API error: {"status":"error","data":"Could not find folder"}
Nextcloud API error: {"status":"error","data":"Could not find folder"}
many many of these
```

**Comment by marcelklehr** [comment]
oof. I can confirm that some things are boken in v4.4.x so far, which is why I've held off publishing it on the chrome webstore so far. I'll be doing a new release today or tomorrow, though, let's see how that fares.

**Comment by dsiminiuk** [comment]
OK I got it fixed up on one client. I cleared the bookmarks on the server, deleted the bookmarks on the browser (some folders were corrupted because I tried Vivaldi Sync and that created a mess).
I imported a backup of my bookmarks (clean) back into the browser and then the upload went fine.
On to other browsers...

**Comment by dsiminiuk** [comment]
Cleared bookmarks on a second machine and clicked the Down Arrow to import. No problem.
I think I'm good now.

**Comment by marcelklehr** [comment]
Backups ftw! :rocket:

**Comment by dsiminiuk** [comment]
Another enhancement (yes) would be to clearly label the Enable switch as "Auto sync" and still allow the Up and Down arrows to do manual forced sync without Auto being enabled. A user might want to download and not auto-update until all clients are synced and safe. Just an idea.

As it is now I think the account needs to be enabled before Up and Down forced will work. Correct?

**Comment by marcelklehr** [comment]
> As it is now I think the account needs to be enabled before Up and Down forced will work. Correct?

Mh, no. The Up/Down buttons temporarily enable the account.

**Comment by dsiminiuk** [comment]
OK great.

**Comment by marcelklehr** [comment]
I'm open to any other enhancements / UX improvements you may have, though :) Feel free to open issues! :heart:
