### ISSUE TITLE
The character ',' in the bookmark folder name must be escaped in the tag name

### ISSUE THREAD

**Issue by mnsold** [marcelklehr/floccus#71]
### Software versions

* Browser: Firefox 59.0.2
* Nextcloud: 13.0.1
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.5

### Steps to reproduce

1. Create a folder "Example folder, other words" in the bookmarks menu
2. Add 2 bookmarks to this folder
3. Specify the synchronization folder in the settings of the Floccus extension in the browser: // Menu of bookmarks
4. Synchronize your bookmarks
5. Go to nextcloud, your bookmarks will be tagged with two tags: the first tag is "floccus:> Example folder" and the second tag is "other words"
6. Delete the account in the settings of the Floccus extension in the browser
7. Delete your bookmarks in the browser
8. Add an account in the settings of the Floccus extension in the browser. You should see: Last synchronization: never
9. Specify the synchronization folder in the settings of the Floccus extension in the browser: // Menu of bookmarks
10. Synchronize your bookmarks
11. The folder "Example folder, other words" will be restored as "Example folder" (no words after the comma)

### Expected outcome

The folder "Example folder, other words" should be restored with the same name.

### Actual outcome

The folder "Example folder, other words" was restored as "Example folder" (without words after the comma)

**Comment by marcelklehr** [comment]
Thanks for reporting this!
I can confirm the problem. Nextcloud bookmarks probably should not accept tags with commas in them, or alternatively escape them in some fashion. I'll add a quick fix to floccus until this is resolved in nextcloud.

**Comment by marcelklehr** [comment]
Should be fixed in the latest release.
