### ISSUE TITLE
Sync stuck in chrome floccus v4.3.0 after syncing bookmarks on firefox v.4.4.2

### ISSUE THREAD

**Issue by adrianharabula** [marcelklehr/floccus#710]
**Describe the bug**
On chrome latest available version as of today is 4.3.0, while in firefox it is v4.4.2.

Xbel sync works fine from firefox floccus v4.4.2, but the sync process gets stuck in chrome when using floccus v4.3.0.

No strange lines in logs found.

**Comment by marcelklehr** [comment]
This might be due to an uncleared lock file. v4.4.x will soon be published for chrome as well, though.

**Comment by adrianharabula** [comment]
Here is a list of steps I've tried:
1. Closed the Chrome browser with stuck sync
2. Manually deleted lock file from webdav
3. Re-opened Chrome browser and re-run sync
3. Sync is still stuck

Many thanks for the answer!

**Comment by marcelklehr** [comment]
You can try checking the browser logs as follows to see what is going wrong:

>In order to aid in debugging, please provide client-side logs.
>
>#### Firefox
>* Go to `about:debugging`
>* click on `debug` button next to floccus entry
>* trigger a sync by clicking on `sync now` for the account of your choice.
>* go back to the inspector window and copy the logs after waiting for the sync to finish
>
>#### Chrome
>* Go to `chrome://extensions`
>* enable `Developer mode`
>* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
>* trigger a sync by clicking on `sync now` for the account of your choice
>* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by ixmu** [comment]
Hope to update the plugin version in the chrome store.

**Comment by marcelklehr** [comment]
Update is rolled out for Chrome and Edge. I'm closing this for now, feel free to shout if this is still an issue with the newest version.

**Comment by adrianharabula** [comment]
Many thanks!
