### ISSUE TITLE
Cycle(s) detected; toposort only works on acyclic graphs  (Firefox) 

### ISSUE THREAD

**Issue by bhlevca** [marcelklehr/floccus#711]
**Describe the bug**

- On Firefox Sync with V4.4.3 I get  the following error: "Cycle(s) detected; toposort only works on acyclic graphs "
- On Edge (Linux and Windows) with V4.3.0 I get no error but it is syncing for ever.
- On Chrome with V4.3.0 all is fine 

**To Reproduce**
I tried to do it from scratch, with merge and overwrite from both direction s

**Expected behavior**
To sync properly with out error and finish

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser: as documented above: Firefox, Chrome and MS Edge
 - Browser Version: latest versions from the respective brands.
 - Floccus version: [4.4.3 & 4.3.0]
 - Floccus sync method: [webdav]

**Server (please complete the following information):**
 - OS: [Debian buster]
 - Nextcloud version: [19.0.3]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
If needed I can provide one for each browser

**Comment by marcelklehr** [comment]
Can you recreate the account, deleting the server bookmarks and try syncing up / overwrite?

**Comment by bhlevca** [comment]
Seems to have worked for Firefox. The only complain is  that the reconstructed bookmarks come in a chaotic order , not in the order they have been saved from the Chrome browser.

However, on the Edge browser the error still persists, while the other browsers are ok. I deleted teh bookmarks from Edge and synchronized with the new bookmarks.xbel. I get the following error in the add on popup and sync stops:

`Trying to insert an already existing item into OrderTracker: folder:8960 Trying to insert an already existing item into OrderTracker: folder:8962 Trying to insert an already existing item into OrderTracker: folder:9052 Trying to insert an already existing item into OrderTracker: folder:8213 Trying to insert an already existing item into OrderTracker: folder:8512 Trying to insert an already existing item into OrderTracker: folder:8264 Trying to insert an already existing item into OrderTracker: folder:8265 Trying to insert an already existing item into OrderTracker: folder:9183 Trying to insert an already existing item into OrderTracker: folder:8965 Trying to insert an already existing item into OrderTracker: folder:9002 Trying to insert an already existing item into OrderTracker: folder:8835 Trying to insert an already existing item into OrderTracker: folder:8833 Trying to insert an already existing item into OrderTracker: folder:8836 Trying to insert an already existing item into OrderTracker: folder:9438 Trying to insert an already existing item into OrderTracker: folder:9438 Trying to insert an already existing item into OrderTracker: folder:9494 Trying to insert an already existing item into OrderTracker: folder:9705 Trying to insert an already existing item into OrderTracker: folder:9716 Trying to insert an already existing item into OrderTracker: folder:9707 Trying to insert an already existing item into OrderTracker: folder:9684 Trying to insert an already existing item into OrderTracker: folder:9811 Trying to insert an already existing item into OrderTracker: folder:9811`

After I press sync again the synchronization continues but soon gives me another issue:

`E011: Item in folder ordering is not an actual child: {"id":45283,"type":"bookmark"} Trying to insert an already existing item into OrderTracker: folder:8373 Trying to insert an already existing item into OrderTracker: folder:8265 E012: Folder ordering is missing some of the folder's children Trying to insert an already existing item into OrderTracker: folder:9927 E012: Folder ordering is missing some of the folder's children E012: Folder ordering is missing some of the folder's children E012: Folder ordering is missing some of the folder's children E012: Folder ordering is missing some of the folder's children`

but this time the sync does not stop, but seem to do it for ever. This is Edge for Linux, so it may have some bugs as it is a dev release.

**Comment by marcelklehr** [comment]
> Seems to have worked for Firefox. 

Very nice. Edge and Chrome are still on the older version, so please stay tuned for the release there.

**Comment by bhlevca** [comment]
Unfortunately the "Cycle(s) detected; toposort only works on acyclic graphs" has resurfaced in Firefox with version 4.4.4

Interestingly, even if sync is turned off "Sync now" triggers the synchronization 
Unfortunately , I am not able to provide the debug logs because the button does not do anything. 

Actually, this version is behaving worse that 4.3.0 on Firefox anyway.

**Comment by bhlevca** [comment]
I deleted the xbel file again and it worked again just fine. It appears that subsequent sync does something.
