### ISSUE TITLE
E019: HTTP status 423. Failed PUT request.

### ISSUE THREAD

**Issue by wildcart** [marcelklehr/floccus#712]
**Describe the bug**
floccus 'in' Firefox fails to sync my bookmarks when restricting floccus to sync a specific "server folder" (`/work` in this case) in the floccus configuration. If I clear the "server folder" floccus syncs the bookmarks as expected. The client side error I get is the similar to the error reported in #699 except that I am getting an HTTP 423 instead of HTTP 403 (see below).

I first noticed this behaviour late last week, I think (not sure which version of floccus I was using at this time). Before this floccus successfully sync bookmarks with my nextcloud for about a year and a half.

In vivaldi, floccus 4.3.0 successfully syncs my bookmarks when the "server folder" is set.  I've already deleted the floccus configuration in Firefox, deleted all bookmarks both server side and client side but it doesn't make a difference. I've also created a new nextcloud user and created a new floccus configuration for this user without success.

**To Reproduce**
1. Create a "nextcloud folder" account in floccus
2. Setup a "server folder" to restrict which bookmarks are synced
3. Click "sync now"

**Expected behavior**
The sync finishes successfully

**Observed behavior**
The sync fails with "E019: HTTP status 423. Failed PUT request. Check your server configuration and log." 

***floccus debug log***
```
2020-10-28T19:57:11.948Z Starting sync process for account <account>
2020-10-28T19:57:12.148Z onSyncStart: begin
2020-10-28T19:57:12.148Z https://<domain>/<nc-path>remote.php/webdav/.floccus-L3dvcms=.lock
2020-10-28T19:57:13.058Z https://<domain>/<nc-path>remote.php/webdav/.floccus-L3dvcms=.lock
2020-10-28T19:57:13.483Z Syncing failed with E019: HTTP status 423. Failed PUT request. Check your server configuration and log.
```

***Server log***
This is only an excerpt from the full log removing the "Trace" information
```
..."app":"no app in context","method":"GET","url":"/<nc-path>/remote.php/webdav/.floccus-L3dvcms=.lock","message":{"Exception":"OC\\Authentication\\Exceptions\\InvalidTokenException","Message":"Token does not exist"...

..."app":"no app in context","method":"GET","url":"/<nc-path>/remote.php/webdav/.floccus-L3dvcms=.lock","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\"...

..."app":"webdav","method":"GET","url":"/<nc-path>/remote.php/webdav/.floccus-L3dvcms=.lock","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name .floccus-L3dvcms=.lock could not be located"...

..."app":"no app in context","method":"GET","url":"/<nc-path>/remote.php/webdav/.floccus-L3dvcms=.lock","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"bookmarks.web_view.index\" as such route does not exist."...
```

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.2
 - Browser Firefox
 - Browser Version 78.4.0esr
 - Floccus version: 4.4.3
 - Floccus sync method: nextcloud folders
**Server (please complete the following information):**
 - OS: Hosted 
 - Nextcloud version: 20.0.1 (also tested with 18.0.4 before upgrading)
 - Bookmarks app version: 4.0.3 (also tried with 3.0.4 before nextcloud upgrade)

**Comment by marcelklehr** [comment]
Have you tried this fix? https://github.com/marcelklehr/floccus/issues/699#issuecomment-714595080

**Comment by wildcart** [comment]
I was using username/password authentication until I re-created the floccus configuration and it stopped working sometime last week (or so). That's probably why I skipped the comment you're referencing. 

I'll try "enable File System Access on the Token" later today and let you know. Is this a nextcloud setting?

**Comment by marcelklehr** [comment]
If you're not using nextcloud flow for authenticating floccus, then this won't fix things for you, I'm afraid. If you do, you should be able to select the apps for which you want to grant access to floccus. In that dialog, select bookmarks and files.

**Comment by errolsancaktar** [comment]
i cant seem to get mine working again, tried w/ app password and real password:
image

![image](https://user-images.githubusercontent.com/60162646/97612599-3d30b080-19dd-11eb-9836-43c7ded20f1d.png)

**Comment by wildcart** [comment]
I initially configured floccus to connect to my nexctcloud using username and password and used the 'nextcloud flow' when I re-created the floccus configuration, both are not working if a "server folder" is specified in the configuration. If I clear this field both authentication methods work fine.

I've verified that "Allow filesystem access" is enabled for floccus but it doesn't fix the problem.
![image](https://user-images.githubusercontent.com/19203041/97614493-4ee47900-1a1a-11eb-85c9-c5009aa9653a.png)

**Comment by marcelklehr** [comment]
HTTP 423 means the file is locked for some reason. Do you have any file locking apps installed?

**Comment by wildcart** [comment]
Not that I know, at least none of the plugin/app names suggest this feature.

Do you have any idea why this only happens if I specify a "server folder" in the floccus configuration? Is there anything else that I can provide to help you figure out what's going on?

**Comment by marcelklehr** [comment]
It seems that the locking functionality as it is implemented now was a bad idea, I'll remove it with the next patch, which should solve this issue as well.

**Comment by marcelklehr** [comment]
Patch is out for firefox.

**Comment by marcelklehr** [comment]
> My fix was update oc_bookmarks_root_folders set locked = 0, after which syncing resumed normally.

Floccus should override the lock after waiting half an hour for it. :/

> I will try to fiddle with this and file a proper issue.

That would be great! Thanks
