### ISSUE TITLE
It's not possible to move Places root folders. 

### ISSUE THREAD

**Issue by NephtonLabs** [marcelklehr/floccus#718]
**To Reproduce**
Newly built out environment. 
Pressing the sync button does nothing. 
Pressing sync up button appears to work as the bookmarks appear in Bookmarks on Nextcloud. 
After that pressing sync presents the error 'It's not possible to move Places root folders. Settings'

**Expected behavior**
Sync happening.

**Screenshots**
![image](https://user-images.githubusercontent.com/51098774/97764742-04c8c980-1ae6-11eb-8877-6c61494be4b0.png)
![image](https://user-images.githubusercontent.com/51098774/97765607-25465300-1ae9-11eb-8ca3-78c40c3bb12f.png)

**Desktop (please complete the following information):**
Windows 10
Browser: Firefox 68.7.0esr (64-bit)
Floccus 4.4.4

**Server (please complete the following information):**
CentOS 8
Nextcloud: 20
Bookmarks: 4.0.2

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
Will be provided to URL as soon as I manage to wipe out the current logs and recapture with less sensitive bookmark data. 

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Can you try a sync from scratch?

**Comment by fezie** [comment]
I have the same problem with Firefox 82.0.2

> Can you try a sync from scratch?

that does fix it for once, but on the next run it fails again

**Comment by NephtonLabs** [comment]
> 
> 
> Can you try a sync from scratch?

Wiped out everything. Reran tests. It seems to kind of work right up until you press the Sync Up arrow, and then it never works again.

**Comment by marco44** [comment]
I'm having the exact same problem. And restarting from scratch did the same. Only worked initially, then died at next sync attempt

**Comment by marco44** [comment]
Oh, I forgot to be more specific: nextcloud 19.0.4 here, bookmarks is 3.4.6, floccus 4.4.4, firefox 82.0.2

**Comment by wohali** [comment]
Exact same issue as marco44 above, exact same version numbers.

**Comment by Whissi** [comment]
I hit the same problem, Firefox 82.0.2 and floccus 4.4.4, still at bookmarks 3.4.5.

**Comment by geho** [comment]
Same issue
- Windows 10 64bit
- Firefox 82.0.2 (64 bit)
- Nextcloud 19.0.4 + Bookmarks 3.4.6
- Floccus 4.4.4
```
2020-11-02T05:56:11.748Z (local)ORDERFOLDER { id: 'root________',
  order: 
   [ { type: 'folder', id: 'menu________' },
     { type: 'folder', id: 'toolbar_____' },
     { type: 'folder', id: 'unfiled_____' },
     { type: 'folder', id: 'mobile______' } ] }
2020-11-02T05:56:11.773Z [Error: It's not possible to move Places root folders.]
2020-11-02T05:56:11.774Z Syncing failed with It's not possible to move Places root folders.
2020-11-02T05:56:12.271Z onSyncFail
```

**Comment by marcelklehr** [comment]
Should be fixed in v4.4.5

**Comment by NephtonLabs** [comment]
Tested 4.4.5, not seeing this issue anymore. 
Thank you very much. :)

**Comment by marco44** [comment]
Same here. Thanks

Le lun. 2 nov. 2020 à 22:18, NephtonLabs <notifications@github.com> a
écrit :
