### ISSUE TITLE
Floccus can not be installed on Android Fennec or Firefox.

### ISSUE THREAD

**Issue by NewB108** [marcelklehr/floccus#719]
Problem:
Floccus can not be installed on Android Fennec or Firefox.

Solution:
I think a signing process is needed...

https://support.mozilla.org/de/kb/add-on-signierung-firefox-fuer-android?as=u&utm_source=inproduct&redirectslug=unsigned-addons&redirectlocale=en-US

https://developer.mozilla.org/de/Add-ons/Distribution

**Comment by NewB108** [comment]
Ups, the extension does not work on an android device as ading an account for the sync process does not work....

Is there any chance to make floccus work on Firefox for Android?

**Comment by marcelklehr** [comment]
see #3 :)
