### ISSUE TITLE
Cannot create new folders locally

### ISSUE THREAD

**Issue by jayarc** [marcelklehr/floccus#72]
### Software versions

* Browser: 
* Nextcloud: 13
* Nextcloud Bookmarks app: latest stable
* Floccus: FF extension tests run ok, syncs fine

### Steps to reproduce
I'm running FF Dev Edition V60 and I'm syncing a custom folder (just my bookmarks toolbar). In FF if I right click on the bookmarks toolbar and create a new folder I quickly see a folder icon appear behind the window that comes up but it dissapears almost instantly from the bar and after I fill in the folder name in the popup window and hit save, it saves nothing because it looks like the original folder "prototype" if we're talking about code that was sitting in the bar vanished. I'm wondering if there's just another way for me to do this properly while using floccus?

### Expected outcome

...

### Actual outcome

...

**Comment by jayarc** [comment]
One of these days here I'll get the source open and send a PR instead of just bad news :P

**Comment by marcelklehr** [comment]
heh :) That would be awesome. Still, I appreciate bug reports, too! :)

**Comment by marcelklehr** [comment]
Should be fixed in the latest release.
