### ISSUE TITLE
Daily Nextcloud API Error

### ISSUE THREAD

**Issue by lightlike** [marcelklehr/floccus#720]
**Describe the bug**

Daily error:
Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: bookmark:969"} 
or
Nextcloud API error: {"status":"error","data":"Could not find folder"} 

Error is fixed by resetting Sync but reappears every evening at about 19:00 to 20:00 (German Time).

**To Reproduce**
1. Have working Sync
2. Wait to about 19:00 to 20:00
3. Error occures

**Expected behavior**

Should keep syncing properly

**Desktop:**
 - OS: Win10
 - Browser: Firefox
 - Browser Version: 82.0.2 (x64)
 - Floccus version: 4.4.4
 - Floccus sync method: Nextcloud Bookmarks

**Server:**
 - OS: OpenMediaVault 5 - Usul (Debian) Docker (Linuxserver.io)
 - Nextcloud version: 19.0.4
 - Bookmarks app version: 3.4.6

**Debug log**
Unable to get.

- [ ] Debug log provided

**Additional context**
Network has some Problems but Server is still reachable.

**Comment by marcelklehr** [comment]
Can you try running `occ maintenance:repair` on nextcloud?

**Comment by lightlike** [comment]
Did that. Now I'm waiting if this happens again this evening.

**Comment by lightlike** [comment]
It seems to be working now. I will observe for 1-2 more days and close this once nothing more comes up.

**Comment by lightlike** [comment]
Everything seems to be working correctly.

Now I only get everything removed due to the Nextcloud Bookmarks update yesterday :sweat_smile:. (good thing I have backups :relieved:)
