### ISSUE TITLE
4.4.6 on firefox cannot sync - claims that a lock file exists  

### ISSUE THREAD

**Issue by bhlevca** [marcelklehr/floccus#723]
**Describe the bug**
cannot sync fils with cannot remove lock file

**To Reproduce**
1 delete any lock file in nextcloud
2 press sync

**Expected behavior**
expect sync to happen

**Desktop (please complete the following information):**
 - OS: opensuse linux thumbleweed
 - Browser : firefox 
 - Browser Version 84
 - Floccus version: 4.4.6
 - Floccus sync method:  webdav

**Server (please complete the following information):**
 - OS: debian 
 - Nextcloud version: 19.4
 - Bookmarks app version: [if applicable]

**Debug log**
020-11-05T03:42:36.609Z onSyncStart: begin
a long list of 
2020-11-05T03:52:24.282Z https://nextcloud.hlevca.com/remot.php/webdav/bookmarks.xbel.lock

**Comment by bhlevca** [comment]
forgot to mention that 4.4.5 was working just fine, but the automatic update screwed it up

**Comment by marcelklehr** [comment]
> remot.php/webdav/bookmarks.xbel.lock

there's a typo in this URL

**Comment by bhlevca** [comment]
You are right. It was late last night and I did not see the missing `e`. 

Is there a way for the client to figure out when an URL is bad, some type of response from the server?

**Comment by bhlevca** [comment]
It seemed to work up to a point, but unlike 4.4.5 the "Cycle(s) detected; toposort only works on acyclic graphs" has resurfaced

**Comment by bhlevca** [comment]
It appears that lock management is too simple to handle multiple browsers competing for the resources. 
I switched to the Nextcloud App and even if it is slower the locking problems do not exist.   I think that a much more robust locking mechanism needs to be implemented on the WebDAV solution in order to work properly, Also the  problem with  duplicating children seems to be solved.

**Comment by marcelklehr** [comment]
Thank you for the feedback! I*m closing this for now.
