### ISSUE TITLE
Support Nextcloud instances protected with HTTP AUTH

### ISSUE THREAD

**Issue by andreas-bulling** [marcelklehr/floccus#730]
**Is your feature request related to a problem? Please describe.**
I have secured my NC instance with HTTP AUTH (Apache). NC supports to directly log in users with their HTTP AUTH credentials, i.e. they have to provide their credentials only once. floccus currently doesn't support this, i.e. I see an authentication error. 

**Describe the solution you'd like**
It would be nice if floccus used HTTP AUTH if required.

**Comment by marcelklehr** [comment]
In case you are talking about syncing with the nextcloud bookmarks app, please file an issue over at https://github.com/nextcloud/bookmarks
