### ISSUE TITLE
Add 'mirror' sync behaviour

### ISSUE THREAD

**Issue by heinhuiz** [marcelklehr/floccus#731]
Maybe I missed something, but I can't find how to do this.

I want the bookmarks on all my devices/browsers to be exactly the same. If I add a bookmark to one instance, it should be added to the others. And if I delete a bookmark from one device, it should be deleted from all other browsers.

'Merge local and remote changes' seems only to work with additions but not with removals.

How can I completely mirror all bookmarks on all instances? I'm using Nextcloud as server.

**Comment by marcelklehr** [comment]
'Merge local and remote changes' should work with removals. If it doesn't for you. That's a bug. Could you open a new issue for that filling out the bug report template instead? :heart:
