### ISSUE TITLE
No Sync with nextCloud 20.0.2

### ISSUE THREAD

**Issue by capricorn72** [marcelklehr/floccus#734]
nextCloud Version: 20.0.2
Bookmarks App in nextCloud: 4.0.5
Floccus: 4:3:0

Sync does not work, state "syncing..." for hours, restart does not change anything.
![Bildschirmfoto von 2020-12-03 13-15-38](https://user-images.githubusercontent.com/47882485/101017089-e97c2e80-3569-11eb-8026-42e747cc034e.png)

**Comment by marcelklehr** [comment]
Hi!
I'm sorry for your troubles. Could you provide an excerpt (with confidential information redacted) of your debug log so I can check what's wrong?

**Comment by marcelklehr** [comment]
Any news?

**Comment by marcelklehr** [comment]
Closing due to lack of response.
