### ISSUE TITLE
How to set port for webdav server

### ISSUE THREAD

**Issue by whyjxz14** [marcelklehr/floccus#735]
**Is your feature request related to a problem? Please describe.**
I don't know how to set the port for the WebDAV server
**Describe the solution you'd like**
For safety reasons, I only open a single random port for WEBDAV on my NAS, however, I find there is no option to set a port.
And if I set the port behind the address with a colon it fails.https://www.whateveraserver.ml:8888
**Describe alternatives you've considered**
ADD a port Setting as others did. 
**Additional context**
![image](https://user-images.githubusercontent.com/6323818/101284022-d40b3c80-37d5-11eb-8fdd-62b3d960745b.png)

**Comment by marcelklehr** [comment]
Adding the port in the URL should no longer fail in the latest version.

**Comment by whyjxz14** [comment]
> Adding the port in the URL should no longer fail in the latest version.

Still, E017 error，is my settings wrong?
I used the same on potplayer.
Should I change the bookmark URL?
Now log is empty

**Comment by marcelklehr** [comment]
The port doesn't seem to be the problem, then, afaict. Do you have a https server running at 8888 or just a http server? Do you use a self-signed certificate or a normal one?
