### ISSUE TITLE
Firefox 59.0.2 -- Open Floccus Options not working in version 2.0.6 with Bookmarks 0.11.0

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#74]
![screenshot9](https://user-images.githubusercontent.com/1787238/38450356-3479402c-39d1-11e8-8e67-412c9f15eb23.png)
**Open Floccus Options** button is non-responsive in version 2.0.6 on Firefox 59.0.2 (64-bit) MacOS with Bookmarks 0.11.0
-----
![screenshot11](https://user-images.githubusercontent.com/1787238/38450372-7c293044-39d1-11e8-9778-3e386849814a.png)
Next I tried selecting **Options** from the extension settings page, but all it did was re-direct me to the main about:addons page in Firefox.
![screenshot10](https://user-images.githubusercontent.com/1787238/38450376-9c38a162-39d1-11e8-8dca-a9e8ae3b1fdf.png)

**Comment by sunjam** [comment]
Tested current Chrome app release of Floccus and none of these issues were present.

**Comment by dud3r** [comment]
Have exactly the same issue on Firefox 59.0.2 (64bit) Linux and Nextcloud 13.0.0 / Bookmarks 0.11.0
After clicking on options I get redirected to about:addons

**Comment by marcelklehr** [comment]
Thanks for reporting this!
Temporary fix is to use the floccus button in your browser toolbar.

**Comment by marcelklehr** [comment]
This should be fixed in the latest release. :)
