### ISSUE TITLE
floccus sync error

### ISSUE THREAD

**Issue by yo-honey** [marcelklehr/floccus#741]
**Describe the bug**
when i click on sync now there is some error
see attached snap.

my account is connected & bookmarks app is already installed i can access it via browser.

**Expected behavior**
 sync properly

**Screenshots**
added

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Browser Version 83.0
 - Floccus version: 4.4.6
 - Floccus sync method: nextcloud

**Server (please complete the following information):**
 - Nextcloud version: 20.0.2
 - Bookmarks app version: 4.0.5

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [yes ] Debug log provided

**Additional context**

![floccus error](https://user-images.githubusercontent.com/46459324/101976129-58dbd780-3c68-11eb-895c-a4ca3dfa995d.png)

**Comment by marcelklehr** [comment]
Can you check the nextcloud log for errors?

**Comment by marcelklehr** [comment]
Any news?

**Comment by panachoi** [comment]
I have something similar, and checking the nextcloud log shows this:

{"reqId":"PpG1QnfMX9xctj4UCaCI","level":3,"time":"2021-01-20T11:16:02+00:00","re
moteAddr":"XXXX","user":"XXX","app":"index","method":"GET","url":"/
index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":{"E
xception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception o
ccurred while executing 'SELECT `b`.`id`, `b`.`url`, `b`.`title`, `b`.`descripti
on`, `b`.`lastmodified`, `b`.`added`, `b`.`clickcount`, `b`.`last_preview`, `b`.
`available`, `b`.`archived_file`, `b`.`user_id`, GROUP_CONCAT(`tree`.`parent_fol
der`) AS `folders`, GROUP_CONCAT(`t`.`tag`) AS `tags` FROM `oc_bookmarks` `b` LE
FT JOIN `oc_bookmarks_tree` `tree` ON (`b`.`id` = `tree`.`id`) AND (`tree`.`type
` = ?) LEFT JOIN `oc_bookmarks_tags` `t` ON `t`.`bookmark_id` = `b`.`id` LEFT JO
IN `oc_bookmarks_tree` `tr` ON (`tr`.`id` = `b`.`id`) AND (`tr`.`type` = ?) LEFT
 JOIN `oc_bookmarks_shared_folders` `sf` ON `tr`.`parent_folder` = `sf`.`folder_
id` LEFT JOIN `oc_bookmarks_tree` `tr2` ON (`tr2`.`id` = `tr`.`parent_folder`) A
ND (`tr2`.`type` = ?) LEFT JOIN `oc_bookmarks_shared_folders` `sf2` ON `tr2`.`pa
rent_folder` = `sf`.`folder_id` WHERE (`b`.`user_id` = ?) OR (`sf`.`user_id` = ?
) OR (`sf2`.`user_id` = ?) GROUP BY `b`.`id`, `b`.`url`, `b`.`title`, `b`.`descr
iption`, `b`.`lastmodified`, `b`.`added`, `b`.`clickcount`, `b`.`last_preview`, 
`b`.`available`, `b`.`archived_file`, `b`.`user_id`, `b`.`id` ORDER BY `b`.`last
modified` DESC, `b`.`id` ASC LIMIT 300' with params [\"bookmark\", \"bookmark\",
 \"folder\", \"XXX\", \"XXX\", \"XXX\"]:\n\nSQLSTATE[HY000]: General er
ror: 3 Error writing file '/tmp/MYTj8xjC' (Errcode: 28 - No space left on device
)","Code":0,

Which seems to indicate a full disk, but this is certainly NOT true. I'm at a loss to explain this error.

**Comment by marcelklehr** [comment]
@panachoi Stackoverflow gives me this: https://stackoverflow.com/questions/51150338/mysql-select-query-error-in-live-server-errcode-28-no-space-left-on-device Other than that, you may have run out of inodes, because of too many files: https://dba.stackexchange.com/questions/57543/mysql-error-28-no-space-left-on-the-device#57544

**Comment by panachoi** [comment]
Its very strange.

The database is remote, and has plenty of space, both where the DB is stored and in /tmp (tmpfs) and plenty of inodes.

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        46G   23G   21G  53% /
tmpfs           1.0G     0  1.0G   0% /tmp

Filesystem     Inodes IUsed IFree IUse% Mounted on

/dev/sda1        3.0M   70K  2.9M    3% /
tmpfs            248K    16  248K    1% /tmp

Hence my confusion.

**Comment by marcelklehr** [comment]
> Selections on columns without indexes use up a large amount of temporary disk space.

This may explain your problems. Some of your indexes may be  broken: https://github.com/marcelklehr/floccus/issues/792

**Comment by panachoi** [comment]
I'm just wondering how they got broke, at the moment. Was working without issues, and other than updating floccus, the server hasn't been touched (still running 19.0.1, I think).

**Comment by marcelklehr** [comment]
Have you ever had to recover a db backup?

**Comment by panachoi** [comment]
No, This is the "original" database that was created at installation of nextcloud (version of 17.0.1, migrated to 18.0.4 and currently 19.0.4). Everything else seems to work fine, just bookmarks appears broken, after updating the the latest Floccus App a few days ago. Maybe related to #792. ?

**Comment by marcelklehr** [comment]
Mh. Floccus shouldn't be able to break your server.

**Comment by mnalis** [comment]
`No space left on device` error can also happen if filesystem implements disk quotas for users or groups. (usually checked with `quota username`)
Another possibility might be if nextcloud itself enforces its disk usage per nextcloud user (I know it does it for pictures and files,  but I have no idea if other extensions like bookmarks might also be subject to those limits).

@panachoi  also, do you have other filesystems? mysql database is usually stored under `/var/lib/mysql`, which *might* be different partition than `/`

**Comment by panachoi** [comment]
The mysql database is remote; there are no users and no quotas on the DB or Nextcloud servers, and there is plenty of space in /tmp on both instances. So this looks like an "internal" mysql thing to me, although I cannot say exactly where the issue is, just that floccus stopped working.

**Comment by mnalis** [comment]
@panachoi  You should check with admin of your remote mysql instance, it looks like it is running out of space (or hitting quota). The `No space left on device` is usually very specific and does not happen unless that is exactly the case what the error says. It is just a matter of finding **on what host** (if they are multiple ones involved as with your case) and **on what partition** it is running out of space.

**Comment by marcelklehr** [comment]
@mnalis Thank you for chiming in with your expertise! :heart: Shall we continue this over at #792? OP seems unresponsive.
