### ISSUE TITLE
Log doesn't rotate in Brave

### ISSUE THREAD

**Issue by rogercreagh** [marcelklehr/floccus#742]
**Describe the bug**
Enabling Floccus v4.3.0 causes Brave to freeze for about 5-10 secs every 30-60 seconds when sync with Nextcloud

**To Reproduce**
Steps to reproduce the behaviour:
1. Install floccus extension on Brave, 
2. Set up sync on a Nextcloud server (v19.0.3) with Bookmarks app v3.4.9 (may be same with earlier versions)
3. Add about 200 bookmarks in about 100 folders nexted about 4 deep max
4. wait till sync has finished
5. stop and restart Brave - after about 50secs Brave will start freezing up every 20 secs or so.
6. Disable Floccus - problem goes.

**Expected behavior**
Brave should work and respond normally irrespective of what floccus is doing in the background.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.0.4
 - Browser Brave/Chrome
 - Browser Version 1.18.70 and all back to 1.11.97
 - Floccus version:  4.3.0
 - Floccus sync method: Nextcloud

**Server (please complete the following information):**
 - OS: Ubuntu 20.04, Apache 2.4.46, php 7.4.13
 - Nextcloud version: 19.0.3
 - Bookmarks app version: 3.4.9

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided - Ha! Clicking on debug log caused it to freeze and nothing happened. Where is the log file stored?

**Additional context**
It has only started happening in the last two weeks. Server software has not changed, Client has had standard Ubuntu stable updates.

**Comment by rogercreagh** [comment]
Further to the above after some difficulty I managed to get floccus to give me its log - its frigging huge - over 230Mb and seems to contain everything floccus has ever done since it was installed 6 months ago. 
Shouldn't it be possible to make it auto prune iteself once a day opr once a week?
How do I manually clear it - a search gives no clues?
No wonder it is struggling - where is the log stored and can I just delete it?
Aren't there options to reduce the log level to only errors?

**Comment by marcelklehr** [comment]
Mmh. The log should be rotated automatically. I'll look into this.

**Comment by rogercreagh** [comment]
Is there any progress on this? I haven't been able to use floccus since the upgrade to 4.3 as it overloads the browser. 
Two specific questions: 
1.Where is the log saved so that I can manually delete it? (using Chrome on Ubuntu)
2.Is there a way to revert to the previous working version? If so how, and wheredo I get it (obvs Chrome store only has the latest malfunctioning version)

**Comment by marcelklehr** [comment]
This is partially fixed in the latest release. (It now doesn't log anything anymore.) And will be completely fixed in the next release. (It will only keep the last sync run then.)
