### ISSUE TITLE
Floccus Options -- No ability to remove after clicking "Add Account"

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#75]
I'd like the ability to remove an account entry after clicking "Add Account" under options on Firefox or Chrome.  Only way to remove the entries, even if blank, is to completely uninstall the extension on either browser.  What I'm hoping for is a "Remove" button next to each account entry.
![screenshot12](https://user-images.githubusercontent.com/1787238/38460114-c72e189c-3a68-11e8-943d-b6c4c6e38223.png)

**Comment by marcelklehr** [comment]
/me think "Ah, finally an easy one :)"

1. Click on options
2. Click on delete account

**Comment by marcelklehr** [comment]
Ah, just saw you also filed #74, so this is kind of a tight spot, I guess. Closing this as it apparently follows directly from #74.
