### ISSUE TITLE
Why does floccus require `https://*/` instead of `activeTab` permission?

### ISSUE THREAD

**Issue by krsch** [marcelklehr/floccus#751]
**Is your feature request related to a problem? Please describe.**
I think giving an extension permission to access and modify data on all pages greatly increases a possible attack surface: a vulnerability in any of the extensions gives an attacker just too much access.

**Describe the solution you'd like**
Web extensions allows a developer to specify the `activeTab` permission. As MDN puts it "If an extension has the activeTab permission, then when the user interacts with the extension, the extension is granted extra privileges for the active tab only." Chrome store considers this permission harmless enough to hide it when showing extension permissions.

**Describe alternatives you've considered**
Another alternative is to remove `https://*/` permission. I don't see how floccus uses it.

**Additional context**
`activeTab` permission is described on [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission) and [Chrome Developers]( https://developer.chrome.com/docs/extensions/mv2/manifest/activeTab/)

**Comment by marcelklehr** [comment]
See the [README section on permissions](https://github.com/marcelklehr/floccus#permissions)

**Comment by krsch** [comment]
Sorry, didn't find it README. Isn't it possible switch to Permission API and runtime permissions?

**Comment by marcelklehr** [comment]
That's a good idea. I'll look into that, once the current issues have been resolved.
