### ISSUE TITLE
Unrecognized manifest key 'applications'

### ISSUE THREAD

**Issue by aktentasche** [marcelklehr/floccus#76]
### Software versions
* Browser: inox-bin 65.0.3325.162 (Developer Build) (64-bit)
* Nextcloud: 13.0.1
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce
1. Deleted all bookmarks and floccus 2.0.0
2. Installed floccus 2.0.6 using inoxunpack.py (https://github.com/gcarq/inoxunpack)
3. Added account, started sync

### Expected outcome
No Errors

### Actual outcome
Error:

![deepinscreenshot_select-area_20180408234953](https://user-images.githubusercontent.com/17249161/38472951-f674d5e4-3b87-11e8-8e28-bf2fa1b1faea.png)

Guess this might be inox specific. In any case, minor bug just for the sake of reporting ;)

**Comment by marcelklehr** [comment]
I can confirm the warning. This is a firefox-specific manifest key, which is not recognized by chromium. As long as it doesn't show up in the floccus UI, it's a harmless warning :)
Thanks for reporting anyway! :)
