### ISSUE TITLE
Floccus never propagates deletions, always adds them back in

### ISSUE THREAD

**Issue by morgannunan** [marcelklehr/floccus#760]
**Describe the bug**

**To Reproduce**
1. Delete and add bookmarks on one computer 1
2. Sync changes with Floccus
3. Go to computer 2 and sync with Foccus
4. Go back to computer 1

**Expected behavior**
The bookmark has been deleted on both sides. However, it hasn't, and when I go back to computer 1, the deleted bookmark is present again. This is especially messy when organizing bookmarks, because I'll move them to a subfolder and then they'lll be put back, so now I have the same bookmark in two places.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Vivaldi (Chromium)
 - Browser Version 3.5.2115.81
 - Floccus version: 4.3.0
 - Floccus sync method: Nextcloud

**Server (please complete the following information):**
 - OS: Ubuntu
 - Nextcloud version: 18.0.6
 - Bookmarks app version: 3.2.4

**Debug log**
When I click 'debug log', nothing happens.

**Comment by marcelklehr** [comment]
Thank you for your feedback. The v4.4.x series has been rolled out now on the chrome webstore, which should fix this. If you continue to experience problems feel free to open a new issue. :heart:
