### ISSUE TITLE
Trying to remove a non-existing item from OrderTracker: bookmark:190

### ISSUE THREAD

**Issue by nemihome** [marcelklehr/floccus#763]
**Describe the bug**
I made an initial sync (basically this was a client to server sync -> Target Nextcloud

After that I created no folders with manage bookmarks in chrome. Took me 10 minutes to run into this bug after new installation. It is reproducable. I did not get 2 syncs without errors.

**Expected behavior**
Sync should recognize movement of urls from one folder to another and just sync that to server

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 87.0.4280.88 
 - Floccus version: 4.3.0
 - Floccus sync method: Nextcloud

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Nextcloud version: Nextcloud 20.04
 - Bookmarks app version: 4.05

Note: Please write down the actual version numbers instead of writing 'latest'.

**Comment by marcelklehr** [comment]
I'm sorry for the delay. I've just released v4.4.7 for firefox with a lot of new fixes, hopefully that will fix this as well. A few issues remain, but I'm confident I'll be able to tackle those soon.

**Comment by nemihome** [comment]
Hi,

 

Thank you for the update. Do I have to test with Firefox or does it take a while until this is available for Chrome?

 

https://chrome.google.com/webstore/detail/floccus-bookmarks-sync/fnaicdffflnofjppbagibeoednhnbjhg

 

4.3.0

 

 

Von: Marcel Klehr <notifications@github.com> 
Gesendet: Dienstag, 5. Januar 2021 17:13
An: marcelklehr/floccus <floccus@noreply.github.com>
Cc: nemihome <nemihome@yahoo.de>; Author <author@noreply.github.com>
Betreff: Re: [marcelklehr/floccus] Trying to remove a non-existing item from OrderTracker: bookmark:190 (#763)

 

I'm sorry for the delay. I've just released v4.4.7 for firefox with a lot of new fixes, hopefully that will fix this as well. A few issues remain, but I'm confident I'll be able to tackle those soon.

**Comment by marcelklehr** [comment]
Ah, yes, I didn't realize you were using chrome. The new version is only available on firefox for now, but will be rolled out on Chrome soon.

**Comment by marcelklehr** [comment]
The new version is now out for chrome as well.

**Comment by nemihome** [comment]
Hi, thank you for the update. I have made fist tests which were ok on one browser. On weekend I will maybe do some more testing with a second PC.

**Comment by marcelklehr** [comment]
I'll close this for now. Feel free to open a new issue, should you run into more problems, but I hope you won't :relaxed:
