### ISSUE TITLE
Syncing failed with Cannot add empty mapping

### ISSUE THREAD

**Issue by frankgerhardt** [marcelklehr/floccus#764]
**Describe the bug**

> 2021-01-02T22:55:54.569Z [Error: Cannot add empty mapping]
> 2021-01-02T22:55:54.569Z Syncing failed with Cannot add empty mapping

**To Reproduce**

?

A better error message would have been helpful. Is there anything wrong with any bookmark? Maybe I could edit or delete that bookmark. What is the context when this happens? Upload or download? At least the error message could say with was it trying to map. Even if something is empty the other side of the mapping would not be empty. 

Did the sync fail completely or is it only a bit incomplete?

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser FF
 - Browser Version 78.6.0esr
 - Floccus version: 4.4.6
 - Floccus sync method:  nextcloud folders

**Server (please complete the following information):**
 - OS: Hetzner hosting
 - Nextcloud version: 19.0.3
 - Bookmarks app version: 3.4.9

**Comment by marcelklehr** [comment]
v4.4.8 is out now. This issue should be fixed in the latest version. I'm closing this for no. Feel free to shout if you continue to experience problems.
