### ISSUE TITLE
Profiles not saved

### ISSUE THREAD

**Issue by jochen-01** [marcelklehr/floccus#766]
**Describe the bug**
In Mozilla Firefox profiles are not saved when leaving the browser.
**To Reproduce**
Install Floccus, create profile (here: WebDAV), configure profile, activate profile if necessary, start initial sync.

**Expected behavior**
If leaving, then starting filefox the sync profile should look like created before. Instead 
"No accounts here
Create a new account to sync your bookmarks. "
appears.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Browser Version 84.0 (64-Bit)
 - Floccus version: 4.4.6
 - Floccus sync method: webdav

**Server (please complete the following information):**
 - OS: Linux, Apache 2.x, WebDAV

**Comment by jochen-01** [comment]
Sorry for closing the issue. It seemed to work but didn't every time. Weired.
Settings are not saved.

**Comment by marcelklehr** [comment]
So, the settings are not persisted between browser restarts or the whole account is removed? Or are the settings just not saved regardless of restart?

**Comment by jochen-01** [comment]
The whole account is lost between restarts. It shows
" No accounts here
Create a new account to sync your bookmarks. "

Within the same session the settings are saved (or seems to).

**Comment by jochen-01** [comment]
A few tests revealed that it has been an installation issue of firefox. After resolving it can say it has nothing to do with floccus. 
Floccus works as expected now.
