### ISSUE TITLE
Process to remove "Invalid Bookmarks"

### ISSUE THREAD

**Issue by sunjam** [marcelklehr/floccus#768]
**Is your feature request related to a problem? Please describe.**
Floccus will list any _Invalid Bookmarks_ and display a red !
![floccus-error](https://user-images.githubusercontent.com/1787238/103575907-357f0380-4e87-11eb-9713-79aae3b2c3f7.PNG)

**Describe the solution you'd like**
Optionally allow Floccus to remove the invalid bookmark entries it finds.  Possibly related to #744 

**Describe alternatives you've considered**
Export as html, delete all bookmarks from Nextcloud, manually remove the entries from the html file in a text editor, and re-import.

Thanks for considering either way!

**Comment by marcelklehr** [comment]
Which error message is that? Usually, floccus should just ignore bookmarks that are not accepted by the bookmarks app.

**Comment by sunjam** [comment]
Unable to screencap, but text copy-pasted from the extension is:

 nextcloud-folders                 Error
Floccus (account@example.org)
account@example.org

_Invalid bookmark: {"title":"Pixel Artist tool for android art","type":1,"url":"http://pixel artist (make pixel art on android) - https/f-droid.org_

**Comment by r4taw2mg** [comment]
Possibly related. I cannot get sync to work after updating the local server software (Firefox based):

2021-01-28T21:00:38.025Z COMPARE { localItem: null,
  cacheItem: null,
  serverItem:   - #354[](data:) parentId: 41 }
2021-01-28T21:00:38.026Z (local)CREATE     - #undefined[](data:) parentId: wElDPdrlxsGJ
2021-01-28T21:00:38.036Z Syncing failed with Invalid bookmark: {"title":"","type":1,"url":"data:","parentGuid":"wElDPdrlxsGJ"}
2021-01-28T21:00:38.040Z onSyncFail

**Comment by sunjam** [comment]
Update: Error I'm seeing has slightly changed.

`Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: bookmark:52301"} `

**Comment by marcelklehr** [comment]
@r4taw2mg Please open a new issue and fill out the template: Which version of floccus is that?  What kind of "local server software" are you talking about?

**Comment by marcelklehr** [comment]
@sunjam please see #800 (which is unsolved)
