### ISSUE TITLE
webdev & xbel not working

### ISSUE THREAD

**Issue by brgbrg** [marcelklehr/floccus#773]
I am trying the webdav / xbel file method.

I exported and imported the following settings:

[
  {
    "localRoot": "toolbar_____",
    "strategy": "default",
    "syncInterval": 15,
    "nestedSync": false,
    "type": "webdav",
    "url": "webdavs://[server]:8443/nextcloud/remote.php/webdav/",
    "username": "[myuser]",
    "password": "[mypassword]",
    "bookmark_file": "01_system/bookmarks.xbel",
    "enabled": false,
    "syncing": false,
    "error": ""
  }
]

I successfully ensured using a file manager, that I can read and write to the directory:
   webdavs://[server]:8443/nextcloud/remote.php/webdav/01_system/
using the same username and password copied from above. There is no file bookmarks.xbel at this time

When trying to synch, I get the following error message: "E017: Netzwerk-Fehler: Überprüfen sie Ihre Netzwerkverbindung und die eingegebenen Konto-Daten" 

**Desktop (please complete the following information):**
 - OS: [OpenSuse Leap 15.2]
 - Browser [Firefox 78.6.0esr (64-Bit)]
 - Browser Version [e.g. 78.6.0esr (64-Bit)]
 - Floccus version: [e.g. 4.4.6]
 - Floccus sync method: [webdav]

**Server (please complete the following information):**
 - OS: [OpenSuse Leap 15.2, which comes with Apache/2.4.43 (Linux/SUSE); running in a virtual box virtual machine]
 - Nextcloud version: [20.0.4]
 - Bookmarks app version: [4.0.5 - should be irrelevant for webdav - xbel]

**Debug log:
2021-01-05T10:54:57.174Z onSyncStart: begin
2021-01-05T10:54:57.175Z webdavs:breuning.selfhost.eu:8443/nextcloud/remote.php/webdav/01_system/bookmarks.xbel.lock
2021-01-05T10:54:57.181Z Syncing failed with E017: Netzwerk-Fehler: Überprüfen sie Ihre Netzwerkverbindung und die eingegebenen Konto-Daten
2021-01-05T10:54:57.185Z onSyncFail
2021-01-05T10:54:57.188Z Error Caught
2021-01-05T10:54:57.189Z [TypeError: NetworkError when attempting to fetch resource.]

**Comment by marcelklehr** [comment]
Please fill out the issue template, especially which software versions you are using.

**Comment by marcelklehr** [comment]
Ah, I just noticed you used "webdavs" as protocol. This should be https.

**Comment by brgbrg** [comment]
Thanks, now working for me
