### ISSUE TITLE
Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this!

### ISSUE THREAD

**Issue by pablohess** [marcelklehr/floccus#78]
### Software versions

* Browser: Firefox 59.0.2
* Nextcloud: 13.0.1
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce

1. Added floccus to Firefox
2. Created account
3. Changed Folder in Options to "bookmark toolbar"
4. Synced

### Expected outcome

sync completes successfully

### Actual outcome

Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this!
url=https://fontawesome.com/v4.7.0/

**Comment by marcelklehr** [comment]
Hey there, sorry for the delay!
I have a few questions for you. Did you already have any bookmarks on the server before syncing? Had you synced to the server before syncing it with the toolbar. Does this happen everytime you sync?

**Comment by pablohess** [comment]
I can't reproduce it anymore with floccus 2.1.0.

But I'm using now the root folder as sync folder. Before I used the bookmark toolbar.

**Comment by marcelklehr** [comment]
I've opened a pull request upstream, that fixes this https://github.com/nextcloud/bookmarks/pull/479

**Comment by marcelklehr** [comment]
This should be fixed in v2.2.2 now. Let me know if you still experience this error.
