### ISSUE TITLE
Basic Authentification

### ISSUE THREAD

**Issue by blackes0x** [marcelklehr/floccus#783]
**Describe the bug**
This APP only uses Basic Authentification to authorize against the nextcloud server. This is a critical security Issue. 

**To Reproduce**
Intercep the traffic with Burp and you will find.

**Comment by marcelklehr** [comment]
This is only a security issue if you're not using TLS. And if you're not using TLS that's your security issue. There's no way to authenticate to the server with a password without it being a critical security issue when you don't use TLS.
