### ISSUE TITLE
Emojis in folder names cause folder paths to be dropped

### ISSUE THREAD

**Issue by Lantizia** [marcelklehr/floccus#79]
### Software versions
* Browser: Chrome 65
* Nextcloud: 12.0.5
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce
1. Donate, whether it works entirely or not yet - this is damned fine software (in theory) and needs supporting.
2. On my home PC I copied all my bookmarks (about 2500 of them) into the bookmark folder that floccus uses for syncronisation.
3. Went onto my work PC (with a new install/profile of Chrome) and tried to sync them down.

### Expected outcome
It to sync up properly and down properly?

### Actual outcome
Noticed that a tonne of my bookmark folders were not preserved but it didn't give any errors either, it just uploaded them anyway without the folder structure.  Folders with names like 'A-B-C' and '♪' worked... but other folders (and also likely because of it - all subfolders too that depended on it) with names like '🏢 💡' or '⚙ 🔬' didn't work.

**Comment by marcelklehr** [comment]
(Using emojis for folder names is an amazing idea, btw! :D)

**Comment by Lantizia** [comment]
yeah it saves tonnes of space on the bookmarks bar :)  like... 🏢 💡 which I mentioned before is my way of saying to myself 'ideas I had at work' :D

**Comment by marcelklehr** [comment]
Mmh, some emojis work, some don't. That's weird.

**Comment by marcelklehr** [comment]
With the latest version of floccus plus the release candidate of the bookmarks app this seems to be fixed.

**Comment by EmperorArthur** [comment]
It's good to hear this has been fixed, in the RC.  Sadly the one on the store has yet to be updated.

Note:  this bug also affects individual bookmarks with emojis in their name.

**Comment by marcelklehr** [comment]
bookmarks v0.12.0 has just been released ;)
