### ISSUE TITLE
Syncing Error: Syncing failed with E020...

### ISSUE THREAD

**Issue by trupf** [marcelklehr/floccus#790]
As the header say I get a syncing error:

2021-01-14T20:05:55.988Z Starting sync process for account trupf@trhome.my-router.de
2021-01-14T20:05:56.058Z Using "merge default" strategy (no cache available)
2021-01-14T20:06:02.768Z Fetching bookmarks
2021-01-14T20:06:03.461Z Syncing failed with E020: Antwort des Servers konnte nicht gelesen werden. Ist die Bookmarks App auf Ihrem Server installiert?
JSON.parse: unexpected character at line 1 column 1 of the JSON data*Describe the bug**

Nextcloud version: 30.7
Bookmarks version 4.0.5
Floccus Version : 4.4.7

I use TOTP in Nextcloud with an app password for floccus. It was working with  nextcloud version 19. (I don't remember which floccus and bookmark versions I used at that time)

**Comment by marcelklehr** [comment]
If the app is installed on your nextcloud, this may indicate a server error. You can try to find out more with the following steps:

#### Firefox
* Go to `about:debugging`
* Click on 'This firefox'
* click on `inspect` button next to floccus entry
* go to the network tab in the inspector tab
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests


Also check the nextcloud log for errors.

**Comment by trupf** [comment]
Don't know about the reason, but after a restart of my webserver it is working again.
