### ISSUE TITLE
[chrome ext] update page gives an error 404

### ISSUE THREAD

**Issue by Albirew** [marcelklehr/floccus#793]
**Describe the bug**
After update on chrome-based browser, it automatically opens an "updated" page witch gives an error 404

**To Reproduce**
1. install old version or wait for an update
2. (self) update
3. See error

**Expected behavior**
page `chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/html/options.html#/update` shows with update notes link or whatever

**Current behavior**
page `chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/options.html#/update`opens giving an error 404 (miss dist/html/ in path)

**Desktop (please complete the following information):**
 - OS: should be any (shown on win 7 & 10)
 - Browser vivaldi
 - Browser version 3.5.2115.87
 - Floccus version: 4.4.8
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: debian 10
 - Nextcloud version: 20
 - Bookmarks app version: 4.0.6

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Thanks for the heads up. Fixed now :)
