### ISSUE TITLE
Password from floccus sync appears in nextcloud logs

### ISSUE THREAD

**Issue by realitygaps** [marcelklehr/floccus#8]
Messages in logs include:

\/index.php\/apps\/bookmarks\/public\/rest\/v1\/bookmark?user=USERNAME&password=PASSWORD

with nextcloud password in plain text.

**Comment by marcelklehr** [comment]
Hi @realitygaps!
Thanks for reporting this. I'm afraid that's a flaw with the nextcloud bookmarks app, which is [being addressed](https://github.com/nextcloud/bookmarks/pull/322) in the upcoming release, however.

**Comment by realitygaps** [comment]
ah thanks for the information, ill wait for the update then. 
also thanks for this extension :)

**Comment by marcelklehr** [comment]
This is fixed now.

**Comment by 9662** [comment]
Hello @marcelklehr, many thanks for your work on this project! 😊

> This is fixed now.

Would that be in [0.10.0](https://github.com/nextcloud/bookmarks/milestone/3)? I have that installed and it is still leaking the plaintext app password. Should I open a bug in the Nextcloud tracker?

**Comment by 9662** [comment]
> I have that installed and it is still leaking the plaintext app password.

Never mind. Disabling and re-enabling the Bookmarks app in Nextcloud did it.
