### ISSUE TITLE
Doesn't like duplicate bookmarks - even in different folders

### ISSUE THREAD

**Issue by Lantizia** [marcelklehr/floccus#80]
### Software versions
* Browser: Chrome 65
* Nextcloud: 12.0.5
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce
1. Donate, whether it works entirely or not yet - this is damned fine software (in theory) and needs supporting.
2. On my home PC I copied all my bookmarks (about 2500 of them) into the bookmark folder that floccus uses for syncronisation.
3. Went onto my work PC (with a new install/profile of Chrome) and tried to sync them down.

### Expected outcome
It to sync up properly and down properly?

### Actual outcome
When they were actually syncing up for the first time it stopped half way through and complained that 8 of them are "bookmarked twice locally".  Saying that I needed to delete one of the two... so I did... and then it continued on just fine *I think*.  Suffice to say, sometimes I like to bookmark the same thing twice under two different folders representing two different projects.  It really shouldn't have an issue with this?  if possible?

**Comment by marcelklehr** [comment]
This is a known issue. the bookmarks app doesn't allow duplicates, so solving this would mean a lot of workarounds (the folders-to-tags functionality already bein a workaround...)

**Comment by Lantizia** [comment]
Have raised this with the Bookmarks App github issues section.  Could this possibly be kept open until maybe this gets addressed with the app?

**Comment by marcelklehr** [comment]
I still think this would be the better place to address this, as I think the bookmarks app shouldn't need to fix issues that result from a different app.

**Comment by marcelklehr** [comment]
I've found a solution which allows the creation of duplicate bookmarks on the client and syncs them to the bookmarks app by creating two tags (so much was obvious, the implementation details were not :D). The upcoming release of v3 will feature this functionality as well as the XBEL/WebDAV backend which naturally allows duplicates and plays much better with move operations. Stay tuned :)

**Comment by marcelklehr** [comment]
This is fixed in the latest beta version, now. See #131 :)
