### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jeanoo** [marcelklehr/floccus#801]
**Describe the bug**
The synchronization could not finish, I got the following error: 
Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: folder:3508"} 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [Firefox]
 - Browser Version [84.0.2]
 - Floccus version: [4.4.8]
 - Floccus sync method: [ nextcloud folders]

**Server (please complete the following information):**
 - OS: [raspbian]
 - Nextcloud version: [20.0.4]
 - Bookmarks app version: [4.0.6]

**Comment by marcelklehr** [comment]
Thank you for your feedback, I will try to help troubleshoot. However, this is basically the same error as #800. Let's merge these two.
