### ISSUE TITLE
ALL CHILD bookmarks deleted!

### ISSUE THREAD

**Issue by dsiminiuk** [marcelklehr/floccus#802]
**Describe the bug**
4.4.8 and bookmarks 4.0.6 were working well for me.
I updated to bookmarks 4.0.7 earlier today
I updated to floccus 4.4.9 today also.
All folders remain but are now empty.

**To Reproduce**
Click Sync

**Expected behavior**
Bookmarks would sync?

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi (Chromium)
 - Browser Version  3.5.2115.87 (Stable channel) (64-bit)
 - Floccus version: 4.4.9
 - Floccus sync method: Nextcloud Bookmarks

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Nextcloud 20.0.6
 - Bookmarks app version: 4.0.7 (update to 4.0.8 pending)

**Debug log**
Clicking DEBUG LOG button produces no file.

**Additional context**

**Comment by dsiminiuk** [comment]
Updated bookmarks to 4.0.8 and restoring bookmarks from a laptop I haven't turned on since last night :)

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/bookmarks/issues/1390
