### ISSUE TITLE
E17 Network Error when using apache reverse proxy, but only on chrome

### ISSUE THREAD

**Issue by CrimsonFez** [marcelklehr/floccus#804]
I have Nextcloud setup through an Apache reverse proxy, so far everything for standard Nextcloud is working as intended. I get E17: Network Error when I try to sync to Nextcloud when using the Chrome client on Brave. I don't have any issues logging into Nextcloud with the Nextcloud login flow feature. The issue doesn't show when using Firefox and I can sync my bookmarks. 

**To Reproduce**
1. Setup Nextcloud behind reverse proxy
2. Try to sync the chrome client

**Expected behavior**
Bookmarks should sync properly

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Brave
 - Browser Version: Version 1.19.88 Chromium: 88.0.4324.96
 - Floccus version: 4.4.9
 - Floccus sync method: Nextcloud

**Server (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Nextcloud version: 20.0.6
 - Bookmarks app version: 4.0.6

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
When I try to export a debug log from the plugin the file is empty.

Additionally, All testing was done over a VPN as not to cause issues with local DNS. That is an issue I will solve later.

**Comment by marcelklehr** [comment]
Can you try inspecting the network requests as follows?

#### Firefox
* Go to `about:debugging` -> `This firefox`
* click on `inspect` button next to floccus entry
* go to the network tab in the inspector tab
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by CrimsonFez** [comment]
I'm not sure if the extension update fixed the issue or If the cache was changed. In Firefox I had it set to always clear page caches. But it's working now.
