### ISSUE TITLE
Icons not being preserved

### ISSUE THREAD

**Issue by Lantizia** [marcelklehr/floccus#81]
### Software versions
* Browser: Chrome 65
* Nextcloud: 12.0.5
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce
1. Donate, whether it works entirely or not yet - this is damned fine software (in theory) and needs supporting.
2. On my home PC I copied all my bookmarks (about 2500 of them) into the bookmark folder that floccus uses for syncronisation.
3. Went onto my work PC (with a new install/profile of Chrome) and tried to sync them down.

### Expected outcome
It to sync up properly and down properly?

### Actual outcome
When all the bookmarks got downloaded on the work PC... none of them had any bookmark icons any more.  This would be very nice as things are just a lot more easy to recognise with the icons... I even use an extension to manually set icons sometimes so that the bookmark doesn't even need a name (a string of just "") so it can take less room on the bookmarks bar and just be recognisable by icon alone.

**Comment by marcelklehr** [comment]
Good point! This is currently not possible with the webextensions API, but the browser should usually populate the icons automatically, once you visit the URLs.

**Comment by marcelklehr** [comment]
Mmmh. Interesting. I have no idea how they pull that off.

**Comment by marcelklehr** [comment]
A possibility would be to load the bookmark url in the background on creation somehow. I will look into this when I have time. It's not a priority for me at the moment.

**Comment by marcelklehr** [comment]
just fyi, I just found this extension by chance which allows you to reload the favicons of your bookmarks: https://addons.mozilla.org/en-US/firefox/addon/checkmarks-web-ext

Just until I get around to implementing this in floccus itself :)

**Comment by Lantizia** [comment]
Lo,

Just wanted to say that I've been temporarily storing URLs in a text file for the last couple of months while I re-install a few machines until I get settled again.  Just installed the new floccus (using the XBEL method) and seems to be working great.

Have also restarted the liberapay thingy - apparently it went a bit odd with their payment processor a while back.

I was wondering (in terms of this issue), if perhaps since the DTD for XBEL has stayed stagnant for a while... if floccus is now the most prominent use of it?

If it is stagnant (or perhaps if we can reach out to the maintainers of it for a comment on that?)... then maybe we can work on a 1.2 version (there already seems to be 1.1 - but I can't find the DTD for it... and floccus is using 1.0)... where we could add in some mechanism for recording the icons as base64 or something.

As mentioned before, browser extensions (like Bookmark Favicon Changer) do have the ability to read and even change favicons associated with bookmarks - so some mechanism must exist.

Thanks for all the hard work guys.

:)

**Comment by marcelklehr** [comment]
I think this is borderline out of scope for this project. It's probably a nice feature, but not something I prioritize. I'm closing this for now.
