### ISSUE TITLE
IIS WebDAV Server

### ISSUE THREAD

**Issue by stefreimer** [marcelklehr/floccus#813]
I installed floccus as Firefox-addon on two Windows Clients and use IIS on a Windows server as webdav server. 
I made the identical configured on both floccus clients with the same account, but every client can only sync its own bookmarks. If I make a change on one client, the complete xbel file will be replaced. There seems no way to merge the data from the two clients.
Can it be a problem with the IIS, that it has a weak webav compatibility maybe? Or should it work and I made a mistake in client configuration?
Unfortunately I can't give you a debug file, because the file is always empty.

Regards,
Stefan

**Comment by marcelklehr** [comment]
I second what the bot said, but it sounds like you set the sync strategy to "Override", perhaps.
