### ISSUE TITLE
sync with IIS

### ISSUE THREAD

**Issue by stefreimer** [marcelklehr/floccus#814]
### Describe the bug
I installed floccus as Firefox-addon on two Windows Clients and use IIS on a Windows server as webdav server.
I made the identical configured on both floccus clients with the same account, but every client can only sync its own bookmarks. If I make a change on one client, the complete xbel file will be replaced. There seems no way to merge the data from the two clients.
Can it be a problem with the IIS, that it has a weak webav compatibility maybe? Or should it work and I made a mistake in client configuration?

### Desktop
(please complete the following information)
 - OS: Windows
 - Browser firefox
 - Browser Version 85
 - Floccus version: 4.4.9
 - Floccus sync method: webdav

### Server
(please complete the following information)
 - OS: IIS Windows 2019
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

Unfortunately I can't give you a debug file, because the file is always empty.

**Comment by stefreimer** [comment]
Sorry, I forgott the screenshots of my configuration
![Floccus bookmark sync-1](https://user-images.githubusercontent.com/78314401/106392467-44a79180-63f2-11eb-86ec-cecb2dd3e323.jpg)
![Floccus bookmark sync-2](https://user-images.githubusercontent.com/78314401/106392468-45402800-63f2-11eb-82fd-7d999b822e77.jpg)

**Comment by marcelklehr** [comment]
Mmmh, that's a tricky one. Floccus shouldn't outright replace an existing file. Could you check the network as follows?

#### Firefox
* Go to `about:debugging` -> `This firefox`
* click on `inspect` button next to floccus entry
* go to the network tab in the inspector tab
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by stefreimer** [comment]
I did this. You can see the result in the attachment. It is strange. Floccus gets back 'not found'. so it created always an new xbel file. It seems to be a misconfiguration of the IIS, but I have no idea, where the error could be. It can't be a missing right, because floccus is able to create the file.
![debug-sync-floccus](https://user-images.githubusercontent.com/78314401/107126221-cdb93f80-68ae-11eb-8c9a-dc0395115b87.jpg)

**Comment by marcelklehr** [comment]
You may want to try http://forums.iis.net/. If it turns out there's something I can fix on my side, let me know here :)

**Comment by marcelklehr** [comment]
It is likely that this is resolved with v4.5.0, I've been able to reproduce and fix a similar issue (see #824) :)
