### ISSUE TITLE
import/export tools

### ISSUE THREAD

**Issue by test-0-zero** [marcelklehr/floccus#826]
### Is your feature request related to a problem? Please describe.
I need to set up some computers.

### Describe the solution you'd like
I would like an import and export features.

### Describe alternatives you've considered
the only solution is to manually copy the configurations, but I don't know how.

### Additional context
it should work for both ff and chrome.

**Comment by marcelklehr** [comment]
You can find the config import/export functionality next to the "New account" button in the account overview.
