### ISSUE TITLE
Empty bookmark folders not syncing

### ISSUE THREAD

**Issue by Lantizia** [marcelklehr/floccus#83]
### Software versions
* Browser: Chrome 65
* Nextcloud: 12.0.5
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce
1. Donate, whether it works entirely or not yet - this is damned fine software (in theory) and needs supporting.
2. On my home PC I copied all my bookmarks (about 2500 of them) into the bookmark folder that floccus uses for syncronisation.
3. Went onto my work PC (with a new install/profile of Chrome) and tried to sync them down.

### Expected outcome
It to sync up properly and down properly?

### Actual outcome
Empty bookmark folders must not be syncing up, as when you try to sync them down - they don't appear.  I'm guessing this is because the folders are preserved through the use of tags in the database, and the code won't make a tag to then not use it against any actual bookmark entries (also since I'm here, I've noticed the database makes the same tag *many* times per folder - isn't this just duplication?).  Whilst this might make sense from a code point of view... I like to make the occasional empty bookmark folder to help me lay out areas in the bookmark bar for future projects that I need to popular bookmarks for.  Essentially it's an organisational thing.

**Comment by Lantizia** [comment]
Have taken this up on the Bookmarks App github issues (one was already open), perhaps this could be left open until this is taken care of on that end?

**Comment by marcelklehr** [comment]
This will not be fixed in the bookmarks app, and can only be worked around in floccus, by not using the bookmarks app. Floccus v3 provides a WebDAV adapter as an alternative. Feel free to help testing #27
