### ISSUE TITLE
Using Floccus with internally hosted Nextcloud does not work

### ISSUE THREAD

**Issue by jahway603** [marcelklehr/floccus#834]
### Describe the bug
Using Floccus with internally hosted Nextcloud does not work
### To Reproduce
1. Click on Floccus in toolbar
2. Click on '+ New Account'
3. Choose "Nextcloud Bookmarks" option
4. Click on 'Add Account'
5. Enter 'https://192.168.x.x' for Nextcloud URL
6. Enter correct username and password
7. Leave the other options as default
8. Click on 'Save'
9. Close that window
10. Click on Floccus in toolbar again
11. Click on 'Sync Now' button
12. Receive the following error message: "E017: Network error: Check your network connection and your account details"
13. Bookmarks fail to sync to internal Nextcloud server

### Expected behavior
At Step 11 above, the expected behavior is that the bookmarks begin syncing and successfully finish. I have tried on a friend's Nextcloud server (not internal) and that does not have any issues with this plugin.

### Desktop
(please complete the following information)
 - OS: [e.g. iOS] Arch Linux
 - Browser [e.g. chrome, safari] Chromium
 - Browser Version [e.g. 22] 88.0.4324.150
 - Floccus version: [e.g. 3.2.2] 4.5.0
 - Floccus sync method: [e.g. webdav, nextcloud legacy or nextcloud folders] nextcloud folders

### Server
(please complete the following information)
 - OS: [e.g. centOS 7] Arch Linux
 - Nextcloud version: [if applicable] 20.0.7
 - Bookmarks app version: [if applicable] 4.0.8

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw
Debug log only contains:
2021-02-14T00:32:55.119Z Starting sync process for account username@192.168.x.x
2021-02-14T00:32:55.155Z Using "merge default" strategy (no cache available)
2021-02-14T00:32:55.244Z Syncing failed with E017: Network error: Check your network connection and your account details
- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Have you added the correct port and the http(s) prefix? Can you access the locally hosted server with your browser's URL bar? If the server is secured with a certificate, make sure it's added to the browser.

**Comment by jahway603** [comment]
Issue resolved after using the [mkcert tool](https://github.com/FiloSottile/mkcert) to add the certificate to the browser. Thank you for this great plugin!
