### ISSUE TITLE
pathSegment is undefined -- Path tag corrupted when editing in bookmarks app

### ISSUE THREAD

**Issue by andreas-bulling** [marcelklehr/floccus#88]
Hi,

I've installed the latest Nextcloud and Floccus versions and use this setup in combination with Firefox 58.0.2 on MacOSX.

Syncing worked fine as long as I only sync from the server to my browser. I just added the first bookmark in my browser and, while syncing back to the server worked, I now see an error message:
"pathSegment is undefined"

Any ideas?

**Comment by marcelklehr** [comment]
Hey @andreas-bulling 
It looks like there's a problem with creating a folder on the client. Could you provide logs as follows?

In order to aid in debugging, please provide client-side logs.

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* allow access
* clear the console
* go to floccus options
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and copy the logs after waiting for the sync to finish (or fail)

**Comment by andreas-bulling** [comment]
Here is the debugging output:
```
Starting sync process for account REMOVED  Account.js:105:6
Fetching bookmarks Object { type: "nextcloud", url: "REMOVED", username: "REMOVED", password: "REMOVED", syncing: true, localRoot: "REMOVED", error: "pathSegment is undefined", lastSync: 1523975824153 }  Nextcloud.js:123:4
Received bookmarks from server Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 53 more… ]  Nextcloud.js:172:4
LOCALUPDATE Object { id: "62", localId: "c1IPsiZcPsW4", url: "https://link.springer.com/article/1…", title: "Control blindness: Why people can m…", path: "&gt;", hashValue: 1705076786 }  Tree.js:95:4
Error: 1 errors
Stack trace:
MultiError@moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/background-script.js:304:9
next/<@moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/background-script.js:423:36
run@moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:4295:22
notify/<@moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:4308:30
flush@moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:1398:9
  Account.js:137:57
Syncing failed with pathSegment is undefined  Account.js:138:8
	_callee8$ Account.js:138:8
	tryCatch moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:6900:37
	invoke moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:7138:22
	defineIteratorMethods/</prototype[method] moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:6952:16
	step moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/background-script.js:4907:183
	step/< moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/background-script.js:4907:402
	run moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:4295:22
	notify/< moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:4308:30
	flush moz-extension://66961562-f723-404e-8333-1416a9f25bbf/dist/js/polyfill.js:1398:9
```

I think I know where the problem is. The tag (which floccus adds automatically) is not "floccus:>" as for all the others but "floccus:&amp;gt;" for the object in question 62. I added this bookmark using floccus but just checked an others that I also added the same way are fine.

Probably the easiest solution (and cleaner as well in my opinion) is to remove the superfluous ":>" in the tag that floccus creates.

**Comment by andreas-bulling** [comment]
I actually think the bug is in Floccus. I can edit/fix the tags using the NextCloud web interface, that all seems to work fine. Adding bookmarks with the link that one can drag into the bookmarks toolbar also works. Only adding using floccus doesn't work.

As I said, I'd remove this weird ":>" anyway...

**Comment by andreas-bulling** [comment]
Adding a new bookmark with Floccus doesn't work == adds the bookmark but produces the wrongly encoded tag.

The bookmark that caused the error I had also added with Floccus so, yes, when the error occurred that bookmark was already on the server.

**Comment by andreas-bulling** [comment]
Hm, I did some more testing, also including folders, and now it seems to work again?! I don't know, this is weird, I have to take back that the error is reproducible. It definitely did occur but I can't reproduce in which conditions... sorry.

**Comment by marcelklehr** [comment]
@andreas-bulling for some reason your latest comments don't appear on the website... :thinking: 

> Hm, I did some more testing, also including folders, and now it seems to work again?! I don't know, this is weird, I have to take back that the error is reproducible. It definitely did occur but I can't reproduce in which conditions... sorry.

Could it be that you edited a bookmark on the server and it subsequently failed to be sycned / caused the error. When I edit bookmarks with floccus tags, the `>` characters in the floccus tag turn into `&gt;`s, which would account for the error you're seeing.

**Comment by andreas-bulling** [comment]
> Could it be that you edited a bookmark on the server and it subsequently failed to be sycned / caused the error. When I edit bookmarks with floccus tags, the `>` characters in the floccus tag turn into `&gt;s`, which would account for the error you're seeing.

Yes, I am pretty sure this is what happened/is the problem. Thanks a lot for pushing this upstream - let's hope it will be fixed soon.

**Comment by marcelklehr** [comment]
Bookmarks v0.12.0 has been released ;)
