### ISSUE TITLE
Firefox version 57 required

### ISSUE THREAD

**Issue by 1stone** [marcelklehr/floccus#90]
Hi Marcel,

I just tried to install floccus on Firefox **ESR** 52.7.3 (64-Bit), which is AFAIK the latest version.
Unfortunately, that is denied with "Firefox version 57 required".

Is there a technical demand for that?
Do you see a chance to provide a version that will work with Firefox ESR?
I optimistically hope so, otherwise all company managed Firefoxes will be ruled out from this...

Cheers

**Comment by marcelklehr** [comment]
Hey @1stone 
Yes, I'm afraid there is a technical demand for that, as not all APIs used by floccus were stable before v57. The good news is that there will be a new ESR soon :)
