### ISSUE TITLE
Unable to sync to Nextcloud, "Unexpected token < in JSON at position 0" error

### ISSUE THREAD

**Issue by smuskiew** [marcelklehr/floccus#93]
### Software versions

* Browser: Chrome 66.0.3359.139 (MacOS)
* Nextcloud: 13.0.2
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.1.0

### Steps to reproduce

1. Added account settings for NextCloud instance to Floccus
2. Selected single folder for "Sync folder" (with about 6 bookmarks in it) as a test
3. Clicked "Sync now".

### Expected outcome

sync of bookmark folder to my NextCloud instance

### Actual outcome

Floccus gives the "Syncing..." status for about 5 seconds and then gives "Error!" with (repeated) message: 
Unexpected token < in JSON at position 0
Unexpected token < in JSON at position 0
Unexpected token < in JSON at position 0
Unexpected token < in JSON at position 0
Unexpected token < in JSON at position 0
Unexpected token < in JSON at position 0

**Comment by marcelklehr** [comment]
Hey @smuskiew 
Thanks for reporting this. This usually happens, when people don't have the nextcloud app installed.
Could you check the network log as follows?

* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* Open 'Network' tab
* go to floccus options and trigger a sync by clicking on `force Sync` for the account of your choice
* go back to the inspector window and check the last network requests in the list. You should be able to find out the content of the HTTP response and the response code.

**Comment by smuskiew** [comment]
Hi @marcelklehr, I did that and see a bunch of 302 responses initiated from Nextcloud.js followed by a bunch of 200 responses for "files/"  (screenshot attached).  Not entirely sure what I should expect to be seeing?

<img width="1098" alt="screen shot 2018-05-02 at 12 16 40 pm" src="https://user-images.githubusercontent.com/37269491/39535858-fde45f42-4e02-11e8-9c68-f2cdd454abe8.png">

**Comment by marcelklehr** [comment]
This means that requests to the bookmark endpoint are redirected to the files app. This is usually the case if you have an outdated version of the bookmarks app or none at all. Could you make sure in your app manager that the bookmarks app is *enabled*?

**Comment by smuskiew** [comment]
@marcelklehr OK, looks like my bad, I had the bookmark app enabled but it was set "limit to groups" and I _thought_ I had put the user i was using in the right group but of course I hadn't.

Seems to be working great now, I can see all my bookmarks in my NextCloud instance.  Thanks for steering me in the right direction!

**Comment by smuskiew** [comment]
User setup error, not a bug 🙄

**Comment by marcelklehr** [comment]
I'm glad it works for you now :)
