### ISSUE TITLE
Network error with Chrome extention

### ISSUE THREAD

**Issue by eRJe79** [marcelklehr/floccus#94]
Since a short while <24 days the Chrome extension is not connecting to the Nextcloud server anymore. The response is:

Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details Network error: Check your network connection and your account details

The Firefox extension is working fine.

### Software versions
* Browser: Chrome Version 65.0.3325.146 (Official Build) (64-bit)
* Nextcloud: 13
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.1.0

### Steps to reproduce
1. I found missing bookmarks in Chrome that were added in Firefox
2. I checked the extension and found the above error message
3. Removed and added account without improvement
4. Removed extension and added it back, no improvement

### Expected outcome
I would expect that the extension syncs with the server as it did in after the initial setup >24 days ago.

...

### Actual outcome
See error message above.

**Comment by marcelklehr** [comment]
Hey @eRJe79 
Thank you for reporting this. Could you a) double check your nextcloud URL b) check the network log as follows?

* Go to chrome://extensions
* enable Developer mode
* click on dist/html/background.html button in floccus' entry next to "Inspect views: "
* Open 'Network' tab
* go to floccus options and trigger a sync by clicking on force Sync for the account of your choice
* go back to the inspector window and check the last network requests in the list. You should be able to find out the content of the HTTP response and the response code.

**Comment by eRJe79** [comment]
Hi @marcelklehr,

Thanks for your response. The nextcloud URL has been verified (also copied from the working FF extension).

I included a screen shot of the inspector window.

![image](https://user-images.githubusercontent.com/5793189/39549401-02fdd9a8-4e5e-11e8-9705-f046dc1a4e1f.png)

**Comment by marcelklehr** [comment]
The error code looks to be related to the TLS certificate used by your nextcloud server. It could be that if it's a recent certificate, chrome hadn't updated its list of CAs to include yours.

I'm closing this, as it seems to work now. Shout if the issue comes up again :)

**Comment by eRJe79** [comment]
It was indeed the TLS certificate. For this test site I do not have a trusted certificate. As long as I load Nextcloud in Chrome and accept the security issues, Floccus works. Without doing this first, I will not sync. During the first tests I was always logged in to Nextcloud and therefore this problem never popped up.
