### ISSUE TITLE
Different errors at the same time due to removing duplicate bookmarks

### ISSUE THREAD

**Issue by akidburn** [marcelklehr/floccus#95]
Hi @marcelklehr 

This time i had different errors on the 2 Chrome clients and 1 Firefox client at the same time.

### Software versions

Clients
Windos 10 Pro Version 1709
Google Chrome 66.0.3359.139 (mostly fine, speedwise)
Mozilla Firefox 59.0.3 (64-Bit)
Floccus 2.1.0 (both FF and Chrome)

Server
odroid-c2 3.14.79-117
Amlogic ARM® Cortex®-A53(ARMv8) 1.5Ghz quad core CPU
2Gbyte DDR3 SDRAM
Ubuntu 16.04
Nextcloud 13.0.2
Bookmarks App 0.11.0
nginx/1.13.12
php Version: 7.2.4
mariadb Version: 10.0.34

### Steps to reproduce

I tried to sync my bookmarks slowly from nc to the clients, while waiting until each had finished before installing the addon on the next and so on.

Each Client was synced into a Subfolder of Other Bookmarks or Bookmark Menü of EXACTLY the SAME NAME.

The 2 Chrome Clients went fine synchronizing without much problems. 
Its after downloading to the Firefox client that the problems started.
The following sync produced an Error saying duplicate bookmarks detected.
So checking this out i found multiple duplicate bookmarks in the PREVIOUSLY EMPTY FOLDER, different just by 2 characters. so i had to use a bookmark duplicate cleaner app to get rid of them all.

after that, the floccus errors started

On Firefox the Error was "Removing a bookmark on the server failed." countless times
Chrome on the same Machine said "Cannot read property localid of undefined" once
Chrome on my Notebook said "Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this!"

After that all went to shit again.

### Expected outcome
I expected the Sync to work if the bookmarks and the folderstructure were the same for all clients.

And i didnt expect the deduplicator to lead to even more errors

And i didnt expect the bookmarks with the same urls to suddenly have different names, as though one was unicode and the other one was ascii.

### Actual outcome
Able to sync once.
Bookmarks duplicating somehow, fucking the sync up.
Tried to fix the Firefox syncfolder by cleaning up the duplicates using the Bookmark Duplicate App.
Fucked everything further.
and some urls have duplicates in the oc_bookmarks table that floccus recognizes, but the bookmark app does not:

In the db:

![error](https://user-images.githubusercontent.com/25623510/39656640-a737960e-5001-11e8-9d16-9d90a367852e.png)

### What i think happened
If i delete a folder on client A and sync the change, the nc server should remember the action and tell clients B, C, D  that this folder has been deleted. 
But the clients should not tell the nc server to delete the same bookmarks again, because the error "Removing a bookmark on the sever failed." comes from there somewhere, because client A already deleted them.

**Comment by marcelklehr** [comment]
> "Removing a bookmark on the sever failed." comes from there somewhere, because client A already deleted them.

This should be fixed in the latest release.

>  some urls have duplicates in the oc_bookmarks table that floccus recognizes, but the bookmark app does not

This looks like an encoding issue. The url is urlencoded. probably in the app. This shouldn't happen in the upcoming version of the bookmarks app. Stay tuned :sweat:

**Comment by akidburn** [comment]
Syncing works now mostly without issues, though sometimes there are still duplicates in the db if new bookmarks are added. 
Normal incremental syncs work, though force sync seems to trigger the duplicate error if duplicates are in the db.

after deleteing the duplicates in the db, syncing works.

though the network error after resume from standby is annoying. and it appears sometimes only.
could you add a timer for retry on that erorr?

**Comment by marcelklehr** [comment]
> though the network error after resume from standby is annoying. and it appears sometimes only.

There's not much I can do about that...

> sometimes there are still duplicates in the db if new bookmarks are added.

This should be fixed in v2.2.6 if I've fixed the exact bug that caused that failure for you... there might be others causing duplicates.
