### ISSUE TITLE
Nothing happens when clicking on icon.

### ISSUE THREAD

**Issue by arnauldb** [marcelklehr/floccus#96]
* Browser: Firefox & Chromium (latest)
* Nextcloud: latest
* Nextcloud Bookmarks app: latest
* Floccus: latest
* I run Linux Mint Sylvia 

After having installed Floccus in Firefox & Chromium, then clicking the Floccus icon, nothing happens in both browsers, I can only see a thin blank rectangle below the icon, same in both browsers (please, see screencast : https://youtu.be/XGkD19aW5BQ  )

Thank you.

**Comment by marcelklehr** [comment]
It should appear eventually, when waiting long enough ;) In any case, this should be fixed in v2.2.0, now. Let me know if you still experience this with the latest release.
