### ISSUE TITLE
Error: "trying to update a node of a bookmark that has none"

### ISSUE THREAD

**Issue by exekutive** [marcelklehr/floccus#97]
tried to sync a subfolder in my Firefox bookmark toolbar
bookmarks were partially synced
some ugly tags were created (floccus:undefined>BLOGS)

* Browser: Firefox 60
* Nextcloud: 13.0.2
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.0

**Comment by marcelklehr** [comment]
Ah. My bad. Will release a patch ASAP.

**Comment by marcelklehr** [comment]
Please try the version v2.2.1 once it's available via mozilla, it should fix your issues.

**Comment by exekutive** [comment]
all good :)

**Comment by exekutive** [comment]
however, in Nextcloud bookmarks, when editing a bookmark, the ">" character in tags appears as "&gt;". But that's a problem with the app, not floccus.

**Comment by marcelklehr** [comment]
Yep, that has been reported already and will be fixed in the upcoming release.
